# Raw file survey

Read-only pass over every `.sas7bdat` file across all 5 raw PDS trial exports.
No analysis, no joins, no cleaning here — just: what columns exist, what does the data look like.
This is the input to the CDISC harmonization mapping in `dbt/models/staging/`.

In [193]:
import pandas as pd
import pyreadstat
from pathlib import Path

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 200)

DATA_DIR = Path('..') / '..' / 'Data' / 'raw'
assert DATA_DIR.exists(), DATA_DIR

In [194]:
def read_domain(trial_folder, filename):
    """Read one .sas7bdat file and print its shape + columns + head. Read-only, no transforms."""
    path = DATA_DIR / trial_folder / filename
    df, meta = pyreadstat.read_sas7bdat(str(path))
    print(f'--- {trial_folder}/{filename} ---')
    print('shape:', df.shape)
    print('columns:', list(df.columns))
    display(df.head())
    return df

## NCT00113763_panitumumab_bsc_ADaM

In [195]:
_ = read_domain('NCT00113763_panitumumab_bsc_ADaM', 'adae_pds2019.sas7bdat')

--- NCT00113763_panitumumab_bsc_ADaM/adae_pds2019.sas7bdat ---
shape: (1037, 7)
columns: ['SUBJID', 'AEPT', 'AESOC', 'AESTDYI', 'AEENDYI', 'AESEVCD', 'AECONT']

   SUBJID                  AEPT                                   AESOC  AESTDYI  AEENDYI  AESEVCD AECONT
0  000001                  RASH  SKIN AND SUBCUTANEOUS TISSUE DISORDERS     29.0     43.0      1.0      N
1  000001         SKIN FISSURES  SKIN AND SUBCUTANEOUS TISSUE DISORDERS     57.0    142.0      1.0      N
2  000001      SKIN EXFOLIATION  SKIN AND SUBCUTANEOUS TISSUE DISORDERS    158.0    172.0      1.0      N
3  000002  DERMATITIS ACNEIFORM  SKIN AND SUBCUTANEOUS TISSUE DISORDERS      NaN      NaN      2.0      Y
4  000004              ERYTHEMA  SKIN AND SUBCUTANEOUS TISSUE DISORDERS      NaN      NaN      1.0      Y

In [196]:
_ = read_domain('NCT00113763_panitumumab_bsc_ADaM', 'adlb_pds2019.sas7bdat')

--- NCT00113763_panitumumab_bsc_ADaM/adlb_pds2019.sas7bdat ---
shape: (12439, 7)
columns: ['SUBJID', 'LBTEST', 'LBBASE', 'LBSTRESN', 'LBSTUNIT', 'VISITDY', 'VISIT']

   SUBJID                LBTEST LBBASE  LBSTRESN LBSTUNIT  VISITDY      VISIT
0  000001               Albumin      N      44.0      g/L     -6.0  Screening
1  000001               Albumin      Y      47.0      g/L      1.0     Week 1
2  000001               Albumin      N      44.0      g/L     57.0     Week 9
3  000001               Albumin      N      42.0      g/L     86.0    Week 13
4  000001  Alkaline Phosphatase      N     160.0      U/L     -6.0  Screening

In [197]:
_ = read_domain('NCT00113763_panitumumab_bsc_ADaM', 'adls_pds2019.sas7bdat')

--- NCT00113763_panitumumab_bsc_ADaM/adls_pds2019.sas7bdat ---
shape: (9935, 11)
columns: ['SUBJID', 'VISITDY', 'VISIT', 'LSCAT', 'LSNEW', 'LSSLD', 'LSLD', 'LSSITE', 'LSNEWANY', 'LSREADER', 'LSTYPE']

   SUBJID  VISITDY    VISIT          LSCAT LSNEW  LSSLD  LSLD LSSITE LSNEWANY       LSREADER   LSTYPE
0  000001     85.0  Week 12  Target lesion     N  210.0  32.0  Liver        N  Radiologist 1  Central
1  000001     85.0  Week 12  Target lesion     N  300.0  51.0  Liver        Y  Radiologist 2  Central
2  000001     85.0  Week 12  Target lesion     N  210.0  53.0  Liver        N  Radiologist 1  Central
3  000001     85.0  Week 12  Target lesion     N  300.0  37.0  Liver        Y  Radiologist 2  Central
4  000001     85.0  Week 12  Target lesion     N  210.0  32.0  Liver        N  Radiologist 1  Central

In [198]:
_ = read_domain('NCT00113763_panitumumab_bsc_ADaM', 'adpm_pds2019.sas7bdat')

--- NCT00113763_panitumumab_bsc_ADaM/adpm_pds2019.sas7bdat ---
shape: (2394, 4)
columns: ['SUBJID', 'VISIT', 'VISITDY', 'WEIGHT']

   SUBJID      VISIT  VISITDY  WEIGHT
0  000001  Screening     -6.0    50.0
1  000001     Week 1      1.0    48.0
2  000001     Week 3     15.0    49.0
3  000001     Week 5     29.0    49.0
4  000001     Week 7     43.0    46.0

In [199]:
_ = read_domain('NCT00113763_panitumumab_bsc_ADaM', 'adrsp_pds2019.sas7bdat')

--- NCT00113763_panitumumab_bsc_ADaM/adrsp_pds2019.sas7bdat ---
shape: (2302, 8)
columns: ['SUBJID', 'RSRESP', 'VISITDY', 'VISIT', 'RSCONFYN', 'RSTRESP', 'RSNTRESP', 'RSREADER']

   SUBJID              RSRESP  VISITDY      VISIT RSCONFYN         RSTRESP        RSNTRESP       RSREADER
0  000001             Unknown      NaN  Screening                  Unknown         Unknown  Radiologist 1
1  000001             Unknown      NaN  Screening                  Unknown         Unknown  Radiologist 2
2  000001             Unknown      NaN  Screening                  Unknown         Unknown     Oncologist
3  000001  Unable to evaluate     50.0     Week 8           Stable disease  Stable disease  Radiologist 1
4  000001  Unable to evaluate     50.0     Week 8           Stable disease  Stable disease  Radiologist 2

In [200]:
_ = read_domain('NCT00113763_panitumumab_bsc_ADaM', 'adsl_pds2019.sas7bdat')

--- NCT00113763_panitumumab_bsc_ADaM/adsl_pds2019.sas7bdat ---
shape: (370, 16)
columns: ['SUBJID', 'TRT', 'ATRT', 'SXANY', 'DTHDYX', 'DTHX', 'PFSDYCR', 'PFSCR', 'DIAGMONS', 'AGE', 'SEX', 'B_WEIGHT', 'RACE', 'B_ECOG', 'HISSUBTY', 'DIAGTYPE']

,SUBJID,TRT,ATRT,SXANY,DTHDYX,DTHX,PFSDYCR,PFSCR,DIAGMONS,AGE,SEX,B_WEIGHT,RACE,B_ECOG,HISSUBTY,DIAGTYPE
0,000001,panit. plus best supportive care,panit. plus best supportive care,Y,218.0,1.0,84.0,1.0,54.983607,68.0,Male,48.0,White or Caucasian,Symptoms but ambulatory,No sub-type,Colon
1,000002,Best supportive care,Best supportive care,Y,231.0,1.0,57.0,1.0,24.983607,48.0,Male,88.0,White or Caucasian,Symptoms but ambulatory,Mucinous,Colon
2,000004,Best supportive care,Best supportive care,Y,581.0,1.0,581.0,1.0,19.409836,70.0,Female,57.0,White or Caucasian,Fully active,No sub-type,Colon
3,000005,Best supportive care,Best supportive care,Y,15.0,1.0,15.0,1.0,6.622951,68.0,Female,64.4,White or Caucasian,In bed less than 50% of the time,No sub-type,Colon
4,000006,panit. plus best supportive care,panit. plus best supportive care,Y,286.0,1.0,112.0,1.0,30.229508,56.0,Male,83.5,White or Caucasian,Fully active,No sub-type,Rectal

In [201]:
_ = read_domain('NCT00113763_panitumumab_bsc_ADaM', 'biomark_pds2019.sas7bdat')

--- NCT00113763_panitumumab_bsc_ADaM/biomark_pds2019.sas7bdat ---
shape: (394, 15)
columns: ['SUBJID', 'BMMTNM1', 'BMMTR1', 'BMMTNM2', 'BMMTR2', 'BMMTNM3', 'BMMTR3', 'BMMTNM4', 'BMMTR4', 'BMMTNM5', 'BMMTR5', 'BMMTNM6', 'BMMTR6', 'BMMTNM7', 'BMMTR7']

,SUBJID,BMMTNM1,BMMTR1,BMMTNM2,BMMTR2,BMMTNM3,BMMTR3,BMMTNM4,BMMTR4,BMMTNM5,BMMTR5,BMMTNM6,BMMTR6,BMMTNM7,BMMTR7
0,000001,KRAS exon 2 (c12/13),Failure,KRAS exon 3 (c61),,KRAS exon 4 (c117/146),,NRAS exon 2 (c12/13),,NRAS exon 3 (c61),,NRAS exon 4 (c117/146),,BRAF exon 15 (c600),
1,000002,KRAS exon 2 (c12/13),Wild-type,KRAS exon 3 (c61),,KRAS exon 4 (c117/146),,NRAS exon 2 (c12/13),,NRAS exon 3 (c61),,NRAS exon 4 (c117/146),,BRAF exon 15 (c600),
2,000004,KRAS exon 2 (c12/13),Mutant,KRAS exon 3 (c61),,KRAS exon 4 (c117/146),,NRAS exon 2 (c12/13),,NRAS exon 3 (c61),,NRAS exon 4 (c117/146),,BRAF exon 15 (c600),
3,000005,KRAS exon 2 (c12/13),Mutant,KRAS exon 3 (c61),Wild-type,KRAS exon 4 (c117/146),Wild-type,NRAS exon 2 (c12/13),Wild-type,NRAS exon 3 (c61),Wild-type,NRAS exon 4 (c117/146),Wild-type,BRAF exon 15 (c600),Wild-type
4,000006,KRAS exon 2 (c12/13),Wild-type,KRAS exon 3 (c61),Wild-type,KRAS exon 4 (c117/146),Wild-type,NRAS exon 2 (c12/13),Wild-type,NRAS exon 3 (c61),Wild-type,NRAS exon 4 (c117/146),Wild-type,BRAF exon 15 (c600),Wild-type

## NCT00115225_PACCE_bev_panitumumab_raw

In [202]:
_ = read_domain('NCT00115225_PACCE_bev_panitumumab_raw', 'a_eendpt.sas7bdat')

--- NCT00115225_PACCE_bev_panitumumab_raw/a_eendpt.sas7bdat ---
shape: (842, 122)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'CHEMOCD', 'CHEMO', 'CHEMOICD', 'CHEMOI', 'ACHEMOCD', 'ACHEMO', 'ACHEMMCD', 'ACHEMM', 'FCHEMOCD', 'FCHEMO', 'B_LESNM', 'B_LESNMT', 'B_LESNMN', 'B_METANM', 'B_METACT', 'BMETACTI', 'FSTOXDS', 'FSTIRDS', 'DURSURG', 'PRADJYN', 'PRADJICD', 'PRADJI', 'B_LDHYN', 'B_ECOGCD', 'B_ECOG', 'BECOGICD', 'B_ECOGI', 'DIAGTYCD', 'DIAGTYPE', 'DIAGICD', 'DIAGI', 'RESPSTAT', 'EVALITT', 'EVALPP', 'PDADEN', 'PDICSIG', 'PDICMIS', 'PDPROMED', 'PDYN', 'KRASCD', 'KRAS', 'EVALKEA', 'EVALKSA', 'EVALKUE', 'R12LR', 'R12LRCA', 'R12LRSD', 'R12CR', 'R12CRCA', 'R12CRSD', 'ROSCR', 'ROSLR', 'ROSLRCA', 'RLR', 'RCR', 'RDURLR', 'RDURWLR', 'RDURLRC', 'RDURCR', 'RDURWCR', 'RDURCRC', 'RDYLR', 'RDYCR', 'PFSDYCR', 'PFSMTCR', 'PFSCR', 'PFSDYLR', 'PFSMTLR', 'PFSLR', 'PDDYCR', 'PDCR', 'PDMTCR', 'PDDYLR', 'PDMTLR', 'PDLR', 'DTHDY', 'DTHMT', 'DTH', 'TFAILDY', 'TFAILMT', 'TFAIL', 'SDDURLR', 'SDDURWLR', 'SDDURLRC', 'SDDURCR', 'SDDURWCR', 'SDDURCRC', 'DTH30', 'DTHDY30', 'DTHMT30', 'PDCR30', 'PDDYCR30', 'PDMTCR30', 'PDLR30', 'PDDYLR30', 'PDMTLR30', 'PFSCR30', 'PFSDCR30', 'PFSMCR30', 'PFSLR30', 'PFSDLR30', 'PFSMLR30', 'PDCRND', 'PDDYCRND', 'PDMTCRND', 'TRTDUR', 'LASTCRDY']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,CHEMOCD,CHEMO,CHEMOICD,CHEMOI,ACHEMOCD,ACHEMO,ACHEMMCD,ACHEMM,FCHEMOCD,FCHEMO,B_LESNM,B_LESNMT,B_LESNMN,B_METANM,B_METACT,BMETACTI,FSTOXDS,FSTIRDS,DURSURG,PRADJYN,PRADJICD,PRADJI,B_LDHYN,B_ECOGCD,B_ECOG,BECOGICD,B_ECOGI,DIAGTYCD,DIAGTYPE,DIAGICD,DIAGI,RESPSTAT,EVALITT,EVALPP,PDADEN,PDICSIG,PDICMIS,PDPROMED,PDYN,KRASCD,KRAS,EVALKEA,EVALKSA,EVALKUE,R12LR,R12LRCA,R12LRSD,R12CR,R12CRCA,R12CRSD,ROSCR,ROSLR,ROSLRCA,RLR,RCR,RDURLR,RDURWLR,RDURLRC,RDURCR,RDURWCR,RDURCRC,RDYLR,RDYCR,PFSDYCR,PFSMTCR,PFSCR,PFSDYLR,PFSMTLR,PFSLR,PDDYCR,PDCR,PDMTCR,PDDYLR,PDMTLR,PDLR,DTHDY,DTHMT,DTH,TFAILDY,TFAILMT,TFAIL,SDDURLR,SDDURWLR,SDDURLRC,SDDURCR,SDDURWCR,SDDURCRC,DTH30,DTHDY30,DTHMT30,PDCR30,PDDYCR30,PDMTCR30,PDLR30,PDDYLR30,PDMTLR30,PFSCR30,PFSDCR30,PFSMCR30,PFSLR30,PFSDLR30,PFSMLR30,PDCRND,PDDYCRND,PDMTCRND,TRTDUR,LASTCRDY
0,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.573770,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,0.0,,0.0,0.0,,0.0,1.0,1.0,PR,1.0,1.0,568.0,81.142857,1.0,568.0,81.142857,1.0,101.0,101.0,668.0,21.946612,1.0,668.0,21.946612,1.0,668.0,1.0,21.946612,668.0,21.946612,1.0,1507.0,49.511294,0.0,668.0,21.946612,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,719.0,23.622177,1.0,668.0,21.946612,1.0,668.0,21.946612,1.0,668.0,21.946612,1.0,668.0,21.946612,1.0,668.0,21.946612,685.0,618.0
1,20040249,101,249101002,72.0,M,Male,1.0,White or Caucasian,0.0,Q2WK,Every 2 weeks,12.0,bevacizumab with chemotherapy,12.0,bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,101.0,2.0,99.0,2.0,>1,>1,90.712273,NaN,44.065574,N,0.0,N,N,1.0,Symptoms but ambulatory,1.0,Symptoms but ambulatory,1251.0,Colon,1251.0,Colon,N,Y,Y,N,N,N,N,N,2.0,Mutant,Y,Y,N,0.0,,0.0,0.0,,0.0,0.0,0.0,SD,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,315.0,10.349076,1.0,369.0,12.123203,1.0,315.0,1.0,10.349076,369.0,12.123203,1.0,482.0,15.835729,1.0,369.0,12.123203,1.0,369.0,52.714286,1.0,315.0,45.000000,1.0,0.0,399.0,13.108830,1.0,315.0,10.349076,1.0,369.0,12.123203,1.0,315.0,10.349076,1.0,369.0,12.123203,1.0,315.0,10.349076,365.0,162.0
2,20040249,101,249101003,78.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,101.0,2.0,99.0,2.0,>1,1,84.244651,NaN,0.000000,N,0.0,N,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,88.0,Failed,N,N,Y,1.0,PR,1.0,0.0,SD,1.0,1.0,1.0,PR,1.0,1.0,113.0,16.142857,0.0,1.0,0.142857,0.0,84.0,185.0,196.0,6.439425,1.0,196.0,6.439425,1.0,185.0,0.0,6.078029,196.0,6.439425,0.0,196.0,6.439425,1.0,191.0,6.275154,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,196.0,6.439425,0.0,185.0,6.078029,0.0,196.0,6.439425,1.0,196.0,6.439425,1.0,196.0,6.439425,0.0,185.0,6.078029,166.0,185.0
3,20040249,101,249101005,66.0,F,Female,2.0,Black or African American,0.0,Q2WK,Every 2 weeks,12.0,bevacizumab with chemotherapy,12.0,bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,101.0,2.0,99.0,2.0,>1,>1,84.943334,NaN,-0.032787,N,0.0,N,N,1.0,Symptoms but ambulatory,1.0,Symptoms but ambulatory,1251.0,Colon,1251.0,Colon,N,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,0.0,SD,1.0,0.0,SD,1.0,0.0,0.0,SD,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.0,3.219713,1.0,98.0,3.219713,1.0,86.0,0.0,2.825462,98.0,3.219713,0.0,98.0,3.219713,1.0,98.0,3.219713,1.0,98.0,14.000000,0.0,86.0,12.285714,0.0,1.0,98.0,3.219713,0.0,86.0,2.825462,0.0,98.0,3.219713,1.0,98.0,3.219713,1.0,98.0,3.219713,0.0,86.0,2.825462,85.0,86.0
4,20040249,101,249101006,67.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,2.0,1.0,1.0,1.0,1,1,91.258658,NaN,45.508197,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1252.0,Rectal,1252.0,Rectal,N,Y,Y,N,N,N,N,N,88.0,Failed,N,N,Y,0.0,SD,1.0,0.0,SD,1.0,0.0,0.0,SD,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,348.0,11.433265,1.0,348.0,11.433265,1.0,348.0,1.0,11.433265,348.0,11.433265,1.0,958.0,31.474333,1.0,348.0,11.433265,1.0,348.0,49.714286,1.0,348.0,49.714286,1.0,0.0,338.0,11.104723,0.0,250.0,8.213552,0.0,348.0,11.433265,0.0,250.0,8.213552,0.0,348.0,11.433265,1.0,348.0,11.433265,302.0,246.0

In [203]:
_ = read_domain('NCT00115225_PACCE_bev_panitumumab_raw', 'a_sendpt.sas7bdat')

--- NCT00115225_PACCE_bev_panitumumab_raw/a_sendpt.sas7bdat ---
shape: (823, 189)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'CHEMOCD', 'CHEMO', 'CHEMOICD', 'CHEMOI', 'ACHEMOCD', 'ACHEMO', 'ACHEMMCD', 'ACHEMM', 'FCHEMOCD', 'FCHEMO', 'B_LESNM', 'B_LESNMT', 'B_LESNMN', 'B_METANM', 'B_METACT', 'BMETACTI', 'FSTOXDS', 'FSTIRDS', 'DURSURG', 'PRADJYN', 'PRADJICD', 'PRADJI', 'B_LDHYN', 'B_ECOGCD', 'B_ECOG', 'BECOGICD', 'B_ECOGI', 'DIAGTYCD', 'DIAGTYPE', 'DIAGICD', 'DIAGI', 'RESPSTAT', 'EVALITT', 'EVALPP', 'PDADEN', 'PDICSIG', 'PDICMIS', 'PDPROMED', 'PDYN', 'KRASCD', 'KRAS', 'EVALKEA', 'EVALKSA', 'EVALKUE', 'INFREAC', 'AE34', 'AE4', 'AESER', 'AEREL', 'AEREL34', 'AEREL4', 'AERELSER', 'AETXDIS', 'AEBEVDIS', 'AETRTDIS', 'DEATH', 'DEATH60', 'DEATH30', 'DTHREL', 'NUMINF', 'NUMBINF', 'NUMOXINF', 'NUMIRINF', 'NUMALINF', 'NUMFBINF', 'NUMFIINF', 'AINFTM', 'AINFHR', 'CDOSE', 'ADOSE', 'CWDOSE', 'AWDOSE', 'BCDOSE', 'BADOSE', 'BCWDOSE', 'BAWDOSE', 'OXCDOSE', 'OXADOSE', 'OXCWDOSE', 'OXAWDOSE', 'IRCDOSE', 'IRADOSE', 'IRCWDOSE', 'IRAWDOSE', 'FBCDOSE', 'FBADOSE', 'FBCWDOSE', 'FBAWDOSE', 'FICDOSE', 'FIADOSE', 'FICWDOSE', 'FIAWDOSE', 'DUREXP', 'EXPWK', 'BDURWK', 'BDSINT', 'BDSINTR', 'IPDURWK', 'IPDSINT', 'IPDSINTR', 'OXDURWK', 'OXDSINT', 'OXDSINTR', 'IRDURWK', 'IRDSINT', 'IRDSINTR', 'FBDURWK', 'FBDSINT', 'FBDSINTR', 'FIDURWK', 'FIDSINT', 'FIDSINTR', 'DSDLYNM', 'DSDLYPC', 'IPDLYPC', 'BDLYNM', 'BDLYPC', 'OXDLYNM', 'OXDLYPC', 'IRDLYNM', 'IRDLYPC', 'FBDLYNM', 'FBDLYPC', 'IPDECPCW', 'BDECPCW', 'OXDECPCW', 'IRDECPCW', 'FBDECPCW', 'DECPCW', 'INFREAC2', 'AE2', 'AE34_2', 'AESER2', 'AEREL2', 'AERELSR2', 'AETXDIS2', 'AEBEVDS2', 'AETRTDS2', 'NUMBINF2', 'NUMOXIN2', 'NUMIRIN2', 'NUMFBIN2', 'NUMFIIN2', 'BCDOSE2', 'BCWDOSE2', 'OXCDOSE2', 'OXCWDOS2', 'IRCDOSE2', 'IRCWDOS2', 'FBCDOSE2', 'FBCWDOS2', 'FICDOSE2', 'FICWDOS2', 'BDURWK2', 'BDSINT2', 'BDSINTR2', 'OXDURWK2', 'OXDSINT2', 'OXDSINR2', 'IRDURWK2', 'IRDSINT2', 'IRDSINR2', 'FBDURWK2', 'FBDSINT2', 'FBDSINR2', 'FIDURWK2', 'FIDSINT2', 'FIDSINR2', 'DEATH2', 'DTH60_2', 'DTH30_2', 'DTHREL2', 'EVALSAF2', 'TRTDUR']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,CHEMOCD,CHEMO,CHEMOICD,CHEMOI,ACHEMOCD,ACHEMO,ACHEMMCD,ACHEMM,FCHEMOCD,FCHEMO,B_LESNM,B_LESNMT,B_LESNMN,B_METANM,B_METACT,BMETACTI,FSTOXDS,FSTIRDS,DURSURG,PRADJYN,PRADJICD,PRADJI,B_LDHYN,B_ECOGCD,B_ECOG,BECOGICD,B_ECOGI,DIAGTYCD,DIAGTYPE,DIAGICD,DIAGI,RESPSTAT,EVALITT,EVALPP,PDADEN,PDICSIG,PDICMIS,PDPROMED,PDYN,KRASCD,KRAS,EVALKEA,EVALKSA,EVALKUE,INFREAC,AE34,AE4,AESER,AEREL,AEREL34,AEREL4,AERELSER,AETXDIS,AEBEVDIS,AETRTDIS,DEATH,DEATH60,DEATH30,DTHREL,NUMINF,NUMBINF,NUMOXINF,NUMIRINF,NUMALINF,NUMFBINF,NUMFIINF,AINFTM,AINFHR,CDOSE,ADOSE,CWDOSE,AWDOSE,BCDOSE,BADOSE,BCWDOSE,BAWDOSE,OXCDOSE,OXADOSE,OXCWDOSE,OXAWDOSE,IRCDOSE,IRADOSE,IRCWDOSE,IRAWDOSE,FBCDOSE,FBADOSE,FBCWDOSE,FBAWDOSE,FICDOSE,FIADOSE,FICWDOSE,FIAWDOSE,DUREXP,EXPWK,BDURWK,BDSINT,BDSINTR,IPDURWK,IPDSINT,IPDSINTR,OXDURWK,OXDSINT,OXDSINTR,IRDURWK,IRDSINT,IRDSINTR,FBDURWK,FBDSINT,FBDSINTR,FIDURWK,FIDSINT,FIDSINTR,DSDLYNM,DSDLYPC,IPDLYPC,BDLYNM,BDLYPC,OXDLYNM,OXDLYPC,IRDLYNM,IRDLYPC,FBDLYNM,FBDLYPC,IPDECPCW,BDECPCW,OXDECPCW,IRDECPCW,FBDECPCW,DECPCW,INFREAC2,AE2,AE34_2,AESER2,AEREL2,AERELSR2,AETXDIS2,AEBEVDS2,AETRTDS2,NUMBINF2,NUMOXIN2,NUMIRIN2,NUMFBIN2,NUMFIIN2,BCDOSE2,BCWDOSE2,OXCDOSE2,OXCWDOS2,IRCDOSE2,IRCWDOS2,FBCDOSE2,FBCWDOS2,FICDOSE2,FICWDOS2,BDURWK2,BDSINT2,BDSINTR2,OXDURWK2,OXDSINT2,OXDSINR2,IRDURWK2,IRDSINT2,IRDSINR2,FBDURWK2,FBDSINT2,FBDSINR2,FIDURWK2,FIDSINT2,FIDSINR2,DEATH2,DTH60_2,DTH30_2,DTHREL2,EVALSAF2,TRTDUR
0,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.573770,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,N,Y,Y,Y,Y,Y,N,N,N,N,N,N,N,N,N,41.0,34.0,19.0,NaN,41.0,19.0,19.0,30.731707,0.512195,18040.0,440.000000,251.596140,6.136491,12478.0,367.000000,173.392107,5.099768,2850.0,150.0,1564.093013,82.320685,NaN,NaN,NaN,NaN,27360.0,1440.000000,15015.292928,790.278575,39960.0,2103.157895,21930.575071,1154.240793,698.0,99.714286,99.714286,3.477779,69.555573,99.714286,5.046341,84.105682,99.714286,31.371493,36.907639,NaN,NaN,NaN,99.714286,301.166334,37.645792,99.714286,439.868268,36.655689,4.0,0.097561,0.097561,3.0,0.088235,2.0,0.105263,NaN,NaN,2.0,0.105263,0.0,0.0,0.0,NaN,0.0,0.0,N,N,N,N,N,N,N,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,N,N,685.0
1,20040249,101,249101002,72.0,M,Male,1.0,White or Caucasian,0.0,Q2WK,Every 2 weeks,12.0,bevacizumab with chemotherapy,12.0,bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,101.0,2.0,99.0,2.0,>1,>1,90.712273,NaN,44.065574,N,0.0,N,N,1.0,Symptoms but ambulatory,1.0,Symptoms but ambulatory,1251.0,Colon,1251.0,Colon,N,Y,Y,N,N,N,N,N,2.0,Mutant,Y,Y,N,N,Y,N,N,N,N,N,N,N,N,N,Y,N,N,N,NaN,23.0,10.0,NaN,23.0,23.0,16.0,NaN,NaN,NaN,NaN,NaN,NaN,8625.0,375.000000,109.098638,4.743419,1800.0,180.0,907.906402,90.790640,NaN,NaN,NaN,NaN,9200.0,400.000000,4590.152186,199.571834,48000.0,3000.000000,24059.109235,1503.694327,378.0,54.000000,54.000000,4.040690,83.507599,NaN,NaN,NaN,23.000000,78.948383,78.948383,NaN,NaN,NaN,54.000000,170.005637,42.501409,37.000000,1300.492391,54.187183,2.0,0.086957,NaN,2.0,0.086957,1.0,0.100000,NaN,NaN,2.0,0.086957,NaN,0.0,0.0,NaN,0.0,0.0,N,N,N,N,N,N,N,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,N,N,365.0
2,20040249,101,249101003,78.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,101.0,2.0,99.0,2.0,>1,1,84.244651,NaN,0.000000,N,0.0,N,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,88.0,Failed,N,N,Y,N,Y,Y,Y,Y,Y,N,Y,N,N,Y,Y,N,Y,N,10.0,10.0,10.0,NaN,10.0,10.0,10.0,36.000000,0.600000,5340.0,534.000000,65.662081,6.566208,4450.0,445.000000,54.718401,5.471840,1800.0,180.0,880.870728,88.087073,NaN,NaN,NaN,NaN,16800.0,1680.000000,8221.460126,822.146013,25000.0,2500.000000,12234.315664,1223.431566,179.0,25.571429,25.571429,4.279651,85.593029,25.571429,5.135582,85.593029,25.571429,68.894917,81.052844,NaN,NaN,NaN,25.571429,643.019228,80.377403,25.571429,956.873851,79.739488,2.0,0.200000,0.200000,2.0,0.200000,2.0,0.200000,NaN,NaN,2.0,0.200000,0.0,0.0,0.0,NaN,0.0,0.0,N,N,N,N,N,N,N,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,N,N,166.0
3,20040249,101,249101005,66.0,F,Female,2.0,Black or African American,0.0,Q2WK,Every 2 weeks,12.0,bevacizumab with chemotherapy,12.0,bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,101.0,2.0,99.0,2.0,>1,>1,84.943334,NaN,-0.032787,N,0.0,N,N,1.0,Symptoms but ambulatory,1.0,Symptoms but ambulatory,1251.0,Colon,1251.0,Colon,N,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,N,Y,N,Y,N,N,N,N,N,N,Y,Y,N,Y,N,NaN,7.0,7.0,NaN,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,1820.0,260.000000,37.828455,5.404065,910.0,130.0,622.010154,88.858593,NaN,NaN,NaN,NaN,8400.0,1200.000000,5741.632187,820.233170,12810.0,1830.000000,8755.989085,1250.855584,98.0,14.000000,14.000000,5.404065,109.536241,NaN,NaN,NaN,14.000000,88.858593,104.539522,NaN,NaN,NaN,14.000000,820.233170,102.529146,14.000000,1250.855584,104.237965,0.0,0.000000,NaN,0.0,0.000000,0.0,0.000000,NaN,NaN,0.0,0.000000,NaN,0.0,0.0,NaN,0.0,0.0,N,N,N,N,N,N,N,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,N,N,N,N,85.0
4,20040249,101,249101006,67.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,2.0,1.0,1.0,1.0,1,1,91.258658,NaN,45.508197,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1252.0,Rectal,1252.0,Rectal,N,Y,Y,N,N,N,N,N,88.0,Failed,N,N,Y,N,Y,Y,Y,Y,Y,N,N,N,N,N,Y,N,N,N,19.0,19.0,9.0,NaN,19.0,19.0,19.0,31.578947,0.526316,10122.0,532.736842,117.638137,6.191481,8435.0,443.947368,98.031780,5.159567,1800.0,200.0,845.838187,93.982021,NaN,NaN,NaN,NaN,15700.0,826.315789,7565.752257,398.197487,86700.0,4563.157895,41755.669950,2197.666839,315.0,45.000000,45.000000,4.356968,88.900688,45.000000,5.228362,87.139360,25.000000,67.667055,67.667055,NaN,NaN,NaN,45.000000,336.255656,84.063914,45.000000,1855.807553,77.325315,2.0,0.105263,0.105263,2.0,0.105263,3.0,0.333333,NaN,NaN,2.0,0.105263,0.0,0.0,0.0,NaN,0.0,0.0,N,N,N,N,N,N,N,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,N,N,N,N,302.0

In [204]:
_ = read_domain('NCT00115225_PACCE_bev_panitumumab_raw', 'ae.sas7bdat')

--- NCT00115225_PACCE_bev_panitumumab_raw/ae.sas7bdat ---
shape: (29080, 102)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'CHEMOCD', 'CHEMO', 'CHEMOICD', 'CHEMOI', 'ACHEMOCD', 'ACHEMO', 'ACHEMMCD', 'ACHEMM', 'FCHEMOCD', 'FCHEMO', 'B_LESNM', 'B_LESNMT', 'B_LESNMN', 'B_METANM', 'B_METACT', 'BMETACTI', 'FSTOXDS', 'FSTIRDS', 'DURSURG', 'PRADJYN', 'PRADJICD', 'PRADJI', 'B_LDHYN', 'B_ECOGCD', 'B_ECOG', 'BECOGICD', 'B_ECOGI', 'DIAGTYCD', 'DIAGTYPE', 'DIAGICD', 'DIAGI', 'RESPSTAT', 'EVALITT', 'EVALPP', 'PDADEN', 'PDICSIG', 'PDICMIS', 'PDPROMED', 'PDYN', 'KRASCD', 'KRAS', 'EVALKEA', 'EVALKSA', 'EVALKUE', 'TRTDUR', 'AEANY', 'AEPAGENO', 'AELINENO', 'PHASE', 'PHASEND', 'AESTDY', 'AESTDYI', 'AEENDY', 'AEENDYI', 'AETERM', 'AELLT', 'AEPT', 'AEHLT', 'AEHLGT', 'AESOC', 'AEDUR', 'AEDURI', 'AECONT', 'AEPRCNT', 'AENUMINF', 'AESEVCD', 'AESEV', 'AEREL', 'AEINFYN', 'AEENDPG', 'AEACTCDS', 'AEACT01', 'AEACT02', 'AEACT03', 'AEACT04', 'AEACT05', 'AEACT06', 'AEACT07', 'AEACT08', 'AEACT09', 'AEACT81', 'AEACT83', 'AEACT85', 'AEACT88', 'AESER', 'SAELIFE', 'MEDDRA_V']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,CHEMOCD,CHEMO,CHEMOICD,CHEMOI,ACHEMOCD,ACHEMO,ACHEMMCD,ACHEMM,FCHEMOCD,FCHEMO,B_LESNM,B_LESNMT,B_LESNMN,B_METANM,B_METACT,BMETACTI,FSTOXDS,FSTIRDS,DURSURG,PRADJYN,PRADJICD,PRADJI,B_LDHYN,B_ECOGCD,B_ECOG,BECOGICD,B_ECOGI,DIAGTYCD,DIAGTYPE,DIAGICD,DIAGI,RESPSTAT,EVALITT,EVALPP,PDADEN,PDICSIG,PDICMIS,PDPROMED,PDYN,KRASCD,KRAS,EVALKEA,EVALKSA,EVALKUE,TRTDUR,AEANY,AEPAGENO,AELINENO,PHASE,PHASEND,AESTDY,AESTDYI,AEENDY,AEENDYI,AETERM,AELLT,AEPT,AEHLT,AEHLGT,AESOC,AEDUR,AEDURI,AECONT,AEPRCNT,AENUMINF,AESEVCD,AESEV,AEREL,AEINFYN,AEENDPG,AEACTCDS,AEACT01,AEACT02,AEACT03,AEACT04,AEACT05,AEACT06,AEACT07,AEACT08,AEACT09,AEACT81,AEACT83,AEACT85,AEACT88,AESER,SAELIFE,MEDDRA_V
0,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,685.0,Y,6.0,1.0,Treatment,Treatment,8.0,8.0,460.0,460.0,ACNE RASH,RASH ACNEIFORM,DERMATITIS ACNEIFORM,ACNES,SKIN APPENDAGE CONDITIONS,SKIN AND SUBCUTANEOUS TISSUE DISORDERS,453.0,453.0,N,N,1.0,1.0,Mild,Y,N,N,1,Y,N,N,N,N,N,N,N,N,N,N,N,N,N,,8.0
1,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,685.0,Y,6.0,5.0,Treatment,Ongoing,14.0,14.0,NaN,NaN,INCREASED THICK SALIVA,SALIVA INCREASED,SALIVARY HYPERSECRETION,SALIVARY GLAND DISORDERS NEC,SALIVARY GLAND CONDITIONS,GASTROINTESTINAL DISORDERS,NaN,NaN,Y,N,2.0,1.0,Mild,Y,N,N,1,Y,N,N,N,N,N,N,N,N,N,N,N,N,N,,8.0
2,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,685.0,Y,6.0,3.0,Treatment,Ongoing,17.0,17.0,NaN,NaN,NAUSEA,NAUSEA,NAUSEA,NAUSEA AND VOMITING SYMPTOMS,GASTROINTESTINAL SIGNS AND SYMPTOMS,GASTROINTESTINAL DISORDERS,NaN,NaN,Y,N,2.0,1.0,Mild,N,N,N,3,N,N,Y,N,N,N,N,N,N,N,N,N,N,N,,8.0
3,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,685.0,Y,6.0,2.0,Treatment,Ongoing,28.0,28.0,NaN,NaN,FATIGUE,FATIGUE,FATIGUE,ASTHENIC CONDITIONS,GENERAL SYSTEM DISORDERS NEC,GENERAL DISORDERS AND ADMINISTRATION SITE COND...,NaN,NaN,Y,N,3.0,2.0,Moderate,Y,N,N,1,Y,N,N,N,N,N,N,N,N,N,N,N,N,N,,8.0
4,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,685.0,Y,6.0,4.0,Treatment,Ongoing,28.0,28.0,NaN,NaN,LEG CRAMPS,LEG CRAMPS,MUSCLE SPASMS,MUSCLE RELATED SIGNS AND SYMPTOMS NEC,MUSCLE DISORDERS,MUSCULOSKELETAL AND CONNECTIVE TISSUE DISORDERS,NaN,NaN,Y,N,3.0,1.0,Mild,N,N,N,88,N,N,N,N,N,N,N,N,N,N,N,N,Y,N,,8.0

In [205]:
_ = read_domain('NCT00115225_PACCE_bev_panitumumab_raw', 'chemotx.sas7bdat')

--- NCT00115225_PACCE_bev_panitumumab_raw/chemotx.sas7bdat ---
shape: (1136, 68)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'CHEMOCD', 'CHEMO', 'CHEMOICD', 'CHEMOI', 'ACHEMOCD', 'ACHEMO', 'ACHEMMCD', 'ACHEMM', 'FCHEMOCD', 'FCHEMO', 'B_LESNM', 'B_LESNMT', 'B_LESNMN', 'B_METANM', 'B_METACT', 'BMETACTI', 'FSTOXDS', 'FSTIRDS', 'DURSURG', 'PRADJYN', 'PRADJICD', 'PRADJI', 'B_LDHYN', 'B_ECOGCD', 'B_ECOG', 'BECOGICD', 'B_ECOGI', 'DIAGTYCD', 'DIAGTYPE', 'DIAGICD', 'DIAGI', 'RESPSTAT', 'EVALITT', 'EVALPP', 'PDADEN', 'PDICSIG', 'PDICMIS', 'PDPROMED', 'PDYN', 'KRASCD', 'KRAS', 'EVALKEA', 'EVALKSA', 'EVALKUE', 'CHANY5YR', 'PHASECD', 'PHASE', 'CHSTDY', 'CHENDY', 'CHREG', 'CHREGPT', 'CHREGCLS', 'TRTDUR']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,CHEMOCD,CHEMO,CHEMOICD,CHEMOI,ACHEMOCD,ACHEMO,ACHEMMCD,ACHEMM,FCHEMOCD,FCHEMO,B_LESNM,B_LESNMT,B_LESNMN,B_METANM,B_METACT,BMETACTI,FSTOXDS,FSTIRDS,DURSURG,PRADJYN,PRADJICD,PRADJI,B_LDHYN,B_ECOGCD,B_ECOG,BECOGICD,B_ECOGI,DIAGTYCD,DIAGTYPE,DIAGICD,DIAGI,RESPSTAT,EVALITT,EVALPP,PDADEN,PDICSIG,PDICMIS,PDPROMED,PDYN,KRASCD,KRAS,EVALKEA,EVALKSA,EVALKUE,CHANY5YR,PHASECD,PHASE,CHSTDY,CHENDY,CHREG,CHREGPT,CHREGCLS,TRTDUR
0,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.573770,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,Y,5.0,Pre-consent,-1046.0,-960.0,SPLIT - FOLFIRI,FLUOROURACIL,PYRIMIDINE ANALOGUES,685.0
1,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.573770,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,Y,5.0,Pre-consent,-1046.0,-960.0,SPLIT - FOLFIRI,FOLINIC ACID,DETOXIFYING AGENTS FOR ANTINEOPLASTIC TREATMENT,685.0
2,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.573770,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,Y,5.0,Pre-consent,-1046.0,-960.0,SPLIT - FOLFIRI,IRINOTECAN,OTHER ANTINEOPLASTIC AGENTS,685.0
3,20040249,101,249101002,72.0,M,Male,1.0,White or Caucasian,0.0,Q2WK,Every 2 weeks,12.0,bevacizumab with chemotherapy,12.0,bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,101.0,2.0,99.0,2.0,>1,>1,90.712273,NaN,44.065574,N,0.0,N,N,1.0,Symptoms but ambulatory,1.0,Symptoms but ambulatory,1251.0,Colon,1251.0,Colon,N,Y,Y,N,N,N,N,N,2.0,Mutant,Y,Y,N,N,10.0,Pre-treatment,NaN,NaN,,,,365.0
4,20040249,101,249101003,78.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,101.0,2.0,99.0,2.0,>1,1,84.244651,NaN,0.000000,N,0.0,N,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,88.0,Failed,N,N,Y,N,10.0,Pre-treatment,NaN,NaN,,,,166.0

In [206]:
_ = read_domain('NCT00115225_PACCE_bev_panitumumab_raw', 'corevar.sas7bdat')

--- NCT00115225_PACCE_bev_panitumumab_raw/corevar.sas7bdat ---
shape: (842, 60)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'CHEMOCD', 'CHEMO', 'CHEMOICD', 'CHEMOI', 'ACHEMOCD', 'ACHEMO', 'ACHEMMCD', 'ACHEMM', 'FCHEMOCD', 'FCHEMO', 'B_LESNM', 'B_LESNMT', 'B_LESNMN', 'B_METANM', 'B_METACT', 'BMETACTI', 'FSTOXDS', 'FSTIRDS', 'DURSURG', 'PRADJYN', 'PRADJICD', 'PRADJI', 'B_LDHYN', 'B_ECOGCD', 'B_ECOG', 'BECOGICD', 'B_ECOGI', 'DIAGTYCD', 'DIAGTYPE', 'DIAGICD', 'DIAGI', 'RESPSTAT', 'EVALITT', 'EVALPP', 'PDADEN', 'PDICSIG', 'PDICMIS', 'PDPROMED', 'PDYN', 'KRASCD', 'KRAS', 'EVALKEA', 'EVALKSA', 'EVALKUE', 'TRTDUR']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,CHEMOCD,CHEMO,CHEMOICD,CHEMOI,ACHEMOCD,ACHEMO,ACHEMMCD,ACHEMM,FCHEMOCD,FCHEMO,B_LESNM,B_LESNMT,B_LESNMN,B_METANM,B_METACT,BMETACTI,FSTOXDS,FSTIRDS,DURSURG,PRADJYN,PRADJICD,PRADJI,B_LDHYN,B_ECOGCD,B_ECOG,BECOGICD,B_ECOGI,DIAGTYCD,DIAGTYPE,DIAGICD,DIAGI,RESPSTAT,EVALITT,EVALPP,PDADEN,PDICSIG,PDICMIS,PDPROMED,PDYN,KRASCD,KRAS,EVALKEA,EVALKSA,EVALKUE,TRTDUR
0,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.573770,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,685.0
1,20040249,101,249101002,72.0,M,Male,1.0,White or Caucasian,0.0,Q2WK,Every 2 weeks,12.0,bevacizumab with chemotherapy,12.0,bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,101.0,2.0,99.0,2.0,>1,>1,90.712273,NaN,44.065574,N,0.0,N,N,1.0,Symptoms but ambulatory,1.0,Symptoms but ambulatory,1251.0,Colon,1251.0,Colon,N,Y,Y,N,N,N,N,N,2.0,Mutant,Y,Y,N,365.0
2,20040249,101,249101003,78.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,101.0,2.0,99.0,2.0,>1,1,84.244651,NaN,0.000000,N,0.0,N,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,88.0,Failed,N,N,Y,166.0
3,20040249,101,249101005,66.0,F,Female,2.0,Black or African American,0.0,Q2WK,Every 2 weeks,12.0,bevacizumab with chemotherapy,12.0,bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,101.0,2.0,99.0,2.0,>1,>1,84.943334,NaN,-0.032787,N,0.0,N,N,1.0,Symptoms but ambulatory,1.0,Symptoms but ambulatory,1251.0,Colon,1251.0,Colon,N,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,85.0
4,20040249,101,249101006,67.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,2.0,1.0,1.0,1.0,1,1,91.258658,NaN,45.508197,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1252.0,Rectal,1252.0,Rectal,N,Y,Y,N,N,N,N,N,88.0,Failed,N,N,Y,302.0

In [207]:
_ = read_domain('NCT00115225_PACCE_bev_panitumumab_raw', 'death.sas7bdat')

--- NCT00115225_PACCE_bev_panitumumab_raw/death.sas7bdat ---
shape: (472, 67)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'CHEMOCD', 'CHEMO', 'CHEMOICD', 'CHEMOI', 'ACHEMOCD', 'ACHEMO', 'ACHEMMCD', 'ACHEMM', 'FCHEMOCD', 'FCHEMO', 'B_LESNM', 'B_LESNMT', 'B_LESNMN', 'B_METANM', 'B_METACT', 'BMETACTI', 'FSTOXDS', 'FSTIRDS', 'DURSURG', 'PRADJYN', 'PRADJICD', 'PRADJI', 'B_LDHYN', 'B_ECOGCD', 'B_ECOG', 'BECOGICD', 'B_ECOGI', 'DIAGTYCD', 'DIAGTYPE', 'DIAGICD', 'DIAGI', 'RESPSTAT', 'EVALITT', 'EVALPP', 'PDADEN', 'PDICSIG', 'PDICMIS', 'PDPROMED', 'PDYN', 'KRASCD', 'KRAS', 'EVALKEA', 'EVALKSA', 'EVALKUE', 'DTHDY', 'DTHDYI', 'PHASECD', 'PHASE', 'DTCAUSCD', 'DTCAUS', 'DTAEPT', 'TRTDUR']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,CHEMOCD,CHEMO,CHEMOICD,CHEMOI,ACHEMOCD,ACHEMO,ACHEMMCD,ACHEMM,FCHEMOCD,FCHEMO,B_LESNM,B_LESNMT,B_LESNMN,B_METANM,B_METACT,BMETACTI,FSTOXDS,FSTIRDS,DURSURG,PRADJYN,PRADJICD,PRADJI,B_LDHYN,B_ECOGCD,B_ECOG,BECOGICD,B_ECOGI,DIAGTYCD,DIAGTYPE,DIAGICD,DIAGI,RESPSTAT,EVALITT,EVALPP,PDADEN,PDICSIG,PDICMIS,PDPROMED,PDYN,KRASCD,KRAS,EVALKEA,EVALKSA,EVALKUE,DTHDY,DTHDYI,PHASECD,PHASE,DTCAUSCD,DTCAUS,DTAEPT,TRTDUR
0,20040249,101,249101002,72.0,M,Male,1.0,White or Caucasian,0.0,Q2WK,Every 2 weeks,12.0,bevacizumab with chemotherapy,12.0,bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,101.0,2.0,99.0,2.0,>1,>1,90.712273,NaN,44.065574,N,0.0,N,N,1.0,Symptoms but ambulatory,1.0,Symptoms but ambulatory,1251.0,Colon,1251.0,Colon,N,Y,Y,N,N,N,N,N,2.0,Mutant,Y,Y,N,478.0,478.0,60.0,Long-term follow-up,88.0,Other,,365.0
1,20040249,101,249101003,78.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,101.0,2.0,99.0,2.0,>1,1,84.244651,NaN,0.000000,N,0.0,N,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,88.0,Failed,N,N,Y,196.0,196.0,50.0,Short-term/safety follow-up,88.0,Other,CARDIO-RESPIRATORY ARREST,166.0
2,20040249,101,249101005,66.0,F,Female,2.0,Black or African American,0.0,Q2WK,Every 2 weeks,12.0,bevacizumab with chemotherapy,12.0,bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,101.0,2.0,99.0,2.0,>1,>1,84.943334,NaN,-0.032787,N,0.0,N,N,1.0,Symptoms but ambulatory,1.0,Symptoms but ambulatory,1251.0,Colon,1251.0,Colon,N,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,98.0,98.0,30.0,Treatment,88.0,Other,CARDIAC ARREST,85.0
3,20040249,101,249101006,67.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,2.0,1.0,1.0,1.0,1,1,91.258658,NaN,45.508197,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1252.0,Rectal,1252.0,Rectal,N,Y,Y,N,N,N,N,N,88.0,Failed,N,N,Y,954.0,954.0,60.0,Long-term follow-up,7.0,Disease progression,,302.0
4,20040249,101,249101007,70.0,M,Male,1.0,White or Caucasian,0.0,Q2WK,Every 2 weeks,12.0,bevacizumab with chemotherapy,12.0,bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,1.0,1.0,0.0,1.0,1,1,82.277770,NaN,51.180328,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,N,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,686.0,686.0,60.0,Long-term follow-up,7.0,Disease progression,,512.0

In [208]:
_ = read_domain('NCT00115225_PACCE_bev_panitumumab_raw', 'demo.sas7bdat')

--- NCT00115225_PACCE_bev_panitumumab_raw/demo.sas7bdat ---
shape: (842, 76)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'CHEMOCD', 'CHEMO', 'CHEMOICD', 'CHEMOI', 'ACHEMOCD', 'ACHEMO', 'ACHEMMCD', 'ACHEMM', 'FCHEMOCD', 'FCHEMO', 'B_LESNM', 'B_LESNMT', 'B_LESNMN', 'B_METANM', 'B_METACT', 'BMETACTI', 'FSTOXDS', 'FSTIRDS', 'DURSURG', 'PRADJYN', 'PRADJICD', 'PRADJI', 'B_LDHYN', 'B_ECOGCD', 'B_ECOG', 'BECOGICD', 'B_ECOGI', 'DIAGTYCD', 'DIAGTYPE', 'DIAGICD', 'DIAGI', 'RESPSTAT', 'EVALITT', 'EVALPP', 'PDADEN', 'PDICSIG', 'PDICMIS', 'PDPROMED', 'PDYN', 'KRASCD', 'KRAS', 'EVALKEA', 'EVALKSA', 'EVALKUE', 'B_WEIGHT', 'B_HEIGHT', 'B_BSA', 'DIAGMONS', 'METMONS', 'BIOPTISB', 'BIOPTISS', 'BIOPSITP', 'BIOPSITM', 'CHILDPOT', 'PREGTYCD', 'PREGTYPE', 'PREGRSCD', 'PREGRES', 'TRTDUR', 'BIOPDY', 'PREGDY']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,CHEMOCD,CHEMO,CHEMOICD,CHEMOI,ACHEMOCD,ACHEMO,ACHEMMCD,ACHEMM,FCHEMOCD,FCHEMO,B_LESNM,B_LESNMT,B_LESNMN,B_METANM,B_METACT,BMETACTI,FSTOXDS,FSTIRDS,DURSURG,PRADJYN,PRADJICD,PRADJI,B_LDHYN,B_ECOGCD,B_ECOG,BECOGICD,B_ECOGI,DIAGTYCD,DIAGTYPE,DIAGICD,DIAGI,RESPSTAT,EVALITT,EVALPP,PDADEN,PDICSIG,PDICMIS,PDPROMED,PDYN,KRASCD,KRAS,EVALKEA,EVALKSA,EVALKUE,B_WEIGHT,B_HEIGHT,B_BSA,DIAGMONS,METMONS,BIOPTISB,BIOPTISS,BIOPSITP,BIOPSITM,CHILDPOT,PREGTYCD,PREGTYPE,PREGRSCD,PREGRES,TRTDUR,BIOPDY,PREGDY
0,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.573770,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,73.4,167.60,1.848561,76.983607,2.032787,Y,N,N,Y,N,NaN,,NaN,,685.0,-2351.0,NaN
1,20040249,101,249101002,72.0,M,Male,1.0,White or Caucasian,0.0,Q2WK,Every 2 weeks,12.0,bevacizumab with chemotherapy,12.0,bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,101.0,2.0,99.0,2.0,>1,>1,90.712273,NaN,44.065574,N,0.0,N,N,1.0,Symptoms but ambulatory,1.0,Symptoms but ambulatory,1251.0,Colon,1251.0,Colon,N,Y,Y,N,N,N,N,N,2.0,Mutant,Y,Y,N,77.5,182.90,1.984296,45.180328,1.114754,Y,N,N,Y,N,NaN,,NaN,,365.0,-1382.0,NaN
2,20040249,101,249101003,78.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,101.0,2.0,99.0,2.0,>1,1,84.244651,NaN,0.000000,N,0.0,N,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,88.0,Failed,N,N,Y,89.0,184.66,2.136634,0.557377,0.557377,N,Y,Y,N,N,NaN,,NaN,,166.0,-17.0,NaN
3,20040249,101,249101005,66.0,F,Female,2.0,Black or African American,0.0,Q2WK,Every 2 weeks,12.0,bevacizumab with chemotherapy,12.0,bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,101.0,2.0,99.0,2.0,>1,>1,84.943334,NaN,-0.032787,N,0.0,N,N,1.0,Symptoms but ambulatory,1.0,Symptoms but ambulatory,1251.0,Colon,1251.0,Colon,N,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,52.7,160.00,1.530432,1.508197,1.508197,Y,Y,Y,Y,N,NaN,,NaN,,85.0,-46.0,NaN
4,20040249,101,249101006,67.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,2.0,1.0,1.0,1.0,1,1,91.258658,NaN,45.508197,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1252.0,Rectal,1252.0,Rectal,N,Y,Y,N,N,N,N,N,88.0,Failed,N,N,Y,95.9,180.30,2.191573,46.393443,4.393443,Y,N,Y,N,N,NaN,,NaN,,302.0,-1329.0,NaN

In [209]:
_ = read_domain('NCT00115225_PACCE_bev_panitumumab_raw', 'disposit.sas7bdat')

--- NCT00115225_PACCE_bev_panitumumab_raw/disposit.sas7bdat ---
shape: (842, 87)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'CHEMOCD', 'CHEMO', 'CHEMOICD', 'CHEMOI', 'ACHEMOCD', 'ACHEMO', 'ACHEMMCD', 'ACHEMM', 'FCHEMOCD', 'FCHEMO', 'B_LESNM', 'B_LESNMT', 'B_LESNMN', 'B_METANM', 'B_METACT', 'BMETACTI', 'FSTOXDS', 'FSTIRDS', 'DURSURG', 'PRADJYN', 'PRADJICD', 'PRADJI', 'B_LDHYN', 'B_ECOGCD', 'B_ECOG', 'BECOGICD', 'B_ECOGI', 'DIAGTYCD', 'DIAGTYPE', 'DIAGICD', 'DIAGI', 'RESPSTAT', 'EVALITT', 'EVALPP', 'PDADEN', 'PDICSIG', 'PDICMIS', 'PDPROMED', 'PDYN', 'KRASCD', 'KRAS', 'EVALKEA', 'EVALKSA', 'EVALKUE', 'ICSIGN', 'LDOSDSDY', 'EOIPCD', 'EOIP', 'EOTACD', 'EOTA', 'EOBCD', 'EOB', 'EOOXIRCD', 'EOOXIR', 'EOLEUCCD', 'EOLEUC', 'EO5FUBCD', 'EO5FUB', 'EO5FUICD', 'DSDOSDY', 'DSEOSYN', 'DSEOSCD', 'DSEOS', 'TRTDUR', 'LASTOSDY', 'EOSDY', 'EO5FIDY', 'EO5FBDY', 'EOLEUDY', 'EOXIRDY', 'EOBDY', 'EOIPDY']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,CHEMOCD,CHEMO,CHEMOICD,CHEMOI,ACHEMOCD,ACHEMO,ACHEMMCD,ACHEMM,FCHEMOCD,FCHEMO,B_LESNM,B_LESNMT,B_LESNMN,B_METANM,B_METACT,BMETACTI,FSTOXDS,FSTIRDS,DURSURG,PRADJYN,PRADJICD,PRADJI,B_LDHYN,B_ECOGCD,B_ECOG,BECOGICD,B_ECOGI,DIAGTYCD,DIAGTYPE,DIAGICD,DIAGI,RESPSTAT,EVALITT,EVALPP,PDADEN,PDICSIG,PDICMIS,PDPROMED,PDYN,KRASCD,KRAS,EVALKEA,EVALKSA,EVALKUE,ICSIGN,LDOSDSDY,EOIPCD,EOIP,EOTACD,EOTA,EOBCD,EOB,EOOXIRCD,EOOXIR,EOLEUCCD,EOLEUC,EO5FUBCD,EO5FUB,EO5FUICD,DSDOSDY,DSEOSYN,DSEOSCD,DSEOS,TRTDUR,LASTOSDY,EOSDY,EO5FIDY,EO5FBDY,EOLEUDY,EOXIRDY,EOBDY,EOIPDY
0,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.573770,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,Y,685.0,88.0,Other,7.0,Disease progression,88.0,Other,88.0,Other,88.0,Other,88.0,Other,88.0,712.0,Y,9.0,Administrative decision,685.0,1505.0,1505.0,281.0,281.0,281.0,281.0,685.0,685.0
1,20040249,101,249101002,72.0,M,Male,1.0,White or Caucasian,0.0,Q2WK,Every 2 weeks,12.0,bevacizumab with chemotherapy,12.0,bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,101.0,2.0,99.0,2.0,>1,>1,90.712273,NaN,44.065574,N,0.0,N,N,1.0,Symptoms but ambulatory,1.0,Symptoms but ambulatory,1251.0,Colon,1251.0,Colon,N,Y,Y,N,N,N,N,N,2.0,Mutant,Y,Y,N,Y,365.0,NaN,,7.0,Disease progression,88.0,Other,5.0,Adverse event,88.0,Other,88.0,Other,5.0,411.0,Y,11.0,Death,365.0,478.0,478.0,295.0,365.0,365.0,197.0,365.0,NaN
2,20040249,101,249101003,78.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,101.0,2.0,99.0,2.0,>1,1,84.244651,NaN,0.000000,N,0.0,N,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,88.0,Failed,N,N,Y,Y,166.0,5.0,Adverse event,5.0,Adverse event,5.0,Adverse event,5.0,Adverse event,5.0,Adverse event,5.0,Adverse event,5.0,NaN,Y,11.0,Death,166.0,196.0,196.0,191.0,191.0,191.0,191.0,191.0,191.0
3,20040249,101,249101005,66.0,F,Female,2.0,Black or African American,0.0,Q2WK,Every 2 weeks,12.0,bevacizumab with chemotherapy,12.0,bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,101.0,2.0,99.0,2.0,>1,>1,84.943334,NaN,-0.032787,N,0.0,N,N,1.0,Symptoms but ambulatory,1.0,Symptoms but ambulatory,1251.0,Colon,1251.0,Colon,N,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,Y,85.0,NaN,,11.0,Death,5.0,Adverse event,5.0,Adverse event,5.0,Adverse event,5.0,Adverse event,5.0,NaN,Y,11.0,Death,85.0,98.0,98.0,98.0,98.0,98.0,98.0,98.0,NaN
4,20040249,101,249101006,67.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,2.0,1.0,1.0,1.0,1,1,91.258658,NaN,45.508197,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1252.0,Rectal,1252.0,Rectal,N,Y,Y,N,N,N,N,N,88.0,Failed,N,N,Y,Y,302.0,88.0,Other,7.0,Disease progression,88.0,Other,5.0,Adverse event,88.0,Other,88.0,Other,88.0,330.0,Y,11.0,Death,302.0,954.0,954.0,344.0,344.0,344.0,211.0,344.0,344.0

In [210]:
_ = read_domain('NCT00115225_PACCE_bev_panitumumab_raw', 'eligcrit.sas7bdat')

--- NCT00115225_PACCE_bev_panitumumab_raw/eligcrit.sas7bdat ---
shape: (848, 63)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'CHEMOCD', 'CHEMO', 'CHEMOICD', 'CHEMOI', 'ACHEMOCD', 'ACHEMO', 'ACHEMMCD', 'ACHEMM', 'FCHEMOCD', 'FCHEMO', 'B_LESNM', 'B_LESNMT', 'B_LESNMN', 'B_METANM', 'B_METACT', 'BMETACTI', 'FSTOXDS', 'FSTIRDS', 'DURSURG', 'PRADJYN', 'PRADJICD', 'PRADJI', 'B_LDHYN', 'B_ECOGCD', 'B_ECOG', 'BECOGICD', 'B_ECOGI', 'DIAGTYCD', 'DIAGTYPE', 'DIAGICD', 'DIAGI', 'RESPSTAT', 'EVALITT', 'EVALPP', 'PDADEN', 'PDICSIG', 'PDICMIS', 'PDPROMED', 'PDYN', 'KRASCD', 'KRAS', 'EVALKEA', 'EVALKSA', 'EVALKUE', 'ELIGIBLE', 'ELIGNMCD', 'ELIGNM', 'TRTDUR']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,CHEMOCD,CHEMO,CHEMOICD,CHEMOI,ACHEMOCD,ACHEMO,ACHEMMCD,ACHEMM,FCHEMOCD,FCHEMO,B_LESNM,B_LESNMT,B_LESNMN,B_METANM,B_METACT,BMETACTI,FSTOXDS,FSTIRDS,DURSURG,PRADJYN,PRADJICD,PRADJI,B_LDHYN,B_ECOGCD,B_ECOG,BECOGICD,B_ECOGI,DIAGTYCD,DIAGTYPE,DIAGICD,DIAGI,RESPSTAT,EVALITT,EVALPP,PDADEN,PDICSIG,PDICMIS,PDPROMED,PDYN,KRASCD,KRAS,EVALKEA,EVALKSA,EVALKUE,ELIGIBLE,ELIGNMCD,ELIGNM,TRTDUR
0,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.573770,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,Y,NaN,,685.0
1,20040249,101,249101002,72.0,M,Male,1.0,White or Caucasian,0.0,Q2WK,Every 2 weeks,12.0,bevacizumab with chemotherapy,12.0,bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,101.0,2.0,99.0,2.0,>1,>1,90.712273,NaN,44.065574,N,0.0,N,N,1.0,Symptoms but ambulatory,1.0,Symptoms but ambulatory,1251.0,Colon,1251.0,Colon,N,Y,Y,N,N,N,N,N,2.0,Mutant,Y,Y,N,Y,NaN,,365.0
2,20040249,101,249101003,78.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,101.0,2.0,99.0,2.0,>1,1,84.244651,NaN,0.000000,N,0.0,N,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,88.0,Failed,N,N,Y,Y,NaN,,166.0
3,20040249,101,249101005,66.0,F,Female,2.0,Black or African American,0.0,Q2WK,Every 2 weeks,12.0,bevacizumab with chemotherapy,12.0,bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,101.0,2.0,99.0,2.0,>1,>1,84.943334,NaN,-0.032787,N,0.0,N,N,1.0,Symptoms but ambulatory,1.0,Symptoms but ambulatory,1251.0,Colon,1251.0,Colon,N,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,Y,NaN,,85.0
4,20040249,101,249101006,67.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,2.0,1.0,1.0,1.0,1,1,91.258658,NaN,45.508197,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1252.0,Rectal,1252.0,Rectal,N,Y,Y,N,N,N,N,N,88.0,Failed,N,N,Y,Y,NaN,,302.0

In [211]:
_ = read_domain('NCT00115225_PACCE_bev_panitumumab_raw', 'exposure.sas7bdat')

--- NCT00115225_PACCE_bev_panitumumab_raw/exposure.sas7bdat ---
shape: (85583, 94)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'CHEMOCD', 'CHEMO', 'CHEMOICD', 'CHEMOI', 'ACHEMOCD', 'ACHEMO', 'ACHEMMCD', 'ACHEMM', 'FCHEMOCD', 'FCHEMO', 'B_LESNM', 'B_LESNMT', 'B_LESNMN', 'B_METANM', 'B_METACT', 'BMETACTI', 'FSTOXDS', 'FSTIRDS', 'DURSURG', 'PRADJYN', 'PRADJICD', 'PRADJI', 'B_LDHYN', 'B_ECOGCD', 'B_ECOG', 'BECOGICD', 'B_ECOGI', 'DIAGTYCD', 'DIAGTYPE', 'DIAGICD', 'DIAGI', 'RESPSTAT', 'EVALITT', 'EVALPP', 'PDADEN', 'PDICSIG', 'PDICMIS', 'PDPROMED', 'PDYN', 'KRASCD', 'KRAS', 'EVALKEA', 'EVALKSA', 'EVALKUE', 'DOSREFDY', 'DOSREFWK', 'VISITCD', 'VISIT', 'PHASECD', 'PHASE', 'EXENDY', 'EXDUR', 'EXDURHR', 'EXDURMN', 'ACTTRTCD', 'ACTTRT', 'QTY', 'CONC', 'DOSE', 'DOSEUNCD', 'DOSEUNIT', 'WDOSE', 'WDOSUNCD', 'WDOSUNIT', 'BSADOSE', 'ROUTECD', 'ROUTE', 'DOSCHGYN', 'DOSND', 'DOSNA', 'EXREASCD', 'EXREAS', 'EXREASSP', 'EXINTCD', 'EXINT', 'EXCYCLDY', 'EXCYCLNM', 'EXAEANY', 'TRTDUR']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,CHEMOCD,CHEMO,CHEMOICD,CHEMOI,ACHEMOCD,ACHEMO,ACHEMMCD,ACHEMM,FCHEMOCD,FCHEMO,B_LESNM,B_LESNMT,B_LESNMN,B_METANM,B_METACT,BMETACTI,FSTOXDS,FSTIRDS,DURSURG,PRADJYN,PRADJICD,PRADJI,B_LDHYN,B_ECOGCD,B_ECOG,BECOGICD,B_ECOGI,DIAGTYCD,DIAGTYPE,DIAGICD,DIAGI,RESPSTAT,EVALITT,EVALPP,PDADEN,PDICSIG,PDICMIS,PDPROMED,PDYN,KRASCD,KRAS,EVALKEA,EVALKSA,EVALKUE,DOSREFDY,DOSREFWK,VISITCD,VISIT,PHASECD,PHASE,EXENDY,EXDUR,EXDURHR,EXDURMN,ACTTRTCD,ACTTRT,QTY,CONC,DOSE,DOSEUNCD,DOSEUNIT,WDOSE,WDOSUNCD,WDOSUNIT,BSADOSE,ROUTECD,ROUTE,DOSCHGYN,DOSND,DOSNA,EXREASCD,EXREAS,EXREASSP,EXINTCD,EXINT,EXCYCLDY,EXCYCLNM,EXAEANY,TRTDUR
0,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,NaN,NaN,UNSCHEDULED,Unscheduled visit,30.0,Treatment,NaN,NaN,NaN,NaN,72.0,Irinotecan,NaN,NaN,NaN,,,NaN,,,NaN,IV,Intravenous,N,,Y,NaN,,,NaN,,NaN,NaN,,685.0
1,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,NaN,NaN,UNSCHEDULED,Unscheduled visit,30.0,Treatment,NaN,NaN,NaN,NaN,72.0,Irinotecan,NaN,NaN,NaN,,,NaN,,,NaN,IV,Intravenous,N,,Y,NaN,,,NaN,,NaN,NaN,,685.0
2,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,NaN,NaN,UNSCHEDULED,Unscheduled visit,30.0,Treatment,NaN,NaN,NaN,NaN,72.0,Irinotecan,NaN,NaN,NaN,,,NaN,,,NaN,IV,Intravenous,N,,Y,NaN,,,NaN,,NaN,NaN,,685.0
3,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,NaN,NaN,UNSCHEDULED,Unscheduled visit,30.0,Treatment,NaN,NaN,NaN,NaN,72.0,Irinotecan,NaN,NaN,NaN,,,NaN,,,NaN,IV,Intravenous,N,,Y,NaN,,,NaN,,NaN,NaN,,685.0
4,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,NaN,NaN,UNSCHEDULED,Unscheduled visit,30.0,Treatment,NaN,NaN,NaN,NaN,72.0,Irinotecan,NaN,NaN,NaN,,,NaN,,,NaN,IV,Intravenous,N,,Y,NaN,,,NaN,,NaN,NaN,,685.0

In [212]:
_ = read_domain('NCT00115225_PACCE_bev_panitumumab_raw', 'lab.sas7bdat')

--- NCT00115225_PACCE_bev_panitumumab_raw/lab.sas7bdat ---
shape: (118749, 92)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'CHEMOCD', 'CHEMO', 'CHEMOICD', 'CHEMOI', 'ACHEMOCD', 'ACHEMO', 'ACHEMMCD', 'ACHEMM', 'FCHEMOCD', 'FCHEMO', 'B_LESNM', 'B_LESNMT', 'B_LESNMN', 'B_METANM', 'B_METACT', 'BMETACTI', 'FSTOXDS', 'FSTIRDS', 'DURSURG', 'PRADJYN', 'PRADJICD', 'PRADJI', 'B_LDHYN', 'B_ECOGCD', 'B_ECOG', 'BECOGICD', 'B_ECOGI', 'DIAGTYCD', 'DIAGTYPE', 'DIAGICD', 'DIAGI', 'RESPSTAT', 'EVALITT', 'EVALPP', 'PDADEN', 'PDICSIG', 'PDICMIS', 'PDPROMED', 'PDYN', 'KRASCD', 'KRAS', 'EVALKEA', 'EVALKSA', 'EVALKUE', 'DOSREFDY', 'DOSREFWK', 'VISITCD', 'VISIT', 'PHASECD', 'PHASE', 'LBREPEAT', 'LBTYPECD', 'LBTYPE', 'LBPANEL', 'LBACCNO', 'LBTESTCD', 'LBTEST', 'LBSTRESN', 'LBSTRESC', 'LBSTUNIT', 'LBSTNRLO', 'LBSTNRHI', 'LBNRINCD', 'LBNRIND', 'LBORRESN', 'LBORUNIT', 'LBORNRLO', 'LBORNRHI', 'LBBASE', 'LBBLRES', 'LBCHGBL', 'LBGRDINC', 'LBGRDDEC', 'LBMIN', 'LBMAX', 'LBLAST', 'TRTDUR']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,CHEMOCD,CHEMO,CHEMOICD,CHEMOI,ACHEMOCD,ACHEMO,ACHEMMCD,ACHEMM,FCHEMOCD,FCHEMO,B_LESNM,B_LESNMT,B_LESNMN,B_METANM,B_METACT,BMETACTI,FSTOXDS,FSTIRDS,DURSURG,PRADJYN,PRADJICD,PRADJI,B_LDHYN,B_ECOGCD,B_ECOG,BECOGICD,B_ECOGI,DIAGTYCD,DIAGTYPE,DIAGICD,DIAGI,RESPSTAT,EVALITT,EVALPP,PDADEN,PDICSIG,PDICMIS,PDPROMED,PDYN,KRASCD,KRAS,EVALKEA,EVALKSA,EVALKUE,DOSREFDY,DOSREFWK,VISITCD,VISIT,PHASECD,PHASE,LBREPEAT,LBTYPECD,LBTYPE,LBPANEL,LBACCNO,LBTESTCD,LBTEST,LBSTRESN,LBSTRESC,LBSTUNIT,LBSTNRLO,LBSTNRHI,LBNRINCD,LBNRIND,LBORRESN,LBORUNIT,LBORNRLO,LBORNRHI,LBBASE,LBBLRES,LBCHGBL,LBGRDINC,LBGRDDEC,LBMIN,LBMAX,LBLAST,TRTDUR
0,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,-9.0,-2.0,SCR,Screening,10.0,Pre-treatment,1.0,1.0,Central,BASO_P,55105098485,BASO_P,BASO_P,0.0,0,%,0.0,3.0,,,0.0,%,0.0,3.0,Y,0.0,NaN,NaN,NaN,N,N,N,685.0
1,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,86.0,13.0,W12,Week 12,30.0,Treatment,1.0,1.0,Central,BASO_P,55105222804,BASO_P,BASO_P,0.0,0,%,0.0,3.0,,,0.0,%,0.0,3.0,N,0.0,0.0,NaN,NaN,Y,N,N,685.0
2,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,140.0,20.0,W18,Week 18,30.0,Treatment,1.0,1.0,Central,BASO_P,55105292962,BASO_P,BASO_P,0.0,0,%,0.0,3.0,,,0.0,%,0.0,3.0,N,0.0,0.0,NaN,NaN,N,N,N,685.0
3,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,181.0,26.0,W24,Week 24,30.0,Treatment,1.0,1.0,Central,BASO_P,55105336726,BASO_P,BASO_P,0.0,0,%,0.0,3.0,,,0.0,%,0.0,3.0,N,0.0,0.0,NaN,NaN,N,N,N,685.0
4,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,295.0,43.0,W36,Week 36,30.0,Treatment,1.0,1.0,Central,BASO_P,55106017567,BASO_P,BASO_P,0.0,0,%,0.0,3.0,,,0.0,%,0.0,3.0,N,0.0,0.0,NaN,NaN,N,N,N,685.0

In [213]:
_ = read_domain('NCT00115225_PACCE_bev_panitumumab_raw', 'lesion.sas7bdat')

--- NCT00115225_PACCE_bev_panitumumab_raw/lesion.sas7bdat ---
shape: (30153, 89)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'CHEMOCD', 'CHEMO', 'CHEMOICD', 'CHEMOI', 'ACHEMOCD', 'ACHEMO', 'ACHEMMCD', 'ACHEMM', 'FCHEMOCD', 'FCHEMO', 'B_LESNM', 'B_LESNMT', 'B_LESNMN', 'B_METANM', 'B_METACT', 'BMETACTI', 'FSTOXDS', 'FSTIRDS', 'DURSURG', 'PRADJYN', 'PRADJICD', 'PRADJI', 'B_LDHYN', 'B_ECOGCD', 'B_ECOG', 'BECOGICD', 'B_ECOGI', 'DIAGTYCD', 'DIAGTYPE', 'DIAGICD', 'DIAGI', 'RESPSTAT', 'EVALITT', 'EVALPP', 'PDADEN', 'PDICSIG', 'PDICMIS', 'PDPROMED', 'PDYN', 'KRASCD', 'KRAS', 'EVALKEA', 'EVALKSA', 'EVALKUE', 'DOSREFDY', 'DOSREFWK', 'VISITCD', 'VISIT', 'PHASECD', 'PHASE', 'LSTYPECD', 'LSTYPE', 'LSCATCD', 'LSCAT', 'LSNO', 'LSSITECD', 'LSSITE', 'LSPROCCD', 'LSPROC', 'LSRAWCD', 'LSRAW', 'LSNEW', 'LSNEWANY', 'LSNUM', 'LSLD', 'LSSLD', 'LSSLDPCH', 'LSSLDPCN', 'LSRESPCD', 'LSRESP', 'LSEXAMNO', 'LSIMAGNO', 'LSRI', 'TRTDUR']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,CHEMOCD,CHEMO,CHEMOICD,CHEMOI,ACHEMOCD,ACHEMO,ACHEMMCD,ACHEMM,FCHEMOCD,FCHEMO,B_LESNM,B_LESNMT,B_LESNMN,B_METANM,B_METACT,BMETACTI,FSTOXDS,FSTIRDS,DURSURG,PRADJYN,PRADJICD,PRADJI,B_LDHYN,B_ECOGCD,B_ECOG,BECOGICD,B_ECOGI,DIAGTYCD,DIAGTYPE,DIAGICD,DIAGI,RESPSTAT,EVALITT,EVALPP,PDADEN,PDICSIG,PDICMIS,PDPROMED,PDYN,KRASCD,KRAS,EVALKEA,EVALKSA,EVALKUE,DOSREFDY,DOSREFWK,VISITCD,VISIT,PHASECD,PHASE,LSTYPECD,LSTYPE,LSCATCD,LSCAT,LSNO,LSSITECD,LSSITE,LSPROCCD,LSPROC,LSRAWCD,LSRAW,LSNEW,LSNEWANY,LSNUM,LSLD,LSSLD,LSSLDPCH,LSSLDPCN,LSRESPCD,LSRESP,LSEXAMNO,LSIMAGNO,LSRI,TRTDUR
0,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,-8.0,-2.0,SCR,Screening,10.0,Pre-treatment,1.0,Central,NaN,,NaN,NaN,,46.0,CT pelvis,NaN,,,N,NaN,NaN,51.0,NaN,NaN,NaN,,3.0,,7.0,685.0
1,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,-8.0,-2.0,SCR,Screening,10.0,Pre-treatment,2.0,Local,1.0,Target lesion,1.0,812.0,Lung,23.0,Spiral CT,NaN,,N,N,1.0,NaN,NaN,NaN,NaN,NaN,,NaN,,NaN,685.0
2,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,-8.0,-2.0,SCR,Screening,10.0,Pre-treatment,1.0,Central,2.0,Non-target lesion,202.0,811.0,Liver,41.0,CT abdomen,262.0,Liver mass/nodule,N,N,NaN,NaN,51.0,NaN,NaN,NaN,,2.0,16,7.0,685.0
3,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,-2.0,-1.0,SCR,Screening,10.0,Pre-treatment,1.0,Central,1.0,Target lesion,1.0,897.0,Pulmonary,40.0,CT chest,257.0,Right Lung mass/nodule,N,N,NaN,13.0,51.0,NaN,NaN,NaN,,1.0,10,5.0,685.0
4,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,-2.0,-1.0,SCR,Screening,10.0,Pre-treatment,2.0,Local,2.0,Non-target lesion,1.0,812.0,Lung,23.0,Spiral CT,NaN,,N,N,99.0,NaN,NaN,NaN,NaN,NaN,,NaN,,NaN,685.0

In [214]:
_ = read_domain('NCT00115225_PACCE_bev_panitumumab_raw', 'medhist.sas7bdat')

--- NCT00115225_PACCE_bev_panitumumab_raw/medhist.sas7bdat ---
shape: (16840, 65)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'CHEMOCD', 'CHEMO', 'CHEMOICD', 'CHEMOI', 'ACHEMOCD', 'ACHEMO', 'ACHEMMCD', 'ACHEMM', 'FCHEMOCD', 'FCHEMO', 'B_LESNM', 'B_LESNMT', 'B_LESNMN', 'B_METANM', 'B_METACT', 'BMETACTI', 'FSTOXDS', 'FSTIRDS', 'DURSURG', 'PRADJYN', 'PRADJICD', 'PRADJI', 'B_LDHYN', 'B_ECOGCD', 'B_ECOG', 'BECOGICD', 'B_ECOGI', 'DIAGTYCD', 'DIAGTYPE', 'DIAGICD', 'DIAGI', 'RESPSTAT', 'EVALITT', 'EVALPP', 'PDADEN', 'PDICSIG', 'PDICMIS', 'PDPROMED', 'PDYN', 'KRASCD', 'KRAS', 'EVALKEA', 'EVALKSA', 'EVALKUE', 'MHANY', 'MHTERM', 'MHSTATCD', 'MHSTAT', 'TRTDUR', 'DOSREFDY']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,CHEMOCD,CHEMO,CHEMOICD,CHEMOI,ACHEMOCD,ACHEMO,ACHEMMCD,ACHEMM,FCHEMOCD,FCHEMO,B_LESNM,B_LESNMT,B_LESNMN,B_METANM,B_METACT,BMETACTI,FSTOXDS,FSTIRDS,DURSURG,PRADJYN,PRADJICD,PRADJI,B_LDHYN,B_ECOGCD,B_ECOG,BECOGICD,B_ECOGI,DIAGTYCD,DIAGTYPE,DIAGICD,DIAGI,RESPSTAT,EVALITT,EVALPP,PDADEN,PDICSIG,PDICMIS,PDPROMED,PDYN,KRASCD,KRAS,EVALKEA,EVALKSA,EVALKUE,MHANY,MHTERM,MHSTATCD,MHSTAT,TRTDUR,DOSREFDY
0,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,N,ANY SURGERY NOT RELATED TO COLORECTAL...,0.0,Normal,685.0,NaN
1,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,N,Autoimmune Disease,0.0,Normal,685.0,NaN
2,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,N,Blood Dyscrasia,0.0,Normal,685.0,NaN
3,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,N,Cardiac Arrythmia,0.0,Normal,685.0,NaN
4,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,N,Cerebrovascular Accident (CVA),0.0,Normal,685.0,NaN

In [215]:
_ = read_domain('NCT00115225_PACCE_bev_panitumumab_raw', 'radiotx.sas7bdat')

--- NCT00115225_PACCE_bev_panitumumab_raw/radiotx.sas7bdat ---
shape: (886, 68)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'CHEMOCD', 'CHEMO', 'CHEMOICD', 'CHEMOI', 'ACHEMOCD', 'ACHEMO', 'ACHEMMCD', 'ACHEMM', 'FCHEMOCD', 'FCHEMO', 'B_LESNM', 'B_LESNMT', 'B_LESNMN', 'B_METANM', 'B_METACT', 'BMETACTI', 'FSTOXDS', 'FSTIRDS', 'DURSURG', 'PRADJYN', 'PRADJICD', 'PRADJI', 'B_LDHYN', 'B_ECOGCD', 'B_ECOG', 'BECOGICD', 'B_ECOGI', 'DIAGTYCD', 'DIAGTYPE', 'DIAGICD', 'DIAGI', 'RESPSTAT', 'EVALITT', 'EVALPP', 'PDADEN', 'PDICSIG', 'PDICMIS', 'PDPROMED', 'PDYN', 'KRASCD', 'KRAS', 'EVALKEA', 'EVALKSA', 'EVALKUE', 'RAANY5YR', 'VISITCD', 'VISIT', 'PHASECD', 'PHASE', 'RASTDY', 'RAENDY', 'RADOSE', 'TRTDUR']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,CHEMOCD,CHEMO,CHEMOICD,CHEMOI,ACHEMOCD,ACHEMO,ACHEMMCD,ACHEMM,FCHEMOCD,FCHEMO,B_LESNM,B_LESNMT,B_LESNMN,B_METANM,B_METACT,BMETACTI,FSTOXDS,FSTIRDS,DURSURG,PRADJYN,PRADJICD,PRADJI,B_LDHYN,B_ECOGCD,B_ECOG,BECOGICD,B_ECOGI,DIAGTYCD,DIAGTYPE,DIAGICD,DIAGI,RESPSTAT,EVALITT,EVALPP,PDADEN,PDICSIG,PDICMIS,PDPROMED,PDYN,KRASCD,KRAS,EVALKEA,EVALKSA,EVALKUE,RAANY5YR,VISITCD,VISIT,PHASECD,PHASE,RASTDY,RAENDY,RADOSE,TRTDUR
0,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.573770,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,N,SCR,Screening,10.0,Pre-treatment,NaN,NaN,NaN,685.0
1,20040249,101,249101002,72.0,M,Male,1.0,White or Caucasian,0.0,Q2WK,Every 2 weeks,12.0,bevacizumab with chemotherapy,12.0,bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,101.0,2.0,99.0,2.0,>1,>1,90.712273,NaN,44.065574,N,0.0,N,N,1.0,Symptoms but ambulatory,1.0,Symptoms but ambulatory,1251.0,Colon,1251.0,Colon,N,Y,Y,N,N,N,N,N,2.0,Mutant,Y,Y,N,N,SCR,Screening,10.0,Pre-treatment,NaN,NaN,NaN,365.0
2,20040249,101,249101003,78.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,101.0,2.0,99.0,2.0,>1,1,84.244651,NaN,0.000000,N,0.0,N,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,88.0,Failed,N,N,Y,N,SCR,Screening,10.0,Pre-treatment,NaN,NaN,NaN,166.0
3,20040249,101,249101005,66.0,F,Female,2.0,Black or African American,0.0,Q2WK,Every 2 weeks,12.0,bevacizumab with chemotherapy,12.0,bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,101.0,2.0,99.0,2.0,>1,>1,84.943334,NaN,-0.032787,N,0.0,N,N,1.0,Symptoms but ambulatory,1.0,Symptoms but ambulatory,1251.0,Colon,1251.0,Colon,N,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,N,SCR,Screening,10.0,Pre-treatment,NaN,NaN,NaN,85.0
4,20040249,101,249101006,67.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,2.0,1.0,1.0,1.0,1,1,91.258658,NaN,45.508197,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1252.0,Rectal,1252.0,Rectal,N,Y,Y,N,N,N,N,N,88.0,Failed,N,N,Y,Y,SCR,Screening,5.0,Pre-consent,-1414.0,-1372.0,50.0,302.0

In [216]:
_ = read_domain('NCT00115225_PACCE_bev_panitumumab_raw', 'respeval.sas7bdat')

--- NCT00115225_PACCE_bev_panitumumab_raw/respeval.sas7bdat ---
shape: (7148, 81)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'CHEMOCD', 'CHEMO', 'CHEMOICD', 'CHEMOI', 'ACHEMOCD', 'ACHEMO', 'ACHEMMCD', 'ACHEMM', 'FCHEMOCD', 'FCHEMO', 'B_LESNM', 'B_LESNMT', 'B_LESNMN', 'B_METANM', 'B_METACT', 'BMETACTI', 'FSTOXDS', 'FSTIRDS', 'DURSURG', 'PRADJYN', 'PRADJICD', 'PRADJI', 'B_LDHYN', 'B_ECOGCD', 'B_ECOG', 'BECOGICD', 'B_ECOGI', 'DIAGTYCD', 'DIAGTYPE', 'DIAGICD', 'DIAGI', 'RESPSTAT', 'EVALITT', 'EVALPP', 'PDADEN', 'PDICSIG', 'PDICMIS', 'PDPROMED', 'PDYN', 'KRASCD', 'KRAS', 'EVALKEA', 'EVALKSA', 'EVALKUE', 'DOSREFDY', 'DOSREFWK', 'VISITCD', 'VISIT', 'RSASMDT', 'RSCOMPLT', 'RSTYPECD', 'RSTYPE', 'RSCRITCD', 'RSCRIT', 'RSRESPCD', 'RSRESP', 'RSBRCD', 'RSBR', 'RSBORCD', 'RSBOR', 'RSTRSPCD', 'RSNTRESP', 'TRTDUR', 'RSBRDY', 'RSBORDY', 'RSRESPDY']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,CHEMOCD,CHEMO,CHEMOICD,CHEMOI,ACHEMOCD,ACHEMO,ACHEMMCD,ACHEMM,FCHEMOCD,FCHEMO,B_LESNM,B_LESNMT,B_LESNMN,B_METANM,B_METACT,BMETACTI,FSTOXDS,FSTIRDS,DURSURG,PRADJYN,PRADJICD,PRADJI,B_LDHYN,B_ECOGCD,B_ECOG,BECOGICD,B_ECOGI,DIAGTYCD,DIAGTYPE,DIAGICD,DIAGI,RESPSTAT,EVALITT,EVALPP,PDADEN,PDICSIG,PDICMIS,PDPROMED,PDYN,KRASCD,KRAS,EVALKEA,EVALKSA,EVALKUE,DOSREFDY,DOSREFWK,VISITCD,VISIT,RSASMDT,RSCOMPLT,RSTYPECD,RSTYPE,RSCRITCD,RSCRIT,RSRESPCD,RSRESP,RSBRCD,RSBR,RSBORCD,RSBOR,RSTRSPCD,RSNTRESP,TRTDUR,RSBRDY,RSBORDY,RSRESPDY
0,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,618.0,89.0,RESPUNSCHED15,RESPUNSCHED15,2006-12-01,NaN,1.0,Central,3.0,Modified RECIST,3.0,Partial response,3.0,Partial response,NaN,,3.0,Incomplete response/Stable disease,685.0,99.0,NaN,618.0
1,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,618.0,89.0,RESPUNSCHED15,RESPUNSCHED15,2006-12-01,1.0,2.0,Local,3.0,Modified RECIST,4.0,Stable disease,NaN,,NaN,,NaN,,685.0,NaN,NaN,NaN
2,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,534.0,77.0,RESPUNSCHED08,RESPUNSCHED08,2006-09-08,NaN,1.0,Central,3.0,Modified RECIST,3.0,Partial response,3.0,Partial response,NaN,,3.0,Incomplete response/Stable disease,685.0,99.0,NaN,534.0
3,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,534.0,77.0,RESPUNSCHED08,RESPUNSCHED08,2006-09-08,1.0,2.0,Local,3.0,Modified RECIST,4.0,Stable disease,NaN,,NaN,,NaN,,685.0,NaN,NaN,NaN
4,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,534.0,77.0,RESPUNSCHED19,RESPUNSCHED19,2006-09-08,NaN,1.0,Central,3.0,Modified RECIST,3.0,Partial response,3.0,Partial response,NaN,,3.0,Incomplete response/Stable disease,685.0,99.0,NaN,534.0

In [217]:
_ = read_domain('NCT00115225_PACCE_bev_panitumumab_raw', 'surghist.sas7bdat')

--- NCT00115225_PACCE_bev_panitumumab_raw/surghist.sas7bdat ---
shape: (1810, 73)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'CHEMOCD', 'CHEMO', 'CHEMOICD', 'CHEMOI', 'ACHEMOCD', 'ACHEMO', 'ACHEMMCD', 'ACHEMM', 'FCHEMOCD', 'FCHEMO', 'B_LESNM', 'B_LESNMT', 'B_LESNMN', 'B_METANM', 'B_METACT', 'BMETACTI', 'FSTOXDS', 'FSTIRDS', 'DURSURG', 'PRADJYN', 'PRADJICD', 'PRADJI', 'B_LDHYN', 'B_ECOGCD', 'B_ECOG', 'BECOGICD', 'B_ECOGI', 'DIAGTYCD', 'DIAGTYPE', 'DIAGICD', 'DIAGI', 'RESPSTAT', 'EVALITT', 'EVALPP', 'PDADEN', 'PDICSIG', 'PDICMIS', 'PDPROMED', 'PDYN', 'KRASCD', 'KRAS', 'EVALKEA', 'EVALKSA', 'EVALKUE', 'SXANY5YR', 'DOSREFDY', 'DOSREFWK', 'PHASECD', 'PHASE', 'SXTYPECD', 'SXTYPE', 'SXTYPDTL', 'SXINTTCD', 'SXINTENT', 'SXSITECD', 'SXSITE', 'SXHEALYN', 'TRTDUR']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,CHEMOCD,CHEMO,CHEMOICD,CHEMOI,ACHEMOCD,ACHEMO,ACHEMMCD,ACHEMM,FCHEMOCD,FCHEMO,B_LESNM,B_LESNMT,B_LESNMN,B_METANM,B_METACT,BMETACTI,FSTOXDS,FSTIRDS,DURSURG,PRADJYN,PRADJICD,PRADJI,B_LDHYN,B_ECOGCD,B_ECOG,BECOGICD,B_ECOGI,DIAGTYCD,DIAGTYPE,DIAGICD,DIAGI,RESPSTAT,EVALITT,EVALPP,PDADEN,PDICSIG,PDICMIS,PDPROMED,PDYN,KRASCD,KRAS,EVALKEA,EVALKSA,EVALKUE,SXANY5YR,DOSREFDY,DOSREFWK,PHASECD,PHASE,SXTYPECD,SXTYPE,SXTYPDTL,SXINTTCD,SXINTENT,SXSITECD,SXSITE,SXHEALYN,TRTDUR
0,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.573770,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,Y,-1098.0,-157.0,5.0,Pre-consent,4.0,Resection,LIVER RESECTION,1.0,Cure (or curative),NaN,,,685.0
1,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.573770,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,Y,-1098.0,-157.0,5.0,Pre-consent,6.0,Surgery,EXPLORATORY LAPAROTOMY,10.0,Diagnostic/Staging,NaN,,,685.0
2,20040249,101,249101002,72.0,M,Male,1.0,White or Caucasian,0.0,Q2WK,Every 2 weeks,12.0,bevacizumab with chemotherapy,12.0,bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,101.0,2.0,99.0,2.0,>1,>1,90.712273,NaN,44.065574,N,0.0,N,N,1.0,Symptoms but ambulatory,1.0,Symptoms but ambulatory,1251.0,Colon,1251.0,Colon,N,Y,Y,N,N,N,N,N,2.0,Mutant,Y,Y,N,Y,NaN,NaN,10.0,Pre-treatment,88.0,Other,NO RECURRENT TUMOR NOTED DURING REVERSAL,99.0,Unknown,NaN,,,365.0
3,20040249,101,249101002,72.0,M,Male,1.0,White or Caucasian,0.0,Q2WK,Every 2 weeks,12.0,bevacizumab with chemotherapy,12.0,bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,101.0,2.0,99.0,2.0,>1,>1,90.712273,NaN,44.065574,N,0.0,N,N,1.0,Symptoms but ambulatory,1.0,Symptoms but ambulatory,1251.0,Colon,1251.0,Colon,N,Y,Y,N,N,N,N,N,2.0,Mutant,Y,Y,N,Y,-1382.0,-198.0,5.0,Pre-consent,4.0,Resection,MODERATELY DIFF. ADENO OR LARGE BOWEL. NO LN`S.,1.0,Cure (or curative),NaN,,,365.0
4,20040249,101,249101002,72.0,M,Male,1.0,White or Caucasian,0.0,Q2WK,Every 2 weeks,12.0,bevacizumab with chemotherapy,12.0,bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,101.0,2.0,99.0,2.0,>1,>1,90.712273,NaN,44.065574,N,0.0,N,N,1.0,Symptoms but ambulatory,1.0,Symptoms but ambulatory,1251.0,Colon,1251.0,Colon,N,Y,Y,N,N,N,N,N,2.0,Mutant,Y,Y,N,Y,-39.0,-6.0,5.0,Pre-consent,6.0,Surgery,"RECURRENCE PELVIS, LIVER, SMALL BOWEL LAPAROTO...",10.0,Diagnostic/Staging,NaN,,,365.0

In [218]:
_ = read_domain('NCT00115225_PACCE_bev_panitumumab_raw', 'vitals_v.sas7bdat')

--- NCT00115225_PACCE_bev_panitumumab_raw/vitals_v.sas7bdat ---
shape: (107855, 89)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'CHEMOCD', 'CHEMO', 'CHEMOICD', 'CHEMOI', 'ACHEMOCD', 'ACHEMO', 'ACHEMMCD', 'ACHEMM', 'FCHEMOCD', 'FCHEMO', 'B_LESNM', 'B_LESNMT', 'B_LESNMN', 'B_METANM', 'B_METACT', 'BMETACTI', 'FSTOXDS', 'FSTIRDS', 'DURSURG', 'PRADJYN', 'PRADJICD', 'PRADJI', 'B_LDHYN', 'B_ECOGCD', 'B_ECOG', 'BECOGICD', 'B_ECOGI', 'DIAGTYCD', 'DIAGTYPE', 'DIAGICD', 'DIAGI', 'RESPSTAT', 'EVALITT', 'EVALPP', 'PDADEN', 'PDICSIG', 'PDICMIS', 'PDPROMED', 'PDYN', 'KRASCD', 'KRAS', 'EVALKEA', 'EVALKSA', 'EVALKUE', 'DOSREFDY', 'DOSREFWK', 'VISITCD', 'VISIT', 'PHASECD', 'PHASE', 'VSDONECD', 'VSDONE', 'VSPTMCD', 'VSPTM', 'VSTESTCD', 'VSTEST', 'VSTRTCD', 'VSTRT', 'VSSTRES', 'VSSTUNIT', 'VSORRES', 'VSORUNIT', 'VSBASE', 'VSBLRES', 'VSCHGBL', 'VSSCRRES', 'VSCHGSCR', 'VSMIN', 'VSMAX', 'VSLAST', 'VSMINCH', 'VSMAXCH', 'VSPCTCH', 'TRTDUR']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,CHEMOCD,CHEMO,CHEMOICD,CHEMOI,ACHEMOCD,ACHEMO,ACHEMMCD,ACHEMM,FCHEMOCD,FCHEMO,B_LESNM,B_LESNMT,B_LESNMN,B_METANM,B_METACT,BMETACTI,FSTOXDS,FSTIRDS,DURSURG,PRADJYN,PRADJICD,PRADJI,B_LDHYN,B_ECOGCD,B_ECOG,BECOGICD,B_ECOGI,DIAGTYCD,DIAGTYPE,DIAGICD,DIAGI,RESPSTAT,EVALITT,EVALPP,PDADEN,PDICSIG,PDICMIS,PDPROMED,PDYN,KRASCD,KRAS,EVALKEA,EVALKSA,EVALKUE,DOSREFDY,DOSREFWK,VISITCD,VISIT,PHASECD,PHASE,VSDONECD,VSDONE,VSPTMCD,VSPTM,VSTESTCD,VSTEST,VSTRTCD,VSTRT,VSSTRES,VSSTUNIT,VSORRES,VSORUNIT,VSBASE,VSBLRES,VSCHGBL,VSSCRRES,VSCHGSCR,VSMIN,VSMAX,VSLAST,VSMINCH,VSMAXCH,VSPCTCH,TRTDUR
0,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,-9.0,-2.0,SCR,Screening,10.0,Pre-treatment,,,998.0,Taken at physical exam,DIABP,Diastolic blood pressure,NaN,,60.0,MMHG,60.0,MMHG,N,80.0,NaN,60.0,NaN,N,N,N,NaN,NaN,NaN,685.0
1,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,-9.0,-2.0,SCR,Screening,10.0,Pre-treatment,,,998.0,Taken at physical exam,ECOG,ECOG performance status,NaN,,0.0,,0.0,,Y,0.0,NaN,0.0,NaN,N,N,N,NaN,NaN,NaN,685.0
2,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,-9.0,-2.0,SCR,Screening,10.0,Pre-treatment,,,998.0,Taken at physical exam,PULSE,Pulse,NaN,,84.0,BEATS/MINUTE,84.0,BEATS/MINUTE,N,72.0,NaN,84.0,NaN,N,N,N,NaN,NaN,NaN,685.0
3,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,-9.0,-2.0,SCR,Screening,10.0,Pre-treatment,,,998.0,Taken at physical exam,RESP,Respiration,NaN,,16.0,BREATHS/MINUTE,16.0,BREATHS/MINUTE,N,14.0,NaN,16.0,NaN,N,N,N,NaN,NaN,NaN,685.0
4,20040249,101,249101001,67.0,F,Female,2.0,Black or African American,6.0,Q2WK,Every 2 weeks,11.0,panit. plus bevacizumab with chemotherapy,11.0,panit. plus bevacizumab with chemotherapy,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,78.0,Oxaliplatin,100.0,1.0,99.0,1.0,1,1,81.144198,NaN,45.57377,Y,1.0,Y,N,0.0,Fully active,0.0,Fully active,1251.0,Colon,1251.0,Colon,Y,Y,Y,N,N,N,N,N,1.0,Wild-type,Y,Y,N,-9.0,-2.0,SCR,Screening,10.0,Pre-treatment,,,998.0,Taken at physical exam,SYSBP,Systolic blood pressure,NaN,,120.0,MMHG,120.0,MMHG,N,152.0,NaN,120.0,NaN,N,N,N,NaN,NaN,NaN,685.0

## NCT00339183_panitumumab_folfiri_raw

In [219]:
_ = read_domain('NCT00339183_panitumumab_folfiri_raw', 'a_eendpt.sas7bdat')

--- NCT00339183_panitumumab_folfiri_raw/a_eendpt.sas7bdat ---
shape: (946, 140)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'PRBEVCDR', 'PRBEVR', 'PRBEVCDM', 'PRBEVM', 'PRBEVCD', 'PRBEV', 'PROXACDR', 'PROXAR', 'PROXACDM', 'PROXAM', 'PROXALCD', 'PROXAL', 'B_METANM', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'PADJYNCD', 'PRADJYN', 'DPADJUV', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'KRASCD', 'KRAS', 'EVALITT', 'EVALPP', 'EVALQOL', 'EVALEGFR', 'ROSCR', 'ROSLR', 'ROSLRCA', 'RDTLR', 'RDURCR', 'RDURCRC', 'RDURLR', 'RDURLRC', 'RDYCR', 'RDYLR', 'PFSDYCR', 'PFSCR', 'PFSDYOCR', 'PFSOCR', 'PFSDYOLR', 'PFSOLR', 'PFSCREWK', 'PFSDYCRE', 'PFSCRE', 'PFSDYCRU', 'PFSCRU', 'PFSCU', 'PFSDYCRV', 'PFSCRV', 'PFSDYLR', 'PFSLR', 'PFSDYCRN', 'PFSCRN', 'PFSDYCRA', 'PFSCRA', 'PFSCRS', 'PFSDYCRS', 'PFSCRT', 'PFSDYCRT', 'PDDYCR', 'PDCR', 'PDOCR', 'PDDYOCR', 'PDOLR', 'PDDYOLR', 'PDDYLR', 'PDLR', 'TTP1', 'TTP1C', 'DTHDY', 'DTH', 'SDDURCR', 'SDDURCRC', 'SDDURLR', 'SDDURLRC', 'SLDCBASE', 'SLDCMIN', 'SLDCMXRD', 'SLDCMXPR', 'SLDLBASE', 'SLDLMIN', 'SLDLMXRD', 'SLDLMXPR', 'PFSDYCEP', 'PFSCEP', 'PFSDYCEB', 'PFSCEB', 'DROPINDY', 'DROPIN', 'VEGFRDY', 'VEGFR', 'IRINDY', 'IRIN', 'OXALDY', 'OXAL', 'BEVZDY', 'BEVZ', 'CHIOFDY', 'CHIOF', 'EGFRIRDY', 'EGFRIR', 'ANTUMDY', 'ANTUM', 'PANITDY', 'PANIT', 'CETUXDY', 'CETUX', 'WOEGFRDY', 'WOEGFR', 'POTOSDY', 'POTOS', 'TRTDUR', 'B_ECOGCD', 'B_ECOG']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,PRBEVCDR,PRBEVR,PRBEVCDM,PRBEVM,PRBEVCD,PRBEV,PROXACDR,PROXAR,PROXACDM,PROXAM,PROXALCD,PROXAL,B_METANM,B_METACT,LIVRONCD,LIVRONLY,PADJYNCD,PRADJYN,DPADJUV,B_LDHYN,B_LDH2YN,B_LDHNM,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,KRASCD,KRAS,EVALITT,EVALPP,EVALQOL,EVALEGFR,ROSCR,ROSLR,ROSLRCA,RDTLR,RDURCR,RDURCRC,RDURLR,RDURLRC,RDYCR,RDYLR,PFSDYCR,PFSCR,PFSDYOCR,PFSOCR,PFSDYOLR,PFSOLR,PFSCREWK,PFSDYCRE,PFSCRE,PFSDYCRU,PFSCRU,PFSCU,PFSDYCRV,PFSCRV,PFSDYLR,PFSLR,PFSDYCRN,PFSCRN,PFSDYCRA,PFSCRA,PFSCRS,PFSDYCRS,PFSCRT,PFSDYCRT,PDDYCR,PDCR,PDOCR,PDDYOCR,PDOLR,PDDYOLR,PDDYLR,PDLR,TTP1,TTP1C,DTHDY,DTH,SDDURCR,SDDURCRC,SDDURLR,SDDURLRC,SLDCBASE,SLDCMIN,SLDCMXRD,SLDCMXPR,SLDLBASE,SLDLMIN,SLDLMXRD,SLDLMXPR,PFSDYCEP,PFSCEP,PFSDYCEB,PFSCEB,DROPINDY,DROPIN,VEGFRDY,VEGFR,IRINDY,IRIN,OXALDY,OXAL,BEVZDY,BEVZ,CHIOFDY,CHIOF,EGFRIRDY,EGFRIR,ANTUMDY,ANTUM,PANITDY,PANIT,CETUXDY,CETUX,WOEGFRDY,WOEGFR,POTOSDY,POTOS,TRTDUR,B_ECOGCD,B_ECOG
0,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,0.0,0.0,SD,0.0,NaN,NaN,NaN,NaN,347.0,370.0,53.0,1.0,53.0,1.0,228.0,1.0,NaN,53.0,1.0,53.0,1.0,N,53.0,1.0,228.0,1.0,53.0,1.0,53.0,1.0,1.0,53.0,1.0,53.0,53.0,1.0,1.0,53.0,1.0,228.0,228.0,1.0,199.0,1.0,295.0,1.0,NaN,NaN,228.0,1.0,49.0,33.0,-16.0,-32.653061,118.0,85.0,-33.0,-27.966102,53.0,1.0,53.0,1.0,249.0,0.0,249.0,0.0,249.0,0.0,249.0,0.0,249.0,0.0,249.0,0.0,249.0,0.0,271.0,1.0,249.0,0.0,249.0,0.0,249.0,0.0,249.0,0.0,219.0,0,Fully active
1,20050181,1001,201001002,66.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,N,N,215.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,0.0,0.0,PD,0.0,NaN,NaN,NaN,NaN,347.0,370.0,69.0,1.0,69.0,1.0,69.0,1.0,NaN,69.0,1.0,69.0,1.0,N,69.0,1.0,69.0,1.0,112.0,1.0,56.0,1.0,1.0,69.0,1.0,69.0,69.0,1.0,1.0,69.0,1.0,69.0,69.0,1.0,81.0,1.0,139.0,1.0,NaN,NaN,NaN,NaN,215.0,292.0,77.0,35.813953,104.0,136.0,32.0,30.769231,69.0,1.0,69.0,1.0,94.0,0.0,94.0,0.0,94.0,0.0,94.0,0.0,94.0,0.0,116.0,1.0,94.0,0.0,116.0,1.0,94.0,0.0,94.0,0.0,94.0,0.0,116.0,1.0,60.0,0,Fully active
2,20050181,1001,201001004,58.0,F,Female,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,0.0,N,0.0,N,0.0,N,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,Y,N,392.0,0.0,Fully active,0 or 1,1252.0,Rectal,0.0,N,Y,1.0,Wild-type,Y,Y,Y,Y,1.0,1.0,PR,1.0,400.0,1.0,338.0,1.0,55.0,117.0,454.0,1.0,454.0,1.0,454.0,1.0,NaN,454.0,1.0,454.0,1.0,N,454.0,1.0,454.0,1.0,454.0,1.0,454.0,1.0,1.0,454.0,1.0,454.0,454.0,1.0,1.0,454.0,1.0,454.0,454.0,1.0,317.0,1.0,793.0,1.0,NaN,NaN,NaN,NaN,167.0,61.0,-106.0,-63.473054,93.0,39.0,-54.0,-58.064516,454.0,1.0,454.0,1.0,729.0,0.0,686.0,1.0,729.0,0.0,729.0,0.0,686.0,1.0,517.0,1.0,729.0,0.0,517.0,1.0,729.0,0.0,729.0,0.0,686.0,1.0,517.0,1.0,437.0,0,Fully active
3,20050181,1001,201001005,75.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,2.0,2,0.0,N,0.0,N,,N,N,267.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,1.0,Wild-type,Y,Y,Y,Y,1.0,1.0,PR,1.0,115.0,1.0,165.0,1.0,63.0,63.0,177.0,1.0,177.0,1.0,227.0,1.0,NaN,177.0,1.0,177.0,1.0,N,177.0,1.0,227.0,1.0,224.0,1.0,168.0,1.0,1.0,177.0,1.0,177.0,177.0,1.0,1.0,177.0,1.0,227.0,227.0,1.0,193.0,1.0,329.0,1.0,NaN,NaN,NaN,NaN,56.0,34.0,-22.0,-39.285714,47.0,23.0,-24.0,-51.063830,177.0,1.0,177.0,1.0,308.0,0.0,308.0,0.0,308.0,0.0,308.0,0.0,308.0,0.0,280.0,1.0,308.0,0.0,280.0,1.0,308.0,0.0,308.0,0.0,308.0,0.0,280.0,1.0,220.0,0,Fully active
4,20050181,1001,201001006,52.0,M,Male,1.0,White or Caucasian,NaN,,,41.0,FOLFIRI alone,41.0,FOLFIRI alone,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,Y,Y,572.0,1.0,Symptoms but ambulatory,0 or 1,1251.0,Colon,1.0,Y,Y,88.0,Failed,Y,Y,N,Y,0.0,0.0,ND,0.0,NaN,NaN,NaN,NaN,347.0,370.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,N,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,54.0,1.0,15.0,0.0,NaN,NaN,NaN,NaN,127.0,NaN,NaN,NaN,214.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,15.0,0.0,15.0,0.0,15.0,0.0,15.0,0.0,15.0,0.0,15.0,0.0,15.0,0.0,15.0,0.0,15.0,0.0,15.0,0.0,15.0,0.0,15.0,0.0,3.0,1,Symptoms but ambulatory

In [220]:
_ = read_domain('NCT00339183_panitumumab_folfiri_raw', 'a_endpt.sas7bdat')

--- NCT00339183_panitumumab_folfiri_raw/a_endpt.sas7bdat ---
shape: (946, 195)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'PRBEVCDR', 'PRBEVR', 'PRBEVCDM', 'PRBEVM', 'PRBEVCD', 'PRBEV', 'PROXACDR', 'PROXAR', 'PROXACDM', 'PROXAM', 'PROXALCD', 'PROXAL', 'B_METANM', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'PADJYNCD', 'PRADJYN', 'DPADJUV', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'KRASCD', 'KRAS', 'EVALITT', 'EVALPP', 'EVALQOL', 'EVALEGFR', 'INVCONF', 'B_WEIGHT', 'B_HEIGHT', 'B_BMI', 'B_BSA', 'WT78', 'PRSURG', 'PRRADIO', 'B_ALPYN', 'B_ALPNM', 'B_ECG', 'B_CEA', 'B_CEAYN', 'B_CREAT', 'CHMOLNCD', 'CHMOLINE', 'HEPATIC', 'RENAL', 'TUMTYPCD', 'TUMTYPE', 'DUREXPCD', 'DUREXPOS', 'IPDUR', 'CDOSE', 'EXLOTID', 'IRDUR', 'IRCDOSE', 'FBDUR', 'FBCDOSE', 'FIDUR', 'FICDOSE', 'DIAGMONS', 'DIAGM2', 'DIAGM15', 'METMONS', 'METM1', 'METM12', 'HISSBTCD', 'HISSUBTY', 'HDIFFCD', 'HDIFFER', 'BIOPNO', 'BIOPTPCT', 'BIOPRSCD', 'BIOPRS', 'BIOPEFCD', 'BIOPEF', 'BIOPNEG', 'BIOPWEAK', 'BIOPMOD', 'BIOPSTRG', 'BIOP3', 'BIOPS123', 'BIOPMAX', 'INVTX', 'INVTXDTC', 'RDTCR', 'ROSCRCA', 'ROSLR', 'ROSLRCA', 'RDTLRCA', 'RDTLR', 'RDURCR', 'RDURCRC', 'RDURLR', 'RDURLRC', 'RDYCR', 'RDYLR', 'PFSDYCR', 'PFSCR', 'PFSDYOCR', 'PFSOCR', 'PFSDYOLR', 'PFSOLR', 'PFSCREWK', 'PFSDYCRE', 'PFSCRE', 'PFSDYCRU', 'PFSCRU', 'PFSCU', 'PFSDYCRV', 'PFSCRV', 'PFSDYLR', 'PFSLR', 'PFSDYCRN', 'PFSCRN', 'PFSDYCRA', 'PFSCRA', 'PFSCRS', 'PFSDYCRS', 'PFSCRT', 'PFSDYCRT', 'PDDYCR', 'PDCR', 'PDOCR', 'PDDYOCR', 'PDOLR', 'PDDYOLR', 'PDDYLR', 'PDLR', 'TTP1', 'TTP1C', 'DTHDY', 'DTH', 'SDDURCR', 'SDDURCRC', 'SDDURLR', 'SDDURLRC', 'SLDCBASE', 'SLDCMIN', 'SLDCMXRD', 'SLDCMXPR', 'SLDLBASE', 'SLDLMIN', 'SLDLMXRD', 'SLDLMXPR', 'PFSDYCEP', 'PFSCEP', 'PFSDYCEB', 'PFSCEB', 'DROPINDY', 'DROPIN', 'VEGFRDY', 'VEGFR', 'IRINDY', 'IRIN', 'OXALDY', 'OXAL', 'BEVZDY', 'BEVZ', 'CHIOFDY', 'CHIOF', 'EGFRIRDY', 'EGFRIR', 'ANTUMDY', 'ANTUM', 'WOEGFRDY', 'WOEGFR', 'POTOSDY', 'POTOS', 'TRTDUR', 'B_ECOGCD', 'B_ECOG', 'NPRSURG']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,PRBEVCDR,PRBEVR,PRBEVCDM,PRBEVM,PRBEVCD,PRBEV,PROXACDR,PROXAR,PROXACDM,PROXAM,PROXALCD,PROXAL,B_METANM,B_METACT,LIVRONCD,LIVRONLY,PADJYNCD,PRADJYN,DPADJUV,B_LDHYN,B_LDH2YN,B_LDHNM,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,KRASCD,KRAS,EVALITT,EVALPP,EVALQOL,EVALEGFR,INVCONF,B_WEIGHT,B_HEIGHT,B_BMI,B_BSA,WT78,PRSURG,PRRADIO,B_ALPYN,B_ALPNM,B_ECG,B_CEA,B_CEAYN,B_CREAT,CHMOLNCD,CHMOLINE,HEPATIC,RENAL,TUMTYPCD,TUMTYPE,DUREXPCD,DUREXPOS,IPDUR,CDOSE,EXLOTID,IRDUR,IRCDOSE,FBDUR,FBCDOSE,FIDUR,FICDOSE,DIAGMONS,DIAGM2,DIAGM15,METMONS,METM1,METM12,HISSBTCD,HISSUBTY,HDIFFCD,HDIFFER,BIOPNO,BIOPTPCT,BIOPRSCD,BIOPRS,BIOPEFCD,BIOPEF,BIOPNEG,BIOPWEAK,BIOPMOD,BIOPSTRG,BIOP3,BIOPS123,BIOPMAX,INVTX,INVTXDTC,RDTCR,ROSCRCA,ROSLR,ROSLRCA,RDTLRCA,RDTLR,RDURCR,RDURCRC,RDURLR,RDURLRC,RDYCR,RDYLR,PFSDYCR,PFSCR,PFSDYOCR,PFSOCR,PFSDYOLR,PFSOLR,PFSCREWK,PFSDYCRE,PFSCRE,PFSDYCRU,PFSCRU,PFSCU,PFSDYCRV,PFSCRV,PFSDYLR,PFSLR,PFSDYCRN,PFSCRN,PFSDYCRA,PFSCRA,PFSCRS,PFSDYCRS,PFSCRT,PFSDYCRT,PDDYCR,PDCR,PDOCR,PDDYOCR,PDOLR,PDDYOLR,PDDYLR,PDLR,TTP1,TTP1C,DTHDY,DTH,SDDURCR,SDDURCRC,SDDURLR,SDDURLRC,SLDCBASE,SLDCMIN,SLDCMXRD,SLDCMXPR,SLDLBASE,SLDLMIN,SLDLMXRD,SLDLMXPR,PFSDYCEP,PFSCEP,PFSDYCEB,PFSCEB,DROPINDY,DROPIN,VEGFRDY,VEGFR,IRINDY,IRIN,OXALDY,OXAL,BEVZDY,BEVZ,CHIOFDY,CHIOF,EGFRIRDY,EGFRIR,ANTUMDY,ANTUM,WOEGFRDY,WOEGFR,POTOSDY,POTOS,TRTDUR,B_ECOGCD,B_ECOG,NPRSURG
0,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,Y,80.0,182.0,24.151673,2.011080,Y,Y,N,N,106.0,Normal,17.5,Y,97.240,5.0,2nd Line,N,N,1.0,Colon,3.0,>= 6 to < 9 Months,230.0,7680.0,"L005289, L005529, L005642",230.0,5804.98,230.0,12900.05,230.0,77418.00,9.540984,,N,9.540984,,N,0.0,No sub-type,2.0,Moderately differentiated,>500 cells present,61.28,1.0,Positive,NaN,,85.3,9.8,5.0,0.0,N,14.8,2+,N,,0.0,PD,0.0,SD,SD,0.0,NaN,NaN,NaN,NaN,347.0,370.0,53.0,1.0,53.0,1.0,228.0,1.0,NaN,53.0,1.0,53.0,1.0,N,53.0,1.0,228.0,1.0,53.0,1.0,53.0,1.0,1.0,53.0,1.0,53.0,53.0,1.0,1.0,53.0,1.0,228.0,228.0,1.0,199.0,1.0,295.0,1.0,NaN,NaN,228.0,1.0,49.0,33.0,-16.0,-32.653061,118.0,85.0,-33.0,-27.966102,53.0,1.0,53.0,1.0,249.0,0.0,249.0,0.0,249.0,0.0,249.0,0.0,249.0,0.0,249.0,0.0,249.0,0.0,271.0,1.0,249.0,0.0,249.0,0.0,219.0,0,Fully active,1
1,20050181,1001,201001002,66.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,N,N,215.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,Y,93.0,178.0,29.352355,2.144372,Y,Y,N,N,173.0,Normal,18.1,Y,87.516,5.0,2nd Line,Y,N,1.0,Colon,1.0,< 3 Months,71.0,2790.0,L005289,71.0,1900.20,71.0,4222.70,71.0,25341.69,6.131148,,N,6.131148,,N,0.0,No sub-type,99.0,Unknown,>500 cells present,43.22,1.0,Positive,NaN,,99.9,0.1,0.0,0.0,N,0.1,1+,N,,0.0,PD,0.0,PD,PD,0.0,NaN,NaN,NaN,NaN,347.0,370.0,69.0,1.0,69.0,1.0,69.0,1.0,NaN,69.0,1.0,69.0,1.0,N,69.0,1.0,69.0,1.0,112.0,1.0,56.0,1.0,1.0,69.0,1.0,69.0,69.0,1.0,1.0,69.0,1.0,69.0,69.0,1.0,81.0,1.0,139.0,1.0,NaN,NaN,NaN,NaN,215.0,292.0,77.0,35.813953,104.0,136.0,32.0,30.769231,69.0,1.0,69.0,1.0,94.0,0.0,94.0,0.0,94.0,0.0,94.0,0.0,94.0,0.0,116.0,1.0,94.0,0.0,116.0,1.0,94.0,0.0,116.0,1.0,60.0,0,Fully active,1
2,20050181,1001,201001004,58.0,F,Female,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,0.0,N,0.0,N,0.0,N,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,Y,N,392.0,0.0,Fully active,0 or 1,1252.0,Rectal,0.0,N,Y,1.0,Wild-type,Y,Y,Y,Y,Y,62.0,164.0,23.051755,1.680608,N,Y,N,N,175.0,Normal,252.6,Y,78.676,5.0,2nd Line,N,N,2.0,Rectum,4.0,>= 9 Months,448.0,10044.0,"L005529, L005642, L005642, L005529, L006037, L...",448.0,8115.57,448.0,15045.67,448.0,93367.44,12.327869,,N,12.852459,,Y,99.0,Unknown,2.0,Moderately differentiated,100-500 cells present,46.74,2.0,Negative,NaN,,100.0,0.0,0.0,0.0,N,0.0,0,N,,1.0,PR,1.0,PR,PR,1.0,400.0,1.0,338.0,1.0,55.0,117.0,454.0,1.0,454.0,1.0,454.0,1.0,NaN,454.0,1.0,454.0,1.0,N,454.0,1.0,454.0,1.0,454.0,1.0,454.0,1.0,1.0,454.0,1.0,454.0,454.0,1.0,1.0,454.0,1.0,454.0,454.0,1.0,317.0,1.0,793.0,1.0,NaN,NaN,NaN,NaN,167.0,61.0,-106.0,-63.473054,93.0,39.0,-54.0,-58.064516,454.0,1.0,454.0,1.0,729.0,0.0,686.0,1.0,729.0,0.0,729.0,0.0,686.0,1.0,517.0,1.0,729.0,0.0,517.0,1.0,686.0,1.0,517.0,1.0,437.0,0,Fully active,3
3,20050181,1001,201001005,75.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,2.0,2,0.0,N,0.0,N,,N,N,267.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,1.0,Wild-type,Y,Y,Y,Y,Y,106.0,188.0,29.990946,2.352776,Y,Y,N,N,170.0,Abnormal - not clinically significant,609.9,Y,89.284,5.0,2nd Line,N,N,1.0,Colon,3.0,>= 6 to < 9 Months,231.0,8904.0,"L005529, L005642, L006037",231.0,6171.37,231.0,13714.88,231.0,82300.00,9.803279,,N,9.803279,,N,0.0,No sub-type,2.0,Moderately differentiated,100-500 cells present,23.90,1.0,Positive,NaN,,96.3,3.8,0.0,0.0,N,3.8,1+,Y,2007-06-22,1.0,PR,1.0,PR,PR,1.0,115.0,1.0,165.0,1.0,63.0,63.0,177.0,1.0,177.0,1.0,227.0,1.0,NaN,177.0,1.0,177.0,1.0,N,177.0,1.0,227.0,1.0,224.0,1.0,168.0,1.0,1.0,177.0,1.0,177.0,177.0,1.0,1.0,177.0,1.0,227.0,227.0,1.0,193.0,1.0,329.0,1.0,NaN,NaN,NaN,NaN,56.0,34.0,-22.0,-39.285714,47.0,23.0,-24.0,-51.063830,177.0,1.0,177.0,1.0,308.0,0.0,308.0,0.0,308.0,0.0,308.0,0.0,308.0,0.0,280.0,1.0,308.0,0.0,280.0,1.0,308.0,0.0,280.0,1.0,220.0,0,Fully active,2
4,20050181,1001,201001006,52.0,M,Male,1.0,White or Caucasian,NaN,,,41.0,FOLFIRI alone,41.0,FOLFIRI alone,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,Y,Y,572.0,1.0,Symptoms but ambulatory,0 or 1,1251.0,Colon,1.0,Y,Y,88.0,Failed,Y,Y,N,Y,Y,130.0,200.0,32.500000,2.687419,Y,Y,N,N,207.0,Abnormal - not clinically significant,70.7,Y,104.312,5.0,2nd Line,N,N,1.0,Colon,1.0,< 3 Months,NaN,NaN,,14.0,360.00,14.0,800.00,14.0,4800.00,2.885246,,N,3.540984,,N,99.0,Unknown,2.0,Moderately differentiated,100-500 cells present,42.19,1.0,Positive,NaN,,95.3,4.5,0.2,0.0,N,4.7,2+,N,,0.0,ND,0.0,ND,ND,0.0,NaN,NaN,NaN,NaN,347.0,370.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,N,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,54.0,1.0,15.0,0.0,NaN,NaN,NaN,NaN,127.0,NaN,NaN,NaN,214.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,15.0,0.0,15.0,0.0,15.0,0.0,15.0,0.0,15.0,0.0,15.0,0.0,15.0,0.0,15.0,0.0,15.0,0.0,15.0,0.0,3.0,1,Symptoms but ambulatory,1

In [221]:
_ = read_domain('NCT00339183_panitumumab_folfiri_raw', 'a_sendpt.sas7bdat')

--- NCT00339183_panitumumab_folfiri_raw/a_sendpt.sas7bdat ---
shape: (946, 236)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'PRBEVCDR', 'PRBEVR', 'PRBEVCDM', 'PRBEVM', 'PRBEVCD', 'PRBEV', 'PROXACDR', 'PROXAR', 'PROXACDM', 'PROXAM', 'PROXALCD', 'PROXAL', 'B_METANM', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'PADJYNCD', 'PRADJYN', 'DPADJUV', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'KRASCD', 'KRAS', 'EVALITT', 'EVALPP', 'EVALQOL', 'EVALEGFR', 'NPRSURG', 'INTEYE', 'INTEYEDY', 'IEG34', 'IEGRDY', 'IEG34DUR', 'IEG34DRC', 'IESEVDY', 'IEDUR', 'IEDURC', 'IESEVDUR', 'IESEVDRC', 'IEDIS', 'IEOT', 'IEOTDY', 'IEOTDYC', 'IEOTFUDY', 'INTINF', 'IERSFU', 'IEGRRSFU', 'RAGRRSFU', 'SKRSFU', 'NARSFU', 'HARSFU', 'EYRSFU', 'CSRSFU', 'INFRSFU', 'DOSWH', 'DOSWR', 'DOSWRF', 'DOSWRW', 'INFCTC', 'INFREP', 'INFUSPI', 'AE', 'AE34', 'AE4', 'AESER', 'AEREL', 'AEREL34', 'AEREL4', 'AERELSER', 'AETXDIS', 'AESTYDIS', 'AELIFE', 'DEATH', 'CALCEM', 'CLCSEVCD', 'CLCSEV', 'MAGNES', 'MAGSEVCD', 'MAGSEV', 'DIARRHEA', 'STOMATIT', 'CARDTOX', 'PULMTOX', 'PULSEVCD', 'PULSEV', 'VASCTOX', 'VASSEVCD', 'VASSEV', 'NUMINFP', 'NUMINF', 'NUMIRINF', 'NUMALINF', 'NUMCHINF', 'NUMCHALL', 'NUMFBINF', 'NUMLLINF', 'NUMDLINF', 'NUMFIINF', 'CDOSE', 'ADOSE', 'CWDOSE', 'AWDOSE', 'IRCDOSE', 'IRADOSE', 'IRCWDOSE', 'IRAWDOSE', 'FBCDOSE', 'FBADOSE', 'FBCWDOSE', 'FBAWDOSE', 'FICDOSE', 'FIADOSE', 'FICWDOSE', 'FIAWDOSE', 'LLCDOSE', 'LLADOSE', 'LLCWDOSE', 'LLAWDOSE', 'DLCDOSE', 'DLADOSE', 'DLCWDOSE', 'DLAWDOSE', 'DUREXP', 'EXPWK', 'IPDURWK', 'IPDSINT', 'IPDSINTR', 'IPDSINR3', 'IRDURWK', 'IRDSINT', 'IRDSINTR', 'IRDSINR3', 'FBDURWK', 'FBDSINT', 'FBDSINTR', 'FBDSINR3', 'FIDURWK', 'FIDSINT', 'FIDSINTR', 'FIDSINR3', 'LLDURWK', 'LLDSINT', 'LLDSINTR', 'LLDSINR3', 'DLDURWK', 'DLDSINT', 'DLDSINTR', 'DLDSINR3', 'IPDLYNM', 'IPDLYPC', 'DSDLYNM', 'DSDLYPC', 'CHDLYNM', 'CHDLYPC', 'IPDECNMW', 'IPDECPCW', 'IRDECNMW', 'IRDECPCW', 'FBDECPCW', 'FIDECPCW', 'DECNMW', 'DECPCW', 'DECCHNMW', 'DECCHPCW', 'PROPDOSE', 'SKYN', 'SKDY', 'SKSEVCD', 'SKSEV', 'SKSEVDY', 'SKDUR', 'SKDURC', 'SKSEVDUR', 'SKSEVDRC', 'SKDIS', 'EYYN', 'EYDY', 'EYSEVCD', 'EYSEV', 'EYSEVDY', 'EYDUR', 'EYDURC', 'EYSEVDUR', 'EYSEVDRC', 'CSYN', 'CSDY', 'CSSEVDY', 'CSDUR', 'CSDURC', 'CSSEVDUR', 'CSSEVDRC', 'CSDIS', 'HAYN', 'HADY', 'HASEVDY', 'HADUR', 'HADURC', 'HASEVDUR', 'HASEVDRC', 'HADIS', 'NAYN', 'NADY', 'NASEVCD', 'NASEV', 'NASEVDY', 'NADUR', 'NADURC', 'NASEVDUR', 'NASEVDRC', 'B_ECOGCD', 'B_ECOG', 'TRTDUR']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,PRBEVCDR,PRBEVR,PRBEVCDM,PRBEVM,PRBEVCD,PRBEV,PROXACDR,PROXAR,PROXACDM,PROXAM,PROXALCD,PROXAL,B_METANM,B_METACT,LIVRONCD,LIVRONLY,PADJYNCD,PRADJYN,DPADJUV,B_LDHYN,B_LDH2YN,B_LDHNM,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,KRASCD,KRAS,EVALITT,EVALPP,EVALQOL,EVALEGFR,NPRSURG,INTEYE,INTEYEDY,IEG34,IEGRDY,IEG34DUR,IEG34DRC,IESEVDY,IEDUR,IEDURC,IESEVDUR,IESEVDRC,IEDIS,IEOT,IEOTDY,IEOTDYC,IEOTFUDY,INTINF,IERSFU,IEGRRSFU,RAGRRSFU,SKRSFU,NARSFU,HARSFU,EYRSFU,CSRSFU,INFRSFU,DOSWH,DOSWR,DOSWRF,DOSWRW,INFCTC,INFREP,INFUSPI,AE,AE34,AE4,AESER,AEREL,AEREL34,AEREL4,AERELSER,AETXDIS,AESTYDIS,AELIFE,DEATH,CALCEM,CLCSEVCD,CLCSEV,MAGNES,MAGSEVCD,MAGSEV,DIARRHEA,STOMATIT,CARDTOX,PULMTOX,PULSEVCD,PULSEV,VASCTOX,VASSEVCD,VASSEV,NUMINFP,NUMINF,NUMIRINF,NUMALINF,NUMCHINF,NUMCHALL,NUMFBINF,NUMLLINF,NUMDLINF,NUMFIINF,CDOSE,ADOSE,CWDOSE,AWDOSE,IRCDOSE,IRADOSE,IRCWDOSE,IRAWDOSE,FBCDOSE,FBADOSE,FBCWDOSE,FBAWDOSE,FICDOSE,FIADOSE,FICWDOSE,FIAWDOSE,LLCDOSE,LLADOSE,LLCWDOSE,LLAWDOSE,DLCDOSE,DLADOSE,DLCWDOSE,DLAWDOSE,DUREXP,EXPWK,IPDURWK,IPDSINT,IPDSINTR,IPDSINR3,IRDURWK,IRDSINT,IRDSINTR,IRDSINR3,FBDURWK,FBDSINT,FBDSINTR,FBDSINR3,FIDURWK,FIDSINT,FIDSINTR,FIDSINR3,LLDURWK,LLDSINT,LLDSINTR,LLDSINR3,DLDURWK,DLDSINT,DLDSINTR,DLDSINR3,IPDLYNM,IPDLYPC,DSDLYNM,DSDLYPC,CHDLYNM,CHDLYPC,IPDECNMW,IPDECPCW,IRDECNMW,IRDECPCW,FBDECPCW,FIDECPCW,DECNMW,DECPCW,DECCHNMW,DECCHPCW,PROPDOSE,SKYN,SKDY,SKSEVCD,SKSEV,SKSEVDY,SKDUR,SKDURC,SKSEVDUR,SKSEVDRC,SKDIS,EYYN,EYDY,EYSEVCD,EYSEV,EYSEVDY,EYDUR,EYDURC,EYSEVDUR,EYSEVDRC,CSYN,CSDY,CSSEVDY,CSDUR,CSDURC,CSSEVDUR,CSSEVDRC,CSDIS,HAYN,HADY,HASEVDY,HADUR,HADURC,HASEVDUR,HASEVDRC,HADIS,NAYN,NADY,NASEVCD,NASEV,NASEVDY,NADUR,NADURC,NASEVDUR,NASEVDRC,B_ECOGCD,B_ECOG,TRTDUR
0,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,1.0,1.0,0.0,0.0,246.0,NaN,NaN,0.0,248.0,0.0,248.0,0.0,N,Y,29.0,0.0,NaN,0.0,Y,N,N,Y,N,Y,N,N,N,N,N,N,N,N,N,N,Y,N,N,N,Y,N,N,N,N,N,N,N,N,0.0,None,N,0.0,None,N,N,N,N,0.0,None,N,0.0,None,16.0,16.0,16.0,16.0,16.0,16.0,16.0,NaN,16.0,16.0,7680.0,480.0,96.083523,6.005220,5804.98,362.811250,2887.702109,180.481382,12900.05,806.253125,6417.162747,401.072672,77418.00,4838.625000,38511.736255,2406.983516,NaN,NaN,NaN,NaN,12892.16,805.760000,6413.226244,400.826640,232.0,33.142857,32.857143,5.848562,97.476037,100.852743,32.857143,175.773172,97.651762,101.056988,32.857143,390.609906,97.652477,101.057545,32.857143,2344.192642,97.674693,101.066081,NaN,NaN,NaN,NaN,32.857143,390.370293,97.592573,101.057545,1.0,0.062500,1.0,0.062500,1.0,0.062500,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,3.041537,1.0,0.0,1.0,Mild,0.0,248.0,0.0,248.0,0.0,N,0.0,246.0,0.0,None,246.0,NaN,NaN,NaN,NaN,0.0,246.0,246.0,NaN,NaN,NaN,NaN,N,1.0,138.0,138.0,110.0,0.0,110.0,0.0,N,0.0,246.0,0.0,None,246.0,NaN,NaN,NaN,NaN,0,Fully active,219.0
1,20050181,1001,201001002,66.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,N,N,215.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,1.0,1.0,10.0,0.0,88.0,NaN,NaN,10.0,33.0,1.0,18.0,1.0,N,N,NaN,NaN,NaN,0.0,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,Y,N,N,N,Y,N,N,N,N,N,N,N,N,0.0,None,N,0.0,None,Y,N,N,N,0.0,None,N,0.0,None,5.0,5.0,5.0,5.0,5.0,5.0,5.0,NaN,5.0,5.0,2790.0,558.0,30.131868,6.026374,1900.20,380.040000,888.070325,177.614065,4222.70,844.540000,1973.505190,394.701038,25341.69,5068.338000,11843.605399,2368.721080,NaN,NaN,NaN,NaN,4222.16,844.432000,1973.253368,394.650674,73.0,10.428571,10.142857,5.941495,99.024919,99.024919,10.142857,175.112459,97.284699,97.284699,10.142857,389.141869,97.285467,97.285467,10.142857,2335.358811,97.306617,97.306617,NaN,NaN,NaN,NaN,10.142857,389.092213,97.273053,97.273053,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,2.770317,1.0,10.0,2.0,Moderate,10.0,33.0,1.0,18.0,1.0,N,0.0,88.0,0.0,None,88.0,NaN,NaN,NaN,NaN,0.0,88.0,88.0,NaN,NaN,NaN,NaN,N,0.0,88.0,88.0,NaN,NaN,NaN,NaN,N,0.0,88.0,0.0,None,88.0,NaN,NaN,NaN,NaN,0,Fully active,60.0
2,20050181,1001,201001004,58.0,F,Female,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,0.0,N,0.0,N,0.0,N,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,Y,N,392.0,0.0,Fully active,0 or 1,1252.0,Rectal,0.0,N,Y,1.0,Wild-type,Y,Y,Y,Y,3.0,1.0,215.0,1.0,448.0,8.0,1.0,448.0,164.0,1.0,8.0,1.0,N,Y,27.0,1.0,27.0,0.0,Y,N,N,Y,N,N,N,N,N,N,N,N,N,N,N,N,Y,Y,N,N,Y,Y,N,N,N,N,N,N,N,0.0,None,Y,2.0,Moderate,Y,N,N,N,0.0,None,N,0.0,None,27.0,27.0,27.0,27.0,27.0,27.0,27.0,NaN,27.0,27.0,10044.0,372.0,160.326744,5.938028,8115.57,300.576667,4801.922625,177.848986,15045.67,557.247037,8906.748058,329.879558,93367.44,3458.053333,55266.565868,2046.909847,NaN,NaN,NaN,NaN,17810.00,659.629630,10536.729345,390.249235,450.0,64.285714,64.000000,5.010211,83.503513,77.713352,64.000000,150.060082,83.366712,74.150184,64.000000,278.335877,69.583969,73.657783,64.000000,1727.080183,71.961674,74.178635,NaN,NaN,NaN,NaN,64.000000,329.272792,82.318198,68.817350,7.0,0.259259,7.0,0.259259,7.0,0.259259,0.0,0.0,1.0,0.037037,0.037037,0.037037,1.0,0.037037,1.0,0.037037,2.845723,1.0,215.0,3.0,Severe,448.0,164.0,1.0,8.0,1.0,N,0.0,463.0,0.0,None,463.0,NaN,NaN,NaN,NaN,0.0,463.0,463.0,NaN,NaN,NaN,NaN,N,0.0,463.0,463.0,NaN,NaN,NaN,NaN,N,0.0,463.0,0.0,None,463.0,NaN,NaN,NaN,NaN,0,Fully active,437.0
3,20050181,1001,201001005,75.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,2.0,2,0.0,N,0.0,N,,N,N,267.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,1.0,Wild-type,Y,Y,Y,Y,2.0,1.0,0.0,1.0,0.0,28.0,1.0,0.0,147.0,1.0,28.0,1.0,N,N,NaN,NaN,NaN,0.0,N,N,N,N,N,N,N,N,N,Y,Y,Y,N,N,N,N,Y,Y,Y,N,Y,Y,Y,N,N,N,N,N,N,0.0,None,Y,4.0,Life threatening,N,N,N,N,0.0,None,N,0.0,None,15.0,14.0,15.0,15.0,15.0,15.0,15.0,NaN,15.0,15.0,8904.0,636.0,87.811927,6.272281,6171.37,411.424667,2680.251769,178.683451,13714.88,914.325333,5956.430729,397.095382,82300.00,5486.666667,35743.244341,2382.882956,NaN,NaN,NaN,NaN,13712.92,914.194667,5955.606959,397.040464,233.0,33.285714,33.000000,5.321935,88.698916,83.419587,33.000000,162.439501,90.244167,93.664506,33.000000,360.995802,90.248950,93.675359,33.000000,2166.257233,90.260718,93.707548,NaN,NaN,NaN,NaN,33.000000,360.945876,90.236469,93.540974,2.0,0.142857,2.0,0.133333,2.0,0.133333,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,2.732272,1.0,0.0,3.0,Severe,0.0,147.0,1.0,28.0,1.0,N,0.0,245.0,0.0,None,245.0,NaN,NaN,NaN,NaN,0.0,245.0,245.0,NaN,NaN,NaN,NaN,N,1.0,28.0,42.0,119.0,1.0,89.0,1.0,N,0.0,245.0,0.0,None,245.0,NaN,NaN,NaN,NaN,0,Fully active,220.0
4,20050181,1001,201001006,52.0,M,Male,1.0,White or Caucasian,NaN,,,41.0,FOLFIRI alone,41.0,FOLFIRI alone,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,Y,Y,572.0,1.0,Symptoms but ambulatory,0 or 1,1251.0,Colon,1.0,Y,Y,88.0,Failed,Y,Y,N,Y,1.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,N,N,NaN,NaN,NaN,0.0,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,Y,N,N,N,N,N,N,N,N,N,N,N,N,0.0,None,N,0.0,None,N,N,N,N,0.0,None,N,0.0,None,1.0,NaN,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,360.00,360.000000,133.957513,133.957513,800.00,800.000000,297.683363,297.683363,4800.00,4800.000000,1786.100178,1786.100178,NaN,NaN,NaN,NaN,800.00,800.000000,297.683363,297.683363,16.0,2.285714,NaN,NaN,NaN,NaN,2.000000,133.957513,74.420841,74.420841,2.000000,297.683363,74.420841,74.420841,2.000000,1786.100178,74.420841,74.420841,NaN,NaN,NaN,NaN,2.000000,297.683363,74.420841,74.420841,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,NaN,0.0,0.0,0.0,None,0.0,NaN,NaN,NaN,NaN,N,0.0,0.0,0.0,None,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,N,0.0,0.0,0.0,NaN,NaN,NaN,NaN,N,0.0,0.0,0.0,None,0.0,NaN,NaN,NaN,NaN,1,Symptoms but ambulatory,3.0

In [222]:
_ = read_domain('NCT00339183_panitumumab_folfiri_raw', 'ae.sas7bdat')

--- NCT00339183_panitumumab_folfiri_raw/ae.sas7bdat ---
shape: (14842, 129)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'PRBEVCDR', 'PRBEVR', 'PRBEVCDM', 'PRBEVM', 'PRBEVCD', 'PRBEV', 'PROXACDR', 'PROXAR', 'PROXACDM', 'PROXAM', 'PROXALCD', 'PROXAL', 'B_METANM', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'PADJYNCD', 'PRADJYN', 'DPADJUV', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'KRASCD', 'KRAS', 'EVALITT', 'EVALPP', 'EVALQOL', 'EVALEGFR', 'AEANY', 'AELINENO', 'PHASECD', 'PHASE', 'PHSENDCD', 'PHASEND', 'AESTDY', 'AESTDYI', 'AEENDY', 'AEENDYI', 'AETERM', 'AELLT', 'AEPT', 'AEHLT', 'AEHLGT', 'AELLTCD', 'AESOC', 'AEDUR', 'AEDURI', 'AECONT', 'AEPRCNT', 'AENUMINF', 'AENUMCTX', 'AEPRIOR', 'AERASH', 'AEINTEYE', 'AEINTINF', 'AEINTCAT', 'AENASTCD', 'AENASTER', 'AEINTMT', 'AESEVCD', 'AESEV', 'AEREL', 'AERELCM', 'AEINFCTC', 'AEINFREP', 'AEINFPI', 'AECRDTOX', 'AEPULTOX', 'AEVASTOX', 'AEDIARR', 'AESTOMA', 'AECALCEM', 'AEMAGNES', 'AENEUTOX', 'AEHEMTOX', 'AEACTCDS', 'AEACT01', 'AEACT02', 'AEACT03', 'AEACT04', 'AEACT05', 'AEACT06', 'AEACT07', 'AEACT10', 'AEACT81', 'AEACT82', 'AEACT83', 'AEACT88', 'AESER', 'SAELIFE', 'AEWDOS', 'AECDOS', 'AEIRWDOS', 'AEIRCDOS', 'AEFIWDOS', 'AEFICDOS', 'AEFBWDOS', 'AEFBCDOS', 'AELLWDOS', 'AELLCDOS', 'AEDLWDOS', 'AEDLCDOS', 'B_ECOGCD', 'B_ECOG', 'TRTDUR', 'MEDDRA_V']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,PRBEVCDR,PRBEVR,PRBEVCDM,PRBEVM,PRBEVCD,PRBEV,PROXACDR,PROXAR,PROXACDM,PROXAM,PROXALCD,PROXAL,B_METANM,B_METACT,LIVRONCD,LIVRONLY,PADJYNCD,PRADJYN,DPADJUV,B_LDHYN,B_LDH2YN,B_LDHNM,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,KRASCD,KRAS,EVALITT,EVALPP,EVALQOL,EVALEGFR,AEANY,AELINENO,PHASECD,PHASE,PHSENDCD,PHASEND,AESTDY,AESTDYI,AEENDY,AEENDYI,AETERM,AELLT,AEPT,AEHLT,AEHLGT,AELLTCD,AESOC,AEDUR,AEDURI,AECONT,AEPRCNT,AENUMINF,AENUMCTX,AEPRIOR,AERASH,AEINTEYE,AEINTINF,AEINTCAT,AENASTCD,AENASTER,AEINTMT,AESEVCD,AESEV,AEREL,AERELCM,AEINFCTC,AEINFREP,AEINFPI,AECRDTOX,AEPULTOX,AEVASTOX,AEDIARR,AESTOMA,AECALCEM,AEMAGNES,AENEUTOX,AEHEMTOX,AEACTCDS,AEACT01,AEACT02,AEACT03,AEACT04,AEACT05,AEACT06,AEACT07,AEACT10,AEACT81,AEACT82,AEACT83,AEACT88,AESER,SAELIFE,AEWDOS,AECDOS,AEIRWDOS,AEIRCDOS,AEFIWDOS,AEFICDOS,AEFBWDOS,AEFBCDOS,AELLWDOS,AELLCDOS,AEDLWDOS,AEDLCDOS,B_ECOGCD,B_ECOG,TRTDUR,MEDDRA_V
0,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,Y,3.0,30.0,Treatment,70.0,Ongoing,NaN,1.0,NaN,NaN,DRY SKIN,Dry skin,DRY SKIN,Dermal and epidermal conditions NEC,Epidermal and dermal conditions,10013786.0,Skin and subcutaneous tissue disorders,NaN,NaN,Y,,1.0,1.0,N,Y,Y,N,SKIN,NaN,,,1.0,Mild,Y,N,N,N,N,N,N,N,N,N,N,N,N,N,1,Y,N,N,N,N,N,N,N,N,N,N,N,N,,6.000000,6.000000,179.903298,179.903298,2398.710643,2398.710643,399.785107,399.785107,NaN,NaN,399.785107,399.785107,0,Fully active,219.0,12.0
1,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,Y,2.0,30.0,Treatment,30.0,Treatment,NaN,1.0,204.0,204.0,OBSTIPATION,Obstipation,CONSTIPATION,Gastrointestinal atonic and hypomotility disor...,Gastrointestinal motility and defaecation cond...,10029932.0,Gastrointestinal disorders,NaN,204.0,N,,1.0,1.0,N,N,N,N,,NaN,,Y,1.0,Mild,N,Y,N,N,N,N,N,N,N,N,N,N,N,N,1,Y,N,N,N,N,N,N,N,N,N,N,N,N,,6.000000,6.000000,179.903298,179.903298,2398.710643,2398.710643,399.785107,399.785107,NaN,NaN,399.785107,399.785107,0,Fully active,219.0,12.0
2,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,Y,1.0,30.0,Treatment,30.0,Treatment,9.0,9.0,57.0,57.0,ACNEIFORM RASH FACE,Rash acneiform,DERMATITIS ACNEIFORM,Acnes,Skin appendage conditions,10037847.0,Skin and subcutaneous tissue disorders,49.0,49.0,N,,1.0,1.0,N,Y,Y,N,SKIN,15.0,Steroids or Narcotics given for tx-related ski...,,1.0,Mild,Y,N,N,N,N,N,N,N,N,N,N,N,N,N,3,N,N,Y,N,N,N,N,N,N,N,N,N,N,,6.000000,6.000000,179.903298,179.903298,2398.710643,2398.710643,399.785107,399.785107,NaN,NaN,399.785107,399.785107,0,Fully active,219.0,12.0
3,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,Y,1.0,30.0,Treatment,70.0,Ongoing,139.0,139.0,NaN,NaN,ALOPECIA,Alopecia,ALOPECIA,Alopecias,Skin appendage conditions,10001760.0,Skin and subcutaneous tissue disorders,NaN,NaN,Y,,11.0,11.0,N,N,Y,N,HAIR,NaN,,,1.0,Mild,N,Y,N,N,N,N,N,N,N,N,N,N,N,N,1,Y,N,N,N,N,N,N,N,N,N,N,N,N,,6.000000,65.777778,181.091714,1982.449216,2416.611468,26442.364034,402.430451,4405.475769,NaN,NaN,401.774088,4404.163042,0,Fully active,219.0,12.0
4,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,Y,1.0,30.0,Treatment,70.0,Ongoing,NaN,220.0,NaN,NaN,GASTROINTESTINAL INFECTION,Gastrointestinal infection,GASTROINTESTINAL INFECTION,Abdominal and gastrointestinal infections,Infections - pathogen unspecified,10017964.0,Infections and infestations,NaN,NaN,Y,,16.0,16.0,N,N,N,N,,NaN,,,2.0,Moderate,N,N,N,N,N,N,N,N,N,N,N,N,N,N,3,N,N,Y,N,N,N,N,N,N,N,N,N,N,,6.075949,96.083523,181.273526,2887.702109,2416.846908,38511.736255,402.832837,6417.162747,NaN,NaN,402.307436,6413.226244,0,Fully active,219.0,12.0

In [223]:
_ = read_domain('NCT00339183_panitumumab_folfiri_raw', 'chemotx.sas7bdat')

--- NCT00339183_panitumumab_folfiri_raw/chemotx.sas7bdat ---
shape: (2283, 70)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'PRBEVCDR', 'PRBEVR', 'PRBEVCDM', 'PRBEVM', 'PRBEVCD', 'PRBEV', 'PROXACDR', 'PROXAR', 'PROXACDM', 'PROXAM', 'PROXALCD', 'PROXAL', 'B_METANM', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'PADJYNCD', 'PRADJYN', 'DPADJUV', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'KRASCD', 'KRAS', 'EVALITT', 'EVALPP', 'EVALQOL', 'EVALEGFR', 'CHANY', 'CHMETA', 'PHASECD', 'PHASE', 'CHSTDY', 'CHENDY', 'CHLINECD', 'CHLINE', 'CHTERM', 'CHPREF', 'CHSTDTV', 'CHDRSNCD', 'CHDREAS', 'CHRESPCD', 'CHRESP', 'TRTDUR', 'CHPDDY', 'B_ECOGCD', 'B_ECOG']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,PRBEVCDR,PRBEVR,PRBEVCDM,PRBEVM,PRBEVCD,PRBEV,PROXACDR,PROXAR,PROXACDM,PROXAM,PROXALCD,PROXAL,B_METANM,B_METACT,LIVRONCD,LIVRONLY,PADJYNCD,PRADJYN,DPADJUV,B_LDHYN,B_LDH2YN,B_LDHNM,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,KRASCD,KRAS,EVALITT,EVALPP,EVALQOL,EVALEGFR,CHANY,CHMETA,PHASECD,PHASE,CHSTDY,CHENDY,CHLINECD,CHLINE,CHTERM,CHPREF,CHSTDTV,CHDRSNCD,CHDREAS,CHRESPCD,CHRESP,TRTDUR,CHPDDY,B_ECOGCD,B_ECOG
0,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,Y,Y,5.0,Pre-consent,-253.0,-145.0,NaN,,5-FU,FLUOROURACIL,14FEB2006,7.0,Disease progression,4.0,Stable disease,219.0,-54.0,0,Fully active
1,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,Y,Y,5.0,Pre-consent,-253.0,-145.0,NaN,,OXALIPLATIN,OXALIPLATIN,14FEB2006,7.0,Disease progression,4.0,Stable disease,219.0,-54.0,0,Fully active
2,20050181,1001,201001002,66.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,N,N,215.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,Y,Y,5.0,Pre-consent,-161.0,-89.0,NaN,,CAPECITABINE,CAPECITABINE,29MAY2006,7.0,Disease progression,5.0,Progressive disease,60.0,-80.0,0,Fully active
3,20050181,1001,201001002,66.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,N,N,215.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,Y,Y,5.0,Pre-consent,-161.0,-89.0,NaN,,OXALIPLATIN,OXALIPLATIN,29MAY2006,7.0,Disease progression,5.0,Progressive disease,60.0,-80.0,0,Fully active
4,20050181,1001,201001004,58.0,F,Female,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,0.0,N,0.0,N,0.0,N,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,Y,N,392.0,0.0,Fully active,0 or 1,1252.0,Rectal,0.0,N,Y,1.0,Wild-type,Y,Y,Y,Y,Y,Y,5.0,Pre-consent,-356.0,-189.0,NaN,,CAPECITABINE,CAPECITABINE,07FEB2006,7.0,Disease progression,3.0,Partial response,437.0,-39.0,0,Fully active

In [224]:
_ = read_domain('NCT00339183_panitumumab_folfiri_raw', 'corevar.sas7bdat')

--- NCT00339183_panitumumab_folfiri_raw/corevar.sas7bdat ---
shape: (946, 54)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'PRBEVCDR', 'PRBEVR', 'PRBEVCDM', 'PRBEVM', 'PRBEVCD', 'PRBEV', 'PROXACDR', 'PROXAR', 'PROXACDM', 'PROXAM', 'PROXALCD', 'PROXAL', 'B_METANM', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'PADJYNCD', 'PRADJYN', 'DPADJUV', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'KRASCD', 'KRAS', 'EVALITT', 'EVALPP', 'EVALQOL', 'EVALEGFR', 'B_ECOGCD', 'B_ECOG', 'TRTDUR']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,PRBEVCDR,PRBEVR,PRBEVCDM,PRBEVM,PRBEVCD,PRBEV,PROXACDR,PROXAR,PROXACDM,PROXAM,PROXALCD,PROXAL,B_METANM,B_METACT,LIVRONCD,LIVRONLY,PADJYNCD,PRADJYN,DPADJUV,B_LDHYN,B_LDH2YN,B_LDHNM,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,KRASCD,KRAS,EVALITT,EVALPP,EVALQOL,EVALEGFR,B_ECOGCD,B_ECOG,TRTDUR
0,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,0,Fully active,219.0
1,20050181,1001,201001002,66.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,N,N,215.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,0,Fully active,60.0
2,20050181,1001,201001004,58.0,F,Female,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,0.0,N,0.0,N,0.0,N,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,Y,N,392.0,0.0,Fully active,0 or 1,1252.0,Rectal,0.0,N,Y,1.0,Wild-type,Y,Y,Y,Y,0,Fully active,437.0
3,20050181,1001,201001005,75.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,2.0,2,0.0,N,0.0,N,,N,N,267.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,1.0,Wild-type,Y,Y,Y,Y,0,Fully active,220.0
4,20050181,1001,201001006,52.0,M,Male,1.0,White or Caucasian,NaN,,,41.0,FOLFIRI alone,41.0,FOLFIRI alone,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,Y,Y,572.0,1.0,Symptoms but ambulatory,0 or 1,1251.0,Colon,1.0,Y,Y,88.0,Failed,Y,Y,N,Y,1,Symptoms but ambulatory,3.0

In [225]:
_ = read_domain('NCT00339183_panitumumab_folfiri_raw', 'death.sas7bdat')

--- NCT00339183_panitumumab_folfiri_raw/death.sas7bdat ---
shape: (837, 62)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'PRBEVCDR', 'PRBEVR', 'PRBEVCDM', 'PRBEVM', 'PRBEVCD', 'PRBEV', 'PROXACDR', 'PROXAR', 'PROXACDM', 'PROXAM', 'PROXALCD', 'PROXAL', 'B_METANM', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'PADJYNCD', 'PRADJYN', 'DPADJUV', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'KRASCD', 'KRAS', 'EVALITT', 'EVALPP', 'EVALQOL', 'EVALEGFR', 'B_ECOGCD', 'B_ECOG', 'TRTDUR', 'DTHDY', 'DTHDYI', 'DTHDYI2', 'PHASECD', 'PHASE', 'DTCAUSCD', 'DTCAUS', 'DTAEPT']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,PRBEVCDR,PRBEVR,PRBEVCDM,PRBEVM,PRBEVCD,PRBEV,PROXACDR,PROXAR,PROXACDM,PROXAM,PROXALCD,PROXAL,B_METANM,B_METACT,LIVRONCD,LIVRONLY,PADJYNCD,PRADJYN,DPADJUV,B_LDHYN,B_LDH2YN,B_LDHNM,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,KRASCD,KRAS,EVALITT,EVALPP,EVALQOL,EVALEGFR,B_ECOGCD,B_ECOG,TRTDUR,DTHDY,DTHDYI,DTHDYI2,PHASECD,PHASE,DTCAUSCD,DTCAUS,DTAEPT
0,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,0,Fully active,219.0,294.0,294.0,294.0,60.0,Long-term follow-up,7.0,Disease progression,
1,20050181,1001,201001002,66.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,N,N,215.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,0,Fully active,60.0,134.0,134.0,134.0,60.0,Long-term follow-up,7.0,Disease progression,
2,20050181,1001,201001004,58.0,F,Female,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,0.0,N,0.0,N,0.0,N,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,Y,N,392.0,0.0,Fully active,0 or 1,1252.0,Rectal,0.0,N,Y,1.0,Wild-type,Y,Y,Y,Y,0,Fully active,437.0,789.0,789.0,789.0,60.0,Long-term follow-up,7.0,Disease progression,
3,20050181,1001,201001005,75.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,2.0,2,0.0,N,0.0,N,,N,N,267.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,1.0,Wild-type,Y,Y,Y,Y,0,Fully active,220.0,323.0,323.0,323.0,60.0,Long-term follow-up,7.0,Disease progression,
4,20050181,1001,201001007,50.0,M,Male,1.0,White or Caucasian,NaN,,,41.0,FOLFIRI alone,41.0,FOLFIRI alone,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,Y,N,475.0,0.0,Fully active,0 or 1,1252.0,Rectal,0.0,N,Y,NaN,,Y,N,Y,N,0,Fully active,52.0,233.0,233.0,233.0,60.0,Long-term follow-up,7.0,Disease progression,

In [226]:
_ = read_domain('NCT00339183_panitumumab_folfiri_raw', 'demo.sas7bdat')

--- NCT00339183_panitumumab_folfiri_raw/demo.sas7bdat ---
shape: (946, 112)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'PRBEVCDR', 'PRBEVR', 'PRBEVCDM', 'PRBEVM', 'PRBEVCD', 'PRBEV', 'PROXACDR', 'PROXAR', 'PROXACDM', 'PROXAM', 'PROXALCD', 'PROXAL', 'B_METANM', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'PADJYNCD', 'PRADJYN', 'DPADJUV', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'KRASCD', 'KRAS', 'EVALITT', 'EVALPP', 'EVALQOL', 'EVALEGFR', 'B_ECOGCD', 'B_ECOG', 'TRTDUR', 'B_WEIGHT', 'B_HEIGHT', 'B_BSA', 'DIAGMONS', 'METMONS', 'HISTYPCD', 'HISTYPE', 'HISSBTCD', 'HISSUBTY', 'HDIFFCD', 'HDIFFER', 'BIOPPNO', 'BIOPACPT', 'BIOPPFCD', 'BIOPF', 'BIOPHACT', 'BIOPHFCD', 'BIOPHF', 'BIOPSTCD', 'BIOPSITE', 'BIOPBSCD', 'BIOPBSIT', 'BIOPNO', 'BIOPTPCT', 'BIOPRSCD', 'BIOPRS', 'BIOPEFCD', 'BIOPEF', 'BIOPNEG', 'BIOPWEAK', 'BIOPMOD', 'BIOPSTRG', 'BIOP3', 'BIOPS123', 'BIOPMAX', 'BIOPPCCD', 'BIOPPCT', 'BIOPCYTO', 'H11NEG', 'H11WEAK', 'H11MOD', 'BIOPMAXC', 'BIOPCYCD', 'BIOPCY', 'UGT1A1YN', 'CHILDPOT', 'PREGDONE', 'PREGTYCD', 'PREGTYPE', 'PREGRSCD', 'PREGRES', 'BIONANY', 'BIORSNCD', 'diagdy', 'metdxdy', 'biopdy', 'biopdy2', 'PREGDY']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,PRBEVCDR,PRBEVR,PRBEVCDM,PRBEVM,PRBEVCD,PRBEV,PROXACDR,PROXAR,PROXACDM,PROXAM,PROXALCD,PROXAL,B_METANM,B_METACT,LIVRONCD,LIVRONLY,PADJYNCD,PRADJYN,DPADJUV,B_LDHYN,B_LDH2YN,B_LDHNM,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,KRASCD,KRAS,EVALITT,EVALPP,EVALQOL,EVALEGFR,B_ECOGCD,B_ECOG,TRTDUR,B_WEIGHT,B_HEIGHT,B_BSA,DIAGMONS,METMONS,HISTYPCD,HISTYPE,HISSBTCD,HISSUBTY,HDIFFCD,HDIFFER,BIOPPNO,BIOPACPT,BIOPPFCD,BIOPF,BIOPHACT,BIOPHFCD,BIOPHF,BIOPSTCD,BIOPSITE,BIOPBSCD,BIOPBSIT,BIOPNO,BIOPTPCT,BIOPRSCD,BIOPRS,BIOPEFCD,BIOPEF,BIOPNEG,BIOPWEAK,BIOPMOD,BIOPSTRG,BIOP3,BIOPS123,BIOPMAX,BIOPPCCD,BIOPPCT,BIOPCYTO,H11NEG,H11WEAK,H11MOD,BIOPMAXC,BIOPCYCD,BIOPCY,UGT1A1YN,CHILDPOT,PREGDONE,PREGTYCD,PREGTYPE,PREGRSCD,PREGRES,BIONANY,BIORSNCD,diagdy,metdxdy,biopdy,biopdy2,PREGDY
0,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,0,Fully active,219.0,80.0,182.0,2.011080,9.540984,9.540984,18.0,Adenocarcinoma,0.0,No sub-type,2.0,Moderately differentiated,167/06,Y,NaN,,Y,NaN,,1.0,Primary,NaN,,>500 cells present,61.28,1.0,Positive,NaN,,85.3,9.8,5.0,0.0,N,14.8,2+,35.0,10 to 35%,2.1,97.9,2.1,0.0,1+,30.0,<10%,N,N,,NaN,,66.0,Not applicable,,NaN,-293.0,-293.0,644.0,667.0,NaN
1,20050181,1001,201001002,66.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,N,N,215.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,0,Fully active,60.0,93.0,178.0,2.144372,6.131148,6.131148,18.0,Adenocarcinoma,0.0,No sub-type,99.0,Unknown,8705/06 Tu,Y,NaN,,Y,NaN,,1.0,Primary,NaN,,>500 cells present,43.22,1.0,Positive,NaN,,99.9,0.1,0.0,0.0,N,0.1,1+,30.0,<10%,0.0,100.0,0.0,0.0,0,30.0,<10%,N,N,,NaN,,66.0,Not applicable,,NaN,-193.0,-193.0,670.0,698.0,NaN
2,20050181,1001,201001004,58.0,F,Female,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,0.0,N,0.0,N,0.0,N,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,Y,N,392.0,0.0,Fully active,0 or 1,1252.0,Rectal,0.0,N,Y,1.0,Wild-type,Y,Y,Y,Y,0,Fully active,437.0,62.0,164.0,1.680608,12.327869,12.852459,18.0,Adenocarcinoma,99.0,Unknown,2.0,Moderately differentiated,141/06Di 4,Y,NaN,,Y,NaN,,1.0,Primary,NaN,,100-500 cells present,46.74,2.0,Negative,NaN,,100.0,0.0,0.0,0.0,N,0.0,0,30.0,<10%,0.0,100.0,0.0,0.0,0,30.0,<10%,N,N,,NaN,,66.0,Not applicable,,NaN,-381.0,-397.0,554.0,571.0,NaN
3,20050181,1001,201001005,75.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,2.0,2,0.0,N,0.0,N,,N,N,267.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,1.0,Wild-type,Y,Y,Y,Y,0,Fully active,220.0,106.0,188.0,2.352776,9.803279,9.803279,18.0,Adenocarcinoma,0.0,No sub-type,2.0,Moderately differentiated,7611/06,Y,NaN,,Y,NaN,,1.0,Primary,NaN,,100-500 cells present,23.90,1.0,Positive,NaN,,96.3,3.8,0.0,0.0,N,3.8,1+,30.0,<10%,0.0,100.0,0.0,0.0,0,30.0,<10%,N,N,,NaN,,66.0,Not applicable,,NaN,-306.0,-306.0,589.0,616.0,NaN
4,20050181,1001,201001006,52.0,M,Male,1.0,White or Caucasian,NaN,,,41.0,FOLFIRI alone,41.0,FOLFIRI alone,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,Y,Y,572.0,1.0,Symptoms but ambulatory,0 or 1,1251.0,Colon,1.0,Y,Y,88.0,Failed,Y,Y,N,Y,1,Symptoms but ambulatory,3.0,130.0,200.0,2.687419,2.885246,3.540984,18.0,Adenocarcinoma,99.0,Unknown,2.0,Moderately differentiated,24140/06,Y,NaN,,Y,NaN,,1.0,Primary,NaN,,100-500 cells present,42.19,1.0,Positive,NaN,,95.3,4.5,0.2,0.0,N,4.7,2+,30.0,<10%,5.1,94.9,5.1,0.0,1+,30.0,<10%,N,N,,NaN,,66.0,Not applicable,,NaN,-89.0,-109.0,518.0,535.0,NaN

In [227]:
_ = read_domain('NCT00339183_panitumumab_folfiri_raw', 'disposit.sas7bdat')

--- NCT00339183_panitumumab_folfiri_raw/disposit.sas7bdat ---
shape: (946, 89)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'PRBEVCDR', 'PRBEVR', 'PRBEVCDM', 'PRBEVM', 'PRBEVCD', 'PRBEV', 'PROXACDR', 'PROXAR', 'PROXACDM', 'PROXAM', 'PROXALCD', 'PROXAL', 'B_METANM', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'PADJYNCD', 'PRADJYN', 'DPADJUV', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'KRASCD', 'KRAS', 'EVALITT', 'EVALPP', 'EVALQOL', 'EVALEGFR', 'ICSIGN', 'RANDNO', 'LDOSDSDY', 'EOIPCD', 'EOIP', 'EOIPPDCD', 'EOIPPD', 'EOIPRDCD', 'EOIPRD', 'DSDOSDY', 'DSSTATCD', 'DSSTAT', 'DSREASCD', 'DSREAS', 'DSFPSCD', 'DSFPS', 'DSCMPEOS', 'DSRRADCD', 'DSRRAD', 'EORCRTCD', 'EORCRIT', 'EORDPCD', 'EORDP', 'PFUP', 'TRTDUR', 'FPANDY', 'LPANDY', 'FCTTXDY', 'LCTTXDY', 'DSDY', 'DECISDY', 'EOIPDY', 'EOPPDY', 'EORADDY', 'LASTOSDY', 'LASTCTDY', 'B_ECOGCD', 'B_ECOG']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,PRBEVCDR,PRBEVR,PRBEVCDM,PRBEVM,PRBEVCD,PRBEV,PROXACDR,PROXAR,PROXACDM,PROXAM,PROXALCD,PROXAL,B_METANM,B_METACT,LIVRONCD,LIVRONLY,PADJYNCD,PRADJYN,DPADJUV,B_LDHYN,B_LDH2YN,B_LDHNM,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,KRASCD,KRAS,EVALITT,EVALPP,EVALQOL,EVALEGFR,ICSIGN,RANDNO,LDOSDSDY,EOIPCD,EOIP,EOIPPDCD,EOIPPD,EOIPRDCD,EOIPRD,DSDOSDY,DSSTATCD,DSSTAT,DSREASCD,DSREAS,DSFPSCD,DSFPS,DSCMPEOS,DSRRADCD,DSRRAD,EORCRTCD,EORCRIT,EORDPCD,EORDP,PFUP,TRTDUR,FPANDY,LPANDY,FCTTXDY,LCTTXDY,DSDY,DECISDY,EOIPDY,EOPPDY,EORADDY,LASTOSDY,LASTCTDY,B_ECOGCD,B_ECOG
0,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,Y,40022.0,219.0,7.0,Disease progression,199.0,Radiographically determined disease progression,199.0,Radiographically determined disease progression,247.0,1.0,Completed safety FUP,NaN,,NaN,,Y,NaN,,NaN,,NaN,,202.0,219.0,1.0,217.0,1.0,219.0,247.0,240.0,240.0,240.0,NaN,248.0,248.0,0,Fully active
1,20050181,1001,201001002,66.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,N,N,215.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,Y,40025.0,60.0,7.0,Disease progression,199.0,Radiographically determined disease progression,199.0,Radiographically determined disease progression,89.0,1.0,Completed safety FUP,NaN,,NaN,,Y,NaN,,NaN,,NaN,,200.0,60.0,1.0,58.0,1.0,60.0,89.0,71.0,71.0,71.0,NaN,89.0,89.0,0,Fully active
2,20050181,1001,201001004,58.0,F,Female,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,0.0,N,0.0,N,0.0,N,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,Y,N,392.0,0.0,Fully active,0 or 1,1252.0,Rectal,0.0,N,Y,1.0,Wild-type,Y,Y,Y,Y,Y,20147.0,437.0,7.0,Disease progression,199.0,Radiographically determined disease progression,199.0,Radiographically determined disease progression,464.0,1.0,Completed safety FUP,NaN,,NaN,,Y,NaN,,NaN,,NaN,,188.0,437.0,1.0,435.0,1.0,437.0,464.0,456.0,456.0,456.0,NaN,464.0,725.0,0,Fully active
3,20050181,1001,201001005,75.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,2.0,2,0.0,N,0.0,N,,N,N,267.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,1.0,Wild-type,Y,Y,Y,Y,Y,40054.0,220.0,7.0,Disease progression,199.0,Radiographically determined disease progression,199.0,Radiographically determined disease progression,246.0,1.0,Completed safety FUP,NaN,,NaN,,Y,NaN,,NaN,,NaN,,186.0,220.0,1.0,218.0,1.0,220.0,246.0,232.0,232.0,232.0,NaN,246.0,302.0,0,Fully active
4,20050181,1001,201001006,52.0,M,Male,1.0,White or Caucasian,NaN,,,41.0,FOLFIRI alone,41.0,FOLFIRI alone,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,Y,Y,572.0,1.0,Symptoms but ambulatory,0 or 1,1251.0,Colon,1.0,Y,Y,88.0,Failed,Y,Y,N,Y,Y,40067.0,3.0,NaN,,NaN,,NaN,,1.0,2.0,Did not complete safety FUP,6.0,Consent withdrawn,NaN,,N,NaN,,NaN,,NaN,,183.0,3.0,NaN,NaN,1.0,3.0,1.0,15.0,NaN,15.0,NaN,15.0,15.0,1,Symptoms but ambulatory

In [228]:
_ = read_domain('NCT00339183_panitumumab_folfiri_raw', 'eligcrit.sas7bdat')

--- NCT00339183_panitumumab_folfiri_raw/eligcrit.sas7bdat ---
shape: (1062, 56)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'PRBEVCDR', 'PRBEVR', 'PRBEVCDM', 'PRBEVM', 'PRBEVCD', 'PRBEV', 'PROXACDR', 'PROXAR', 'PROXACDM', 'PROXAM', 'PROXALCD', 'PROXAL', 'B_METANM', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'PADJYNCD', 'PRADJYN', 'DPADJUV', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'KRASCD', 'KRAS', 'EVALITT', 'EVALPP', 'EVALQOL', 'EVALEGFR', 'B_ECOGCD', 'B_ECOG', 'TRTDUR', 'ELIGIBLE', 'ELIGNMCD']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,PRBEVCDR,PRBEVR,PRBEVCDM,PRBEVM,PRBEVCD,PRBEV,PROXACDR,PROXAR,PROXACDM,PROXAM,PROXALCD,PROXAL,B_METANM,B_METACT,LIVRONCD,LIVRONLY,PADJYNCD,PRADJYN,DPADJUV,B_LDHYN,B_LDH2YN,B_LDHNM,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,KRASCD,KRAS,EVALITT,EVALPP,EVALQOL,EVALEGFR,B_ECOGCD,B_ECOG,TRTDUR,ELIGIBLE,ELIGNMCD
0,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,0,Fully active,219.0,Y,NaN
1,20050181,1001,201001002,66.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,N,N,215.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,0,Fully active,60.0,Y,NaN
2,20050181,1001,201001004,58.0,F,Female,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,0.0,N,0.0,N,0.0,N,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,Y,N,392.0,0.0,Fully active,0 or 1,1252.0,Rectal,0.0,N,Y,1.0,Wild-type,Y,Y,Y,Y,0,Fully active,437.0,Y,NaN
3,20050181,1001,201001005,75.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,2.0,2,0.0,N,0.0,N,,N,N,267.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,1.0,Wild-type,Y,Y,Y,Y,0,Fully active,220.0,Y,NaN
4,20050181,1001,201001006,52.0,M,Male,1.0,White or Caucasian,NaN,,,41.0,FOLFIRI alone,41.0,FOLFIRI alone,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,Y,Y,572.0,1.0,Symptoms but ambulatory,0 or 1,1251.0,Colon,1.0,Y,Y,88.0,Failed,Y,Y,N,Y,1,Symptoms but ambulatory,3.0,Y,NaN

In [229]:
_ = read_domain('NCT00339183_panitumumab_folfiri_raw', 'exposure.sas7bdat')

--- NCT00339183_panitumumab_folfiri_raw/exposure.sas7bdat ---
shape: (46115, 94)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'PRBEVCDR', 'PRBEVR', 'PRBEVCDM', 'PRBEVM', 'PRBEVCD', 'PRBEV', 'PROXACDR', 'PROXAR', 'PROXACDM', 'PROXAM', 'PROXALCD', 'PROXAL', 'B_METANM', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'PADJYNCD', 'PRADJYN', 'DPADJUV', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'KRASCD', 'KRAS', 'EVALITT', 'EVALPP', 'EVALQOL', 'EVALEGFR', 'DOSREFDY', 'DOSREFWK', 'ENRREFDY', 'ENRREFWK', 'VISITCD', 'VISIT', 'PHASECD', 'PHASE', 'EXDURMN', 'ACTTRTCD', 'ACTTRT', 'DRUGTP', 'QTY', 'QTYUNCD', 'QTYUNIT', 'CONC', 'CONCUNCD', 'CONCUNIT', 'DOSE', 'DOSEUNCD', 'DOSEUNIT', 'WDOSE', 'WDOSUNCD', 'WDOSUNIT', 'BSADOSE', 'ROUTECD', 'ROUTE', 'DOSEFRCD', 'DOSEFREQ', 'DOSINTYN', 'DOSDLAY', 'EXDELDY', 'EXCHEMO', 'EXREASCD', 'EXREAS', 'EXPPRSCD', 'EXCYCLNM', 'EXLOTID', 'EXINFRCT', 'EXENDY', 'TRTDUR', 'B_ECOGCD', 'B_ECOG']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,PRBEVCDR,PRBEVR,PRBEVCDM,PRBEVM,PRBEVCD,PRBEV,PROXACDR,PROXAR,PROXACDM,PROXAM,PROXALCD,PROXAL,B_METANM,B_METACT,LIVRONCD,LIVRONLY,PADJYNCD,PRADJYN,DPADJUV,B_LDHYN,B_LDH2YN,B_LDHNM,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,KRASCD,KRAS,EVALITT,EVALPP,EVALQOL,EVALEGFR,DOSREFDY,DOSREFWK,ENRREFDY,ENRREFWK,VISITCD,VISIT,PHASECD,PHASE,EXDURMN,ACTTRTCD,ACTTRT,DRUGTP,QTY,QTYUNCD,QTYUNIT,CONC,CONCUNCD,CONCUNIT,DOSE,DOSEUNCD,DOSEUNIT,WDOSE,WDOSUNCD,WDOSUNIT,BSADOSE,ROUTECD,ROUTE,DOSEFRCD,DOSEFREQ,DOSINTYN,DOSDLAY,EXDELDY,EXCHEMO,EXREASCD,EXREAS,EXPPRSCD,EXCYCLNM,EXLOTID,EXINFRCT,EXENDY,TRTDUR,B_ECOGCD,B_ECOG
0,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,1.0,1.0,3.0,1.0,C1D1,"Cycle 1, day 1",30.0,Treatment,65.0,1.0,panit.,,124.0,ML,Milliliter (cc),6.0,MG/KG,Milligram/kilogram,480.0,MG,Milligram,6.0000,MG/KG,Milligram/kilogram,NaN,IV,Intravenous,,,N,,NaN,,NaN,,NaN,1.0,L005289,N,NaN,219.0,0,Fully active
1,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,1.0,1.0,3.0,1.0,C1D1,"Cycle 1, day 1",30.0,Treatment,90.0,72.0,Irinotecan,,NaN,,,NaN,,,361.8,MG,Milligram,4.5225,MG/KG,Milligram/kilogram,179.903298,IV,Intravenous,,,,,NaN,Y,NaN,,NaN,1.0,,,1.0,219.0,0,Fully active
2,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,1.0,1.0,3.0,1.0,C1D1,"Cycle 1, day 1",30.0,Treatment,120.0,73.0,Leucovorin,racemic (dl-) leucovorin,NaN,,,NaN,,,804.0,MG,Milligram,10.0500,MG/KG,Milligram/kilogram,399.785107,IV,Intravenous,,,,,NaN,Y,NaN,,NaN,1.0,,,1.0,219.0,0,Fully active
3,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,1.0,1.0,3.0,1.0,C1D1,"Cycle 1, day 1",30.0,Treatment,4.0,75.0,5-Fluorouracil bolus,,NaN,,,NaN,,,804.0,MG,Milligram,10.0500,MG/KG,Milligram/kilogram,399.785107,IV,Intravenous,OTO,One time only,,,NaN,Y,NaN,,NaN,1.0,,,1.0,219.0,0,Fully active
4,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,1.0,1.0,3.0,1.0,C1D1,"Cycle 1, day 1",30.0,Treatment,2670.0,100.0,5-Fluorouracil continuous,,NaN,,,NaN,,,4824.0,MG,Milligram,60.3000,MG/KG,Milligram/kilogram,2398.710643,IV,Intravenous,CI,Continuous infusion,,,NaN,Y,NaN,,NaN,1.0,,,3.0,219.0,0,Fully active

In [230]:
_ = read_domain('NCT00339183_panitumumab_folfiri_raw', 'lab.sas7bdat')

--- NCT00339183_panitumumab_folfiri_raw/lab.sas7bdat ---
shape: (406508, 95)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'PRBEVCDR', 'PRBEVR', 'PRBEVCDM', 'PRBEVM', 'PRBEVCD', 'PRBEV', 'PROXACDR', 'PROXAR', 'PROXACDM', 'PROXAM', 'PROXALCD', 'PROXAL', 'B_METANM', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'PADJYNCD', 'PRADJYN', 'DPADJUV', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'KRASCD', 'KRAS', 'EVALITT', 'EVALPP', 'EVALQOL', 'EVALEGFR', 'DOSREFDY', 'DOSREFWK', 'ENRREFDY', 'ENRREFWK', 'VISITCD', 'VISIT', 'PHASECD', 'PHASE', 'LBNUMINF', 'LBNUMCTX', 'LBANLCYC', 'LBREPEAT', 'LBTYPECD', 'LBTYPE', 'LBPANEL', 'LBTESTCD', 'LBTEST', 'LBSTRESN', 'LBSTRESC', 'LBSTUNIT', 'LBSTNRLO', 'LBSTNRHI', 'LBNRINCD', 'LBNRIND', 'LBORRES', 'LBORRESN', 'LBORUNIT', 'LBORNRLO', 'LBORNRHI', 'LBBASE', 'LBBLRES', 'LBCHGBL', 'LBPCHGBL', 'LBANCMCD', 'LBANCMTH', 'LBGRDINC', 'LBGRDDEC', 'LBMIN', 'LBMAX', 'LBLAST', 'LBANALWK', 'TRTDUR', 'B_ECOGCD', 'B_ECOG']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,PRBEVCDR,PRBEVR,PRBEVCDM,PRBEVM,PRBEVCD,PRBEV,PROXACDR,PROXAR,PROXACDM,PROXAM,PROXALCD,PROXAL,B_METANM,B_METACT,LIVRONCD,LIVRONLY,PADJYNCD,PRADJYN,DPADJUV,B_LDHYN,B_LDH2YN,B_LDHNM,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,KRASCD,KRAS,EVALITT,EVALPP,EVALQOL,EVALEGFR,DOSREFDY,DOSREFWK,ENRREFDY,ENRREFWK,VISITCD,VISIT,PHASECD,PHASE,LBNUMINF,LBNUMCTX,LBANLCYC,LBREPEAT,LBTYPECD,LBTYPE,LBPANEL,LBTESTCD,LBTEST,LBSTRESN,LBSTRESC,LBSTUNIT,LBSTNRLO,LBSTNRHI,LBNRINCD,LBNRIND,LBORRES,LBORRESN,LBORUNIT,LBORNRLO,LBORNRHI,LBBASE,LBBLRES,LBCHGBL,LBPCHGBL,LBANCMCD,LBANCMTH,LBGRDINC,LBGRDDEC,LBMIN,LBMAX,LBLAST,LBANALWK,TRTDUR,B_ECOGCD,B_ECOG
0,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,-2.0,-1.0,1.0,1.0,SCR,Screening,10.0,Pre-treatment,0.0,0.0,1.0,1.0,2.0,Local,CHEMISTRY,ALB,Albumin,44.3,44,g/L,32.0,45.0,,,44.3,44.3,g/L,NaN,NaN,N,41.9,NaN,NaN,NaN,,NaN,0.0,N,N,N,NaN,219.0,0,Fully active
1,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,1.0,1.0,3.0,1.0,C1D1,"Cycle 1, day 1",10.0,Pre-treatment,0.0,0.0,1.0,1.0,2.0,Local,CHEMISTRY,ALB,Albumin,41.9,42,g/L,32.0,45.0,,,41.9,41.9,g/L,NaN,NaN,Y,41.9,NaN,NaN,NaN,,NaN,0.0,N,N,N,1.0,219.0,0,Fully active
2,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,15.0,3.0,17.0,3.0,C2D1,"Cycle 2, day 1",30.0,Treatment,1.0,1.0,2.0,1.0,2.0,Local,CHEMISTRY,ALB,Albumin,41.7,42,g/L,32.0,45.0,,,41.7,41.7,g/L,NaN,NaN,N,41.9,-0.2,-0.477327,NaN,,NaN,0.0,N,N,N,NaN,219.0,0,Fully active
3,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,29.0,5.0,31.0,5.0,C3D1,"Cycle 3, day 1",30.0,Treatment,2.0,2.0,3.0,1.0,2.0,Local,CHEMISTRY,ALB,Albumin,41.7,42,g/L,32.0,45.0,,,41.7,41.7,g/L,NaN,NaN,N,41.9,-0.2,-0.477327,NaN,,NaN,0.0,N,N,N,NaN,219.0,0,Fully active
4,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,43.0,7.0,45.0,7.0,C4D1,"Cycle 4, day 1",30.0,Treatment,3.0,3.0,4.0,1.0,2.0,Local,CHEMISTRY,ALB,Albumin,43.0,43,g/L,32.0,45.0,,,43,43.0,g/L,NaN,NaN,N,41.9,1.1,2.625298,NaN,,NaN,0.0,N,N,N,NaN,219.0,0,Fully active

In [231]:
_ = read_domain('NCT00339183_panitumumab_folfiri_raw', 'lesion.sas7bdat')

--- NCT00339183_panitumumab_folfiri_raw/lesion.sas7bdat ---
shape: (71644, 87)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'PRBEVCDR', 'PRBEVR', 'PRBEVCDM', 'PRBEVM', 'PRBEVCD', 'PRBEV', 'PROXACDR', 'PROXAR', 'PROXACDM', 'PROXAM', 'PROXALCD', 'PROXAL', 'B_METANM', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'PADJYNCD', 'PRADJYN', 'DPADJUV', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'KRASCD', 'KRAS', 'EVALITT', 'EVALPP', 'EVALQOL', 'EVALEGFR', 'DOSREFDY', 'DOSREFWK', 'ENRREFDY', 'ENRREFWK', 'VISITCD', 'VISIT', 'PHASECD', 'PHASE', 'LSTYPECD', 'LSTYPE', 'LSCATCD', 'LSCAT', 'LSANY', 'LSNO', 'LSPERFNY', 'LSPIRRNY', 'LSSITECD', 'LSSITE', 'LSPROCCD', 'LSPROC', 'LSRAWCD', 'LSRAW', 'LSNEW', 'LSNEWANY', 'LSLD', 'LSSLD', 'LSSLDPCH', 'LSSLDPCN', 'LSRESPCD', 'LSRESP', 'LSPROGNY', 'LSEXAMNO', 'LSRI', 'TRTDUR', 'B_ECOGCD', 'B_ECOG']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,PRBEVCDR,PRBEVR,PRBEVCDM,PRBEVM,PRBEVCD,PRBEV,PROXACDR,PROXAR,PROXACDM,PROXAM,PROXALCD,PROXAL,B_METANM,B_METACT,LIVRONCD,LIVRONLY,PADJYNCD,PRADJYN,DPADJUV,B_LDHYN,B_LDH2YN,B_LDHNM,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,KRASCD,KRAS,EVALITT,EVALPP,EVALQOL,EVALEGFR,DOSREFDY,DOSREFWK,ENRREFDY,ENRREFWK,VISITCD,VISIT,PHASECD,PHASE,LSTYPECD,LSTYPE,LSCATCD,LSCAT,LSANY,LSNO,LSPERFNY,LSPIRRNY,LSSITECD,LSSITE,LSPROCCD,LSPROC,LSRAWCD,LSRAW,LSNEW,LSNEWANY,LSLD,LSSLD,LSSLDPCH,LSSLDPCN,LSRESPCD,LSRESP,LSPROGNY,LSEXAMNO,LSRI,TRTDUR,B_ECOGCD,B_ECOG
0,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,NaN,NaN,NaN,NaN,FUP,Safety follow-Up,50.0,Short-term/safety follow-up,2.0,Local,1.0,Target lesion,N,NaN,,,NaN,,NaN,,NaN,,,,NaN,NaN,NaN,NaN,NaN,,,NaN,NaN,219.0,0,Fully active
1,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,-15.0,-3.0,-13.0,-2.0,SCR,Screening,10.0,Pre-treatment,1.0,Central,NaN,,,NaN,,,NaN,,46.0,CT pelvis,NaN,,,,NaN,NaN,NaN,NaN,NaN,,,3.0,4.0,219.0,0,Fully active
2,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,-15.0,-3.0,-13.0,-2.0,SCR,Screening,10.0,Pre-treatment,1.0,Central,1.0,Target lesion,,1.0,,,897.0,Pulmonary,40.0,CT chest,258.0,Left Lung mass/nodule,N,N,22.0,49.0,NaN,NaN,NaN,,,1.0,4.0,219.0,0,Fully active
3,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,-15.0,-3.0,-13.0,-2.0,SCR,Screening,10.0,Pre-treatment,1.0,Central,1.0,Target lesion,,1.0,,,897.0,Pulmonary,40.0,CT chest,258.0,Left Lung mass/nodule,N,N,22.0,151.0,NaN,NaN,NaN,,,1.0,4.0,219.0,0,Fully active
4,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,-15.0,-3.0,-13.0,-2.0,SCR,Screening,10.0,Pre-treatment,2.0,Local,1.0,Target lesion,N,1.0,,N,904.0,Lung parenchyma,23.0,Spiral CT,NaN,,,,23.0,118.0,NaN,NaN,NaN,,,NaN,NaN,219.0,0,Fully active

In [232]:
_ = read_domain('NCT00339183_panitumumab_folfiri_raw', 'lesnprog.sas7bdat')

--- NCT00339183_panitumumab_folfiri_raw/lesnprog.sas7bdat ---
shape: (128, 60)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'PRBEVCDR', 'PRBEVR', 'PRBEVCDM', 'PRBEVM', 'PRBEVCD', 'PRBEV', 'PROXACDR', 'PROXAR', 'PROXACDM', 'PROXAM', 'PROXALCD', 'PROXAL', 'B_METANM', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'PADJYNCD', 'PRADJYN', 'DPADJUV', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'KRASCD', 'KRAS', 'EVALITT', 'EVALPP', 'EVALQOL', 'EVALEGFR', 'DOSREFDY', 'DOSREFWK', 'LPWK', 'VISITCD', 'VISIT', 'LPSUM', 'TRTDUR', 'B_ECOGCD', 'B_ECOG']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,PRBEVCDR,PRBEVR,PRBEVCDM,PRBEVM,PRBEVCD,PRBEV,PROXACDR,PROXAR,PROXACDM,PROXAM,PROXALCD,PROXAL,B_METANM,B_METACT,LIVRONCD,LIVRONLY,PADJYNCD,PRADJYN,DPADJUV,B_LDHYN,B_LDH2YN,B_LDHNM,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,KRASCD,KRAS,EVALITT,EVALPP,EVALQOL,EVALEGFR,DOSREFDY,DOSREFWK,LPWK,VISITCD,VISIT,LPSUM,TRTDUR,B_ECOGCD,B_ECOG
0,20050181,1001,201001011,62.0,F,Female,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,300.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,60.0,9.0,08,UNSCHED,Unscheduled visit,100.0,59.0,0,Fully active
1,20050181,1010,201010002,58.0,M,Male,1.0,White or Caucasian,NaN,,,41.0,FOLFIRI alone,41.0,FOLFIRI alone,1.0,Y,1.0,Y,1.0,Y,0.0,N,0.0,N,1.0,Y,1.0,1,1.0,Y,0.0,N,,Y,N,464.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,1.0,Wild-type,Y,N,Y,Y,59.0,9.0,8,UNSCHED,Unscheduled visit,78.0,90.0,0,Fully active
2,20050181,1103,201103005,49.0,M,Male,1.0,White or Caucasian,NaN,,,41.0,FOLFIRI alone,41.0,FOLFIRI alone,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,2.0,2,0.0,N,0.0,N,,N,N,302.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,113.0,17.0,16,UNSCHED,Unscheduled visit,19.0,115.0,0,Fully active
3,20050181,1103,201103007,68.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,2.0,2,0.0,N,0.0,N,,N,N,347.0,0.0,Fully active,0 or 1,1252.0,Rectal,0.0,N,Y,2.0,Mutant,Y,Y,Y,Y,512.0,74.0,72,UNSCHED,Unscheduled visit,32.0,584.0,0,Fully active
4,20050181,1103,201103008,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,0.0,N,0.0,N,0.0,N,1.0,Y,1.0,Y,1.0,Y,2.0,2,0.0,N,0.0,N,,N,N,650.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,1.0,Wild-type,Y,Y,Y,Y,-21.0,-3.0,SCR,UNSCHED,Unscheduled visit,17.0,178.0,0,Fully active

In [233]:
_ = read_domain('NCT00339183_panitumumab_folfiri_raw', 'medhist.sas7bdat')

--- NCT00339183_panitumumab_folfiri_raw/medhist.sas7bdat ---
shape: (4845, 66)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'PRBEVCDR', 'PRBEVR', 'PRBEVCDM', 'PRBEVM', 'PRBEVCD', 'PRBEV', 'PROXACDR', 'PROXAR', 'PROXACDM', 'PROXAM', 'PROXALCD', 'PROXAL', 'B_METANM', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'PADJYNCD', 'PRADJYN', 'DPADJUV', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'KRASCD', 'KRAS', 'EVALITT', 'EVALPP', 'EVALQOL', 'EVALEGFR', 'MHANY', 'MHBNGNYN', 'MHBSYSCD', 'MHBODSYS', 'MHCONDCD', 'MHCOND', 'MHSITECD', 'MHSITE', 'MHTERM', 'MHSTATCD', 'MHSTAT', 'TRTDUR', 'B_ECOGCD', 'B_ECOG', 'MHSTDY']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,PRBEVCDR,PRBEVR,PRBEVCDM,PRBEVM,PRBEVCD,PRBEV,PROXACDR,PROXAR,PROXACDM,PROXAM,PROXALCD,PROXAL,B_METANM,B_METACT,LIVRONCD,LIVRONLY,PADJYNCD,PRADJYN,DPADJUV,B_LDHYN,B_LDH2YN,B_LDHNM,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,KRASCD,KRAS,EVALITT,EVALPP,EVALQOL,EVALEGFR,MHANY,MHBNGNYN,MHBSYSCD,MHBODSYS,MHCONDCD,MHCOND,MHSITECD,MHSITE,MHTERM,MHSTATCD,MHSTAT,TRTDUR,B_ECOGCD,B_ECOG,MHSTDY
0,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,N,N,NaN,,NaN,,NaN,,,NaN,,219.0,0,Fully active,NaN
1,20050181,1001,201001002,66.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,N,N,215.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,Y,N,NaN,,NaN,,NaN,,,NaN,,60.0,0,Fully active,NaN
2,20050181,1001,201001002,66.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,N,N,215.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,Y,N,2.0,Cardiovascular,NaN,,NaN,,ATRIAL FIBRILATION,1.0,Current or continuing,60.0,0,Fully active,NaN
3,20050181,1001,201001002,66.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,N,N,215.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,Y,N,88.0,Other,NaN,,NaN,,PULMONARY EMBOLIA,1.0,Current or continuing,60.0,0,Fully active,NaN
4,20050181,1001,201001004,58.0,F,Female,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,0.0,N,0.0,N,0.0,N,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,Y,N,392.0,0.0,Fully active,0 or 1,1252.0,Rectal,0.0,N,Y,1.0,Wild-type,Y,Y,Y,Y,N,N,NaN,,NaN,,NaN,,,NaN,,437.0,0,Fully active,NaN

In [234]:
_ = read_domain('NCT00339183_panitumumab_folfiri_raw', 'othcantx.sas7bdat')

--- NCT00339183_panitumumab_folfiri_raw/othcantx.sas7bdat ---
shape: (2302, 73)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'PRBEVCDR', 'PRBEVR', 'PRBEVCDM', 'PRBEVM', 'PRBEVCD', 'PRBEV', 'PROXACDR', 'PROXAR', 'PROXACDM', 'PROXAM', 'PROXALCD', 'PROXAL', 'B_METANM', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'PADJYNCD', 'PRADJYN', 'DPADJUV', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'KRASCD', 'KRAS', 'EVALITT', 'EVALPP', 'EVALQOL', 'EVALEGFR', 'OTANY', 'OTTYPE', 'PHASECD', 'PHASE', 'OTSTDY', 'OTENDY', 'OTLINE', 'OTPREF', 'OTBODSCD', 'OTBODSIT', 'OTDPAREA', 'OTRGTXYN', 'OTINTCD', 'OTINT', 'OTDRSNCD', 'OTDREAS', 'OTRESPCD', 'OTRESP', 'TRTDUR', 'OTPDDY', 'B_ECOGCD', 'B_ECOG']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,PRBEVCDR,PRBEVR,PRBEVCDM,PRBEVM,PRBEVCD,PRBEV,PROXACDR,PROXAR,PROXACDM,PROXAM,PROXALCD,PROXAL,B_METANM,B_METACT,LIVRONCD,LIVRONLY,PADJYNCD,PRADJYN,DPADJUV,B_LDHYN,B_LDH2YN,B_LDHNM,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,KRASCD,KRAS,EVALITT,EVALPP,EVALQOL,EVALEGFR,OTANY,OTTYPE,PHASECD,PHASE,OTSTDY,OTENDY,OTLINE,OTPREF,OTBODSCD,OTBODSIT,OTDPAREA,OTRGTXYN,OTINTCD,OTINT,OTDRSNCD,OTDREAS,OTRESPCD,OTRESP,TRTDUR,OTPDDY,B_ECOGCD,B_ECOG
0,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,Y,,NaN,,NaN,NaN,,,NaN,,,N,NaN,,NaN,,NaN,,219.0,NaN,0,Fully active
1,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,Y,Immunotherapy,5.0,Pre-consent,-253.0,-145.0,Metastatic,BEVACIZUMAB,NaN,,,N,NaN,,7.0,Disease progression,4.0,Stable disease,219.0,-53.0,0,Fully active
2,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,Y,Cryotherapy or Other,5.0,Pre-consent,-253.0,-145.0,Metastatic,FOLINIC ACID,NaN,,,N,NaN,,7.0,Disease progression,4.0,Stable disease,219.0,-53.0,0,Fully active
3,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,Y,,NaN,,NaN,NaN,,,NaN,,,Y,NaN,,NaN,,NaN,,219.0,NaN,0,Fully active
4,20050181,1001,201001002,66.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,N,N,215.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,N,,NaN,,NaN,NaN,,,NaN,,,N,NaN,,NaN,,NaN,,60.0,NaN,0,Fully active

In [235]:
_ = read_domain('NCT00339183_panitumumab_folfiri_raw', 'radiotx.sas7bdat')

--- NCT00339183_panitumumab_folfiri_raw/radiotx.sas7bdat ---
shape: (988, 67)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'PRBEVCDR', 'PRBEVR', 'PRBEVCDM', 'PRBEVM', 'PRBEVCD', 'PRBEV', 'PROXACDR', 'PROXAR', 'PROXACDM', 'PROXAM', 'PROXALCD', 'PROXAL', 'B_METANM', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'PADJYNCD', 'PRADJYN', 'DPADJUV', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'KRASCD', 'KRAS', 'EVALITT', 'EVALPP', 'EVALQOL', 'EVALEGFR', 'RAANY', 'VISITCD', 'VISIT', 'PHASECD', 'PHASE', 'RASTDY', 'RASTDYE', 'RAENDY', 'RASITECD', 'RASITE', 'RAINTCD', 'RAINT', 'RADPAREA', 'TRTDUR', 'B_ECOGCD', 'B_ECOG']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,PRBEVCDR,PRBEVR,PRBEVCDM,PRBEVM,PRBEVCD,PRBEV,PROXACDR,PROXAR,PROXACDM,PROXAM,PROXALCD,PROXAL,B_METANM,B_METACT,LIVRONCD,LIVRONLY,PADJYNCD,PRADJYN,DPADJUV,B_LDHYN,B_LDH2YN,B_LDHNM,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,KRASCD,KRAS,EVALITT,EVALPP,EVALQOL,EVALEGFR,RAANY,VISITCD,VISIT,PHASECD,PHASE,RASTDY,RASTDYE,RAENDY,RASITECD,RASITE,RAINTCD,RAINT,RADPAREA,TRTDUR,B_ECOGCD,B_ECOG
0,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,N,SCR,Screening,10.0,Pre-treatment,NaN,NaN,NaN,NaN,,NaN,,,219.0,0,Fully active
1,20050181,1001,201001002,66.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,N,N,215.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,N,SCR,Screening,10.0,Pre-treatment,NaN,NaN,NaN,NaN,,NaN,,,60.0,0,Fully active
2,20050181,1001,201001004,58.0,F,Female,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,0.0,N,0.0,N,0.0,N,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,Y,N,392.0,0.0,Fully active,0 or 1,1252.0,Rectal,0.0,N,Y,1.0,Wild-type,Y,Y,Y,Y,N,SCR,Screening,10.0,Pre-treatment,NaN,NaN,NaN,NaN,,NaN,,,437.0,0,Fully active
3,20050181,1001,201001005,75.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,2.0,2,0.0,N,0.0,N,,N,N,267.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,1.0,Wild-type,Y,Y,Y,Y,N,SCR,Screening,10.0,Pre-treatment,NaN,NaN,NaN,NaN,,NaN,,,220.0,0,Fully active
4,20050181,1001,201001006,52.0,M,Male,1.0,White or Caucasian,NaN,,,41.0,FOLFIRI alone,41.0,FOLFIRI alone,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,Y,Y,572.0,1.0,Symptoms but ambulatory,0 or 1,1251.0,Colon,1.0,Y,Y,88.0,Failed,Y,Y,N,Y,N,SCR,Screening,10.0,Pre-treatment,NaN,NaN,NaN,NaN,,NaN,,,3.0,1,Symptoms but ambulatory

In [236]:
_ = read_domain('NCT00339183_panitumumab_folfiri_raw', 'respeval.sas7bdat')

--- NCT00339183_panitumumab_folfiri_raw/respeval.sas7bdat ---
shape: (15322, 82)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'PRBEVCDR', 'PRBEVR', 'PRBEVCDM', 'PRBEVM', 'PRBEVCD', 'PRBEV', 'PROXACDR', 'PROXAR', 'PROXACDM', 'PROXAM', 'PROXALCD', 'PROXAL', 'B_METANM', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'PADJYNCD', 'PRADJYN', 'DPADJUV', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'KRASCD', 'KRAS', 'EVALITT', 'EVALPP', 'EVALQOL', 'EVALEGFR', 'DOSREFDY', 'DOSREFWK', 'ENRREFDY', 'ENRREFWK', 'VISITCD', 'VISIT', 'PHASECD', 'PHASE', 'RSTYPECD', 'RSTYPE', 'RSCRITCD', 'RSCRIT', 'RSRESPCD', 'RSRESP', 'RSRSPDCD', 'RSRSPD', 'RSCONFYN', 'RSBRCD', 'RSBR', 'RSCRCD', 'RSCR', 'RSITRSCD', 'RSITRESP', 'RSTRSPCD', 'RSTRESP', 'RSNTRSCD', 'RSNTRESP', 'RSNEW', 'TRTDUR', 'B_ECOGCD', 'B_ECOG']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,PRBEVCDR,PRBEVR,PRBEVCDM,PRBEVM,PRBEVCD,PRBEV,PROXACDR,PROXAR,PROXACDM,PROXAM,PROXALCD,PROXAL,B_METANM,B_METACT,LIVRONCD,LIVRONLY,PADJYNCD,PRADJYN,DPADJUV,B_LDHYN,B_LDH2YN,B_LDHNM,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,KRASCD,KRAS,EVALITT,EVALPP,EVALQOL,EVALEGFR,DOSREFDY,DOSREFWK,ENRREFDY,ENRREFWK,VISITCD,VISIT,PHASECD,PHASE,RSTYPECD,RSTYPE,RSCRITCD,RSCRIT,RSRESPCD,RSRESP,RSRSPDCD,RSRSPD,RSCONFYN,RSBRCD,RSBR,RSCRCD,RSCR,RSITRSCD,RSITRESP,RSTRSPCD,RSTRESP,RSNTRSCD,RSNTRESP,RSNEW,TRTDUR,B_ECOGCD,B_ECOG
0,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,-15.0,-3.0,-13.0,-2.0,SCR,Screening,10.0,Pre-treatment,1.0,Central,3.0,Modified RECIST,NaN,,NaN,,,NaN,,NaN,,NaN,,NaN,,NaN,,N,219.0,0,Fully active
1,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,-15.0,-3.0,-13.0,-2.0,SCR,Screening,10.0,Pre-treatment,1.0,Central,3.0,Modified RECIST,NaN,,NaN,,,NaN,,NaN,,NaN,,NaN,,NaN,,N,219.0,0,Fully active
2,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,-15.0,-3.0,-13.0,-2.0,SCR,Screening,10.0,Pre-treatment,1.0,Central,3.0,Modified RECIST,NaN,,NaN,,,NaN,,NaN,,NaN,,NaN,,NaN,,N,219.0,0,Fully active
3,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,52.0,8.0,54.0,8.0,W8,Week 8,30.0,Treatment,1.0,Central,3.0,Modified RECIST,5.0,Progressive disease,5.0,Progressive disease,,5.0,Progressive disease,NaN,,NaN,,4.0,Stable disease,4.0,Stable disease,Y,219.0,0,Fully active
4,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,52.0,8.0,54.0,8.0,W8,Week 8,30.0,Treatment,1.0,Central,3.0,Modified RECIST,5.0,Progressive disease,5.0,Progressive disease,,5.0,Progressive disease,NaN,,NaN,,4.0,Stable disease,4.0,Stable disease,Y,219.0,0,Fully active

In [237]:
_ = read_domain('NCT00339183_panitumumab_folfiri_raw', 'surghist.sas7bdat')

--- NCT00339183_panitumumab_folfiri_raw/surghist.sas7bdat ---
shape: (1691, 67)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'PRBEVCDR', 'PRBEVR', 'PRBEVCDM', 'PRBEVM', 'PRBEVCD', 'PRBEV', 'PROXACDR', 'PROXAR', 'PROXACDM', 'PROXAM', 'PROXALCD', 'PROXAL', 'B_METANM', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'PADJYNCD', 'PRADJYN', 'DPADJUV', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'KRASCD', 'KRAS', 'EVALITT', 'EVALPP', 'EVALQOL', 'EVALEGFR', 'SXANY', 'DOSREFDY', 'DOSREFWK', 'SXTYPECD', 'SXTYPE', 'SXSITECD', 'SXSITE', 'SXSITCD2', 'SXSITE2', 'SXSITCD3', 'SXSITE3', 'SXINTCD', 'SXINT', 'TRTDUR', 'B_ECOGCD', 'B_ECOG']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,PRBEVCDR,PRBEVR,PRBEVCDM,PRBEVM,PRBEVCD,PRBEV,PROXACDR,PROXAR,PROXACDM,PROXAM,PROXALCD,PROXAL,B_METANM,B_METACT,LIVRONCD,LIVRONLY,PADJYNCD,PRADJYN,DPADJUV,B_LDHYN,B_LDH2YN,B_LDHNM,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,KRASCD,KRAS,EVALITT,EVALPP,EVALQOL,EVALEGFR,SXANY,DOSREFDY,DOSREFWK,SXTYPECD,SXTYPE,SXSITECD,SXSITE,SXSITCD2,SXSITE2,SXSITCD3,SXSITE3,SXINTCD,SXINT,TRTDUR,B_ECOGCD,B_ECOG
0,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,Y,-296.0,-43.0,4.0,Resection,893.0,Colon,NaN,,NaN,,15.0,Palliative,219.0,0,Fully active
1,20050181,1001,201001002,66.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,N,N,215.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,Y,-193.0,-28.0,4.0,Resection,893.0,Colon,NaN,,NaN,,15.0,Palliative,60.0,0,Fully active
2,20050181,1001,201001004,58.0,F,Female,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,0.0,N,0.0,N,0.0,N,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,Y,N,392.0,0.0,Fully active,0 or 1,1252.0,Rectal,0.0,N,Y,1.0,Wild-type,Y,Y,Y,Y,Y,-381.0,-55.0,3.0,Biopsy,894.0,Rectum,NaN,,NaN,,16.0,Diagnostic/Staging,437.0,0,Fully active
3,20050181,1001,201001004,58.0,F,Female,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,0.0,N,0.0,N,0.0,N,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,Y,N,392.0,0.0,Fully active,0 or 1,1252.0,Rectal,0.0,N,Y,1.0,Wild-type,Y,Y,Y,Y,Y,-367.0,-53.0,88.0,Other,894.0,Rectum,NaN,,NaN,,15.0,Palliative,437.0,0,Fully active
4,20050181,1001,201001004,58.0,F,Female,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,0.0,N,0.0,N,0.0,N,1.0,Y,1.0,Y,1.0,Y,3.0,>=3,0.0,N,0.0,N,,Y,N,392.0,0.0,Fully active,0 or 1,1252.0,Rectal,0.0,N,Y,1.0,Wild-type,Y,Y,Y,Y,Y,-296.0,-43.0,88.0,Other,894.0,Rectum,NaN,,NaN,,15.0,Palliative,437.0,0,Fully active

In [238]:
_ = read_domain('NCT00339183_panitumumab_folfiri_raw', 'vitals_v.sas7bdat')

--- NCT00339183_panitumumab_folfiri_raw/vitals_v.sas7bdat ---
shape: (65560, 78)
columns: ['STUDYID', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'PRBEVCDR', 'PRBEVR', 'PRBEVCDM', 'PRBEVM', 'PRBEVCD', 'PRBEV', 'PROXACDR', 'PROXAR', 'PROXACDM', 'PROXAM', 'PROXALCD', 'PROXAL', 'B_METANM', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'PADJYNCD', 'PRADJYN', 'DPADJUV', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'KRASCD', 'KRAS', 'EVALITT', 'EVALPP', 'EVALQOL', 'EVALEGFR', 'DOSREFDY', 'DOSREFWK', 'ENRREFDY', 'ENRREFWK', 'VISITCD', 'VISIT', 'PHASECD', 'PHASE', 'VSPTMCD', 'VSPTM', 'VSNUMINF', 'VSTESTCD', 'VSTEST', 'VSSTRES', 'VSSTUNIT', 'VSORRES', 'VSORUNIT', 'VSBASE', 'VSBLRES', 'VSCHGBL', 'VSMIN', 'VSMAX', 'VSLAST', 'VSCYCLNM', 'TRTDUR', 'B_ECOGCD', 'B_ECOG']

,STUDYID,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,PRBEVCDR,PRBEVR,PRBEVCDM,PRBEVM,PRBEVCD,PRBEV,PROXACDR,PROXAR,PROXACDM,PROXAM,PROXALCD,PROXAL,B_METANM,B_METACT,LIVRONCD,LIVRONLY,PADJYNCD,PRADJYN,DPADJUV,B_LDHYN,B_LDH2YN,B_LDHNM,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,KRASCD,KRAS,EVALITT,EVALPP,EVALQOL,EVALEGFR,DOSREFDY,DOSREFWK,ENRREFDY,ENRREFWK,VISITCD,VISIT,PHASECD,PHASE,VSPTMCD,VSPTM,VSNUMINF,VSTESTCD,VSTEST,VSSTRES,VSSTUNIT,VSORRES,VSORUNIT,VSBASE,VSBLRES,VSCHGBL,VSMIN,VSMAX,VSLAST,VSCYCLNM,TRTDUR,B_ECOGCD,B_ECOG
0,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,-2.0,-1.0,1.0,1.0,SCR,Screening,10.0,Pre-treatment,998.0,Taken at physical exam,0.0,DIABP,Diastolic blood pressure,70.0,MMHG,70.0,MMHG,N,80.0,NaN,N,N,N,NaN,219.0,0,Fully active
1,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,-2.0,-1.0,1.0,1.0,SCR,Screening,10.0,Pre-treatment,998.0,Taken at physical exam,0.0,ECOG,ECOG performance status,0.0,,0.0,,N,0.0,NaN,N,N,N,NaN,219.0,0,Fully active
2,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,-2.0,-1.0,1.0,1.0,SCR,Screening,10.0,Pre-treatment,998.0,Taken at physical exam,0.0,PULSE,Pulse,80.0,BEATS/MINUTE,80.0,BEATS/MINUTE,N,80.0,NaN,N,N,N,NaN,219.0,0,Fully active
3,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,-2.0,-1.0,1.0,1.0,SCR,Screening,10.0,Pre-treatment,998.0,Taken at physical exam,0.0,RESP,Respiration,12.0,BREATHS/MINUTE,12.0,BREATHS/MINUTE,N,14.0,NaN,N,N,N,NaN,219.0,0,Fully active
4,20050181,1001,201001001,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,40.0,Panitumumab + FOLFIRI,40.0,Panitumumab + FOLFIRI,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,1.0,Y,4.0,>=3,0.0,N,0.0,N,,N,N,187.0,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,2.0,Mutant,Y,Y,Y,Y,-2.0,-1.0,1.0,1.0,SCR,Screening,10.0,Pre-treatment,998.0,Taken at physical exam,0.0,SYSBP,Systolic blood pressure,130.0,MMHG,130.0,MMHG,N,130.0,NaN,N,N,N,NaN,219.0,0,Fully active

## NCT00364013_panitumumab_folfox_ADaM

In [239]:
_ = read_domain('NCT00364013_panitumumab_folfox_ADaM', 'adae_pds2019.sas7bdat')

--- NCT00364013_panitumumab_folfox_ADaM/adae_pds2019.sas7bdat ---
shape: (3211, 7)
columns: ['SUBJID', 'AEPT', 'AESOC', 'AESTDYI', 'AEENDYI', 'AESEVCD', 'AECONT']

   SUBJID                  AEPT                                   AESOC  AESTDYI  AEENDYI  AESEVCD AECONT
0  000003  Dermatitis acneiform  Skin and subcutaneous tissue disorders     12.0     29.0      1.0      N
1  000003  Dermatitis acneiform  Skin and subcutaneous tissue disorders     41.0     57.0      1.0      N
2  000007                  Rash  Skin and subcutaneous tissue disorders      9.0    127.0      1.0      N
3  000007                  Rash  Skin and subcutaneous tissue disorders    128.0    141.0      2.0      N
4  000007                  Rash  Skin and subcutaneous tissue disorders    142.0    160.0      1.0      N

In [240]:
_ = read_domain('NCT00364013_panitumumab_folfox_ADaM', 'adlb_pds2019.sas7bdat')

--- NCT00364013_panitumumab_folfox_ADaM/adlb_pds2019.sas7bdat ---
shape: (125123, 7)
columns: ['SUBJID', 'LBTEST', 'LBBASE', 'LBSTRESN', 'LBSTUNIT', 'VISITDY', 'VISIT']

   SUBJID   LBTEST LBBASE  LBSTRESN LBSTUNIT  VISITDY           VISIT
0  000001  Albumin      N      32.0      g/L     -6.0       Screening
1  000001  Albumin      Y      30.0      g/L      3.0  Cycle 1, day 1
2  000001  Albumin      N      31.0      g/L     17.0  Cycle 2, day 1
3  000001  Albumin      N      29.0      g/L     31.0  Cycle 3, day 1
4  000001  Albumin      N      30.0      g/L     45.0  Cycle 4, day 1

In [241]:
_ = read_domain('NCT00364013_panitumumab_folfox_ADaM', 'adls_pds2019.sas7bdat')

--- NCT00364013_panitumumab_folfox_ADaM/adls_pds2019.sas7bdat ---
shape: (29118, 11)
columns: ['SUBJID', 'VISITDY', 'VISIT', 'LSCAT', 'LSNEW', 'LSSLD', 'LSLD', 'LSSITE', 'LSNEWANY', 'LSREADER', 'LSTYPE']

   SUBJID  VISITDY      VISIT          LSCAT LSNEW  LSSLD   LSLD LSSITE LSNEWANY       LSREADER   LSTYPE
0  000001    -28.0  Screening  Target lesion     N  426.0  168.0  Liver        N  Radiologist 1  Central
1  000001    -28.0  Screening  Target lesion     N  426.0   80.0  Liver        N  Radiologist 1  Central
2  000001    -28.0  Screening  Target lesion     N  426.0   55.0  Liver        N  Radiologist 1  Central
3  000001    -28.0  Screening  Target lesion     N  426.0   71.0  Liver        N  Radiologist 1  Central
4  000001    -28.0  Screening  Target lesion     N  426.0   52.0  Liver        N  Radiologist 1  Central

In [242]:
_ = read_domain('NCT00364013_panitumumab_folfox_ADaM', 'adpm_pds2019.sas7bdat')

--- NCT00364013_panitumumab_folfox_ADaM/adpm_pds2019.sas7bdat ---
shape: (14924, 4)
columns: ['SUBJID', 'VISIT', 'VISITDY', 'WEIGHT']

   SUBJID           VISIT  VISITDY  WEIGHT
0  000001       Screening     -6.0    64.6
1  000001  Cycle 1, day 1      3.0    64.2
2  000001  Cycle 2, day 1     17.0    63.1
3  000001  Cycle 3, day 1     31.0    62.4
4  000001  Cycle 4, day 1     45.0    62.3

In [243]:
_ = read_domain('NCT00364013_panitumumab_folfox_ADaM', 'adrsp_pds2019.sas7bdat')

--- NCT00364013_panitumumab_folfox_ADaM/adrsp_pds2019.sas7bdat ---
shape: (10856, 9)
columns: ['SUBJID', 'RSRESP', 'VISITDY', 'VISIT', 'RSCONFYN', 'RSTRESP', 'RSNTRESP', 'RSNEW', 'RSREADER']

   SUBJID          RSRESP  VISITDY      VISIT RSCONFYN         RSTRESP        RSNTRESP RSNEW       RSREADER
0  000001                    -28.0  Screening                                              N  Radiologist 1
1  000001                    -28.0  Screening                                              N  Radiologist 2
2  000001                    -28.0  Screening                                              N     Oncologist
3  000001  Stable disease     57.0     Week 8           Stable disease  Stable disease     N  Radiologist 1
4  000001  Stable disease     57.0     Week 8           Stable disease  Stable disease     N  Radiologist 2

In [244]:
_ = read_domain('NCT00364013_panitumumab_folfox_ADaM', 'adsl_pds2019.sas7bdat')

--- NCT00364013_panitumumab_folfox_ADaM/adsl_pds2019.sas7bdat ---
shape: (935, 19)
columns: ['SUBJID', 'TRT', 'ATRT', 'PRSURG', 'DTHDY', 'DTH', 'PFSDYCR', 'PFSCR', 'LIVERMET', 'DIAGMONS', 'AGE', 'SEX', 'B_WEIGHT', 'B_HEIGHT', 'RACE', 'B_ECOG', 'HISSUBTY', 'B_METANM', 'DIAGTYPE']

,SUBJID,TRT,ATRT,PRSURG,DTHDY,DTH,PFSDYCR,PFSCR,LIVERMET,DIAGMONS,AGE,SEX,B_WEIGHT,B_HEIGHT,RACE,B_ECOG,HISSUBTY,B_METANM,DIAGTYPE
0,000001,FOLFOX alone,FOLFOX alone,Y,558.0,1.0,558.0,1.0,Y,0.622951,64.0,Male,64.2,167.0,White or Caucasian,Symptoms but ambulatory,No sub-type,3.0,Colon
1,000003,Panitumumab + FOLFOX,Panitumumab + FOLFOX,Y,301.0,1.0,54.0,1.0,Y,1.868852,65.0,Male,67.0,165.0,White or Caucasian,Symptoms but ambulatory,No sub-type,5.0,Colon
2,000004,FOLFOX alone,FOLFOX alone,Y,460.0,1.0,293.0,1.0,Y,1.213115,60.0,Male,75.0,175.0,White or Caucasian,Symptoms but ambulatory,No sub-type,1.0,Colon
3,000005,FOLFOX alone,FOLFOX alone,Y,965.0,1.0,965.0,1.0,Y,2.196721,64.0,Female,52.0,160.0,White or Caucasian,Symptoms but ambulatory,Mucinous,2.0,Colon
4,000006,FOLFOX alone,FOLFOX alone,N,211.0,1.0,56.0,1.0,Y,0.950820,74.0,Male,66.0,171.0,White or Caucasian,Fully active,Mucinous,1.0,Rectal

In [245]:
_ = read_domain('NCT00364013_panitumumab_folfox_ADaM', 'biomark_pds2019.sas7bdat')

--- NCT00364013_panitumumab_folfox_ADaM/biomark_pds2019.sas7bdat ---
shape: (935, 19)
columns: ['SUBJID', 'BMMTNM1', 'BMMTR1', 'BMMTNM2', 'BMMTR2', 'BMMTNM3', 'BMMTR3', 'BMMTNM4', 'BMMTR4', 'BMMTNM5', 'BMMTR5', 'BMMTNM6', 'BMMTR6', 'BMMTNM7', 'BMMTR7', 'BMMTNM15', 'BMMTR15', 'BMMTNM16', 'BMMTR16']

,SUBJID,BMMTNM1,BMMTR1,BMMTNM2,BMMTR2,BMMTNM3,BMMTR3,BMMTNM4,BMMTR4,BMMTNM5,BMMTR5,BMMTNM6,BMMTR6,BMMTNM7,BMMTR7,BMMTNM15,BMMTR15,BMMTNM16,BMMTR16
0,000001,KRAS exon 2 (c12/13),,KRAS exon 3 (c61),,KRAS exon 4 (c117/146),,NRAS exon 2 (c12/13),,NRAS exon 3 (c61),,NRAS exon 4 (c117/146),,BRAF exon 15 (c600),,KRAS exon 3 (c59/c61),,NRAS exon 3 (c59/c61),
1,000003,KRAS exon 2 (c12/13),Mutant,KRAS exon 3 (c61),,KRAS exon 4 (c117/146),,NRAS exon 2 (c12/13),,NRAS exon 3 (c61),,NRAS exon 4 (c117/146),,BRAF exon 15 (c600),,KRAS exon 3 (c59/c61),,NRAS exon 3 (c59/c61),
2,000004,KRAS exon 2 (c12/13),Mutant,KRAS exon 3 (c61),,KRAS exon 4 (c117/146),,NRAS exon 2 (c12/13),,NRAS exon 3 (c61),,NRAS exon 4 (c117/146),,BRAF exon 15 (c600),,KRAS exon 3 (c59/c61),,NRAS exon 3 (c59/c61),
3,000005,KRAS exon 2 (c12/13),Mutant,KRAS exon 3 (c61),,KRAS exon 4 (c117/146),,NRAS exon 2 (c12/13),,NRAS exon 3 (c61),,NRAS exon 4 (c117/146),,BRAF exon 15 (c600),,KRAS exon 3 (c59/c61),,NRAS exon 3 (c59/c61),
4,000006,KRAS exon 2 (c12/13),,KRAS exon 3 (c61),,KRAS exon 4 (c117/146),,NRAS exon 2 (c12/13),,NRAS exon 3 (c61),,NRAS exon 4 (c117/146),,BRAF exon 15 (c600),,KRAS exon 3 (c59/c61),,NRAS exon 3 (c59/c61),

## NCT00364013_panitumumab_folfox_raw

In [246]:
_ = read_domain('NCT00364013_panitumumab_folfox_raw', 'a_eendpt.sas7bdat')

--- NCT00364013_panitumumab_folfox_raw/a_eendpt.sas7bdat ---
shape: (935, 119)
columns: ['STUDYID', 'REGIONCD', 'REGION', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'B_ECOGCT', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'EVALITT', 'EVALPP', 'EVALCTR', 'EVALEGFR', 'RDTCR', 'ROSCR', 'ROSLR', 'ROSLRCA', 'RDTLRCA', 'RDTLR', 'RDURCR', 'RDURCRC', 'RDURLR', 'RDURLRC', 'RDYCR', 'RDYLR', 'PFSDYCR', 'PFSCR', 'PFSDYOCR', 'PFSOCR', 'PFSDYOLR', 'PFSOLR', 'PFSCREWK', 'PFSDYCRE', 'PFSCRE', 'PFSDYCRU', 'PFSCRU', 'PFSCU', 'PFSDYCRV', 'PFSCRV', 'PFSDYLR', 'PFSLR', 'PFSDYCRN', 'PFSCRN', 'PFSDYCRA', 'PFSCRA', 'PFSCRS', 'PFSDYCRS', 'PFSCRT', 'PFSDYCRT', 'PDDYCR', 'PDCR', 'PDOCR', 'PDDYOCR', 'PDOLR', 'PDDYOLR', 'PDDYLR', 'PDLR', 'DTHDY', 'DTH', 'SDDURCR', 'SDDURCRC', 'SDDURLR', 'SDDURLRC', 'SLDCBASE', 'SLDCMIN', 'SLDCMXRD', 'SLDCMXPR', 'SLDLBASE', 'SLDLMIN', 'SLDLMXRD', 'SLDLMXPR', 'PFSDYCEP', 'PFSCEP', 'PFSDYCEB', 'PFSCEB', 'DROPINDY', 'DROPIN', 'VEGFRDY', 'VEGFR', 'IRINDY', 'IRIN', 'OXALDY', 'OXAL', 'BEVZDY', 'BEVZ', 'CHIOFDY', 'CHIOF', 'EGFRIRDY', 'EGFRIR', 'ANTUMDY', 'ANTUM', 'WOEGFRDY', 'WOEGFR', 'POTOSDY', 'POTOS', 'TRTDUR']

,STUDYID,REGIONCD,REGION,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,B_METACT,LIVRONCD,LIVRONLY,B_LDHYN,B_LDH2YN,B_LDHNM,B_ECOGCT,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,EVALITT,EVALPP,EVALCTR,EVALEGFR,RDTCR,ROSCR,ROSLR,ROSLRCA,RDTLRCA,RDTLR,RDURCR,RDURCRC,RDURLR,RDURLRC,RDYCR,RDYLR,PFSDYCR,PFSCR,PFSDYOCR,PFSOCR,PFSDYOLR,PFSOLR,PFSCREWK,PFSDYCRE,PFSCRE,PFSDYCRU,PFSCRU,PFSCU,PFSDYCRV,PFSCRV,PFSDYLR,PFSLR,PFSDYCRN,PFSCRN,PFSDYCRA,PFSCRA,PFSCRS,PFSDYCRS,PFSCRT,PFSDYCRT,PDDYCR,PDCR,PDOCR,PDDYOCR,PDOLR,PDDYOLR,PDDYLR,PDLR,DTHDY,DTH,SDDURCR,SDDURCRC,SDDURLR,SDDURLRC,SLDCBASE,SLDCMIN,SLDCMXRD,SLDCMXPR,SLDLBASE,SLDLMIN,SLDLMXRD,SLDLMXPR,PFSDYCEP,PFSCEP,PFSDYCEB,PFSCEB,DROPINDY,DROPIN,VEGFRDY,VEGFR,IRINDY,IRIN,OXALDY,OXAL,BEVZDY,BEVZ,CHIOFDY,CHIOF,EGFRIRDY,EGFRIR,ANTUMDY,ANTUM,WOEGFRDY,WOEGFR,POTOSDY,POTOS,TRTDUR
0,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,0.0,0.0,0.0,SD,SD,0.0,NaN,NaN,NaN,NaN,731.0,184.0,184.0,1.0,184.0,1.0,184.0,0.0,NaN,184.0,1.0,184.0,1.0,N,184.0,1.0,672.0,1.0,224.0,1.0,168.0,1.0,1.0,184.0,1.0,184.0,184.0,1.0,1.0,184.0,0.0,184.0,184.0,0.0,672.0,1.0,NaN,NaN,184.0,0.0,110.0,107.0,-3.0,-2.727273,168.0,159.0,-9.0,-5.357143,184.0,1.0,184.0,1.0,374.0,1.0,623.0,0.0,301.0,1.0,623.0,0.0,623.0,0.0,301.0,1.0,374.0,1.0,301.0,1.0,301.0,1.0,301.0,1.0,206.0
1,20050203,1.0,Western Europe,1101,211101002,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,2,0.0,N,N,N,386.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,N,Y,N,1.0,1.0,1.0,PR,PR,1.0,785.0,1.0,1070.0,1.0,48.0,48.0,832.0,1.0,832.0,1.0,979.0,0.0,NaN,832.0,1.0,832.0,1.0,N,832.0,1.0,1117.0,1.0,840.0,1.0,840.0,1.0,1.0,832.0,1.0,832.0,832.0,1.0,1.0,832.0,0.0,979.0,1117.0,1.0,1301.0,0.0,NaN,NaN,NaN,NaN,119.0,32.0,-87.0,-73.109244,49.0,0.0,-49.0,-100.000000,832.0,1.0,832.0,1.0,1301.0,0.0,1125.0,1.0,1125.0,1.0,1301.0,0.0,1125.0,1.0,1125.0,1.0,1301.0,0.0,1125.0,1.0,1125.0,1.0,1125.0,1.0,933.0
2,20050203,1.0,Western Europe,1101,211101003,73.0,F,Female,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,403.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,0.0,0.0,1.0,PR,PR,1.0,NaN,NaN,407.0,1.0,731.0,58.0,240.0,1.0,240.0,1.0,464.0,1.0,NaN,240.0,1.0,240.0,1.0,N,240.0,1.0,464.0,1.0,280.0,1.0,224.0,1.0,1.0,240.0,1.0,240.0,240.0,1.0,1.0,240.0,1.0,464.0,464.0,1.0,1016.0,1.0,NaN,NaN,NaN,NaN,63.0,39.0,-24.0,-38.095238,62.0,34.0,-28.0,-45.161290,240.0,1.0,240.0,1.0,947.0,0.0,504.0,1.0,504.0,1.0,947.0,0.0,947.0,0.0,504.0,1.0,947.0,0.0,504.0,1.0,504.0,1.0,504.0,1.0,444.0
3,20050203,1.0,Western Europe,1101,211101004,69.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,389.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,0.0,0.0,1.0,PR,PR,1.0,NaN,NaN,119.0,1.0,731.0,105.0,105.0,1.0,105.0,1.0,223.0,1.0,NaN,105.0,1.0,105.0,1.0,N,105.0,1.0,223.0,1.0,105.0,1.0,105.0,1.0,1.0,105.0,1.0,105.0,105.0,1.0,1.0,105.0,1.0,223.0,223.0,1.0,874.0,1.0,105.0,1.0,NaN,NaN,188.0,105.0,-83.0,-44.148936,42.0,16.0,-26.0,-61.904762,105.0,1.0,105.0,1.0,483.0,1.0,755.0,1.0,281.0,1.0,803.0,0.0,755.0,1.0,281.0,1.0,483.0,1.0,281.0,1.0,281.0,1.0,281.0,1.0,224.0
4,20050203,1.0,Western Europe,1101,211101005,64.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,1,1.0,Y,N,N,406.0,0 or 1,0.0,Fully active,0 or 1,1252.0,Rectal,0.0,N,Y,Y,Y,Y,N,1.0,1.0,1.0,PR,PR,1.0,771.0,1.0,882.0,1.0,57.0,57.0,827.0,1.0,827.0,1.0,938.0,1.0,NaN,827.0,1.0,827.0,1.0,N,827.0,1.0,938.0,1.0,840.0,1.0,840.0,1.0,1.0,827.0,1.0,827.0,827.0,1.0,1.0,827.0,1.0,938.0,938.0,1.0,1269.0,0.0,NaN,NaN,NaN,NaN,27.0,0.0,-27.0,-100.000000,25.0,0.0,-25.0,-100.000000,827.0,1.0,827.0,1.0,1269.0,0.0,1101.0,1.0,1101.0,1.0,1269.0,0.0,1101.0,1.0,1101.0,1.0,1269.0,0.0,1101.0,1.0,1101.0,1.0,1101.0,1.0,926.0

In [247]:
_ = read_domain('NCT00364013_panitumumab_folfox_raw', 'a_endpt.sas7bdat')

--- NCT00364013_panitumumab_folfox_raw/a_endpt.sas7bdat ---
shape: (935, 167)
columns: ['STUDYID', 'REGIONCD', 'REGION', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'B_ECOGCT', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'EVALITT', 'EVALPP', 'EVALCTR', 'EVALEGFR', 'INVCONF', 'B_WEIGHT', 'B_HEIGHT', 'B_BMI', 'B_BSA', 'PRSURG', 'PRRADIO', 'PADJYNCD', 'PRADJYN', 'B_ALPYN', 'B_ALPNM', 'B_ECG', 'B_CEA', 'B_CEAYN', 'B_CREAT', 'CHMOLNCD', 'CHMOLINE', 'HEPATIC', 'RENAL', 'TUMTYPCD', 'TUMTYPE', 'DUREXPCD', 'DUREXPOS', 'IPDUR', 'CDOSE', 'OXDUR', 'OXCDOSE', 'FBDUR', 'FBCDOSE', 'FIDUR', 'FICDOSE', 'DIAGMONS', 'METMONS', 'BIOPNO', 'BIOPTPCT', 'BIOPRSCD', 'BIOPEFCD', 'BIOPEF', 'BIOPNEG', 'BIOPWEAK', 'BIOPMOD', 'BIOPSTRG', 'BIOP3', 'BIOPS123', 'BIOPMAX', 'INVTX', 'INVTXDTC', 'RDTCR', 'ROSCR', 'ROSLR', 'ROSLRCA', 'RDTLRCA', 'RDTLR', 'RDURCR', 'RDURCRC', 'RDURLR', 'RDURLRC', 'RDYCR', 'RDYLR', 'PFSDYCR', 'PFSCR', 'PFSDYOCR', 'PFSOCR', 'PFSDYOLR', 'PFSOLR', 'PFSCREWK', 'PFSDYCRE', 'PFSCRE', 'PFSDYCRU', 'PFSCRU', 'PFSCU', 'PFSDYCRV', 'PFSCRV', 'PFSDYLR', 'PFSLR', 'PFSDYCRN', 'PFSCRN', 'PFSDYCRA', 'PFSCRA', 'PFSCRS', 'PFSDYCRS', 'PFSCRT', 'PFSDYCRT', 'PDDYCR', 'PDCR', 'PDOCR', 'PDDYOCR', 'PDOLR', 'PDDYOLR', 'PDDYLR', 'PDLR', 'DTHDY', 'DTH', 'SDDURCR', 'SDDURCRC', 'SDDURLR', 'SDDURLRC', 'SLDCBASE', 'SLDCMIN', 'SLDCMXRD', 'SLDCMXPR', 'SLDLBASE', 'SLDLMIN', 'SLDLMXRD', 'SLDLMXPR', 'PFSDYCEP', 'PFSCEP', 'PFSDYCEB', 'PFSCEB', 'DROPINDY', 'DROPIN', 'VEGFRDY', 'VEGFR', 'IRINDY', 'IRIN', 'OXALDY', 'OXAL', 'BEVZDY', 'BEVZ', 'CHIOFDY', 'CHIOF', 'EGFRIRDY', 'EGFRIR', 'ANTUMDY', 'ANTUM', 'WOEGFRDY', 'WOEGFR', 'POTOSDY', 'POTOS', 'RESRATE', 'TRTDUR']

,STUDYID,REGIONCD,REGION,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,B_METACT,LIVRONCD,LIVRONLY,B_LDHYN,B_LDH2YN,B_LDHNM,B_ECOGCT,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,EVALITT,EVALPP,EVALCTR,EVALEGFR,INVCONF,B_WEIGHT,B_HEIGHT,B_BMI,B_BSA,PRSURG,PRRADIO,PADJYNCD,PRADJYN,B_ALPYN,B_ALPNM,B_ECG,B_CEA,B_CEAYN,B_CREAT,CHMOLNCD,CHMOLINE,HEPATIC,RENAL,TUMTYPCD,TUMTYPE,DUREXPCD,DUREXPOS,IPDUR,CDOSE,OXDUR,OXCDOSE,FBDUR,FBCDOSE,FIDUR,FICDOSE,DIAGMONS,METMONS,BIOPNO,BIOPTPCT,BIOPRSCD,BIOPEFCD,BIOPEF,BIOPNEG,BIOPWEAK,BIOPMOD,BIOPSTRG,BIOP3,BIOPS123,BIOPMAX,INVTX,INVTXDTC,RDTCR,ROSCR,ROSLR,ROSLRCA,RDTLRCA,RDTLR,RDURCR,RDURCRC,RDURLR,RDURLRC,RDYCR,RDYLR,PFSDYCR,PFSCR,PFSDYOCR,PFSOCR,PFSDYOLR,PFSOLR,PFSCREWK,PFSDYCRE,PFSCRE,PFSDYCRU,PFSCRU,PFSCU,PFSDYCRV,PFSCRV,PFSDYLR,PFSLR,PFSDYCRN,PFSCRN,PFSDYCRA,PFSCRA,PFSCRS,PFSDYCRS,PFSCRT,PFSDYCRT,PDDYCR,PDCR,PDOCR,PDDYOCR,PDOLR,PDDYOLR,PDDYLR,PDLR,DTHDY,DTH,SDDURCR,SDDURCRC,SDDURLR,SDDURLRC,SLDCBASE,SLDCMIN,SLDCMXRD,SLDCMXPR,SLDLBASE,SLDLMIN,SLDLMXRD,SLDLMXPR,PFSDYCEP,PFSCEP,PFSDYCEB,PFSCEB,DROPINDY,DROPIN,VEGFRDY,VEGFR,IRINDY,IRIN,OXALDY,OXAL,BEVZDY,BEVZ,CHIOFDY,CHIOF,EGFRIRDY,EGFRIR,ANTUMDY,ANTUM,WOEGFRDY,WOEGFR,POTOSDY,POTOS,RESRATE,TRTDUR
0,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,N,111.0,189.0,31.074158,2.414022,Y,Y,1.0,Y,N,209.0,Normal,6.2,Y,114.920,4.0,1st Line,N,N,1.0,Colon,3.0,>= 6 to < 9 Months,217.0,8934.0,162.0,2031.5,217.0,26552.0,217.0,39828.0,65.081967,0.557377,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,N,NaN,,N,,0.0,0.0,0.0,SD,SD,0.0,NaN,NaN,NaN,NaN,731.0,184.0,184.0,1.0,184.0,1.0,184.0,0.0,NaN,184.0,1.0,184.0,1.0,N,184.0,1.0,672.0,1.0,224.0,1.0,168.0,1.0,1.0,184.0,1.0,184.0,184.0,1.0,1.0,184.0,0.0,184.0,184.0,0.0,672.0,1.0,NaN,NaN,184.0,0.0,110.0,107.0,-3.0,-2.727273,168.0,159.0,-9.0,-5.357143,184.0,1.0,184.0,1.0,374.0,1.0,623.0,0.0,301.0,1.0,623.0,0.0,623.0,0.0,301.0,1.0,374.0,1.0,301.0,1.0,301.0,1.0,301.0,1.0,0.0,206.0
1,20050203,1.0,Western Europe,1101,211101002,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,2,0.0,N,N,N,386.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,N,Y,N,N,62.7,166.0,22.753665,1.700343,Y,N,0.0,N,N,228.0,Normal,88.3,Y,93.704,4.0,1st Line,N,N,1.0,Colon,4.0,>= 9 Months,944.0,20288.0,194.0,1192.0,944.0,47942.0,944.0,78455.0,1.573770,1.639344,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,N,NaN,,Y,2009-08-21,1.0,1.0,1.0,PR,PR,1.0,785.0,1.0,1070.0,1.0,48.0,48.0,832.0,1.0,832.0,1.0,979.0,0.0,NaN,832.0,1.0,832.0,1.0,N,832.0,1.0,1117.0,1.0,840.0,1.0,840.0,1.0,1.0,832.0,1.0,832.0,832.0,1.0,1.0,832.0,0.0,979.0,1117.0,1.0,1301.0,0.0,NaN,NaN,NaN,NaN,119.0,32.0,-87.0,-73.109244,49.0,0.0,-49.0,-100.000000,832.0,1.0,832.0,1.0,1301.0,0.0,1125.0,1.0,1125.0,1.0,1301.0,0.0,1125.0,1.0,1125.0,1.0,1301.0,0.0,1125.0,1.0,1125.0,1.0,1125.0,1.0,1.0,933.0
2,20050203,1.0,Western Europe,1101,211101003,73.0,F,Female,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,403.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,N,52.0,160.5,20.186139,1.522607,Y,N,0.0,N,Y,802.0,Abnormal - not clinically significant,227.9,Y,75.140,4.0,1st Line,N,N,1.0,Colon,4.0,>= 9 Months,455.0,7892.0,455.0,2618.0,455.0,24738.0,455.0,46546.0,1.409836,1.409836,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,N,NaN,,N,,0.0,0.0,1.0,PR,PR,1.0,NaN,NaN,407.0,1.0,731.0,58.0,240.0,1.0,240.0,1.0,464.0,1.0,NaN,240.0,1.0,240.0,1.0,N,240.0,1.0,464.0,1.0,280.0,1.0,224.0,1.0,1.0,240.0,1.0,240.0,240.0,1.0,1.0,240.0,1.0,464.0,464.0,1.0,1016.0,1.0,NaN,NaN,NaN,NaN,63.0,39.0,-24.0,-38.095238,62.0,34.0,-28.0,-45.161290,240.0,1.0,240.0,1.0,947.0,0.0,504.0,1.0,504.0,1.0,947.0,0.0,947.0,0.0,504.0,1.0,947.0,0.0,504.0,1.0,504.0,1.0,504.0,1.0,0.0,444.0
3,20050203,1.0,Western Europe,1101,211101004,69.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,389.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,N,90.0,171.0,30.778701,2.067607,Y,N,0.0,N,,NaN,Normal,4.6,N,89.284,4.0,1st Line,N,N,1.0,Colon,3.0,>= 6 to < 9 Months,235.0,7996.0,144.0,1700.0,235.0,25600.0,235.0,38400.0,1.180328,1.180328,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,N,NaN,,N,,0.0,0.0,1.0,PR,PR,1.0,NaN,NaN,119.0,1.0,731.0,105.0,105.0,1.0,105.0,1.0,223.0,1.0,NaN,105.0,1.0,105.0,1.0,N,105.0,1.0,223.0,1.0,105.0,1.0,105.0,1.0,1.0,105.0,1.0,105.0,105.0,1.0,1.0,105.0,1.0,223.0,223.0,1.0,874.0,1.0,105.0,1.0,NaN,NaN,188.0,105.0,-83.0,-44.148936,42.0,16.0,-26.0,-61.904762,105.0,1.0,105.0,1.0,483.0,1.0,755.0,1.0,281.0,1.0,803.0,0.0,755.0,1.0,281.0,1.0,483.0,1.0,281.0,1.0,281.0,1.0,281.0,1.0,0.0,224.0
4,20050203,1.0,Western Europe,1101,211101005,64.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,1,1.0,Y,N,N,406.0,0 or 1,0.0,Fully active,0 or 1,1252.0,Rectal,0.0,N,Y,Y,Y,Y,N,N,58.0,168.0,20.549887,1.645195,Y,N,0.0,N,Y,393.0,Normal,23.3,Y,95.472,4.0,1st Line,N,N,2.0,Rectum,4.0,>= 9 Months,937.0,19692.0,198.0,1444.0,937.0,61580.0,937.0,95847.0,1.639344,1.114754,,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,N,NaN,,Y,2008-12-09,1.0,1.0,1.0,PR,PR,1.0,771.0,1.0,882.0,1.0,57.0,57.0,827.0,1.0,827.0,1.0,938.0,1.0,NaN,827.0,1.0,827.0,1.0,N,827.0,1.0,938.0,1.0,840.0,1.0,840.0,1.0,1.0,827.0,1.0,827.0,827.0,1.0,1.0,827.0,1.0,938.0,938.0,1.0,1269.0,0.0,NaN,NaN,NaN,NaN,27.0,0.0,-27.0,-100.000000,25.0,0.0,-25.0,-100.000000,827.0,1.0,827.0,1.0,1269.0,0.0,1101.0,1.0,1101.0,1.0,1269.0,0.0,1101.0,1.0,1101.0,1.0,1269.0,0.0,1101.0,1.0,1101.0,1.0,1101.0,1.0,1.0,926.0

In [248]:
_ = read_domain('NCT00364013_panitumumab_folfox_raw', 'a_sendpt.sas7bdat')

--- NCT00364013_panitumumab_folfox_raw/a_sendpt.sas7bdat ---
shape: (935, 221)
columns: ['STUDYID', 'REGIONCD', 'REGION', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'B_ECOGCT', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'EVALITT', 'EVALPP', 'EVALCTR', 'EVALEGFR', 'INTEYE', 'INTEYEDY', 'IEG34', 'IEGRDY', 'IEG34DUR', 'IEG34DRC', 'IESEVCD', 'IESEV', 'IESEVDY', 'IEDUR', 'IEDURC', 'IESEVDUR', 'IESEVDRC', 'IEDIS', 'IEOT', 'IEOTDY', 'IEOTDYC', 'IEOTFUDY', 'INTINF', 'IERSFU', 'IEGRRSFU', 'RAGRRSFU', 'SKRSFU', 'NARSFU', 'HARSFU', 'EYRSFU', 'INFRSFU', 'DOSWH', 'DOSWR', 'DOSWRF', 'DOSWRW', 'INFCTC', 'INFREP', 'INFUSPI', 'AE', 'AE34', 'AE4', 'AESER', 'AEREL', 'AEREL34', 'AEREL4', 'AERELSER', 'AETXDIS', 'AESTYDIS', 'AELIFE', 'DEATH', 'CALCEM', 'CLCSEVCD', 'CLCSEV', 'MAGNES', 'MAGSEVCD', 'MAGSEV', 'DIARRHEA', 'DIASEVCD', 'DIASEV', 'STOMATIT', 'STOSEVCD', 'STOSEV', 'CARDTOX', 'CTXSEVCD', 'CTXSEV', 'PULMTOX', 'VASCTOX', 'NUMINFP', 'NUMINF', 'NUMOXINF', 'NUMALINF', 'NUMCHINF', 'NUMCHALL', 'NUMFBINF', 'NUMLLINF', 'NUMDLINF', 'NUMFIINF', 'CDOSE', 'ADOSE', 'CWDOSE', 'AWDOSE', 'OXCDOSE', 'OXADOSE', 'OXCWDOSE', 'OXAWDOSE', 'FBCDOSE', 'FBADOSE', 'FBCWDOSE', 'FBAWDOSE', 'FICDOSE', 'FIADOSE', 'FICWDOSE', 'FIAWDOSE', 'LLCDOSE', 'LLADOSE', 'LLCWDOSE', 'LLAWDOSE', 'DLCDOSE', 'DLADOSE', 'DLCWDOSE', 'DLAWDOSE', 'DUREXP', 'EXPWK', 'IPDURWK', 'IPDSINT', 'IPDSINTR', 'IPDSINR3', 'OXDURWK', 'OXDSINT', 'OXDSINTR', 'OXDSINR3', 'FBDURWK', 'FBDSINT', 'FBDSINTR', 'FBDSINR3', 'FIDURWK', 'FIDSINT', 'FIDSINTR', 'FIDSINR3', 'LLDURWK', 'LLDSINT', 'LLDSINTR', 'LLDSINR3', 'DLDURWK', 'DLDSINT', 'DLDSINTR', 'DLDSINR3', 'IPDLYNM', 'IPDLYPC', 'DSDLYNM', 'DSDLYPC', 'CHDLYNM', 'CHDLYPC', 'IPDECNMW', 'IPDECPCW', 'OXDECNMW', 'OXDECPCW', 'FBDECNMW', 'FIDECNMW', 'FBDECPCW', 'FIDECPCW', 'DECNMW', 'DECPCW', 'DECCHNMW', 'DECCHPCW', 'PROPDOSE', 'SKYN', 'SKDY', 'SKSEVCD', 'SKSEV', 'SKSEVDY', 'SKDUR', 'SKDURC', 'SKSEVDUR', 'SKSEVDRC', 'SKDIS', 'EYYN', 'EYDY', 'EYSEVCD', 'EYSEV', 'EYSEVDY', 'EYDUR', 'EYDURC', 'EYSEVDUR', 'EYSEVDRC', 'CSYN', 'CSDY', 'CSSEVDY', 'CSDIS', 'HAYN', 'HADY', 'HASEVCD', 'HASEV', 'HASEVDY', 'HADUR', 'HADURC', 'HASEVDUR', 'HASEVDRC', 'HADIS', 'NAYN', 'NADY', 'NASEVCD', 'NASEV', 'NASEVDY', 'NADUR', 'NADURC', 'NASEVDUR', 'NASEVDRC', 'TRTDUR']

,STUDYID,REGIONCD,REGION,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,B_METACT,LIVRONCD,LIVRONLY,B_LDHYN,B_LDH2YN,B_LDHNM,B_ECOGCT,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,EVALITT,EVALPP,EVALCTR,EVALEGFR,INTEYE,INTEYEDY,IEG34,IEGRDY,IEG34DUR,IEG34DRC,IESEVCD,IESEV,IESEVDY,IEDUR,IEDURC,IESEVDUR,IESEVDRC,IEDIS,IEOT,IEOTDY,IEOTDYC,IEOTFUDY,INTINF,IERSFU,IEGRRSFU,RAGRRSFU,SKRSFU,NARSFU,HARSFU,EYRSFU,INFRSFU,DOSWH,DOSWR,DOSWRF,DOSWRW,INFCTC,INFREP,INFUSPI,AE,AE34,AE4,AESER,AEREL,AEREL34,AEREL4,AERELSER,AETXDIS,AESTYDIS,AELIFE,DEATH,CALCEM,CLCSEVCD,CLCSEV,MAGNES,MAGSEVCD,MAGSEV,DIARRHEA,DIASEVCD,DIASEV,STOMATIT,STOSEVCD,STOSEV,CARDTOX,CTXSEVCD,CTXSEV,PULMTOX,VASCTOX,NUMINFP,NUMINF,NUMOXINF,NUMALINF,NUMCHINF,NUMCHALL,NUMFBINF,NUMLLINF,NUMDLINF,NUMFIINF,CDOSE,ADOSE,CWDOSE,AWDOSE,OXCDOSE,OXADOSE,OXCWDOSE,OXAWDOSE,FBCDOSE,FBADOSE,FBCWDOSE,FBAWDOSE,FICDOSE,FIADOSE,FICWDOSE,FIAWDOSE,LLCDOSE,LLADOSE,LLCWDOSE,LLAWDOSE,DLCDOSE,DLADOSE,DLCWDOSE,DLAWDOSE,DUREXP,EXPWK,IPDURWK,IPDSINT,IPDSINTR,IPDSINR3,OXDURWK,OXDSINT,OXDSINTR,OXDSINR3,FBDURWK,FBDSINT,FBDSINTR,FBDSINR3,FIDURWK,FIDSINT,FIDSINTR,FIDSINR3,LLDURWK,LLDSINT,LLDSINTR,LLDSINR3,DLDURWK,DLDSINT,DLDSINTR,DLDSINR3,IPDLYNM,IPDLYPC,DSDLYNM,DSDLYPC,CHDLYNM,CHDLYPC,IPDECNMW,IPDECPCW,OXDECNMW,OXDECPCW,FBDECNMW,FIDECNMW,FBDECPCW,FIDECPCW,DECNMW,DECPCW,DECCHNMW,DECCHPCW,PROPDOSE,SKYN,SKDY,SKSEVCD,SKSEV,SKSEVDY,SKDUR,SKDURC,SKSEVDUR,SKSEVDRC,SKDIS,EYYN,EYDY,EYSEVCD,EYSEV,EYSEVDY,EYDUR,EYDURC,EYSEVDUR,EYSEVDRC,CSYN,CSDY,CSSEVDY,CSDIS,HAYN,HADY,HASEVCD,HASEV,HASEVDY,HADUR,HADURC,HASEVDUR,HASEVDRC,HADIS,NAYN,NADY,NASEVCD,NASEV,NASEVDY,NADUR,NADURC,NASEVDUR,NASEVDRC,TRTDUR
0,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,1.0,0.0,1.0,4.0,18.0,1.0,3.0,Severe,4.0,274.0,0.0,18.0,1.0,N,Y,68.0,0.0,NaN,1.0,Y,N,N,Y,N,Y,N,N,N,N,N,N,N,N,N,Y,Y,N,N,Y,Y,N,N,N,N,N,N,N,0.0,None,N,0.0,None,Y,2.0,Moderate,Y,1.0,Mild,N,0.0,None,Y,N,14.0,14.0,10.0,14.0,14.0,10.0,14.0,14.0,NaN,14.0,8934.0,638.142857,87.970059,6.283576,2031.5,203.150000,867.007426,86.700743,26552.0,1896.571429,11504.057560,821.718397,39828.0,2844.857143,17256.086340,1232.577596,6638.0,474.142857,2876.014390,205.429599,NaN,NaN,NaN,NaN,219.0,31.285714,31.000000,5.675488,94.591461,87.763068,23.142857,74.926568,88.148903,86.261224,31.000000,742.197262,92.774658,86.585690,31.000000,1113.295893,92.774658,86.585690,31.000000,185.549315,92.774658,86.585690,NaN,NaN,NaN,NaN,3.0,0.214286,3.0,0.214286,3.0,0.214286,1.0,0.071429,1.0,0.100000,1.0,1.0,0.071429,0.071429,1.0,0.071429,1.0,0.071429,1.231708,1.0,0.0,3.0,Severe,4.0,274.0,0.0,18.0,1.0,N,1.0,175.0,1.0,Mild,175.0,59.0,1.0,59.0,1.0,0.0,273.0,273.0,N,1.0,63.0,1.0,Mild,63.0,211.0,0.0,211.0,0.0,N,1.0,80.0,1.0,Mild,80.0,154.0,1.0,154.0,1.0,206.0
1,20050203,1.0,Western Europe,1101,211101002,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,2,0.0,N,N,N,386.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,N,Y,N,1.0,5.0,0.0,958.0,NaN,NaN,2.0,Moderate,5.0,1111.0,0.0,1065.0,0.0,N,Y,185.0,0.0,NaN,1.0,Y,N,N,Y,Y,Y,N,Y,N,N,N,N,N,N,N,Y,Y,N,N,Y,N,N,N,N,N,N,N,N,0.0,None,Y,1.0,Mild,Y,2.0,Moderate,Y,2.0,Moderate,N,0.0,None,N,N,54.0,54.0,10.0,54.0,54.0,10.0,54.0,53.0,1.0,54.0,20288.0,375.703704,327.622857,6.067090,1192.0,119.200000,698.864016,69.886402,47942.0,887.814815,28360.930513,525.202417,78455.0,1452.870370,46415.895554,859.553621,18013.2,339.871698,10657.643170,201.087607,340.0,340.0,202.893193,202.893193,946.0,135.142857,134.857143,4.858814,80.980226,72.546491,27.714286,50.433486,59.333513,72.610062,134.857143,420.607020,52.575878,72.359683,134.857143,688.371332,57.364278,72.359683,134.857143,158.058267,79.029134,72.359683,2.0,202.893193,50.723298,NaN,18.0,0.333333,18.0,0.333333,18.0,0.333333,1.0,0.018519,2.0,0.200000,3.0,3.0,0.055556,0.055556,3.0,0.055556,3.0,0.055556,1.126375,1.0,5.0,2.0,Moderate,5.0,1111.0,0.0,1065.0,0.0,N,1.0,242.0,1.0,Mild,242.0,156.0,1.0,156.0,1.0,0.0,958.0,958.0,N,1.0,111.0,2.0,Moderate,193.0,1007.0,0.0,925.0,0.0,N,1.0,102.0,2.0,Moderate,102.0,1016.0,0.0,906.0,0.0,933.0
2,20050203,1.0,Western Europe,1101,211101003,73.0,F,Female,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,403.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,1.0,4.0,0.0,475.0,NaN,NaN,2.0,Moderate,76.0,472.0,0.0,162.0,0.0,N,Y,32.0,0.0,NaN,1.0,Y,N,N,Y,N,Y,N,N,N,N,N,N,N,N,N,Y,Y,Y,Y,Y,N,N,N,N,N,N,N,N,0.0,None,N,0.0,None,N,0.0,None,Y,1.0,Mild,Y,1.0,Mild,Y,N,26.0,26.0,26.0,26.0,26.0,26.0,26.0,26.0,NaN,26.0,7892.0,303.538462,155.673153,5.987429,2618.0,100.692308,1743.358211,67.052239,24738.0,951.461538,16473.113425,633.581286,46546.0,1790.230769,30964.777660,1190.952987,7744.0,297.846154,5151.929003,198.151115,NaN,NaN,NaN,NaN,457.0,65.285714,65.000000,4.789943,79.832386,93.954407,65.000000,53.641791,63.107990,86.899499,65.000000,506.865028,63.358129,81.823903,65.000000,952.762390,79.396866,87.007260,65.000000,158.520892,79.260446,87.007260,NaN,NaN,NaN,NaN,8.0,0.307692,8.0,0.307692,8.0,0.307692,9.0,0.346154,1.0,0.038462,1.0,0.0,0.038462,0.000000,10.0,0.384615,1.0,0.038462,1.417413,1.0,4.0,2.0,Moderate,76.0,472.0,0.0,162.0,0.0,N,0.0,475.0,0.0,None,475.0,NaN,NaN,NaN,NaN,1.0,41.0,41.0,N,1.0,51.0,1.0,Mild,51.0,399.0,0.0,399.0,0.0,N,1.0,244.0,1.0,Mild,244.0,61.0,1.0,61.0,1.0,444.0
3,20050203,1.0,Western Europe,1101,211101004,69.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,389.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,1.0,7.0,1.0,166.0,7.0,1.0,3.0,Severe,166.0,255.0,0.0,7.0,1.0,N,Y,28.0,0.0,NaN,1.0,Y,N,N,Y,Y,Y,Y,Y,Y,Y,Y,N,Y,N,N,Y,Y,N,Y,Y,Y,N,N,N,N,N,N,N,0.0,None,N,0.0,None,N,0.0,None,Y,3.0,Severe,Y,1.0,Mild,N,Y,16.0,15.0,10.0,16.0,16.0,10.0,16.0,16.0,NaN,16.0,7996.0,533.066667,90.214576,6.014305,1700.0,170.000000,826.584598,82.658460,25600.0,1600.000000,12485.065934,780.316621,38400.0,2400.000000,18727.598901,1170.474931,6400.0,400.000000,3121.266483,195.079155,NaN,NaN,NaN,NaN,237.0,33.857143,33.571429,5.374485,89.574756,95.543809,20.571429,80.362391,94.543990,93.170471,33.571429,743.791162,92.973895,93.170471,33.571429,1115.686743,92.973895,93.170471,33.571429,185.947791,92.973895,93.170471,NaN,NaN,NaN,NaN,2.0,0.133333,2.0,0.125000,2.0,0.125000,3.0,0.200000,0.0,0.000000,0.0,0.0,0.000000,0.000000,3.0,0.187500,0.0,0.000000,1.178009,1.0,7.0,3.0,Severe,166.0,255.0,0.0,7.0,1.0,N,1.0,102.0,2.0,Moderate,223.0,103.0,1.0,39.0,1.0,0.0,251.0,251.0,N,1.0,130.0,2.0,Moderate,130.0,122.0,0.0,122.0,0.0,N,1.0,88.0,1.0,Mild,88.0,174.0,1.0,174.0,1.0,224.0
4,20050203,1.0,Western Europe,1101,211101005,64.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,1,1.0,Y,N,N,406.0,0 or 1,0.0,Fully active,0 or 1,1252.0,Rectal,0.0,N,Y,Y,Y,Y,N,1.0,14.0,0.0,962.0,NaN,NaN,2.0,Moderate,105.0,949.0,0.0,858.0,0.0,N,Y,37.0,0.0,NaN,1.0,Y,N,N,Y,N,Y,Y,N,N,N,N,N,N,N,N,Y,Y,N,N,Y,N,N,N,N,N,N,N,N,0.0,None,N,0.0,None,Y,1.0,Mild,N,0.0,None,Y,1.0,Mild,N,N,58.0,58.0,12.0,58.0,58.0,12.0,58.0,51.0,7.0,58.0,19692.0,339.517241,354.126972,6.105637,1444.0,120.333333,896.377476,74.698123,61580.0,1061.724138,38237.067667,659.259787,95847.0,1652.534483,59514.988383,1026.120489,16726.4,327.968627,10387.620866,203.678841,2296.0,328.0,1426.453477,203.779068,939.0,134.142857,133.857143,5.291118,88.185301,87.827946,28.285714,63.380226,74.564971,82.080597,133.857143,571.311577,71.413947,82.754203,133.857143,889.231417,74.102618,83.227545,133.857143,155.204581,77.602290,85.616104,36.0,79.247415,19.811854,NaN,8.0,0.137931,8.0,0.137931,8.0,0.137931,1.0,0.017241,1.0,0.083333,1.0,1.0,0.017241,0.017241,2.0,0.034483,1.0,0.017241,1.346901,1.0,14.0,2.0,Moderate,105.0,949.0,0.0,858.0,0.0,N,1.0,155.0,1.0,Mild,155.0,746.0,0.0,746.0,0.0,0.0,962.0,962.0,N,1.0,127.0,2.0,Moderate,127.0,836.0,0.0,836.0,0.0,N,1.0,198.0,1.0,Mild,198.0,124.0,1.0,124.0,1.0,926.0

In [249]:
_ = read_domain('NCT00364013_panitumumab_folfox_raw', 'ae.sas7bdat')

--- NCT00364013_panitumumab_folfox_raw/ae.sas7bdat ---
shape: (22801, 110)
columns: ['STUDYID', 'REGIONCD', 'REGION', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'B_ECOGCT', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'EVALITT', 'EVALPP', 'EVALCTR', 'EVALEGFR', 'AEANY', 'AELINENO', 'PHASECD', 'PHASE', 'PHASEND', 'AESTDY', 'AEENDY', 'AETERM', 'AELLT', 'AEPT', 'AEHLT', 'AEHLGT', 'AELLTCD', 'AESOC', 'PRECUT', 'AEDUR', 'AEDURI', 'AENUMINF', 'AENUMCTX', 'AEPRIOR', 'AERASH', 'AEINTEYE', 'AEINTINF', 'AEINTCAT', 'AENASTCD', 'AENASTER', 'AEINTMT', 'AESEVCD', 'AESEV', 'AEREL', 'AERELCM', 'AEINFCTC', 'AEINFREP', 'AEINFPI', 'AECRDTOX', 'AEPULTOX', 'AEVASTOX', 'AEDIARR', 'AESTOMA', 'AECALCEM', 'AEMAGNES', 'AENEUTOX', 'AEHEMTOX', 'AECRDARR', 'AEISCHAE', 'AEACTCDS', 'AEACT01', 'AEACT02', 'AEACT03', 'AEACT04', 'AEACT05', 'AEACT06', 'AEACT07', 'AEACT10', 'AEACT81', 'AEACT82', 'AEACT83', 'AEACT88', 'AESER', 'SAELIFE', 'AEWDOS', 'AECDOS', 'AEOXWDOS', 'AEOXCDOS', 'AEFIWDOS', 'AEFICDOS', 'AEFBWDOS', 'AEFBCDOS', 'AELLWDOS', 'AELLCDOS', 'AEDLWDOS', 'AEDLCDOS', 'TRTDUR', 'MEDDRA_V']

,STUDYID,REGIONCD,REGION,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,B_METACT,LIVRONCD,LIVRONLY,B_LDHYN,B_LDH2YN,B_LDHNM,B_ECOGCT,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,EVALITT,EVALPP,EVALCTR,EVALEGFR,AEANY,AELINENO,PHASECD,PHASE,PHASEND,AESTDY,AEENDY,AETERM,AELLT,AEPT,AEHLT,AEHLGT,AELLTCD,AESOC,PRECUT,AEDUR,AEDURI,AENUMINF,AENUMCTX,AEPRIOR,AERASH,AEINTEYE,AEINTINF,AEINTCAT,AENASTCD,AENASTER,AEINTMT,AESEVCD,AESEV,AEREL,AERELCM,AEINFCTC,AEINFREP,AEINFPI,AECRDTOX,AEPULTOX,AEVASTOX,AEDIARR,AESTOMA,AECALCEM,AEMAGNES,AENEUTOX,AEHEMTOX,AECRDARR,AEISCHAE,AEACTCDS,AEACT01,AEACT02,AEACT03,AEACT04,AEACT05,AEACT06,AEACT07,AEACT10,AEACT81,AEACT82,AEACT83,AEACT88,AESER,SAELIFE,AEWDOS,AECDOS,AEOXWDOS,AEOXCDOS,AEFIWDOS,AEFICDOS,AEFBWDOS,AEFBCDOS,AELLWDOS,AELLCDOS,AEDLWDOS,AEDLCDOS,TRTDUR,MEDDRA_V
0,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,Y,10.0,30.0,Treatment,Treatment,NaN,22.0,ITCH,Itch,Pruritus,Pruritus NEC,Epidermal and dermal conditions,10023082.0,Skin and subcutaneous tissue disorders,Y,NaN,22.0,1.0,1.0,N,N,Y,N,SKIN,NaN,,Y,2.0,Moderate,Y,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,3,N,N,Y,N,N,N,N,N,N,N,N,N,N,,6.0,6.0,84.713411,84.713411,599.000454,599.000454,399.333636,399.333636,99.833409,99.833409,NaN,NaN,206.0,12.0
1,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,Y,7.0,30.0,Treatment,Treatment,NaN,113.0,FATIGUE,Fatigue,Fatigue,Asthenic conditions,General system disorders NEC,10016256.0,General disorders and administration site cond...,Y,NaN,113.0,1.0,1.0,N,N,N,N,,NaN,,Y,2.0,Moderate,N,Y,N,N,N,N,N,N,N,N,N,N,N,N,N,N,1,Y,N,N,N,N,N,N,N,N,N,N,N,N,,6.0,6.0,84.713411,84.713411,599.000454,599.000454,399.333636,399.333636,99.833409,99.833409,NaN,NaN,206.0,12.0
2,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,Y,3.0,30.0,Treatment,Treatment,NaN,149.0,ANOREXIA,Anorexia,Anorexia,Appetite disorders,Appetite and general nutritional disorders,10002646.0,Metabolism and nutrition disorders,Y,NaN,149.0,1.0,1.0,N,N,N,N,,NaN,,Y,2.0,Moderate,N,Y,N,N,N,N,N,N,N,N,N,N,N,N,N,N,1,Y,N,N,N,N,N,N,N,N,N,N,N,N,,6.0,6.0,84.713411,84.713411,599.000454,599.000454,399.333636,399.333636,99.833409,99.833409,NaN,NaN,206.0,12.0
3,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,Y,3.0,30.0,Treatment,Treatment,4.0,NaN,ABDOMINAL CRAMPS,Abdominal cramps,Abdominal pain,Gastrointestinal and abdominal pains (excl ora...,Gastrointestinal signs and symptoms,10000057.0,Gastrointestinal disorders,Y,NaN,15.0,1.0,1.0,N,N,N,N,,NaN,,Y,1.0,Mild,N,Y,N,N,N,N,N,N,N,N,N,N,N,N,N,N,1,Y,N,N,N,N,N,N,N,N,N,N,N,N,,6.0,6.0,84.713411,84.713411,599.000454,1198.000909,399.333636,798.667273,99.833409,199.666818,NaN,NaN,206.0,12.0
4,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,Y,5.0,30.0,Treatment,Treatment,5.0,22.0,ACNE,Acne,Acne,Acnes,Skin appendage conditions,10000496.0,Skin and subcutaneous tissue disorders,Y,18.0,18.0,1.0,1.0,N,Y,Y,N,SKIN,NaN,,,3.0,Severe,Y,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,3,N,N,Y,N,N,N,N,N,N,N,N,N,N,,6.0,6.0,84.713411,84.713411,599.000454,1198.000909,399.333636,798.667273,99.833409,199.666818,NaN,NaN,206.0,12.0

In [250]:
_ = read_domain('NCT00364013_panitumumab_folfox_raw', 'chemotx.sas7bdat')

--- NCT00364013_panitumumab_folfox_raw/chemotx.sas7bdat ---
shape: (237, 46)
columns: ['STUDYID', 'REGIONCD', 'REGION', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'B_ECOGCT', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'EVALITT', 'EVALPP', 'EVALCTR', 'EVALEGFR', 'CHANY', 'PHASECD', 'PHASE', 'CHSTDY', 'CHENDY', 'CHLINECD', 'CHLINE', 'CHTERM', 'TRTDUR', 'CHPDDY']

,STUDYID,REGIONCD,REGION,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,B_METACT,LIVRONCD,LIVRONLY,B_LDHYN,B_LDH2YN,B_LDHNM,B_ECOGCT,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,EVALITT,EVALPP,EVALCTR,EVALEGFR,CHANY,PHASECD,PHASE,CHSTDY,CHENDY,CHLINECD,CHLINE,CHTERM,TRTDUR,CHPDDY
0,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,Y,5.0,Pre-consent,-1930.0,-1894.0,88.0,Other,5-FU,206.0,-17.0
1,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,Y,5.0,Pre-consent,-1855.0,-1781.0,50.0,Adjuvant,5-FU,206.0,-17.0
2,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,Y,5.0,Pre-consent,-1855.0,-1781.0,NaN,,IRINOTECAN,206.0,-17.0
3,20050203,1.0,Western Europe,1103,211103001,76.0,M,Male,1.0,White or Caucasian,NaN,,,43.0,FOLFOX alone,43.0,FOLFOX alone,>=3,0.0,N,N,N,269.0,0 or 1,1.0,Symptoms but ambulatory,0 or 1,1252.0,Rectal,0.0,N,Y,Y,Y,Y,N,Y,5.0,Pre-consent,-89.0,-61.0,88.0,Other,FLUORO(5)-URACIL,213.0,-13.0
4,20050203,1.0,Western Europe,1103,211103002,58.0,M,Male,1.0,White or Caucasian,NaN,,,43.0,FOLFOX alone,43.0,FOLFOX alone,2,0.0,N,N,N,269.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,Y,5.0,Pre-consent,-990.0,-846.0,50.0,Adjuvant,5-FU,149.0,-21.0

In [251]:
_ = read_domain('NCT00364013_panitumumab_folfox_raw', 'corevar.sas7bdat')

--- NCT00364013_panitumumab_folfox_raw/corevar.sas7bdat ---
shape: (935, 37)
columns: ['STUDYID', 'REGIONCD', 'REGION', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'B_ECOGCT', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'EVALITT', 'EVALPP', 'EVALCTR', 'EVALEGFR', 'TRTDUR']

,STUDYID,REGIONCD,REGION,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,B_METACT,LIVRONCD,LIVRONLY,B_LDHYN,B_LDH2YN,B_LDHNM,B_ECOGCT,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,EVALITT,EVALPP,EVALCTR,EVALEGFR,TRTDUR
0,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,206.0
1,20050203,1.0,Western Europe,1101,211101002,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,2,0.0,N,N,N,386.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,N,Y,N,933.0
2,20050203,1.0,Western Europe,1101,211101003,73.0,F,Female,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,403.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,444.0
3,20050203,1.0,Western Europe,1101,211101004,69.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,389.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,224.0
4,20050203,1.0,Western Europe,1101,211101005,64.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,1,1.0,Y,N,N,406.0,0 or 1,0.0,Fully active,0 or 1,1252.0,Rectal,0.0,N,Y,Y,Y,Y,N,926.0

In [252]:
_ = read_domain('NCT00364013_panitumumab_folfox_raw', 'death.sas7bdat')

--- NCT00364013_panitumumab_folfox_raw/death.sas7bdat ---
shape: (693, 46)
columns: ['STUDYID', 'REGIONCD', 'REGION', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'B_ECOGCT', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'EVALITT', 'EVALPP', 'EVALCTR', 'EVALEGFR', 'PRECUT', 'DTHDY', 'DTHDYI', 'DTHDYI2', 'PHASECD', 'PHASE', 'DTCAUSCD', 'DTCAUS', 'DTAEPT', 'TRTDUR']

,STUDYID,REGIONCD,REGION,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,B_METACT,LIVRONCD,LIVRONLY,B_LDHYN,B_LDH2YN,B_LDHNM,B_ECOGCT,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,EVALITT,EVALPP,EVALCTR,EVALEGFR,PRECUT,DTHDY,DTHDYI,DTHDYI2,PHASECD,PHASE,DTCAUSCD,DTCAUS,DTAEPT,TRTDUR
0,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,Y,673.0,673.0,673.0,60.0,Long-term follow-up,7.0,Disease progression,,206.0
1,20050203,1.0,Western Europe,1101,211101003,73.0,F,Female,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,403.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,Y,1017.0,1017.0,1017.0,60.0,Long-term follow-up,7.0,Disease progression,,444.0
2,20050203,1.0,Western Europe,1101,211101004,69.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,389.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,Y,875.0,875.0,875.0,60.0,Long-term follow-up,7.0,Disease progression,,224.0
3,20050203,1.0,Western Europe,1101,211101006,37.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,604.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,Y,551.0,551.0,551.0,60.0,Long-term follow-up,7.0,Disease progression,,325.0
4,20050203,1.0,Western Europe,1103,211103001,76.0,M,Male,1.0,White or Caucasian,NaN,,,43.0,FOLFOX alone,43.0,FOLFOX alone,>=3,0.0,N,N,N,269.0,0 or 1,1.0,Symptoms but ambulatory,0 or 1,1252.0,Rectal,0.0,N,Y,Y,Y,Y,N,Y,777.0,777.0,777.0,60.0,Long-term follow-up,7.0,Disease progression,,213.0

In [253]:
_ = read_domain('NCT00364013_panitumumab_folfox_raw', 'demo.sas7bdat')

--- NCT00364013_panitumumab_folfox_raw/demo.sas7bdat ---
shape: (935, 78)
columns: ['STUDYID', 'REGIONCD', 'REGION', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'B_ECOGCT', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'EVALITT', 'EVALPP', 'EVALCTR', 'EVALEGFR', 'B_WEIGHT', 'B_HEIGHT', 'B_BSA', 'DIAGMONS', 'METMONS', 'BIOPACPT', 'BIOPHACT', 'BIOPSTCD', 'BIOPSITE', 'BIOPBSCD', 'BIOPBSIT', 'BIOPNOCD', 'BIOPNO', 'BIOPTPCT', 'BIOPEFCD', 'BIOPEF', 'BIOPNEG', 'BIOPWEAK', 'BIOPMOD', 'BIOPSTRG', 'BIOP3', 'BIOPS123', 'BIOPMAX', 'BIOPPCCD', 'BIOPPCT', 'BIOPCYTO', 'H11NEG', 'H11WEAK', 'H11MOD', 'BIOPMAXC', 'BIOPCYCD', 'BIOPCY', 'CHILDPOT', 'PREGDONE', 'PREGTYCD', 'PREGTYPE', 'BIONANY', 'BIORSNCD', 'TRTDUR', 'PREGDY', 'BIOPDY', 'BIOPDY2']

,STUDYID,REGIONCD,REGION,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,B_METACT,LIVRONCD,LIVRONLY,B_LDHYN,B_LDH2YN,B_LDHNM,B_ECOGCT,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,EVALITT,EVALPP,EVALCTR,EVALEGFR,B_WEIGHT,B_HEIGHT,B_BSA,DIAGMONS,METMONS,BIOPACPT,BIOPHACT,BIOPSTCD,BIOPSITE,BIOPBSCD,BIOPBSIT,BIOPNOCD,BIOPNO,BIOPTPCT,BIOPEFCD,BIOPEF,BIOPNEG,BIOPWEAK,BIOPMOD,BIOPSTRG,BIOP3,BIOPS123,BIOPMAX,BIOPPCCD,BIOPPCT,BIOPCYTO,H11NEG,H11WEAK,H11MOD,BIOPMAXC,BIOPCYCD,BIOPCY,CHILDPOT,PREGDONE,PREGTYCD,PREGTYPE,BIONANY,BIORSNCD,TRTDUR,PREGDY,BIOPDY,BIOPDY2
0,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,111.0,189.0,2.414022,65.081967,0.557377,N,,2.0,Metastatic,88.0,Other,NaN,,NaN,NaN,,NaN,NaN,NaN,NaN,N,NaN,,NaN,,NaN,NaN,NaN,NaN,,NaN,,N,,NaN,,,NaN,206.0,NaN,NaN,NaN
1,20050203,1.0,Western Europe,1101,211101002,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,2,0.0,N,N,N,386.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,N,Y,N,62.7,166.0,1.700343,1.573770,1.639344,N,,1.0,Primary,NaN,,NaN,,NaN,NaN,,NaN,NaN,NaN,NaN,N,NaN,,NaN,,NaN,NaN,NaN,NaN,,NaN,,N,,NaN,,,NaN,933.0,NaN,NaN,NaN
2,20050203,1.0,Western Europe,1101,211101003,73.0,F,Female,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,403.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,52.0,160.5,1.522607,1.409836,1.409836,N,,1.0,Primary,NaN,,NaN,,NaN,NaN,,NaN,NaN,NaN,NaN,N,NaN,,NaN,,NaN,NaN,NaN,NaN,,NaN,,N,,NaN,,,NaN,444.0,NaN,NaN,NaN
3,20050203,1.0,Western Europe,1101,211101004,69.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,389.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,90.0,171.0,2.067607,1.180328,1.180328,N,,1.0,Primary,NaN,,NaN,,NaN,NaN,,NaN,NaN,NaN,NaN,N,NaN,,NaN,,NaN,NaN,NaN,NaN,,NaN,,N,,NaN,,,NaN,224.0,NaN,NaN,NaN
4,20050203,1.0,Western Europe,1101,211101005,64.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,1,1.0,Y,N,N,406.0,0 or 1,0.0,Fully active,0 or 1,1252.0,Rectal,0.0,N,Y,Y,Y,Y,N,58.0,168.0,1.645195,1.639344,1.114754,N,,1.0,Primary,NaN,,NaN,,NaN,NaN,,NaN,NaN,NaN,NaN,N,NaN,,NaN,,NaN,NaN,NaN,NaN,,NaN,,N,,NaN,,,NaN,926.0,NaN,NaN,NaN

In [254]:
_ = read_domain('NCT00364013_panitumumab_folfox_raw', 'disposit.sas7bdat')

--- NCT00364013_panitumumab_folfox_raw/disposit.sas7bdat ---
shape: (935, 67)
columns: ['STUDYID', 'REGIONCD', 'REGION', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'B_ECOGCT', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'EVALITT', 'EVALPP', 'EVALCTR', 'EVALEGFR', 'ICSIGN', 'LDOSDSDY', 'EOIPCD', 'EOIP', 'PPCRITCD', 'PPCRIT', 'EOIPPDCD', 'EOIPPD', 'EOIPPRCD', 'EOIPPR', 'EOIPRDCD', 'EOIPRD', 'DSSTATCD', 'DSSTAT', 'DSREASCD', 'DSREAS', 'DSFPSCD', 'DSFPS', 'DSCMPEOS', 'EORDPCD', 'EORDP', 'TRTDUR', 'LASTCTDY', 'LASTOSDY', 'EORADDY', 'EOPPDY', 'EOIPDY', 'DECISDY', 'DSDY', 'FPANDY', 'LPANDY']

,STUDYID,REGIONCD,REGION,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,B_METACT,LIVRONCD,LIVRONLY,B_LDHYN,B_LDH2YN,B_LDHNM,B_ECOGCT,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,EVALITT,EVALPP,EVALCTR,EVALEGFR,ICSIGN,LDOSDSDY,EOIPCD,EOIP,PPCRITCD,PPCRIT,EOIPPDCD,EOIPPD,EOIPPRCD,EOIPPR,EOIPRDCD,EOIPRD,DSSTATCD,DSSTAT,DSREASCD,DSREAS,DSFPSCD,DSFPS,DSCMPEOS,EORDPCD,EORDP,TRTDUR,LASTCTDY,LASTOSDY,EORADDY,EOPPDY,EOIPDY,DECISDY,DSDY,FPANDY,LPANDY
0,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,Y,206.0,88.0,Other,NaN,,NaN,,88.0,Other,NaN,,1.0,Completed safety FUP,NaN,,NaN,,Y,NaN,,206.0,624.0,274.0,284.0,214.0,214.0,214.0,274.0,1.0,204.0
1,20050203,1.0,Western Europe,1101,211101002,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,2,0.0,N,N,N,386.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,N,Y,N,Y,933.0,88.0,Other,NaN,,NaN,,88.0,Other,NaN,,2.0,Did not complete safety FUP,9.0,Administrative decision,NaN,,Y,NaN,,933.0,1302.0,1118.0,NaN,1012.0,1012.0,1012.0,959.0,1.0,931.0
2,20050203,1.0,Western Europe,1101,211101003,73.0,F,Female,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,403.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,Y,444.0,7.0,Disease progression,NaN,,199.0,Radiographically determined disease progression,7.0,Disease progression,199.0,Radiographically determined disease progression,1.0,Completed safety FUP,NaN,,NaN,,Y,NaN,,444.0,948.0,476.0,NaN,465.0,465.0,465.0,476.0,1.0,442.0
3,20050203,1.0,Western Europe,1101,211101004,69.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,389.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,Y,224.0,7.0,Disease progression,NaN,,199.0,Radiographically determined disease progression,7.0,Disease progression,199.0,Radiographically determined disease progression,1.0,Completed safety FUP,NaN,,NaN,,Y,NaN,,224.0,804.0,252.0,NaN,224.0,224.0,224.0,252.0,1.0,222.0
4,20050203,1.0,Western Europe,1101,211101005,64.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,1,1.0,Y,N,N,406.0,0 or 1,0.0,Fully active,0 or 1,1252.0,Rectal,0.0,N,Y,Y,Y,Y,N,Y,926.0,7.0,Disease progression,NaN,,199.0,Radiographically determined disease progression,7.0,Disease progression,199.0,Radiographically determined disease progression,1.0,Completed safety FUP,NaN,,NaN,,Y,NaN,,926.0,1270.0,963.0,NaN,941.0,941.0,941.0,963.0,1.0,924.0

In [255]:
_ = read_domain('NCT00364013_panitumumab_folfox_raw', 'eligcrit.sas7bdat')

--- NCT00364013_panitumumab_folfox_raw/eligcrit.sas7bdat ---
shape: (1080, 40)
columns: ['STUDYID', 'REGIONCD', 'REGION', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'B_ECOGCT', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'EVALITT', 'EVALPP', 'EVALCTR', 'EVALEGFR', 'ELIGIBLE', 'ELIGNMCD', 'ELIGNM', 'TRTDUR']

,STUDYID,REGIONCD,REGION,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,B_METACT,LIVRONCD,LIVRONLY,B_LDHYN,B_LDH2YN,B_LDHNM,B_ECOGCT,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,EVALITT,EVALPP,EVALCTR,EVALEGFR,ELIGIBLE,ELIGNMCD,ELIGNM,TRTDUR
0,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,Y,NaN,,206.0
1,20050203,1.0,Western Europe,1101,211101002,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,2,0.0,N,N,N,386.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,N,Y,N,Y,NaN,,933.0
2,20050203,1.0,Western Europe,1101,211101003,73.0,F,Female,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,403.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,Y,NaN,,444.0
3,20050203,1.0,Western Europe,1101,211101004,69.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,389.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,Y,NaN,,224.0
4,20050203,1.0,Western Europe,1101,211101005,64.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,1,1.0,Y,N,N,406.0,0 or 1,0.0,Fully active,0 or 1,1252.0,Rectal,0.0,N,Y,Y,Y,Y,N,Y,NaN,,926.0

In [256]:
_ = read_domain('NCT00364013_panitumumab_folfox_raw', 'exposure.sas7bdat')

--- NCT00364013_panitumumab_folfox_raw/exposure.sas7bdat ---
shape: (94339, 79)
columns: ['STUDYID', 'REGIONCD', 'REGION', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'B_ECOGCT', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'EVALITT', 'EVALPP', 'EVALCTR', 'EVALEGFR', 'DOSREFDY', 'DOSREFWK', 'ENRREFDY', 'ENRREFWK', 'VISITCD', 'VISIT', 'EXDURMN', 'ACTTRTCD', 'ACTTRT', 'DRUGTP', 'QTY', 'QTYUNCD', 'QTYUNIT', 'CONC', 'CONCUNCD', 'CONCUNIT', 'DOSE', 'DOSEUNCD', 'DOSEUNIT', 'WDOSE', 'WDOSUNCD', 'WDOSUNIT', 'BSADOSE', 'ROUTECD', 'ROUTE', 'DOSEFRCD', 'DOSEFREQ', 'DOSINTYN', 'DOSDLAY', 'EXDELDY', 'EXCHEMO', 'EXINTCD', 'EXINT', 'EXDRESCD', 'EXDRES', 'EXDRSCD2', 'EXDRES2', 'EXDRSCD3', 'EXDRES3', 'EXPPRSCD', 'EXCYCLNM', 'EXINFRCT', 'TRTDUR']

,STUDYID,REGIONCD,REGION,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,B_METACT,LIVRONCD,LIVRONLY,B_LDHYN,B_LDH2YN,B_LDHNM,B_ECOGCT,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,EVALITT,EVALPP,EVALCTR,EVALEGFR,DOSREFDY,DOSREFWK,ENRREFDY,ENRREFWK,VISITCD,VISIT,EXDURMN,ACTTRTCD,ACTTRT,DRUGTP,QTY,QTYUNCD,QTYUNIT,CONC,CONCUNCD,CONCUNIT,DOSE,DOSEUNCD,DOSEUNIT,WDOSE,WDOSUNCD,WDOSUNIT,BSADOSE,ROUTECD,ROUTE,DOSEFRCD,DOSEFREQ,DOSINTYN,DOSDLAY,EXDELDY,EXCHEMO,EXINTCD,EXINT,EXDRESCD,EXDRES,EXDRSCD2,EXDRES2,EXDRSCD3,EXDRES3,EXPPRSCD,EXCYCLNM,EXINFRCT,TRTDUR
0,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,1.0,1.0,1.0,1.0,C1D1,"Cycle 1, day 1",NaN,100.0,5-Fluorouracil continuous,,NaN,,,NaN,,,1446.0,MG,Milligram,13.027027,MG/KG,Milligram/kilogram,599.000454,IV,Intravenous,CI,Continuous infusion,,,NaN,Y,NaN,,NaN,,NaN,,NaN,,NaN,1.0,,206.0
1,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,1.0,1.0,1.0,1.0,C1D1,"Cycle 1, day 1",NaN,1.0,panit.,,100.0,ML,Milliliter (cc),6.0,MG/KG,Milligram/kilogram,666.0,MG,Milligram,6.000000,MG/KG,Milligram/kilogram,NaN,IV,Intravenous,,,N,,NaN,,NaN,,NaN,,NaN,,NaN,,NaN,1.0,N,206.0
2,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,1.0,1.0,1.0,1.0,C1D1,"Cycle 1, day 1",NaN,73.0,Leucovorin,l-leucovorin,NaN,,,NaN,,,241.0,MG,Milligram,2.171171,MG/KG,Milligram/kilogram,99.833409,IV,Intravenous,,,,,NaN,Y,NaN,,NaN,,NaN,,NaN,,NaN,1.0,,206.0
3,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,1.0,1.0,1.0,1.0,C1D1,"Cycle 1, day 1",120.0,78.0,Oxaliplatin,,NaN,,,NaN,,,204.5,MG,Milligram,1.842342,MG/KG,Milligram/kilogram,84.713411,IV,Intravenous,,,,,NaN,Y,NaN,,NaN,,NaN,,NaN,,NaN,1.0,,206.0
4,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,1.0,1.0,1.0,1.0,C1D1,"Cycle 1, day 1",NaN,75.0,5-Fluorouracil bolus,,NaN,,,NaN,,,964.0,MG,Milligram,8.684685,MG/KG,Milligram/kilogram,399.333636,IV,Intravenous,OTO,One time only,,,NaN,Y,NaN,,NaN,,NaN,,NaN,,NaN,1.0,,206.0

In [257]:
_ = read_domain('NCT00364013_panitumumab_folfox_raw', 'lab.sas7bdat')

--- NCT00364013_panitumumab_folfox_raw/lab.sas7bdat ---
shape: (516051, 72)
columns: ['STUDYID', 'REGIONCD', 'REGION', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'B_ECOGCT', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'EVALITT', 'EVALPP', 'EVALCTR', 'EVALEGFR', 'DOSREFDY', 'DOSREFWK', 'ENRREFDY', 'ENRREFWK', 'VISITCD', 'VISIT', 'PHASECD', 'PHASE', 'LBNUMINF', 'LBNUMCTX', 'LBANLCYC', 'LBPANEL', 'LBTESTCD', 'LBTEST', 'LBSTRESN', 'LBSTRESC', 'LBSTUNIT', 'LBSTNRLO', 'LBSTNRHI', 'LBNRIND', 'LBORRES', 'LBORRESN', 'LBORUNIT', 'LBORNRLO', 'LBORNRHI', 'LBBASE', 'LBBLRES', 'LBCHGBL', 'LBPCHGBL', 'LBGRDINC', 'LBGRDDEC', 'LBMIN', 'LBMAX', 'LBLAST', 'LBANALWK', 'TRTDUR']

,STUDYID,REGIONCD,REGION,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,B_METACT,LIVRONCD,LIVRONLY,B_LDHYN,B_LDH2YN,B_LDHNM,B_ECOGCT,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,EVALITT,EVALPP,EVALCTR,EVALEGFR,DOSREFDY,DOSREFWK,ENRREFDY,ENRREFWK,VISITCD,VISIT,PHASECD,PHASE,LBNUMINF,LBNUMCTX,LBANLCYC,LBPANEL,LBTESTCD,LBTEST,LBSTRESN,LBSTRESC,LBSTUNIT,LBSTNRLO,LBSTNRHI,LBNRIND,LBORRES,LBORRESN,LBORUNIT,LBORNRLO,LBORNRHI,LBBASE,LBBLRES,LBCHGBL,LBPCHGBL,LBGRDINC,LBGRDDEC,LBMIN,LBMAX,LBLAST,LBANALWK,TRTDUR
0,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,-6.0,-1.0,-6.0,-1.0,SCR,Screening,5.0,Pre-consent,0.0,0.0,NaN,CHEMISTRY,ALB,Albumin,NaN,,g/L,32.0,45.0,,,NaN,,NaN,NaN,N,45.7,NaN,NaN,NaN,NaN,N,N,N,NaN,206.0
1,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,1.0,1.0,1.0,1.0,C1D1,"Cycle 1, day 1",10.0,Pre-treatment,0.0,0.0,1.0,CHEMISTRY,ALB,Albumin,45.7,46,g/L,32.0,45.0,Above upper limit of reference range,45.7,45.7,g/L,NaN,NaN,Y,45.7,NaN,NaN,NaN,0.0,N,N,N,1.0,206.0
2,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,19.0,3.0,19.0,3.0,C2D1,"Cycle 2, day 1",30.0,Treatment,1.0,1.0,2.0,CHEMISTRY,ALB,Albumin,40.2,40,g/L,32.0,45.0,,40.2,40.2,g/L,NaN,NaN,N,45.7,-5.5,-12.035011,NaN,0.0,N,N,N,NaN,206.0
3,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,33.0,5.0,33.0,5.0,C3D1,"Cycle 3, day 1",30.0,Treatment,2.0,2.0,3.0,CHEMISTRY,ALB,Albumin,NaN,,g/L,32.0,45.0,,,NaN,,NaN,NaN,N,45.7,NaN,NaN,NaN,NaN,N,N,N,NaN,206.0
4,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,51.0,8.0,51.0,8.0,C4D1,"Cycle 4, day 1",30.0,Treatment,3.0,3.0,4.0,CHEMISTRY,ALB,Albumin,39.1,39,g/L,32.0,45.0,,39.1,39.1,g/L,NaN,NaN,N,45.7,-6.6,-14.442013,NaN,0.0,N,N,N,9.0,206.0

In [258]:
_ = read_domain('NCT00364013_panitumumab_folfox_raw', 'lesion.sas7bdat')

--- NCT00364013_panitumumab_folfox_raw/lesion.sas7bdat ---
shape: (100724, 72)
columns: ['STUDYID', 'REGIONCD', 'REGION', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'B_ECOGCT', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'EVALITT', 'EVALPP', 'EVALCTR', 'EVALEGFR', 'DOSREFDY', 'DOSREFWK', 'ENRREFDY', 'ENRREFWK', 'PRECUT', 'VISITCD', 'VISIT', 'PHASECD', 'PHASE', 'LSTYPECD', 'LSTYPE', 'LSCATCD', 'LSCAT', 'LSANY', 'LSNO', 'LSPERFNY', 'LSPIRRNY', 'LSSITECD', 'LSSITE', 'LSPROCCD', 'LSPROC', 'LSRAWCD', 'LSRAW', 'LSNEW', 'LSNEWANY', 'LSNONMYN', 'LSLD', 'LSSLD', 'LSSLDPCH', 'LSSLDPCN', 'LSRESPCD', 'LSRESP', 'LSPROGNY', 'LSEXAMNO', 'LSRI', 'TRTDUR']

,STUDYID,REGIONCD,REGION,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,B_METACT,LIVRONCD,LIVRONLY,B_LDHYN,B_LDH2YN,B_LDHNM,B_ECOGCT,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,EVALITT,EVALPP,EVALCTR,EVALEGFR,DOSREFDY,DOSREFWK,ENRREFDY,ENRREFWK,PRECUT,VISITCD,VISIT,PHASECD,PHASE,LSTYPECD,LSTYPE,LSCATCD,LSCAT,LSANY,LSNO,LSPERFNY,LSPIRRNY,LSSITECD,LSSITE,LSPROCCD,LSPROC,LSRAWCD,LSRAW,LSNEW,LSNEWANY,LSNONMYN,LSLD,LSSLD,LSSLDPCH,LSSLDPCN,LSRESPCD,LSRESP,LSPROGNY,LSEXAMNO,LSRI,TRTDUR
0,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,NaN,NaN,NaN,NaN,Y,FUP,Safety follow-Up,50.0,Short-term/safety follow-up,2.0,Local,1.0,Target lesion,N,NaN,,,NaN,,NaN,,NaN,,,,,NaN,NaN,NaN,NaN,NaN,,,NaN,NaN,206.0
1,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,NaN,NaN,NaN,NaN,Y,SCR,Screening,10.0,Pre-treatment,2.0,Local,2.0,Non-target lesion,N,NaN,,,NaN,,NaN,,NaN,,,,,NaN,NaN,NaN,NaN,NaN,,,NaN,NaN,206.0
2,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,-6.0,-1.0,-6.0,-1.0,Y,SCR,Screening,5.0,Pre-consent,1.0,Central,NaN,,,NaN,,,NaN,,41.0,CT abdomen,NaN,,,,,NaN,NaN,NaN,NaN,NaN,,,2.0,5.0,206.0
3,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,-6.0,-1.0,-6.0,-1.0,Y,SCR,Screening,5.0,Pre-consent,1.0,Central,1.0,Target lesion,,1.0,,,88.0,Other,46.0,CT pelvis,283.0,Muscular mass/nodule,N,N,,110.0,110.0,NaN,NaN,NaN,,,3.0,5.0,206.0
4,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,-6.0,-1.0,-6.0,-1.0,Y,SCR,Screening,5.0,Pre-consent,1.0,Central,1.0,Target lesion,,1.0,,,811.0,Liver,41.0,CT abdomen,262.0,Liver mass/nodule,N,N,,46.0,163.0,NaN,NaN,NaN,,,2.0,5.0,206.0

In [259]:
_ = read_domain('NCT00364013_panitumumab_folfox_raw', 'lesnprog.sas7bdat')

--- NCT00364013_panitumumab_folfox_raw/lesnprog.sas7bdat ---
shape: (125, 43)
columns: ['STUDYID', 'REGIONCD', 'REGION', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'B_ECOGCT', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'EVALITT', 'EVALPP', 'EVALCTR', 'EVALEGFR', 'DOSREFDY', 'DOSREFWK', 'LPWK', 'VISITCD', 'VISIT', 'LPSUM', 'TRTDUR']

,STUDYID,REGIONCD,REGION,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,B_METACT,LIVRONCD,LIVRONLY,B_LDHYN,B_LDH2YN,B_LDHNM,B_ECOGCT,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,EVALITT,EVALPP,EVALCTR,EVALEGFR,DOSREFDY,DOSREFWK,LPWK,VISITCD,VISIT,LPSUM,TRTDUR
0,20050203,1.0,Western Europe,1105,211105002,61.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,2,0.0,N,N,N,260.0,0 or 1,1.0,Symptoms but ambulatory,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,-6.0,-1.0,0,UNSCHED,Unscheduled visit,23.0,115.0
1,20050203,1.0,Western Europe,1105,211105002,61.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,2,0.0,N,N,N,260.0,0 or 1,1.0,Symptoms but ambulatory,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,56.0,8.0,8,UNSCHED,Unscheduled visit,23.0,115.0
2,20050203,1.0,Western Europe,1105,211105002,61.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,2,0.0,N,N,N,260.0,0 or 1,1.0,Symptoms but ambulatory,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,112.0,16.0,16,UNSCHED,Unscheduled visit,40.0,115.0
3,20050203,1.0,Western Europe,1105,211105003,59.0,F,Female,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,1,0.0,N,Y,N,858.0,0 or 1,1.0,Symptoms but ambulatory,0 or 1,1251.0,Colon,1.0,Y,N,Y,Y,Y,N,-1.0,-1.0,0,UNSCHED,Unscheduled visit,17.0,136.0
4,20050203,1.0,Western Europe,1105,211105003,59.0,F,Female,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,1,0.0,N,Y,N,858.0,0 or 1,1.0,Symptoms but ambulatory,0 or 1,1251.0,Colon,1.0,Y,N,Y,Y,Y,N,63.0,9.0,8,UNSCHED,Unscheduled visit,11.0,136.0

In [260]:
_ = read_domain('NCT00364013_panitumumab_folfox_raw', 'medhist.sas7bdat')

--- NCT00364013_panitumumab_folfox_raw/medhist.sas7bdat ---
shape: (5791, 48)
columns: ['STUDYID', 'REGIONCD', 'REGION', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'B_ECOGCT', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'EVALITT', 'EVALPP', 'EVALCTR', 'EVALEGFR', 'MHANY', 'MHBNGNYN', 'MHBSYSCD', 'MHBODSYS', 'MHCONDCD', 'MHCOND', 'MHSITECD', 'MHSITE', 'MHSTATCD', 'MHSTAT', 'TRTDUR', 'MHSTDY']

,STUDYID,REGIONCD,REGION,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,B_METACT,LIVRONCD,LIVRONLY,B_LDHYN,B_LDH2YN,B_LDHNM,B_ECOGCT,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,EVALITT,EVALPP,EVALCTR,EVALEGFR,MHANY,MHBNGNYN,MHBSYSCD,MHBODSYS,MHCONDCD,MHCOND,MHSITECD,MHSITE,MHSTATCD,MHSTAT,TRTDUR,MHSTDY
0,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,Y,N,NaN,,NaN,,NaN,,NaN,,206.0,NaN
1,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,Y,N,7.0,Renal,NaN,,NaN,,2.0,Resolved,206.0,NaN
2,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,Y,N,51.0,Psychiatric,NaN,,NaN,,1.0,Current or continuing,206.0,NaN
3,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,Y,N,51.0,Psychiatric,NaN,,NaN,,1.0,Current or continuing,206.0,NaN
4,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,Y,N,4.0,Gastrointestinal,NaN,,NaN,,1.0,Current or continuing,206.0,NaN

In [261]:
_ = read_domain('NCT00364013_panitumumab_folfox_raw', 'othcantx.sas7bdat')

--- NCT00364013_panitumumab_folfox_raw/othcantx.sas7bdat ---
shape: (977, 44)
columns: ['STUDYID', 'REGIONCD', 'REGION', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'B_ECOGCT', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'EVALITT', 'EVALPP', 'EVALCTR', 'EVALEGFR', 'OTANY', 'PHASECD', 'PHASE', 'OTSTDY', 'OTENDY', 'OTRGTXYN', 'TRTDUR', 'OTPDDY']

,STUDYID,REGIONCD,REGION,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,B_METACT,LIVRONCD,LIVRONLY,B_LDHYN,B_LDH2YN,B_LDHNM,B_ECOGCT,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,EVALITT,EVALPP,EVALCTR,EVALEGFR,OTANY,PHASECD,PHASE,OTSTDY,OTENDY,OTRGTXYN,TRTDUR,OTPDDY
0,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,Y,5.0,Pre-consent,-1855.0,-1781.0,N,206.0,-16.0
1,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,Y,5.0,Pre-consent,-1855.0,-1781.0,N,206.0,-16.0
2,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,Y,NaN,,NaN,NaN,Y,206.0,NaN
3,20050203,1.0,Western Europe,1101,211101002,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,2,0.0,N,N,N,386.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,N,Y,N,N,NaN,,NaN,NaN,Y,933.0,NaN
4,20050203,1.0,Western Europe,1101,211101003,73.0,F,Female,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,403.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,N,NaN,,NaN,NaN,Y,444.0,NaN

In [262]:
_ = read_domain('NCT00364013_panitumumab_folfox_raw', 'radiotx.sas7bdat')

--- NCT00364013_panitumumab_folfox_raw/radiotx.sas7bdat ---
shape: (954, 49)
columns: ['STUDYID', 'REGIONCD', 'REGION', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'B_ECOGCT', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'EVALITT', 'EVALPP', 'EVALCTR', 'EVALEGFR', 'RAANY', 'VISITCD', 'VISIT', 'PHASECD', 'PHASE', 'RASTDY', 'RASTDYE', 'RAENDY', 'RAAREA', 'RAINTCD', 'RAINT', 'RADPAREA', 'TRTDUR']

,STUDYID,REGIONCD,REGION,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,B_METACT,LIVRONCD,LIVRONLY,B_LDHYN,B_LDH2YN,B_LDHNM,B_ECOGCT,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,EVALITT,EVALPP,EVALCTR,EVALEGFR,RAANY,VISITCD,VISIT,PHASECD,PHASE,RASTDY,RASTDYE,RAENDY,RAAREA,RAINTCD,RAINT,RADPAREA,TRTDUR
0,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,Y,SCR,Screening,5.0,Pre-consent,-1932.0,-1932.0,-1908.0,RECTOSIGMOID,1.0,Curative,N,206.0
1,20050203,1.0,Western Europe,1101,211101002,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,2,0.0,N,N,N,386.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,N,Y,N,N,SCR,Screening,10.0,Pre-treatment,NaN,NaN,NaN,,NaN,,,933.0
2,20050203,1.0,Western Europe,1101,211101003,73.0,F,Female,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,403.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,N,SCR,Screening,10.0,Pre-treatment,NaN,NaN,NaN,,NaN,,,444.0
3,20050203,1.0,Western Europe,1101,211101004,69.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,389.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,N,SCR,Screening,10.0,Pre-treatment,NaN,NaN,NaN,,NaN,,,224.0
4,20050203,1.0,Western Europe,1101,211101005,64.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,1,1.0,Y,N,N,406.0,0 or 1,0.0,Fully active,0 or 1,1252.0,Rectal,0.0,N,Y,Y,Y,Y,N,N,SCR,Screening,10.0,Pre-treatment,NaN,NaN,NaN,,NaN,,,926.0

In [263]:
_ = read_domain('NCT00364013_panitumumab_folfox_raw', 'respeval.sas7bdat')

--- NCT00364013_panitumumab_folfox_raw/respeval.sas7bdat ---
shape: (20851, 81)
columns: ['STUDYID', 'REGIONCD', 'REGION', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'B_ECOGCT', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'EVALITT', 'EVALPP', 'EVALCTR', 'EVALEGFR', 'DOSREFDY', 'DOSREFWK', 'ENRREFDY', 'ENRREFWK', 'VISITCD', 'VISIT', 'RSTYPECD', 'RSTYPE', 'RSCRITCD', 'RSCRIT', 'RSRESP', 'RSRSPDCD', 'RSRSPD', 'RSCONFYN', 'RSBRCD', 'RSBR', 'RSBORCD', 'RSBOR', 'RSBORDT', 'RSBORDTC', 'RSCRCD', 'RSCR', 'RSITRSCD', 'RSITRESP', 'RSINRSCD', 'RSINRESP', 'RSTRSPCD', 'RSTRESP', 'RSNTRSCD', 'RSNTRESP', 'RSNEW', 'RSPORT1', 'RSPORT2', 'RSPORT3', 'TRTDUR', 'RSBRDY', 'PROGDY', 'RSP3EDY', 'RSP3SDY', 'RSP2EDY', 'RSP2SDY', 'RSP1EDY', 'RSP1SDY', 'RSBORDY', 'RSRESPDY']

,STUDYID,REGIONCD,REGION,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,B_METACT,LIVRONCD,LIVRONLY,B_LDHYN,B_LDH2YN,B_LDHNM,B_ECOGCT,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,EVALITT,EVALPP,EVALCTR,EVALEGFR,DOSREFDY,DOSREFWK,ENRREFDY,ENRREFWK,VISITCD,VISIT,RSTYPECD,RSTYPE,RSCRITCD,RSCRIT,RSRESP,RSRSPDCD,RSRSPD,RSCONFYN,RSBRCD,RSBR,RSBORCD,RSBOR,RSBORDT,RSBORDTC,RSCRCD,RSCR,RSITRSCD,RSITRESP,RSINRSCD,RSINRESP,RSTRSPCD,RSTRESP,RSNTRSCD,RSNTRESP,RSNEW,RSPORT1,RSPORT2,RSPORT3,TRTDUR,RSBRDY,PROGDY,RSP3EDY,RSP3SDY,RSP2EDY,RSP2SDY,RSP1EDY,RSP1SDY,RSBORDY,RSRESPDY
0,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,-6.0,-1.0,-6.0,-1.0,SCR,Screening,1.0,Central,3.0,Modified RECIST,,NaN,,,NaN,,NaN,,NaN,,NaN,,NaN,,NaN,,NaN,,NaN,,N,,,,206.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,-6.0,-1.0,-6.0,-1.0,SCR,Screening,1.0,Central,3.0,Modified RECIST,,NaN,,,NaN,,NaN,,NaN,,NaN,,NaN,,NaN,,NaN,,NaN,,N,,,,206.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,-6.0,-1.0,-6.0,-1.0,SCR,Screening,1.0,Central,3.0,Modified RECIST,,NaN,,,NaN,,5.0,Progressive disease,2007-05-16,2007-05-16,NaN,,NaN,,NaN,,NaN,,NaN,,N,,,,206.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,185.0,NaN
3,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,60.0,9.0,60.0,9.0,W8,Week 8,1.0,Central,3.0,Modified RECIST,Stable disease,4.0,Stable disease,,4.0,Stable disease,NaN,,NaN,,NaN,,NaN,,NaN,,4.0,Stable disease,4.0,Stable disease,N,,,,206.0,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.0
4,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,60.0,9.0,60.0,9.0,W8,Week 8,1.0,Central,3.0,Modified RECIST,Stable disease,4.0,Stable disease,,4.0,Stable disease,NaN,,NaN,,NaN,,NaN,,NaN,,4.0,Stable disease,4.0,Stable disease,N,,,,206.0,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.0

In [264]:
_ = read_domain('NCT00364013_panitumumab_folfox_raw', 'surghist.sas7bdat')

--- NCT00364013_panitumumab_folfox_raw/surghist.sas7bdat ---
shape: (1560, 50)
columns: ['STUDYID', 'REGIONCD', 'REGION', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'B_ECOGCT', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'EVALITT', 'EVALPP', 'EVALCTR', 'EVALEGFR', 'SXANY', 'DOSREFDY', 'DOSREFWK', 'SXTYPECD', 'SXTYPE', 'SXSITECD', 'SXSITE', 'SXSITCD2', 'SXSITE2', 'SXSITCD3', 'SXSITE3', 'SXINTCD', 'SXINT', 'TRTDUR']

,STUDYID,REGIONCD,REGION,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,B_METACT,LIVRONCD,LIVRONLY,B_LDHYN,B_LDH2YN,B_LDHNM,B_ECOGCT,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,EVALITT,EVALPP,EVALCTR,EVALEGFR,SXANY,DOSREFDY,DOSREFWK,SXTYPECD,SXTYPE,SXSITECD,SXSITE,SXSITCD2,SXSITE2,SXSITCD3,SXSITE3,SXINTCD,SXINT,TRTDUR
0,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,Y,-1987.0,-284.0,3.0,Biopsy,893.0,Colon,NaN,,NaN,,16.0,Diagnostic/Staging,206.0
1,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,Y,-1985.0,-284.0,4.0,Resection,893.0,Colon,NaN,,NaN,,1.0,Curative,206.0
2,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,Y,-5.0,-1.0,3.0,Biopsy,88.0,Other,NaN,,NaN,,16.0,Diagnostic/Staging,206.0
3,20050203,1.0,Western Europe,1101,211101002,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,2,0.0,N,N,N,386.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,N,Y,N,Y,-56.0,-8.0,3.0,Biopsy,893.0,Colon,NaN,,NaN,,16.0,Diagnostic/Staging,933.0
4,20050203,1.0,Western Europe,1101,211101002,54.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,2,0.0,N,N,N,386.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,N,Y,N,Y,-48.0,-7.0,4.0,Resection,893.0,Colon,NaN,,NaN,,15.0,Palliative,933.0

In [265]:
_ = read_domain('NCT00364013_panitumumab_folfox_raw', 'vitals_v.sas7bdat')

--- NCT00364013_panitumumab_folfox_raw/vitals_v.sas7bdat ---
shape: (77192, 61)
columns: ['STUDYID', 'REGIONCD', 'REGION', 'SITEID', 'SUBJID', 'AGE', 'SEXCD', 'SEX', 'RACCATCD', 'RACCAT', 'TRTDOSE', 'TRTFRQCD', 'TRTFREQ', 'TRTCD', 'TRT', 'ATRTCD', 'ATRT', 'B_METACT', 'LIVRONCD', 'LIVRONLY', 'B_LDHYN', 'B_LDH2YN', 'B_LDHNM', 'B_ECOGCT', 'BECOGICD', 'B_ECOGI', 'BECGICT', 'DIAGTYCD', 'DIAGTYPE', 'TUMCATCD', 'TUMCAT', 'LIVERMET', 'EVALITT', 'EVALPP', 'EVALCTR', 'EVALEGFR', 'DOSREFDY', 'DOSREFWK', 'ENRREFDY', 'ENRREFWK', 'VISITCD', 'VISIT', 'PHASECD', 'PHASE', 'VSPTMCD', 'VSPTM', 'VSNUMINF', 'VSTESTCD', 'VSTEST', 'VSSTRES', 'VSSTUNIT', 'VSORRES', 'VSORUNIT', 'VSBASE', 'VSBLRES', 'VSCHGBL', 'VSMIN', 'VSMAX', 'VSLAST', 'VSCYCLNM', 'TRTDUR']

,STUDYID,REGIONCD,REGION,SITEID,SUBJID,AGE,SEXCD,SEX,RACCATCD,RACCAT,TRTDOSE,TRTFRQCD,TRTFREQ,TRTCD,TRT,ATRTCD,ATRT,B_METACT,LIVRONCD,LIVRONLY,B_LDHYN,B_LDH2YN,B_LDHNM,B_ECOGCT,BECOGICD,B_ECOGI,BECGICT,DIAGTYCD,DIAGTYPE,TUMCATCD,TUMCAT,LIVERMET,EVALITT,EVALPP,EVALCTR,EVALEGFR,DOSREFDY,DOSREFWK,ENRREFDY,ENRREFWK,VISITCD,VISIT,PHASECD,PHASE,VSPTMCD,VSPTM,VSNUMINF,VSTESTCD,VSTEST,VSSTRES,VSSTUNIT,VSORRES,VSORUNIT,VSBASE,VSBLRES,VSCHGBL,VSMIN,VSMAX,VSLAST,VSCYCLNM,TRTDUR
0,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,-6.0,-1.0,-6.0,-1.0,SCR,Screening,5.0,Pre-consent,998.0,Taken at physical exam,0.0,DIABP,Diastolic blood pressure,80.0,MMHG,80.0,MMHG,N,81.0,NaN,N,N,N,NaN,206.0
1,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,-6.0,-1.0,-6.0,-1.0,SCR,Screening,5.0,Pre-consent,998.0,Taken at physical exam,0.0,ECOG,ECOG performance status,0.0,,0.0,,N,0.0,NaN,N,N,N,NaN,206.0
2,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,-6.0,-1.0,-6.0,-1.0,SCR,Screening,5.0,Pre-consent,998.0,Taken at physical exam,0.0,PULSE,Pulse,72.0,BEATS/MINUTE,72.0,BEATS/MINUTE,N,98.0,NaN,N,N,N,NaN,206.0
3,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,-6.0,-1.0,-6.0,-1.0,SCR,Screening,5.0,Pre-consent,998.0,Taken at physical exam,0.0,RESP,Respiration,12.0,BREATHS/MINUTE,12.0,BREATHS/MINUTE,N,12.0,NaN,N,N,N,NaN,206.0
4,20050203,1.0,Western Europe,1101,211101001,36.0,M,Male,1.0,White or Caucasian,6.0,Q2WK,Every 2 weeks,42.0,Panitumumab + FOLFOX,42.0,Panitumumab + FOLFOX,>=3,0.0,N,N,N,640.0,0 or 1,0.0,Fully active,0 or 1,1251.0,Colon,1.0,Y,Y,Y,Y,Y,N,-6.0,-1.0,-6.0,-1.0,SCR,Screening,5.0,Pre-consent,998.0,Taken at physical exam,0.0,SYSBP,Systolic blood pressure,136.0,MMHG,136.0,MMHG,N,145.0,NaN,N,N,N,NaN,206.0