# Column comparison across trials

Structural comparison only — which columns exist in which trial's files.
No row-level analysis. Built to make `raw_file_survey.ipynb`'s output diffable
instead of scrolling 71 tables by eye.

Two views:
1. **Presence matrix** for the 3 raw-domain trials (they share filenames: `demo`, `disposit`, `death`, `ae`, ...) — column x trial boolean table, sorted by how many trials share each column.
2. **Side-by-side column lists** for the 2 ADaM trials (`adsl`, `adae`) — these don't share a naming convention with the raw domains, so a boolean matrix isn't meaningful; just eyeball the two lists together.

In [2]:
import sys
from pathlib import Path

sys.path.insert(0, str(Path('..') / 'src'))
from column_survey import presence_matrix, columns_only, RAW_DOMAIN_TRIALS, ADAM_TRIALS

import pandas as pd
pd.set_option('display.max_rows', None)

DATA_DIR = Path('..') / '..' / 'Data' / 'raw'
assert DATA_DIR.exists(), DATA_DIR

## Raw-domain trials — presence matrix per domain

Domains present in all 3: `demo`, `disposit`, `death`, `ae`, `lab`, `medhist`, `chemotx`, `radiotx`, `surghist`, `eligcrit`, `corevar`, `respeval`, `lesion`, `exposure`, `vitals_v`, `a_eendpt`, `a_sendpt`.

Start with the ones that matter most for the outcome variable: `disposit` and `death` (dropout/censoring), then `demo` (baseline), then `ae`.

### `disposit.sas7bdat`

In [3]:
presence_matrix(DATA_DIR, 'disposit.sas7bdat', RAW_DOMAIN_TRIALS)

,NCT00115225_PACCE_bev_panitumumab_raw,NCT00339183_panitumumab_folfiri_raw,NCT00364013_panitumumab_folfox_raw,n_trials_present
EOIPCD,True,True,True,3
STUDYID,True,True,True,3
ICSIGN,True,True,True,3
LASTOSDY,True,True,True,3
DIAGTYPE,True,True,True,3
DIAGTYCD,True,True,True,3
LDOSDSDY,True,True,True,3
EOIP,True,True,True,3
RACCAT,True,True,True,3
RACCATCD,True,True,True,3
B_METACT,True,True,True,3
EVALITT,True,True,True,3
SEXCD,True,True,True,3
SITEID,True,True,True,3
B_LDHYN,True,True,True,3
SEX,True,True,True,3
SUBJID,True,True,True,3
TRTFREQ,True,True,True,3
EOIPDY,True,True,True,3
TRTFRQCD,True,True,True,3
AGE,True,True,True,3
ATRT,True,True,True,3
ATRTCD,True,True,True,3
B_ECOGI,True,True,True,3
EVALPP,True,True,True,3
BECOGICD,True,True,True,3
TRTDUR,True,True,True,3
TRTDOSE,True,True,True,3
TRTCD,True,True,True,3
TRT,True,True,True,3
EOIPPDCD,False,True,True,2
EOIPRD,False,True,True,2
EOIPPD,False,True,True,2
EOPPDY,False,True,True,2
EORADDY,False,True,True,2
EORDPCD,False,True,True,2
EVALEGFR,False,True,True,2
EOIPRDCD,False,True,True,2
EORDP,False,True,True,2
FPANDY,False,True,True,2
KRAS,True,True,False,2
KRASCD,True,True,False,2
LASTCTDY,False,True,True,2
LIVERMET,False,True,True,2
LIVRONCD,False,True,True,2
LIVRONLY,False,True,True,2
PRADJYN,True,True,False,2
TUMCAT,False,True,True,2
LPANDY,False,True,True,2
TUMCATCD,False,True,True,2
DSDY,False,True,True,2
B_LDH2YN,False,True,True,2
DSFPSCD,False,True,True,2
DSREAS,False,True,True,2
B_METANM,True,True,False,2
DSREASCD,False,True,True,2
DSDOSDY,True,True,False,2
DSCMPEOS,False,True,True,2
DSSTAT,False,True,True,2
B_LDHNM,False,True,True,2
DSFPS,False,True,True,2
DSSTATCD,False,True,True,2
B_ECOG,True,True,False,2
DECISDY,False,True,True,2
BECGICT,False,True,True,2
B_ECOGCD,True,True,False,2
PDICMIS,True,False,False,1
PDYN,True,False,False,1
PRBEVCDR,False,True,False,1
PRBEVCDM,False,True,False,1
PRBEVCD,False,True,False,1
PRBEV,False,True,False,1
CHEMOCD,True,False,False,1
PRADJICD,True,False,False,1
PRBEVM,False,True,False,1
PRADJI,True,False,False,1
PDPROMED,True,False,False,1
PDICSIG,True,False,False,1
PPCRITCD,False,False,True,1
PPCRIT,False,False,True,1
PFUP,False,True,False,1
EO5FUBCD,True,False,False,1
PROXALCD,False,True,False,1
PRBEVR,False,True,False,1
PROXACDM,False,True,False,1
ACHEMO,True,False,False,1
ACHEMOCD,True,False,False,1
BMETACTI,True,False,False,1
B_ECOGCT,False,False,True,1
B_LESNM,True,False,False,1
B_LESNMN,True,False,False,1
B_LESNMT,True,False,False,1
RESPSTAT,True,False,False,1
REGIONCD,False,False,True,1
REGION,False,False,True,1
RANDNO,False,True,False,1
CHEMO,True,False,False,1
PROXAR,False,True,False,1
PROXAM,False,True,False,1
PADJYNCD,False,True,False,1
PROXAL,False,True,False,1
PROXACDR,False,True,False,1
PDADEN,True,False,False,1
LCTTXDY,False,True,False,1
CHEMOI,True,False,False,1
DSRRADCD,False,True,False,1
EORCRTCD,False,True,False,1
EORCRIT,False,True,False,1
DSRRAD,False,True,False,1
EOOXIRCD,True,False,False,1
EOOXIR,True,False,False,1
EOLEUDY,True,False,False,1
EOLEUCCD,True,False,False,1
EOLEUC,True,False,False,1
EOIPPRCD,False,False,True,1
EOSDY,True,False,False,1
EOIPPR,False,False,True,1
DURSURG,True,False,False,1
EO5FBDY,True,False,False,1
EO5FIDY,True,False,False,1
EO5FUB,True,False,False,1
EOBDY,True,False,False,1
EOBCD,True,False,False,1
EOB,True,False,False,1
ACHEMMCD,True,False,False,1
EOTA,True,False,False,1
CHEMOICD,True,False,False,1
FCTTXDY,False,True,False,1
DIAGI,True,False,False,1
DIAGICD,True,False,False,1
EO5FUICD,True,False,False,1
DPADJUV,False,True,False,1
DSEOS,True,False,False,1
FSTOXDS,True,False,False,1
FSTIRDS,True,False,False,1
DSEOSCD,True,False,False,1
FCHEMOCD,True,False,False,1
EOTACD,True,False,False,1
FCHEMO,True,False,False,1
EVALQOL,False,True,False,1
DSEOSYN,True,False,False,1
EVALKUE,True,False,False,1
EVALKSA,True,False,False,1
EVALKEA,True,False,False,1
EVALCTR,False,False,True,1
EOXIRDY,True,False,False,1
ACHEMM,True,False,False,1

### `death.sas7bdat`

In [4]:
presence_matrix(DATA_DIR, 'death.sas7bdat', RAW_DOMAIN_TRIALS)

,NCT00115225_PACCE_bev_panitumumab_raw,NCT00339183_panitumumab_folfiri_raw,NCT00364013_panitumumab_folfox_raw,n_trials_present
DTCAUS,True,True,True,3
RACCATCD,True,True,True,3
B_METACT,True,True,True,3
SUBJID,True,True,True,3
STUDYID,True,True,True,3
SITEID,True,True,True,3
SEXCD,True,True,True,3
SEX,True,True,True,3
EVALPP,True,True,True,3
DIAGTYCD,True,True,True,3
DIAGTYPE,True,True,True,3
RACCAT,True,True,True,3
DTAEPT,True,True,True,3
EVALITT,True,True,True,3
DTCAUSCD,True,True,True,3
DTHDY,True,True,True,3
DTHDYI,True,True,True,3
TRT,True,True,True,3
TRTCD,True,True,True,3
TRTDOSE,True,True,True,3
B_LDHYN,True,True,True,3
PHASECD,True,True,True,3
TRTFRQCD,True,True,True,3
AGE,True,True,True,3
ATRT,True,True,True,3
ATRTCD,True,True,True,3
PHASE,True,True,True,3
BECOGICD,True,True,True,3
TRTFREQ,True,True,True,3
TRTDUR,True,True,True,3
B_ECOGI,True,True,True,3
LIVRONLY,False,True,True,2
LIVRONCD,False,True,True,2
LIVERMET,False,True,True,2
KRASCD,True,True,False,2
KRAS,True,True,False,2
EVALEGFR,False,True,True,2
TUMCATCD,False,True,True,2
B_LDHNM,False,True,True,2
B_METANM,True,True,False,2
TUMCAT,False,True,True,2
BECGICT,False,True,True,2
B_ECOG,True,True,False,2
B_ECOGCD,True,True,False,2
B_LDH2YN,False,True,True,2
DTHDYI2,False,True,True,2
PRADJYN,True,True,False,2
PROXACDR,False,True,False,1
PRBEVM,False,True,False,1
PRADJICD,True,False,False,1
REGIONCD,False,False,True,1
PRBEV,False,True,False,1
PRBEVCD,False,True,False,1
PRBEVCDM,False,True,False,1
PRBEVCDR,False,True,False,1
PRBEVR,False,True,False,1
PROXACDM,False,True,False,1
PROXAR,False,True,False,1
PROXAM,False,True,False,1
RESPSTAT,True,False,False,1
PROXALCD,False,True,False,1
PROXAL,False,True,False,1
PRECUT,False,False,True,1
REGION,False,False,True,1
ACHEMM,True,False,False,1
PRADJI,True,False,False,1
PDYN,True,False,False,1
ACHEMO,True,False,False,1
ACHEMOCD,True,False,False,1
BMETACTI,True,False,False,1
B_ECOGCT,False,False,True,1
B_LESNM,True,False,False,1
B_LESNMN,True,False,False,1
B_LESNMT,True,False,False,1
CHEMO,True,False,False,1
CHEMOCD,True,False,False,1
CHEMOI,True,False,False,1
CHEMOICD,True,False,False,1
DIAGI,True,False,False,1
DIAGICD,True,False,False,1
DPADJUV,False,True,False,1
DURSURG,True,False,False,1
EVALCTR,False,False,True,1
EVALKEA,True,False,False,1
EVALKSA,True,False,False,1
EVALKUE,True,False,False,1
EVALQOL,False,True,False,1
FCHEMO,True,False,False,1
FCHEMOCD,True,False,False,1
ACHEMMCD,True,False,False,1
FSTOXDS,True,False,False,1
PADJYNCD,False,True,False,1
PDADEN,True,False,False,1
PDICMIS,True,False,False,1
PDICSIG,True,False,False,1
PDPROMED,True,False,False,1
FSTIRDS,True,False,False,1

### `demo.sas7bdat`

In [5]:
presence_matrix(DATA_DIR, 'demo.sas7bdat', RAW_DOMAIN_TRIALS)

,NCT00115225_PACCE_bev_panitumumab_raw,NCT00339183_panitumumab_folfiri_raw,NCT00364013_panitumumab_folfox_raw,n_trials_present
SEX,True,True,True,3
B_METACT,True,True,True,3
TRTDUR,True,True,True,3
TRTDOSE,True,True,True,3
TRTCD,True,True,True,3
TRT,True,True,True,3
SUBJID,True,True,True,3
SITEID,True,True,True,3
SEXCD,True,True,True,3
B_BSA,True,True,True,3
B_ECOGI,True,True,True,3
B_HEIGHT,True,True,True,3
B_LDHYN,True,True,True,3
B_WEIGHT,True,True,True,3
TRTFRQCD,True,True,True,3
RACCATCD,True,True,True,3
RACCAT,True,True,True,3
CHILDPOT,True,True,True,3
DIAGMONS,True,True,True,3
DIAGTYCD,True,True,True,3
DIAGTYPE,True,True,True,3
PREGTYPE,True,True,True,3
EVALITT,True,True,True,3
PREGTYCD,True,True,True,3
EVALPP,True,True,True,3
PREGDY,True,True,True,3
TRTFREQ,True,True,True,3
STUDYID,True,True,True,3
BECOGICD,True,True,True,3
METMONS,True,True,True,3
AGE,True,True,True,3
ATRT,True,True,True,3
ATRTCD,True,True,True,3
BIOP3,False,True,True,2
BIOPNO,False,True,True,2
KRASCD,True,True,False,2
KRAS,True,True,False,2
BIOPCY,False,True,True,2
B_METANM,True,True,False,2
BIOPBSIT,False,True,True,2
BIOPBSCD,False,True,True,2
BIOPACPT,False,True,True,2
PRADJYN,True,True,False,2
BIOPNEG,False,True,True,2
BIONANY,False,True,True,2
B_LDH2YN,False,True,True,2
BECGICT,False,True,True,2
H11WEAK,False,True,True,2
EVALEGFR,False,True,True,2
PREGRSCD,True,True,False,2
PREGRES,True,True,False,2
PREGDONE,False,True,True,2
H11NEG,False,True,True,2
B_LDHNM,False,True,True,2
BIOPCYCD,False,True,True,2
BIOPCYTO,False,True,True,2
BIOPDY,True,False,True,2
BIOPMOD,False,True,True,2
BIOPPCCD,False,True,True,2
BIOPPCT,False,True,True,2
BIOPMAXC,False,True,True,2
BIOPMAX,False,True,True,2
TUMCAT,False,True,True,2
TUMCATCD,False,True,True,2
BIOPS123,False,True,True,2
BIOPSITE,False,True,True,2
BIOPHACT,False,True,True,2
LIVRONCD,False,True,True,2
BIOPSTCD,False,True,True,2
BIOPSTRG,False,True,True,2
BIORSNCD,False,True,True,2
BIOPWEAK,False,True,True,2
LIVERMET,False,True,True,2
B_ECOGCD,True,True,False,2
B_ECOG,True,True,False,2
LIVRONLY,False,True,True,2
BIOPEF,False,True,True,2
H11MOD,False,True,True,2
BIOPTPCT,False,True,True,2
BIOPEFCD,False,True,True,2
PRBEV,False,True,False,1
PRADJICD,True,False,False,1
PRADJI,True,False,False,1
PRBEVCDM,False,True,False,1
PDYN,True,False,False,1
PRBEVCDR,False,True,False,1
PRBEVCD,False,True,False,1
ACHEMM,True,False,False,1
PRBEVM,False,True,False,1
REGIONCD,False,False,True,1
diagdy,False,True,False,1
biopdy2,False,True,False,1
biopdy,False,True,False,1
UGT1A1YN,False,True,False,1
PDICSIG,True,False,False,1
RESPSTAT,True,False,False,1
REGION,False,False,True,1
PRBEVR,False,True,False,1
PROXAR,False,True,False,1
PROXAM,False,True,False,1
PROXALCD,False,True,False,1
PROXAL,False,True,False,1
PROXACDR,False,True,False,1
PROXACDM,False,True,False,1
PDPROMED,True,False,False,1
EVALCTR,False,False,True,1
PDICMIS,True,False,False,1
BIOPRSCD,False,True,False,1
B_LESNMT,True,False,False,1
B_LESNMN,True,False,False,1
B_LESNM,True,False,False,1
B_ECOGCT,False,False,True,1
BMETACTI,True,False,False,1
BIOPTISS,True,False,False,1
BIOPTISB,True,False,False,1
BIOPSITP,True,False,False,1
BIOPSITM,True,False,False,1
BIOPRS,False,True,False,1
CHEMOCD,True,False,False,1
BIOPPNO,False,True,False,1
BIOPPFCD,False,True,False,1
BIOPNOCD,False,False,True,1
BIOPHFCD,False,True,False,1
BIOPHF,False,True,False,1
BIOPF,False,True,False,1
BIOPDY2,False,False,True,1
ACHEMOCD,True,False,False,1
ACHEMO,True,False,False,1
CHEMO,True,False,False,1
CHEMOI,True,False,False,1
PDADEN,True,False,False,1
FCHEMOCD,True,False,False,1
PADJYNCD,False,True,False,1
HISTYPE,False,True,False,1
HISTYPCD,False,True,False,1
HISSUBTY,False,True,False,1
HISSBTCD,False,True,False,1
HDIFFER,False,True,False,1
HDIFFCD,False,True,False,1
FSTOXDS,True,False,False,1
FSTIRDS,True,False,False,1
FCHEMO,True,False,False,1
CHEMOICD,True,False,False,1
EVALQOL,False,True,False,1
EVALKUE,True,False,False,1
EVALKSA,True,False,False,1
EVALKEA,True,False,False,1
ACHEMMCD,True,False,False,1
DURSURG,True,False,False,1
DPADJUV,False,True,False,1
DIAGICD,True,False,False,1
DIAGI,True,False,False,1
metdxdy,False,True,False,1

### `ae.sas7bdat`

In [6]:
presence_matrix(DATA_DIR, 'ae.sas7bdat', RAW_DOMAIN_TRIALS)

,NCT00115225_PACCE_bev_panitumumab_raw,NCT00339183_panitumumab_folfiri_raw,NCT00364013_panitumumab_folfox_raw,n_trials_present
BECOGICD,True,True,True,3
B_LDHYN,True,True,True,3
AEENDY,True,True,True,3
PHASEND,True,True,True,3
PHASE,True,True,True,3
MEDDRA_V,True,True,True,3
AESEVCD,True,True,True,3
AEHLGT,True,True,True,3
AEHLT,True,True,True,3
EVALPP,True,True,True,3
EVALITT,True,True,True,3
DIAGTYPE,True,True,True,3
DIAGTYCD,True,True,True,3
B_METACT,True,True,True,3
AELINENO,True,True,True,3
AEDUR,True,True,True,3
AELLT,True,True,True,3
B_ECOGI,True,True,True,3
ATRTCD,True,True,True,3
ATRT,True,True,True,3
AENUMINF,True,True,True,3
AGE,True,True,True,3
AETERM,True,True,True,3
AEPT,True,True,True,3
AESTDY,True,True,True,3
AEREL,True,True,True,3
AESOC,True,True,True,3
AESER,True,True,True,3
AEDURI,True,True,True,3
AESEV,True,True,True,3
RACCAT,True,True,True,3
AEACT88,True,True,True,3
TRTFRQCD,True,True,True,3
AEACT01,True,True,True,3
AEACT02,True,True,True,3
AEACT03,True,True,True,3
AEACT04,True,True,True,3
AEACT05,True,True,True,3
AEACT06,True,True,True,3
AEACT07,True,True,True,3
TRTFREQ,True,True,True,3
TRTDUR,True,True,True,3
TRTDOSE,True,True,True,3
TRTCD,True,True,True,3
AEACT83,True,True,True,3
TRT,True,True,True,3
AEACT81,True,True,True,3
STUDYID,True,True,True,3
SITEID,True,True,True,3
AEANY,True,True,True,3
RACCATCD,True,True,True,3
SAELIFE,True,True,True,3
SEX,True,True,True,3
SEXCD,True,True,True,3
SUBJID,True,True,True,3
AEACTCDS,True,True,True,3
TUMCAT,False,True,True,2
PHASECD,False,True,True,2
AESTDYI,True,True,False,2
AESTOMA,False,True,True,2
AEVASTOX,False,True,True,2
AEWDOS,False,True,True,2
EVALEGFR,False,True,True,2
LIVRONCD,False,True,True,2
BECGICT,False,True,True,2
B_ECOG,True,True,False,2
B_ECOGCD,True,True,False,2
LIVERMET,False,True,True,2
B_LDH2YN,False,True,True,2
KRASCD,True,True,False,2
B_LDHNM,False,True,True,2
PRADJYN,True,True,False,2
KRAS,True,True,False,2
B_METANM,True,True,False,2
LIVRONLY,False,True,True,2
TUMCATCD,False,True,True,2
AERELCM,False,True,True,2
AEFBCDOS,False,True,True,2
AEINTEYE,False,True,True,2
AEINTCAT,False,True,True,2
AEINFREP,False,True,True,2
AEINFPI,False,True,True,2
AERASH,False,True,True,2
AEHEMTOX,False,True,True,2
AEFIWDOS,False,True,True,2
AEFICDOS,False,True,True,2
AEFBWDOS,False,True,True,2
AEENDYI,True,True,False,2
AEINTMT,False,True,True,2
AEDLWDOS,False,True,True,2
AEDLCDOS,False,True,True,2
AEDIARR,False,True,True,2
AECRDTOX,False,True,True,2
AECONT,True,True,False,2
AECDOS,False,True,True,2
AECALCEM,False,True,True,2
AEACT82,False,True,True,2
AEACT10,False,True,True,2
AEINTINF,False,True,True,2
AEINFCTC,False,True,True,2
AENASTER,False,True,True,2
AELLCDOS,False,True,True,2
AELLTCD,False,True,True,2
AENASTCD,False,True,True,2
AENEUTOX,False,True,True,2
AEPULTOX,False,True,True,2
AEPRIOR,False,True,True,2
AELLWDOS,False,True,True,2
AEPRCNT,True,True,False,2
AEMAGNES,False,True,True,2
AENUMCTX,False,True,True,2
PROXACDM,False,True,False,1
PROXACDR,False,True,False,1
PRBEVR,False,True,False,1
PRECUT,False,False,True,1
PROXALCD,False,True,False,1
PRBEVM,False,True,False,1
PRBEVCDR,False,True,False,1
PRBEVCDM,False,True,False,1
PRBEVCD,False,True,False,1
PRBEV,False,True,False,1
PROXAL,False,True,False,1
AEIRCDOS,False,True,False,1
PROXAM,False,True,False,1
PROXAR,False,True,False,1
PRADJICD,True,False,False,1
REGION,False,False,True,1
REGIONCD,False,False,True,1
RESPSTAT,True,False,False,1
AEOXCDOS,False,False,True,1
AECRDARR,False,False,True,1
AEOXWDOS,False,False,True,1
AEPAGENO,True,False,False,1
AEACT85,True,False,False,1
AEACT09,True,False,False,1
AEACT08,True,False,False,1
ACHEMOCD,True,False,False,1
ACHEMO,True,False,False,1
AEENDPG,True,False,False,1
ACHEMMCD,True,False,False,1
PRADJI,True,False,False,1
DPADJUV,False,True,False,1
EVALKSA,True,False,False,1
EVALKEA,True,False,False,1
B_LESNM,True,False,False,1
B_LESNMN,True,False,False,1
EVALCTR,False,False,True,1
DURSURG,True,False,False,1
B_LESNMT,True,False,False,1
PHSENDCD,False,True,False,1
AEIRWDOS,False,True,False,1
DIAGICD,True,False,False,1
DIAGI,True,False,False,1
CHEMOICD,True,False,False,1
CHEMOI,True,False,False,1
CHEMOCD,True,False,False,1
EVALKUE,True,False,False,1
AEINFYN,True,False,False,1
EVALQOL,False,True,False,1
FCHEMO,True,False,False,1
FCHEMOCD,True,False,False,1
FSTIRDS,True,False,False,1
FSTOXDS,True,False,False,1
AEISCHAE,False,False,True,1
B_ECOGCT,False,False,True,1
PADJYNCD,False,True,False,1
PDADEN,True,False,False,1
PDICMIS,True,False,False,1
PDICSIG,True,False,False,1
PDPROMED,True,False,False,1
PDYN,True,False,False,1
BMETACTI,True,False,False,1
CHEMO,True,False,False,1
ACHEMM,True,False,False,1

### `lab.sas7bdat`

In [7]:
presence_matrix(DATA_DIR, 'lab.sas7bdat', RAW_DOMAIN_TRIALS)

,NCT00115225_PACCE_bev_panitumumab_raw,NCT00339183_panitumumab_folfiri_raw,NCT00364013_panitumumab_folfox_raw,n_trials_present
VISITCD,True,True,True,3
LBSTNRHI,True,True,True,3
DIAGTYPE,True,True,True,3
DOSREFDY,True,True,True,3
LBNRIND,True,True,True,3
LBTESTCD,True,True,True,3
EVALITT,True,True,True,3
LBTEST,True,True,True,3
LBSTUNIT,True,True,True,3
LBSTRESN,True,True,True,3
EVALPP,True,True,True,3
LBSTRESC,True,True,True,3
LBSTNRLO,True,True,True,3
LBPANEL,True,True,True,3
PHASE,True,True,True,3
LBORUNIT,True,True,True,3
LBORRESN,True,True,True,3
LBORNRLO,True,True,True,3
LBORNRHI,True,True,True,3
LBBASE,True,True,True,3
LBBLRES,True,True,True,3
LBCHGBL,True,True,True,3
LBGRDDEC,True,True,True,3
LBGRDINC,True,True,True,3
LBLAST,True,True,True,3
LBMAX,True,True,True,3
DIAGTYCD,True,True,True,3
DOSREFWK,True,True,True,3
PHASECD,True,True,True,3
SUBJID,True,True,True,3
VISIT,True,True,True,3
AGE,True,True,True,3
ATRT,True,True,True,3
ATRTCD,True,True,True,3
BECOGICD,True,True,True,3
TRTFRQCD,True,True,True,3
TRTFREQ,True,True,True,3
TRTDUR,True,True,True,3
TRTDOSE,True,True,True,3
B_ECOGI,True,True,True,3
TRT,True,True,True,3
B_LDHYN,True,True,True,3
TRTCD,True,True,True,3
STUDYID,True,True,True,3
SEXCD,True,True,True,3
RACCAT,True,True,True,3
RACCATCD,True,True,True,3
SITEID,True,True,True,3
SEX,True,True,True,3
LBMIN,True,True,True,3
B_METACT,True,True,True,3
LBORRES,False,True,True,2
LBTYPE,True,True,False,2
LBPCHGBL,False,True,True,2
LBNUMINF,False,True,True,2
LIVERMET,False,True,True,2
TUMCAT,False,True,True,2
LIVRONCD,False,True,True,2
LIVRONLY,False,True,True,2
LBREPEAT,True,True,False,2
TUMCATCD,False,True,True,2
PRADJYN,True,True,False,2
LBTYPECD,True,True,False,2
LBNUMCTX,False,True,True,2
LBNRINCD,True,True,False,2
EVALEGFR,False,True,True,2
LBANLCYC,False,True,True,2
B_METANM,True,True,False,2
LBANALWK,False,True,True,2
BECGICT,False,True,True,2
KRASCD,True,True,False,2
KRAS,True,True,False,2
ENRREFDY,False,True,True,2
B_ECOG,True,True,False,2
B_ECOGCD,True,True,False,2
ENRREFWK,False,True,True,2
B_LDH2YN,False,True,True,2
B_LDHNM,False,True,True,2
CHEMOI,True,False,False,1
PROXAR,False,True,False,1
PROXAL,False,True,False,1
PROXAM,False,True,False,1
PROXALCD,False,True,False,1
REGION,False,False,True,1
PROXACDR,False,True,False,1
PROXACDM,False,True,False,1
PRBEVR,False,True,False,1
CHEMOCD,True,False,False,1
B_LESNMT,True,False,False,1
REGIONCD,False,False,True,1
RESPSTAT,True,False,False,1
CHEMO,True,False,False,1
PRBEVCDR,False,True,False,1
B_LESNMN,True,False,False,1
B_LESNM,True,False,False,1
B_ECOGCT,False,False,True,1
BMETACTI,True,False,False,1
ACHEMOCD,True,False,False,1
ACHEMO,True,False,False,1
PRBEVM,False,True,False,1
CHEMOICD,True,False,False,1
PRBEVCDM,False,True,False,1
DURSURG,True,False,False,1
LBANCMTH,False,True,False,1
LBANCMCD,False,True,False,1
LBACCNO,True,False,False,1
FSTOXDS,True,False,False,1
FSTIRDS,True,False,False,1
FCHEMOCD,True,False,False,1
FCHEMO,True,False,False,1
EVALQOL,False,True,False,1
EVALKUE,True,False,False,1
EVALKSA,True,False,False,1
EVALKEA,True,False,False,1
EVALCTR,False,False,True,1
DPADJUV,False,True,False,1
PRBEVCD,False,True,False,1
PADJYNCD,False,True,False,1
PDADEN,True,False,False,1
PDICMIS,True,False,False,1
PDICSIG,True,False,False,1
PDPROMED,True,False,False,1
PDYN,True,False,False,1
DIAGICD,True,False,False,1
DIAGI,True,False,False,1
PRADJI,True,False,False,1
PRADJICD,True,False,False,1
ACHEMMCD,True,False,False,1
PRBEV,False,True,False,1
ACHEMM,True,False,False,1

### `medhist.sas7bdat`

In [8]:
presence_matrix(DATA_DIR, 'medhist.sas7bdat', RAW_DOMAIN_TRIALS)

,NCT00115225_PACCE_bev_panitumumab_raw,NCT00339183_panitumumab_folfiri_raw,NCT00364013_panitumumab_folfox_raw,n_trials_present
MHANY,True,True,True,3
STUDYID,True,True,True,3
EVALPP,True,True,True,3
EVALITT,True,True,True,3
DIAGTYPE,True,True,True,3
DIAGTYCD,True,True,True,3
MHSTAT,True,True,True,3
MHSTATCD,True,True,True,3
RACCAT,True,True,True,3
B_METACT,True,True,True,3
SEX,True,True,True,3
SEXCD,True,True,True,3
SITEID,True,True,True,3
B_LDHYN,True,True,True,3
RACCATCD,True,True,True,3
SUBJID,True,True,True,3
BECOGICD,True,True,True,3
TRTFRQCD,True,True,True,3
B_ECOGI,True,True,True,3
ATRT,True,True,True,3
ATRTCD,True,True,True,3
TRTFREQ,True,True,True,3
AGE,True,True,True,3
TRT,True,True,True,3
TRTDUR,True,True,True,3
TRTDOSE,True,True,True,3
TRTCD,True,True,True,3
PRADJYN,True,True,False,2
LIVERMET,False,True,True,2
LIVRONCD,False,True,True,2
TUMCAT,False,True,True,2
LIVRONLY,False,True,True,2
MHBNGNYN,False,True,True,2
MHBODSYS,False,True,True,2
MHCOND,False,True,True,2
MHBSYSCD,False,True,True,2
MHTERM,True,True,False,2
MHCONDCD,False,True,True,2
MHSITE,False,True,True,2
MHSITECD,False,True,True,2
KRAS,True,True,False,2
MHSTDY,False,True,True,2
KRASCD,True,True,False,2
TUMCATCD,False,True,True,2
BECGICT,False,True,True,2
B_ECOG,True,True,False,2
B_ECOGCD,True,True,False,2
B_METANM,True,True,False,2
EVALEGFR,False,True,True,2
B_LDH2YN,False,True,True,2
B_LDHNM,False,True,True,2
FSTOXDS,True,False,False,1
PROXAL,False,True,False,1
PROXAR,False,True,False,1
PROXAM,False,True,False,1
PROXALCD,False,True,False,1
PROXACDR,False,True,False,1
PROXACDM,False,True,False,1
PRBEVR,False,True,False,1
PRBEVM,False,True,False,1
CHEMO,True,False,False,1
B_LESNMT,True,False,False,1
REGION,False,False,True,1
REGIONCD,False,False,True,1
RESPSTAT,True,False,False,1
PRBEVCDM,False,True,False,1
B_LESNMN,True,False,False,1
B_LESNM,True,False,False,1
B_ECOGCT,False,False,True,1
BMETACTI,True,False,False,1
ACHEMOCD,True,False,False,1
ACHEMO,True,False,False,1
PRBEVCDR,False,True,False,1
PRBEVCD,False,True,False,1
FSTIRDS,True,False,False,1
DIAGICD,True,False,False,1
FCHEMOCD,True,False,False,1
FCHEMO,True,False,False,1
EVALQOL,False,True,False,1
EVALKUE,True,False,False,1
ACHEMMCD,True,False,False,1
EVALKSA,True,False,False,1
EVALKEA,True,False,False,1
EVALCTR,False,False,True,1
DURSURG,True,False,False,1
DPADJUV,False,True,False,1
DOSREFDY,True,False,False,1
DIAGI,True,False,False,1
PRBEV,False,True,False,1
CHEMOICD,True,False,False,1
CHEMOI,True,False,False,1
PADJYNCD,False,True,False,1
PDADEN,True,False,False,1
PDICMIS,True,False,False,1
PDICSIG,True,False,False,1
PDPROMED,True,False,False,1
PDYN,True,False,False,1
PRADJI,True,False,False,1
PRADJICD,True,False,False,1
CHEMOCD,True,False,False,1
ACHEMM,True,False,False,1

### `chemotx.sas7bdat`

In [9]:
presence_matrix(DATA_DIR, 'chemotx.sas7bdat', RAW_DOMAIN_TRIALS)

,NCT00115225_PACCE_bev_panitumumab_raw,NCT00339183_panitumumab_folfiri_raw,NCT00364013_panitumumab_folfox_raw,n_trials_present
TRTCD,True,True,True,3
SITEID,True,True,True,3
TRT,True,True,True,3
B_METACT,True,True,True,3
PHASECD,True,True,True,3
EVALPP,True,True,True,3
SUBJID,True,True,True,3
STUDYID,True,True,True,3
SEXCD,True,True,True,3
TRTDOSE,True,True,True,3
SEX,True,True,True,3
EVALITT,True,True,True,3
CHENDY,True,True,True,3
DIAGTYPE,True,True,True,3
DIAGTYCD,True,True,True,3
RACCATCD,True,True,True,3
CHSTDY,True,True,True,3
RACCAT,True,True,True,3
B_LDHYN,True,True,True,3
B_ECOGI,True,True,True,3
TRTDUR,True,True,True,3
TRTFRQCD,True,True,True,3
TRTFREQ,True,True,True,3
BECOGICD,True,True,True,3
PHASE,True,True,True,3
AGE,True,True,True,3
ATRTCD,True,True,True,3
ATRT,True,True,True,3
EVALEGFR,False,True,True,2
LIVRONLY,False,True,True,2
CHTERM,False,True,True,2
LIVRONCD,False,True,True,2
PRADJYN,True,True,False,2
LIVERMET,False,True,True,2
KRASCD,True,True,False,2
KRAS,True,True,False,2
TUMCATCD,False,True,True,2
CHPDDY,False,True,True,2
TUMCAT,False,True,True,2
BECGICT,False,True,True,2
B_ECOG,True,True,False,2
B_ECOGCD,True,True,False,2
B_LDH2YN,False,True,True,2
CHLINECD,False,True,True,2
B_LDHNM,False,True,True,2
B_METANM,True,True,False,2
CHLINE,False,True,True,2
CHANY,False,True,True,2
PROXAM,False,True,False,1
RESPSTAT,True,False,False,1
PDPROMED,True,False,False,1
PDYN,True,False,False,1
PRADJI,True,False,False,1
PRADJICD,True,False,False,1
PRBEVCD,False,True,False,1
PRBEV,False,True,False,1
PROXALCD,False,True,False,1
REGIONCD,False,False,True,1
PRBEVCDM,False,True,False,1
PRBEVCDR,False,True,False,1
PRBEVM,False,True,False,1
REGION,False,False,True,1
PRBEVR,False,True,False,1
PROXACDM,False,True,False,1
PDICMIS,True,False,False,1
PROXAR,False,True,False,1
PROXACDR,False,True,False,1
PROXAL,False,True,False,1
PDICSIG,True,False,False,1
ACHEMM,True,False,False,1
PDADEN,True,False,False,1
CHDREAS,False,True,False,1
CHPREF,False,True,False,1
CHMETA,False,True,False,1
CHEMOICD,True,False,False,1
CHEMOI,True,False,False,1
CHEMOCD,True,False,False,1
CHEMO,True,False,False,1
CHDRSNCD,False,True,False,1
CHANY5YR,True,False,False,1
PADJYNCD,False,True,False,1
B_LESNMT,True,False,False,1
B_LESNMN,True,False,False,1
B_LESNM,True,False,False,1
B_ECOGCT,False,False,True,1
BMETACTI,True,False,False,1
ACHEMOCD,True,False,False,1
ACHEMO,True,False,False,1
CHREG,True,False,False,1
CHREGCLS,True,False,False,1
CHREGPT,True,False,False,1
CHRESP,False,True,False,1
FSTOXDS,True,False,False,1
FSTIRDS,True,False,False,1
FCHEMOCD,True,False,False,1
FCHEMO,True,False,False,1
EVALQOL,False,True,False,1
EVALKUE,True,False,False,1
ACHEMMCD,True,False,False,1
EVALKEA,True,False,False,1
EVALCTR,False,False,True,1
DURSURG,True,False,False,1
DPADJUV,False,True,False,1
DIAGICD,True,False,False,1
DIAGI,True,False,False,1
CHSTDTV,False,True,False,1
CHRESPCD,False,True,False,1
EVALKSA,True,False,False,1

### `radiotx.sas7bdat`

In [10]:
presence_matrix(DATA_DIR, 'radiotx.sas7bdat', RAW_DOMAIN_TRIALS)

,NCT00115225_PACCE_bev_panitumumab_raw,NCT00339183_panitumumab_folfiri_raw,NCT00364013_panitumumab_folfox_raw,n_trials_present
VISITCD,True,True,True,3
TRTDOSE,True,True,True,3
TRTCD,True,True,True,3
TRT,True,True,True,3
SUBJID,True,True,True,3
STUDYID,True,True,True,3
SITEID,True,True,True,3
PHASE,True,True,True,3
DIAGTYCD,True,True,True,3
DIAGTYPE,True,True,True,3
SEX,True,True,True,3
EVALITT,True,True,True,3
RASTDY,True,True,True,3
EVALPP,True,True,True,3
RAENDY,True,True,True,3
RACCATCD,True,True,True,3
RACCAT,True,True,True,3
B_METACT,True,True,True,3
SEXCD,True,True,True,3
TRTDUR,True,True,True,3
TRTFRQCD,True,True,True,3
VISIT,True,True,True,3
AGE,True,True,True,3
ATRT,True,True,True,3
TRTFREQ,True,True,True,3
BECOGICD,True,True,True,3
ATRTCD,True,True,True,3
PHASECD,True,True,True,3
B_ECOGI,True,True,True,3
B_LDHYN,True,True,True,3
B_ECOG,True,True,False,2
RAANY,False,True,True,2
B_METANM,True,True,False,2
TUMCATCD,False,True,True,2
RADPAREA,False,True,True,2
LIVRONLY,False,True,True,2
LIVRONCD,False,True,True,2
LIVERMET,False,True,True,2
KRASCD,True,True,False,2
KRAS,True,True,False,2
RAINT,False,True,True,2
B_ECOGCD,True,True,False,2
PRADJYN,True,True,False,2
B_LDHNM,False,True,True,2
B_LDH2YN,False,True,True,2
RASTDYE,False,True,True,2
BECGICT,False,True,True,2
EVALEGFR,False,True,True,2
TUMCAT,False,True,True,2
RAINTCD,False,True,True,2
PROXAM,False,True,False,1
PROXALCD,False,True,False,1
PROXAR,False,True,False,1
PROXAL,False,True,False,1
PROXACDR,False,True,False,1
REGIONCD,False,False,True,1
RAANY5YR,True,False,False,1
RAAREA,False,False,True,1
RADOSE,True,False,False,1
RASITE,False,True,False,1
RASITECD,False,True,False,1
REGION,False,False,True,1
PRBEVR,False,True,False,1
RESPSTAT,True,False,False,1
PROXACDM,False,True,False,1
ACHEMM,True,False,False,1
PRBEVM,False,True,False,1
CHEMOCD,True,False,False,1
EVALCTR,False,False,True,1
DURSURG,True,False,False,1
DPADJUV,False,True,False,1
DIAGICD,True,False,False,1
DIAGI,True,False,False,1
CHEMOICD,True,False,False,1
CHEMOI,True,False,False,1
CHEMO,True,False,False,1
PRBEVCDR,False,True,False,1
B_LESNMT,True,False,False,1
B_LESNMN,True,False,False,1
B_LESNM,True,False,False,1
B_ECOGCT,False,False,True,1
BMETACTI,True,False,False,1
ACHEMOCD,True,False,False,1
ACHEMO,True,False,False,1
EVALKEA,True,False,False,1
EVALKSA,True,False,False,1
EVALKUE,True,False,False,1
EVALQOL,False,True,False,1
PRBEVCDM,False,True,False,1
PRBEVCD,False,True,False,1
PRBEV,False,True,False,1
PRADJICD,True,False,False,1
PRADJI,True,False,False,1
PDYN,True,False,False,1
PDPROMED,True,False,False,1
ACHEMMCD,True,False,False,1
PDICMIS,True,False,False,1
PDADEN,True,False,False,1
PADJYNCD,False,True,False,1
FSTOXDS,True,False,False,1
FSTIRDS,True,False,False,1
FCHEMOCD,True,False,False,1
FCHEMO,True,False,False,1
PDICSIG,True,False,False,1

### `surghist.sas7bdat`

In [11]:
presence_matrix(DATA_DIR, 'surghist.sas7bdat', RAW_DOMAIN_TRIALS)

,NCT00115225_PACCE_bev_panitumumab_raw,NCT00339183_panitumumab_folfiri_raw,NCT00364013_panitumumab_folfox_raw,n_trials_present
TRT,True,True,True,3
TRTDOSE,True,True,True,3
DOSREFWK,True,True,True,3
DOSREFDY,True,True,True,3
DIAGTYPE,True,True,True,3
DIAGTYCD,True,True,True,3
SUBJID,True,True,True,3
SXSITECD,True,True,True,3
EVALITT,True,True,True,3
SXTYPE,True,True,True,3
SXTYPECD,True,True,True,3
STUDYID,True,True,True,3
B_METACT,True,True,True,3
EVALPP,True,True,True,3
TRTCD,True,True,True,3
B_LDHYN,True,True,True,3
BECOGICD,True,True,True,3
SITEID,True,True,True,3
TRTFRQCD,True,True,True,3
AGE,True,True,True,3
ATRT,True,True,True,3
ATRTCD,True,True,True,3
RACCAT,True,True,True,3
SXSITE,True,True,True,3
TRTFREQ,True,True,True,3
RACCATCD,True,True,True,3
SEX,True,True,True,3
TRTDUR,True,True,True,3
B_ECOGI,True,True,True,3
SEXCD,True,True,True,3
KRAS,True,True,False,2
SXANY,False,True,True,2
KRASCD,True,True,False,2
TUMCATCD,False,True,True,2
LIVERMET,False,True,True,2
LIVRONCD,False,True,True,2
LIVRONLY,False,True,True,2
PRADJYN,True,True,False,2
SXINT,False,True,True,2
SXSITCD3,False,True,True,2
SXINTCD,False,True,True,2
SXSITE3,False,True,True,2
TUMCAT,False,True,True,2
BECGICT,False,True,True,2
B_ECOG,True,True,False,2
B_ECOGCD,True,True,False,2
B_LDHNM,False,True,True,2
B_METANM,True,True,False,2
B_LDH2YN,False,True,True,2
SXSITE2,False,True,True,2
SXSITCD2,False,True,True,2
EVALEGFR,False,True,True,2
SXANY5YR,True,False,False,1
PROXACDR,False,True,False,1
PROXAL,False,True,False,1
PROXALCD,False,True,False,1
PROXAM,False,True,False,1
SXHEALYN,True,False,False,1
PROXAR,False,True,False,1
SXINTTCD,True,False,False,1
SXTYPDTL,True,False,False,1
REGION,False,False,True,1
REGIONCD,False,False,True,1
RESPSTAT,True,False,False,1
SXINTENT,True,False,False,1
PRBEVR,False,True,False,1
PROXACDM,False,True,False,1
ACHEMM,True,False,False,1
PRBEVM,False,True,False,1
PRBEVCDR,False,True,False,1
EVALKEA,True,False,False,1
EVALCTR,False,False,True,1
DURSURG,True,False,False,1
DPADJUV,False,True,False,1
DIAGICD,True,False,False,1
DIAGI,True,False,False,1
CHEMOICD,True,False,False,1
CHEMOI,True,False,False,1
CHEMOCD,True,False,False,1
CHEMO,True,False,False,1
B_LESNMT,True,False,False,1
B_LESNMN,True,False,False,1
B_LESNM,True,False,False,1
B_ECOGCT,False,False,True,1
BMETACTI,True,False,False,1
ACHEMOCD,True,False,False,1
ACHEMO,True,False,False,1
EVALKSA,True,False,False,1
EVALKUE,True,False,False,1
EVALQOL,False,True,False,1
PDYN,True,False,False,1
PRBEVCDM,False,True,False,1
PRBEVCD,False,True,False,1
PRBEV,False,True,False,1
PRADJICD,True,False,False,1
PRADJI,True,False,False,1
PHASECD,True,False,False,1
PHASE,True,False,False,1
PDPROMED,True,False,False,1
FCHEMO,True,False,False,1
ACHEMMCD,True,False,False,1
PDICMIS,True,False,False,1
PDADEN,True,False,False,1
PADJYNCD,False,True,False,1
FSTOXDS,True,False,False,1
FSTIRDS,True,False,False,1
FCHEMOCD,True,False,False,1
PDICSIG,True,False,False,1

### `eligcrit.sas7bdat`

In [12]:
presence_matrix(DATA_DIR, 'eligcrit.sas7bdat', RAW_DOMAIN_TRIALS)

,NCT00115225_PACCE_bev_panitumumab_raw,NCT00339183_panitumumab_folfiri_raw,NCT00364013_panitumumab_folfox_raw,n_trials_present
DIAGTYPE,True,True,True,3
TRTDOSE,True,True,True,3
ELIGNMCD,True,True,True,3
RACCATCD,True,True,True,3
DIAGTYCD,True,True,True,3
EVALITT,True,True,True,3
SEX,True,True,True,3
SEXCD,True,True,True,3
SITEID,True,True,True,3
STUDYID,True,True,True,3
SUBJID,True,True,True,3
RACCAT,True,True,True,3
B_METACT,True,True,True,3
TRT,True,True,True,3
TRTCD,True,True,True,3
B_LDHYN,True,True,True,3
BECOGICD,True,True,True,3
TRTFREQ,True,True,True,3
TRTFRQCD,True,True,True,3
AGE,True,True,True,3
ATRT,True,True,True,3
ATRTCD,True,True,True,3
EVALPP,True,True,True,3
ELIGIBLE,True,True,True,3
TRTDUR,True,True,True,3
B_ECOGI,True,True,True,3
LIVERMET,False,True,True,2
LIVRONCD,False,True,True,2
KRASCD,True,True,False,2
EVALEGFR,False,True,True,2
KRAS,True,True,False,2
LIVRONLY,False,True,True,2
ELIGNM,True,False,True,2
TUMCATCD,False,True,True,2
PRADJYN,True,True,False,2
B_LDH2YN,False,True,True,2
B_METANM,True,True,False,2
B_LDHNM,False,True,True,2
TUMCAT,False,True,True,2
BECGICT,False,True,True,2
B_ECOG,True,True,False,2
B_ECOGCD,True,True,False,2
PRBEV,False,True,False,1
PRBEVCD,False,True,False,1
PRBEVCDM,False,True,False,1
PRBEVCDR,False,True,False,1
PRBEVM,False,True,False,1
REGION,False,False,True,1
REGIONCD,False,False,True,1
PROXACDM,False,True,False,1
PROXACDR,False,True,False,1
PROXAL,False,True,False,1
PROXALCD,False,True,False,1
PROXAM,False,True,False,1
PROXAR,False,True,False,1
RESPSTAT,True,False,False,1
PRADJICD,True,False,False,1
PRBEVR,False,True,False,1
ACHEMM,True,False,False,1
PRADJI,True,False,False,1
PDYN,True,False,False,1
ACHEMO,True,False,False,1
ACHEMOCD,True,False,False,1
BMETACTI,True,False,False,1
B_ECOGCT,False,False,True,1
B_LESNM,True,False,False,1
B_LESNMN,True,False,False,1
B_LESNMT,True,False,False,1
CHEMO,True,False,False,1
CHEMOCD,True,False,False,1
CHEMOI,True,False,False,1
CHEMOICD,True,False,False,1
DIAGI,True,False,False,1
DIAGICD,True,False,False,1
DPADJUV,False,True,False,1
DURSURG,True,False,False,1
EVALCTR,False,False,True,1
EVALKEA,True,False,False,1
EVALKSA,True,False,False,1
EVALKUE,True,False,False,1
EVALQOL,False,True,False,1
FCHEMO,True,False,False,1
FCHEMOCD,True,False,False,1
ACHEMMCD,True,False,False,1
FSTOXDS,True,False,False,1
PADJYNCD,False,True,False,1
PDADEN,True,False,False,1
PDICMIS,True,False,False,1
PDICSIG,True,False,False,1
PDPROMED,True,False,False,1
FSTIRDS,True,False,False,1

### `corevar.sas7bdat`

In [13]:
presence_matrix(DATA_DIR, 'corevar.sas7bdat', RAW_DOMAIN_TRIALS)

,NCT00115225_PACCE_bev_panitumumab_raw,NCT00339183_panitumumab_folfiri_raw,NCT00364013_panitumumab_folfox_raw,n_trials_present
B_LDHYN,True,True,True,3
B_ECOGI,True,True,True,3
EVALPP,True,True,True,3
DIAGTYPE,True,True,True,3
DIAGTYCD,True,True,True,3
RACCAT,True,True,True,3
RACCATCD,True,True,True,3
B_METACT,True,True,True,3
SEX,True,True,True,3
SEXCD,True,True,True,3
SITEID,True,True,True,3
STUDYID,True,True,True,3
SUBJID,True,True,True,3
EVALITT,True,True,True,3
TRT,True,True,True,3
TRTDOSE,True,True,True,3
TRTDUR,True,True,True,3
BECOGICD,True,True,True,3
TRTFREQ,True,True,True,3
ATRTCD,True,True,True,3
ATRT,True,True,True,3
TRTCD,True,True,True,3
TRTFRQCD,True,True,True,3
AGE,True,True,True,3
KRASCD,True,True,False,2
TUMCAT,False,True,True,2
PRADJYN,True,True,False,2
LIVERMET,False,True,True,2
LIVRONCD,False,True,True,2
LIVRONLY,False,True,True,2
EVALEGFR,False,True,True,2
KRAS,True,True,False,2
TUMCATCD,False,True,True,2
BECGICT,False,True,True,2
B_ECOG,True,True,False,2
B_ECOGCD,True,True,False,2
B_LDH2YN,False,True,True,2
B_LDHNM,False,True,True,2
B_METANM,True,True,False,2
EVALCTR,False,False,True,1
REGION,False,False,True,1
PRBEVR,False,True,False,1
PROXACDM,False,True,False,1
PROXACDR,False,True,False,1
PROXAL,False,True,False,1
PROXALCD,False,True,False,1
PROXAM,False,True,False,1
PROXAR,False,True,False,1
CHEMO,True,False,False,1
B_LESNMT,True,False,False,1
REGIONCD,False,False,True,1
RESPSTAT,True,False,False,1
PRBEVCDR,False,True,False,1
B_LESNMN,True,False,False,1
B_LESNM,True,False,False,1
B_ECOGCT,False,False,True,1
BMETACTI,True,False,False,1
ACHEMOCD,True,False,False,1
ACHEMO,True,False,False,1
PRBEVM,False,True,False,1
PRBEVCDM,False,True,False,1
DURSURG,True,False,False,1
DIAGI,True,False,False,1
EVALKEA,True,False,False,1
EVALKSA,True,False,False,1
EVALKUE,True,False,False,1
DPADJUV,False,True,False,1
EVALQOL,False,True,False,1
FCHEMO,True,False,False,1
FCHEMOCD,True,False,False,1
FSTIRDS,True,False,False,1
FSTOXDS,True,False,False,1
ACHEMMCD,True,False,False,1
DIAGICD,True,False,False,1
CHEMOICD,True,False,False,1
PRBEVCD,False,True,False,1
CHEMOI,True,False,False,1
PADJYNCD,False,True,False,1
PDADEN,True,False,False,1
PDICMIS,True,False,False,1
PDICSIG,True,False,False,1
PDPROMED,True,False,False,1
PDYN,True,False,False,1
PRADJI,True,False,False,1
PRADJICD,True,False,False,1
CHEMOCD,True,False,False,1
PRBEV,False,True,False,1
ACHEMM,True,False,False,1

### `respeval.sas7bdat`

In [14]:
presence_matrix(DATA_DIR, 'respeval.sas7bdat', RAW_DOMAIN_TRIALS)

,NCT00115225_PACCE_bev_panitumumab_raw,NCT00339183_panitumumab_folfiri_raw,NCT00364013_panitumumab_folfox_raw,n_trials_present
VISITCD,True,True,True,3
RSTYPE,True,True,True,3
STUDYID,True,True,True,3
SITEID,True,True,True,3
SEXCD,True,True,True,3
DIAGTYCD,True,True,True,3
DIAGTYPE,True,True,True,3
DOSREFDY,True,True,True,3
DOSREFWK,True,True,True,3
SEX,True,True,True,3
RSTYPECD,True,True,True,3
EVALITT,True,True,True,3
TRT,True,True,True,3
RSTRSPCD,True,True,True,3
RSRESP,True,True,True,3
RSNTRESP,True,True,True,3
RSCRITCD,True,True,True,3
RSCRIT,True,True,True,3
RSBRCD,True,True,True,3
RACCAT,True,True,True,3
RACCATCD,True,True,True,3
RSBR,True,True,True,3
SUBJID,True,True,True,3
EVALPP,True,True,True,3
TRTCD,True,True,True,3
VISIT,True,True,True,3
BECOGICD,True,True,True,3
ATRTCD,True,True,True,3
TRTFRQCD,True,True,True,3
AGE,True,True,True,3
B_ECOGI,True,True,True,3
ATRT,True,True,True,3
TRTFREQ,True,True,True,3
TRTDUR,True,True,True,3
B_METACT,True,True,True,3
B_LDHYN,True,True,True,3
TRTDOSE,True,True,True,3
RSBORDY,True,False,True,2
RSITRESP,False,True,True,2
RSNTRSCD,False,True,True,2
PRADJYN,True,True,False,2
RSNEW,False,True,True,2
RSITRSCD,False,True,True,2
RSCRCD,False,True,True,2
BECGICT,False,True,True,2
RSCR,False,True,True,2
RSCONFYN,False,True,True,2
RSBRDY,True,False,True,2
LIVRONLY,False,True,True,2
TUMCATCD,False,True,True,2
B_METANM,True,True,False,2
RSBOR,True,False,True,2
LIVRONCD,False,True,True,2
B_ECOG,True,True,False,2
RSRSPDCD,False,True,True,2
RSBORCD,True,False,True,2
RSRSPD,False,True,True,2
B_ECOGCD,True,True,False,2
RSRESPDY,True,False,True,2
RSRESPCD,True,True,False,2
TUMCAT,False,True,True,2
EVALEGFR,False,True,True,2
KRAS,True,True,False,2
KRASCD,True,True,False,2
ENRREFWK,False,True,True,2
ENRREFDY,False,True,True,2
B_LDH2YN,False,True,True,2
B_LDHNM,False,True,True,2
LIVERMET,False,True,True,2
RSTRESP,False,True,True,2
RSCOMPLT,True,False,False,1
RSBORDTC,False,False,True,1
RSBORDT,False,False,True,1
RSINRESP,False,False,True,1
RSPORT2,False,False,True,1
RSINRSCD,False,False,True,1
RSPORT3,False,False,True,1
RSP1EDY,False,False,True,1
RSP1SDY,False,False,True,1
RSP2EDY,False,False,True,1
RSP2SDY,False,False,True,1
RSP3EDY,False,False,True,1
RSP3SDY,False,False,True,1
RSPORT1,False,False,True,1
ACHEMM,True,False,False,1
RSASMDT,True,False,False,1
RESPSTAT,True,False,False,1
FSTIRDS,True,False,False,1
FCHEMOCD,True,False,False,1
FCHEMO,True,False,False,1
EVALQOL,False,True,False,1
EVALKUE,True,False,False,1
EVALKSA,True,False,False,1
EVALKEA,True,False,False,1
EVALCTR,False,False,True,1
DURSURG,True,False,False,1
DPADJUV,False,True,False,1
DIAGICD,True,False,False,1
DIAGI,True,False,False,1
CHEMOICD,True,False,False,1
CHEMOI,True,False,False,1
CHEMOCD,True,False,False,1
CHEMO,True,False,False,1
B_LESNMT,True,False,False,1
B_LESNMN,True,False,False,1
B_LESNM,True,False,False,1
B_ECOGCT,False,False,True,1
BMETACTI,True,False,False,1
ACHEMOCD,True,False,False,1
ACHEMO,True,False,False,1
FSTOXDS,True,False,False,1
PADJYNCD,False,True,False,1
PDADEN,True,False,False,1
ACHEMMCD,True,False,False,1
REGIONCD,False,False,True,1
REGION,False,False,True,1
PROXAR,False,True,False,1
PROXAM,False,True,False,1
PROXALCD,False,True,False,1
PROXAL,False,True,False,1
PROXACDR,False,True,False,1
PROXACDM,False,True,False,1
PROGDY,False,False,True,1
PRBEVR,False,True,False,1
PRBEVCDR,False,True,False,1
PDICMIS,True,False,False,1
PRBEVCDM,False,True,False,1
PRBEVCD,False,True,False,1
PRBEV,False,True,False,1
PRADJICD,True,False,False,1
PRADJI,True,False,False,1
PHASECD,False,True,False,1
PHASE,False,True,False,1
PDYN,True,False,False,1
PDPROMED,True,False,False,1
PDICSIG,True,False,False,1
PRBEVM,False,True,False,1

### `lesion.sas7bdat`

In [15]:
presence_matrix(DATA_DIR, 'lesion.sas7bdat', RAW_DOMAIN_TRIALS)

,NCT00115225_PACCE_bev_panitumumab_raw,NCT00339183_panitumumab_folfiri_raw,NCT00364013_panitumumab_folfox_raw,n_trials_present
VISITCD,True,True,True,3
DOSREFDY,True,True,True,3
SEX,True,True,True,3
EVALITT,True,True,True,3
RACCATCD,True,True,True,3
RACCAT,True,True,True,3
EVALPP,True,True,True,3
LSCAT,True,True,True,3
LSCATCD,True,True,True,3
LSEXAMNO,True,True,True,3
LSLD,True,True,True,3
LSNEW,True,True,True,3
LSNEWANY,True,True,True,3
LSNO,True,True,True,3
LSPROC,True,True,True,3
LSPROCCD,True,True,True,3
LSRAW,True,True,True,3
LSRAWCD,True,True,True,3
LSRESP,True,True,True,3
LSRESPCD,True,True,True,3
LSRI,True,True,True,3
LSSITE,True,True,True,3
LSSITECD,True,True,True,3
LSSLD,True,True,True,3
LSSLDPCH,True,True,True,3
LSSLDPCN,True,True,True,3
LSTYPE,True,True,True,3
LSTYPECD,True,True,True,3
PHASE,True,True,True,3
DOSREFWK,True,True,True,3
PHASECD,True,True,True,3
DIAGTYPE,True,True,True,3
TRT,True,True,True,3
VISIT,True,True,True,3
AGE,True,True,True,3
ATRT,True,True,True,3
ATRTCD,True,True,True,3
BECOGICD,True,True,True,3
TRTFRQCD,True,True,True,3
B_ECOGI,True,True,True,3
B_LDHYN,True,True,True,3
TRTFREQ,True,True,True,3
DIAGTYCD,True,True,True,3
TRTDOSE,True,True,True,3
B_METACT,True,True,True,3
TRTCD,True,True,True,3
TRTDUR,True,True,True,3
SEXCD,True,True,True,3
SITEID,True,True,True,3
SUBJID,True,True,True,3
STUDYID,True,True,True,3
LSPROGNY,False,True,True,2
LSPERFNY,False,True,True,2
BECGICT,False,True,True,2
EVALEGFR,False,True,True,2
TUMCAT,False,True,True,2
B_ECOG,True,True,False,2
B_ECOGCD,True,True,False,2
TUMCATCD,False,True,True,2
B_LDH2YN,False,True,True,2
KRAS,True,True,False,2
B_LDHNM,False,True,True,2
LSPIRRNY,False,True,True,2
ENRREFDY,False,True,True,2
ENRREFWK,False,True,True,2
B_METANM,True,True,False,2
PRADJYN,True,True,False,2
LSANY,False,True,True,2
LIVRONLY,False,True,True,2
LIVRONCD,False,True,True,2
LIVERMET,False,True,True,2
KRASCD,True,True,False,2
PRBEVM,False,True,False,1
PRBEVCDM,False,True,False,1
PRBEVCD,False,True,False,1
PRBEV,False,True,False,1
RESPSTAT,True,False,False,1
PRBEVCDR,False,True,False,1
PROXACDR,False,True,False,1
REGIONCD,False,False,True,1
REGION,False,False,True,1
PRBEVR,False,True,False,1
PRECUT,False,False,True,1
PROXAR,False,True,False,1
PRADJICD,True,False,False,1
PROXACDM,False,True,False,1
PROXALCD,False,True,False,1
PROXAL,False,True,False,1
PROXAM,False,True,False,1
ACHEMM,True,False,False,1
PRADJI,True,False,False,1
CHEMO,True,False,False,1
DPADJUV,False,True,False,1
DIAGICD,True,False,False,1
DIAGI,True,False,False,1
CHEMOICD,True,False,False,1
CHEMOI,True,False,False,1
CHEMOCD,True,False,False,1
B_LESNMT,True,False,False,1
EVALCTR,False,False,True,1
B_LESNMN,True,False,False,1
B_LESNM,True,False,False,1
B_ECOGCT,False,False,True,1
BMETACTI,True,False,False,1
ACHEMOCD,True,False,False,1
ACHEMO,True,False,False,1
DURSURG,True,False,False,1
EVALKEA,True,False,False,1
PDYN,True,False,False,1
ACHEMMCD,True,False,False,1
PDPROMED,True,False,False,1
PDICSIG,True,False,False,1
PDICMIS,True,False,False,1
PDADEN,True,False,False,1
PADJYNCD,False,True,False,1
LSNUM,True,False,False,1
LSIMAGNO,True,False,False,1
EVALKSA,True,False,False,1
FSTOXDS,True,False,False,1
FSTIRDS,True,False,False,1
FCHEMOCD,True,False,False,1
FCHEMO,True,False,False,1
EVALQOL,False,True,False,1
EVALKUE,True,False,False,1
LSNONMYN,False,False,True,1

### `exposure.sas7bdat`

In [16]:
presence_matrix(DATA_DIR, 'exposure.sas7bdat', RAW_DOMAIN_TRIALS)

,NCT00115225_PACCE_bev_panitumumab_raw,NCT00339183_panitumumab_folfiri_raw,NCT00364013_panitumumab_folfox_raw,n_trials_present
WDOSUNIT,True,True,True,3
TRTDUR,True,True,True,3
TRTCD,True,True,True,3
CONC,True,True,True,3
RACCAT,True,True,True,3
TRT,True,True,True,3
SUBJID,True,True,True,3
DIAGTYCD,True,True,True,3
DIAGTYPE,True,True,True,3
STUDYID,True,True,True,3
DOSE,True,True,True,3
DOSEUNCD,True,True,True,3
DOSEUNIT,True,True,True,3
SITEID,True,True,True,3
SEXCD,True,True,True,3
DOSREFDY,True,True,True,3
DOSREFWK,True,True,True,3
SEX,True,True,True,3
EXDURMN,True,True,True,3
ROUTECD,True,True,True,3
QTY,True,True,True,3
ROUTE,True,True,True,3
EVALITT,True,True,True,3
EXCYCLNM,True,True,True,3
EVALPP,True,True,True,3
TRTDOSE,True,True,True,3
RACCATCD,True,True,True,3
TRTFREQ,True,True,True,3
B_ECOGI,True,True,True,3
VISITCD,True,True,True,3
BSADOSE,True,True,True,3
ATRTCD,True,True,True,3
ATRT,True,True,True,3
AGE,True,True,True,3
VISIT,True,True,True,3
ACTTRTCD,True,True,True,3
BECOGICD,True,True,True,3
ACTTRT,True,True,True,3
WDOSE,True,True,True,3
B_LDHYN,True,True,True,3
WDOSUNCD,True,True,True,3
TRTFRQCD,True,True,True,3
B_METACT,True,True,True,3
PHASECD,True,True,False,2
QTYUNCD,False,True,True,2
QTYUNIT,False,True,True,2
EXCHEMO,False,True,True,2
EXDELDY,False,True,True,2
PRADJYN,True,True,False,2
EXREASCD,True,True,False,2
EXENDY,True,True,False,2
LIVRONLY,False,True,True,2
EXINFRCT,False,True,True,2
EXINT,True,False,True,2
EXINTCD,True,False,True,2
LIVRONCD,False,True,True,2
LIVERMET,False,True,True,2
KRASCD,True,True,False,2
KRAS,True,True,False,2
EXPPRSCD,False,True,True,2
EXREAS,True,True,False,2
DRUGTP,False,True,True,2
CONCUNIT,False,True,True,2
DOSEFREQ,False,True,True,2
BECGICT,False,True,True,2
B_ECOG,True,True,False,2
B_ECOGCD,True,True,False,2
B_LDH2YN,False,True,True,2
B_LDHNM,False,True,True,2
TUMCATCD,False,True,True,2
TUMCAT,False,True,True,2
B_METANM,True,True,False,2
CONCUNCD,False,True,True,2
DOSDLAY,False,True,True,2
DOSEFRCD,False,True,True,2
PHASE,True,True,False,2
DOSINTYN,False,True,True,2
EVALEGFR,False,True,True,2
ENRREFWK,False,True,True,2
ENRREFDY,False,True,True,2
PDYN,True,False,False,1
RESPSTAT,True,False,False,1
PRADJI,True,False,False,1
PRADJICD,True,False,False,1
PROXAR,False,True,False,1
PROXAM,False,True,False,1
PROXALCD,False,True,False,1
PRBEV,False,True,False,1
PRBEVCD,False,True,False,1
PRBEVCDM,False,True,False,1
PRBEVCDR,False,True,False,1
PRBEVM,False,True,False,1
PROXAL,False,True,False,1
PROXACDR,False,True,False,1
REGIONCD,False,False,True,1
PRBEVR,False,True,False,1
PROXACDM,False,True,False,1
REGION,False,False,True,1
ACHEMM,True,False,False,1
PDPROMED,True,False,False,1
EVALKSA,True,False,False,1
EVALCTR,False,False,True,1
DURSURG,True,False,False,1
DPADJUV,False,True,False,1
DOSND,True,False,False,1
DOSNA,True,False,False,1
DOSCHGYN,True,False,False,1
DIAGICD,True,False,False,1
DIAGI,True,False,False,1
CHEMOICD,True,False,False,1
CHEMOI,True,False,False,1
CHEMOCD,True,False,False,1
CHEMO,True,False,False,1
B_LESNMT,True,False,False,1
B_LESNMN,True,False,False,1
B_LESNM,True,False,False,1
B_ECOGCT,False,False,True,1
BMETACTI,True,False,False,1
ACHEMOCD,True,False,False,1
ACHEMO,True,False,False,1
EVALKEA,True,False,False,1
EVALKUE,True,False,False,1
PDICSIG,True,False,False,1
EVALQOL,False,True,False,1
PDICMIS,True,False,False,1
PDADEN,True,False,False,1
PADJYNCD,False,True,False,1
FSTOXDS,True,False,False,1
FSTIRDS,True,False,False,1
FCHEMOCD,True,False,False,1
FCHEMO,True,False,False,1
EXREASSP,True,False,False,1
EXLOTID,False,True,False,1
EXDURHR,True,False,False,1
ACHEMMCD,True,False,False,1
EXDRSCD3,False,False,True,1
EXDRSCD2,False,False,True,1
EXDRESCD,False,False,True,1
EXDRES3,False,False,True,1
EXDRES2,False,False,True,1
EXDRES,False,False,True,1
EXCYCLDY,True,False,False,1
EXAEANY,True,False,False,1
EXDUR,True,False,False,1

### `vitals_v.sas7bdat`

In [17]:
presence_matrix(DATA_DIR, 'vitals_v.sas7bdat', RAW_DOMAIN_TRIALS)

,NCT00115225_PACCE_bev_panitumumab_raw,NCT00339183_panitumumab_folfiri_raw,NCT00364013_panitumumab_folfox_raw,n_trials_present
PHASECD,True,True,True,3
DIAGTYCD,True,True,True,3
DOSREFDY,True,True,True,3
DOSREFWK,True,True,True,3
VSMIN,True,True,True,3
VSMAX,True,True,True,3
EVALITT,True,True,True,3
VSLAST,True,True,True,3
EVALPP,True,True,True,3
VSCHGBL,True,True,True,3
VSBLRES,True,True,True,3
VSBASE,True,True,True,3
VISITCD,True,True,True,3
VISIT,True,True,True,3
TRTFRQCD,True,True,True,3
TRTFREQ,True,True,True,3
PHASE,True,True,True,3
TRTDUR,True,True,True,3
TRTDOSE,True,True,True,3
TRTCD,True,True,True,3
TRT,True,True,True,3
SUBJID,True,True,True,3
STUDYID,True,True,True,3
SITEID,True,True,True,3
SEXCD,True,True,True,3
SEX,True,True,True,3
RACCATCD,True,True,True,3
DIAGTYPE,True,True,True,3
RACCAT,True,True,True,3
VSTEST,True,True,True,3
VSSTRES,True,True,True,3
VSPTMCD,True,True,True,3
B_ECOGI,True,True,True,3
B_METACT,True,True,True,3
B_LDHYN,True,True,True,3
BECOGICD,True,True,True,3
VSPTM,True,True,True,3
ATRTCD,True,True,True,3
ATRT,True,True,True,3
AGE,True,True,True,3
VSTESTCD,True,True,True,3
VSORUNIT,True,True,True,3
VSORRES,True,True,True,3
VSSTUNIT,True,True,True,3
TUMCATCD,False,True,True,2
TUMCAT,False,True,True,2
B_LDH2YN,False,True,True,2
LIVRONLY,False,True,True,2
B_ECOGCD,True,True,False,2
B_ECOG,True,True,False,2
PRADJYN,True,True,False,2
BECGICT,False,True,True,2
B_LDHNM,False,True,True,2
EVALEGFR,False,True,True,2
VSNUMINF,False,True,True,2
VSCYCLNM,False,True,True,2
ENRREFDY,False,True,True,2
ENRREFWK,False,True,True,2
LIVRONCD,False,True,True,2
B_METANM,True,True,False,2
KRAS,True,True,False,2
KRASCD,True,True,False,2
LIVERMET,False,True,True,2
VSCHGSCR,True,False,False,1
VSSCRRES,True,False,False,1
VSDONE,True,False,False,1
VSDONECD,True,False,False,1
PROXAR,False,True,False,1
VSPCTCH,True,False,False,1
VSMAXCH,True,False,False,1
RESPSTAT,True,False,False,1
REGIONCD,False,False,True,1
REGION,False,False,True,1
VSTRT,True,False,False,1
VSMINCH,True,False,False,1
ACHEMM,True,False,False,1
PROXAM,False,True,False,1
FCHEMO,True,False,False,1
EVALKUE,True,False,False,1
EVALKSA,True,False,False,1
EVALKEA,True,False,False,1
EVALCTR,False,False,True,1
DURSURG,True,False,False,1
DPADJUV,False,True,False,1
DIAGICD,True,False,False,1
DIAGI,True,False,False,1
CHEMOICD,True,False,False,1
CHEMOI,True,False,False,1
CHEMOCD,True,False,False,1
CHEMO,True,False,False,1
B_LESNMT,True,False,False,1
B_LESNMN,True,False,False,1
B_LESNM,True,False,False,1
B_ECOGCT,False,False,True,1
BMETACTI,True,False,False,1
ACHEMOCD,True,False,False,1
ACHEMO,True,False,False,1
EVALQOL,False,True,False,1
FCHEMOCD,True,False,False,1
PROXALCD,False,True,False,1
FSTIRDS,True,False,False,1
PROXAL,False,True,False,1
PROXACDR,False,True,False,1
PROXACDM,False,True,False,1
PRBEVR,False,True,False,1
PRBEVM,False,True,False,1
PRBEVCDR,False,True,False,1
PRBEVCDM,False,True,False,1
PRBEVCD,False,True,False,1
PRBEV,False,True,False,1
PRADJICD,True,False,False,1
PRADJI,True,False,False,1
ACHEMMCD,True,False,False,1
PDYN,True,False,False,1
PDPROMED,True,False,False,1
PDICSIG,True,False,False,1
PDICMIS,True,False,False,1
PDADEN,True,False,False,1
PADJYNCD,False,True,False,1
FSTOXDS,True,False,False,1
VSTRTCD,True,False,False,1

### `a_eendpt.sas7bdat`

In [18]:
presence_matrix(DATA_DIR, 'a_eendpt.sas7bdat', RAW_DOMAIN_TRIALS)

,NCT00115225_PACCE_bev_panitumumab_raw,NCT00339183_panitumumab_folfiri_raw,NCT00364013_panitumumab_folfox_raw,n_trials_present
RDYCR,True,True,True,3
DTHDY,True,True,True,3
SEXCD,True,True,True,3
SDDURLRC,True,True,True,3
SDDURLR,True,True,True,3
SDDURCRC,True,True,True,3
DIAGTYCD,True,True,True,3
DIAGTYPE,True,True,True,3
SDDURCR,True,True,True,3
ROSLRCA,True,True,True,3
ROSLR,True,True,True,3
DTH,True,True,True,3
ROSCR,True,True,True,3
RDYLR,True,True,True,3
PDCR,True,True,True,3
RDURLRC,True,True,True,3
RDURLR,True,True,True,3
RDURCRC,True,True,True,3
RDURCR,True,True,True,3
RACCATCD,True,True,True,3
EVALITT,True,True,True,3
RACCAT,True,True,True,3
EVALPP,True,True,True,3
PFSDYCR,True,True,True,3
PFSLR,True,True,True,3
PFSDYLR,True,True,True,3
SITEID,True,True,True,3
SEX,True,True,True,3
TRTFREQ,True,True,True,3
SUBJID,True,True,True,3
ATRT,True,True,True,3
ATRTCD,True,True,True,3
AGE,True,True,True,3
BECOGICD,True,True,True,3
TRTFRQCD,True,True,True,3
TRTDUR,True,True,True,3
TRTDOSE,True,True,True,3
TRTCD,True,True,True,3
B_ECOGI,True,True,True,3
TRT,True,True,True,3
STUDYID,True,True,True,3
B_LDHYN,True,True,True,3
PDDYLR,True,True,True,3
B_METACT,True,True,True,3
PDLR,True,True,True,3
PDDYCR,True,True,True,3
PFSCR,True,True,True,3
PFSDYCEP,False,True,True,2
PFSCEB,False,True,True,2
PFSDYCRE,False,True,True,2
PFSDYCRA,False,True,True,2
PFSDYCRN,False,True,True,2
PFSDYCRS,False,True,True,2
PFSCEP,False,True,True,2
PFSCRU,False,True,True,2
PFSDYCEB,False,True,True,2
PFSCU,False,True,True,2
PFSCRA,False,True,True,2
PFSCRT,False,True,True,2
PFSCRV,False,True,True,2
PFSCRE,False,True,True,2
PFSCREWK,False,True,True,2
PFSDYCRU,False,True,True,2
PFSCRN,False,True,True,2
PFSDYCRT,False,True,True,2
PFSCRS,False,True,True,2
PFSDYCRV,False,True,True,2
PFSDYOCR,False,True,True,2
WOEGFR,False,True,True,2
VEGFRDY,False,True,True,2
VEGFR,False,True,True,2
TUMCATCD,False,True,True,2
TUMCAT,False,True,True,2
SLDLMXRD,False,True,True,2
SLDLMXPR,False,True,True,2
SLDLMIN,False,True,True,2
SLDLBASE,False,True,True,2
SLDCMXRD,False,True,True,2
SLDCMXPR,False,True,True,2
SLDCMIN,False,True,True,2
SLDCBASE,False,True,True,2
PDOCR,False,True,True,2
RDTLR,False,True,True,2
PRADJYN,True,True,False,2
POTOSDY,False,True,True,2
POTOS,False,True,True,2
PFSOLR,False,True,True,2
PFSOCR,False,True,True,2
PFSDYOLR,False,True,True,2
PDOLR,False,True,True,2
WOEGFRDY,False,True,True,2
IRINDY,False,True,True,2
B_LDH2YN,False,True,True,2
CHIOF,False,True,True,2
DROPIN,False,True,True,2
DROPINDY,False,True,True,2
IRIN,False,True,True,2
EVALEGFR,False,True,True,2
KRAS,True,True,False,2
KRASCD,True,True,False,2
B_METANM,True,True,False,2
LIVERMET,False,True,True,2
LIVRONCD,False,True,True,2
LIVRONLY,False,True,True,2
OXAL,False,True,True,2
OXALDY,False,True,True,2
B_LDHNM,False,True,True,2
CHIOFDY,False,True,True,2
EGFRIRDY,False,True,True,2
B_ECOG,True,True,False,2
BECGICT,False,True,True,2
BEVZ,False,True,True,2
PDDYOLR,False,True,True,2
BEVZDY,False,True,True,2
PDDYOCR,False,True,True,2
EGFRIR,False,True,True,2
ANTUM,False,True,True,2
B_ECOGCD,True,True,False,2
ANTUMDY,False,True,True,2
RESPSTAT,True,False,False,1
EVALCTR,False,False,True,1
RDTCR,False,False,True,1
DPADJUV,False,True,False,1
DTH30,True,False,False,1
RLR,True,False,False,1
DIAGICD,True,False,False,1
DTHMT30,True,False,False,1
REGIONCD,False,False,True,1
RDTLRCA,False,False,True,1
RDURWCR,True,False,False,1
REGION,False,False,True,1
DTHDY30,True,False,False,1
DIAGI,True,False,False,1
DURSURG,True,False,False,1
RDURWLR,True,False,False,1
DTHMT,True,False,False,1
PDMTCR30,True,False,False,1
SDDURWCR,True,False,False,1
TFAIL,True,False,False,1
ACHEMO,True,False,False,1
ACHEMOCD,True,False,False,1
TTP1C,False,True,False,1
TTP1,False,True,False,1
BMETACTI,True,False,False,1
B_ECOGCT,False,False,True,1
TFAILMT,True,False,False,1
TFAILDY,True,False,False,1
B_LESNM,True,False,False,1
SDDURWLR,True,False,False,1
B_LESNMN,True,False,False,1
B_LESNMT,True,False,False,1
CETUX,False,True,False,1
CETUXDY,False,True,False,1
CHEMO,True,False,False,1
CHEMOCD,True,False,False,1
CHEMOI,True,False,False,1
CHEMOICD,True,False,False,1
RCR,True,False,False,1
R12CRCA,True,False,False,1
EVALKEA,True,False,False,1
R12LRSD,True,False,False,1
PFSLR30,True,False,False,1
FSTIRDS,True,False,False,1
FSTOXDS,True,False,False,1
LASTCRDY,True,False,False,1
PADJYNCD,False,True,False,1
PANIT,False,True,False,1
PFSDLR30,True,False,False,1
PFSDCR30,True,False,False,1
PANITDY,False,True,False,1
PDADEN,True,False,False,1
PDCR30,True,False,False,1
PDCRND,True,False,False,1
ACHEMMCD,True,False,False,1
PDDYCR30,True,False,False,1
PDDYCRND,True,False,False,1
PDDYLR30,True,False,False,1
PFSCR30,True,False,False,1
PDICMIS,True,False,False,1
PDICSIG,True,False,False,1
PDYN,True,False,False,1
PDPROMED,True,False,False,1
PDLR30,True,False,False,1
PDMTCR,True,False,False,1
PDMTLR30,True,False,False,1
PDMTLR,True,False,False,1
PFSMCR30,True,False,False,1
PFSMLR30,True,False,False,1
PFSMTCR,True,False,False,1
PRBEVR,False,True,False,1
R12LRCA,True,False,False,1
R12LR,True,False,False,1
R12CRSD,True,False,False,1
PDMTCRND,True,False,False,1
R12CR,True,False,False,1
PROXAR,False,True,False,1
PROXAM,False,True,False,1
PROXALCD,False,True,False,1
PROXAL,False,True,False,1
PROXACDR,False,True,False,1
PROXACDM,False,True,False,1
PRBEVM,False,True,False,1
PFSMTLR,True,False,False,1
PRBEVCDR,False,True,False,1
PRBEVCDM,False,True,False,1
PRBEVCD,False,True,False,1
PRBEV,False,True,False,1
EVALKSA,True,False,False,1
PRADJICD,True,False,False,1
PRADJI,True,False,False,1
EVALKUE,True,False,False,1
EVALQOL,False,True,False,1
FCHEMO,True,False,False,1
FCHEMOCD,True,False,False,1
ACHEMM,True,False,False,1

### `a_sendpt.sas7bdat`

In [19]:
presence_matrix(DATA_DIR, 'a_sendpt.sas7bdat', RAW_DOMAIN_TRIALS)

,NCT00115225_PACCE_bev_panitumumab_raw,NCT00339183_panitumumab_folfiri_raw,NCT00364013_panitumumab_folfox_raw,n_trials_present
IPDECPCW,True,True,True,3
FIDSINTR,True,True,True,3
DUREXP,True,True,True,3
B_LDHYN,True,True,True,3
NUMALINF,True,True,True,3
B_ECOGI,True,True,True,3
FIDURWK,True,True,True,3
EVALITT,True,True,True,3
BECOGICD,True,True,True,3
FICDOSE,True,True,True,3
DIAGTYCD,True,True,True,3
SEX,True,True,True,3
SEXCD,True,True,True,3
SITEID,True,True,True,3
EVALPP,True,True,True,3
EXPWK,True,True,True,3
RACCATCD,True,True,True,3
B_METACT,True,True,True,3
CDOSE,True,True,True,3
DSDLYPC,True,True,True,3
DSDLYNM,True,True,True,3
RACCAT,True,True,True,3
IPDURWK,True,True,True,3
IPDSINTR,True,True,True,3
IPDSINT,True,True,True,3
IPDLYPC,True,True,True,3
NUMINF,True,True,True,3
FBDECPCW,True,True,True,3
NUMFIINF,True,True,True,3
CWDOSE,True,True,True,3
DEATH,True,True,True,3
NUMFBINF,True,True,True,3
DECPCW,True,True,True,3
FICWDOSE,True,True,True,3
FIDSINT,True,True,True,3
AEREL4,True,True,True,3
TRTFREQ,True,True,True,3
AESER,True,True,True,3
TRTDOSE,True,True,True,3
AERELSER,True,True,True,3
AEREL34,True,True,True,3
TRTDUR,True,True,True,3
AEREL,True,True,True,3
FBADOSE,True,True,True,3
TRTFRQCD,True,True,True,3
FBDSINTR,True,True,True,3
AE4,True,True,True,3
FBAWDOSE,True,True,True,3
AE34,True,True,True,3
FBCDOSE,True,True,True,3
FBDSINT,True,True,True,3
ADOSE,True,True,True,3
FBCWDOSE,True,True,True,3
TRTCD,True,True,True,3
DIAGTYPE,True,True,True,3
FBDURWK,True,True,True,3
ATRTCD,True,True,True,3
FIAWDOSE,True,True,True,3
SUBJID,True,True,True,3
AETXDIS,True,True,True,3
TRT,True,True,True,3
AWDOSE,True,True,True,3
STUDYID,True,True,True,3
AGE,True,True,True,3
FIADOSE,True,True,True,3
ATRT,True,True,True,3
IEDUR,False,True,True,2
IEDURC,False,True,True,2
IEG34,False,True,True,2
OXADOSE,True,False,True,2
NUMIRINF,True,True,False,2
IEG34DRC,False,True,True,2
HAYN,False,True,True,2
IEG34DUR,False,True,True,2
IEGRDY,False,True,True,2
FBDSINR3,False,True,True,2
IEGRRSFU,False,True,True,2
IEOT,False,True,True,2
IEDIS,False,True,True,2
NUMOXINF,True,False,True,2
HASEVDY,False,True,True,2
HASEVDUR,False,True,True,2
HASEVDRC,False,True,True,2
FIDECPCW,False,True,True,2
FIDSINR3,False,True,True,2
NUMINFP,False,True,True,2
OXCWDOSE,True,False,True,2
OXAWDOSE,True,False,True,2
HADY,False,True,True,2
HADURC,False,True,True,2
HADUR,False,True,True,2
HADIS,False,True,True,2
NUMLLINF,False,True,True,2
OXCDOSE,True,False,True,2
HARSFU,False,True,True,2
IEOTDY,False,True,True,2
NASEVDY,False,True,True,2
IRDURWK,True,True,False,2
NASEVDUR,False,True,True,2
KRAS,True,True,False,2
KRASCD,True,True,False,2
LIVERMET,False,True,True,2
LIVRONCD,False,True,True,2
LIVRONLY,False,True,True,2
LLADOSE,False,True,True,2
LLAWDOSE,False,True,True,2
LLCDOSE,False,True,True,2
LLCWDOSE,False,True,True,2
LLDSINR3,False,True,True,2
LLDSINT,False,True,True,2
LLDSINTR,False,True,True,2
LLDURWK,False,True,True,2
MAGNES,False,True,True,2
MAGSEV,False,True,True,2
MAGSEVCD,False,True,True,2
NADUR,False,True,True,2
NADURC,False,True,True,2
NADY,False,True,True,2
NARSFU,False,True,True,2
NASEV,False,True,True,2
IRDSINTR,True,True,False,2
IRDSINT,True,True,False,2
IEOTDYC,False,True,True,2
NAYN,False,True,True,2
IEOTFUDY,False,True,True,2
IERSFU,False,True,True,2
IESEVDRC,False,True,True,2
IESEVDUR,False,True,True,2
IESEVDY,False,True,True,2
INFCTC,False,True,True,2
NUMDLINF,False,True,True,2
INFREP,False,True,True,2
INFRSFU,False,True,True,2
INFUSPI,False,True,True,2
INTEYE,False,True,True,2
INTEYEDY,False,True,True,2
INTINF,False,True,True,2
IPDECNMW,False,True,True,2
IPDLYNM,False,True,True,2
IPDSINR3,False,True,True,2
IRADOSE,True,True,False,2
IRAWDOSE,True,True,False,2
IRCDOSE,True,True,False,2
NUMCHINF,False,True,True,2
NUMCHALL,False,True,True,2
IRCWDOSE,True,True,False,2
IRDECPCW,True,True,False,2
OXDECPCW,True,False,True,2
EYDUR,False,True,True,2
NASEVCD,False,True,True,2
DOSWH,False,True,True,2
SKDIS,False,True,True,2
DECCHPCW,False,True,True,2
DECNMW,False,True,True,2
SKDUR,False,True,True,2
SKDURC,False,True,True,2
DIARRHEA,False,True,True,2
SKDY,False,True,True,2
PRADJYN,True,True,False,2
DLADOSE,False,True,True,2
DLAWDOSE,False,True,True,2
DLCDOSE,False,True,True,2
DLCWDOSE,False,True,True,2
DLDSINR3,False,True,True,2
B_METANM,True,True,False,2
DLDSINTR,False,True,True,2
DECCHNMW,False,True,True,2
BECGICT,False,True,True,2
B_ECOG,True,True,False,2
CLCSEVCD,False,True,True,2
CARDTOX,False,True,True,2
CHDLYNM,False,True,True,2
CHDLYPC,False,True,True,2
RAGRRSFU,False,True,True,2
PULMTOX,False,True,True,2
CLCSEV,False,True,True,2
CSDIS,False,True,True,2
PROPDOSE,False,True,True,2
CSDY,False,True,True,2
B_LDHNM,False,True,True,2
B_LDH2YN,False,True,True,2
CSSEVDY,False,True,True,2
CSYN,False,True,True,2
B_ECOGCD,True,True,False,2
DLDURWK,False,True,True,2
DLDSINT,False,True,True,2
DOSWR,False,True,True,2
TUMCAT,False,True,True,2
DOSWRF,False,True,True,2
EYDY,False,True,True,2
EYRSFU,False,True,True,2
EYSEV,False,True,True,2
EYSEVCD,False,True,True,2
EYSEVDRC,False,True,True,2
TUMCATCD,False,True,True,2
AELIFE,False,True,True,2
EYSEVDUR,False,True,True,2
EYSEVDY,False,True,True,2
EYYN,False,True,True,2
AE,False,True,True,2
OXDSINT,True,False,True,2
VASCTOX,False,True,True,2
NASEVDRC,False,True,True,2
EYDURC,False,True,True,2
CALCEM,False,True,True,2
SKSEVCD,False,True,True,2
OXDURWK,True,False,True,2
AESTYDIS,False,True,True,2
DOSWRW,False,True,True,2
SKRSFU,False,True,True,2
EVALEGFR,False,True,True,2
SKSEV,False,True,True,2
STOMATIT,False,True,True,2
SKYN,False,True,True,2
OXDSINTR,True,False,True,2
SKSEVDY,False,True,True,2
SKSEVDUR,False,True,True,2
SKSEVDRC,False,True,True,2
VASSEV,False,True,False,1
NUMBINF2,True,False,False,1
RESPSTAT,True,False,False,1
REGION,False,False,True,1
NPRSURG,False,True,False,1
STOSEV,False,False,True,1
STOSEVCD,False,False,True,1
REGIONCD,False,False,True,1
NUMBINF,True,False,False,1
OXDLYPC,True,False,False,1
PULSEVCD,False,True,False,1
NUMOXIN2,True,False,False,1
PDPROMED,True,False,False,1
PDICSIG,True,False,False,1
NUMIRIN2,True,False,False,1
PDICMIS,True,False,False,1
PDADEN,True,False,False,1
PADJYNCD,False,True,False,1
OXDURWK2,True,False,False,1
PULSEV,False,True,False,1
OXDSINT2,True,False,False,1
OXCDOSE2,True,False,False,1
OXCWDOS2,True,False,False,1
OXDECNMW,False,False,True,1
OXDSINR3,False,False,True,1
OXDSINR2,True,False,False,1
PDYN,True,False,False,1
PRADJI,True,False,False,1
PRADJICD,True,False,False,1
PRBEV,False,True,False,1
PRBEVCD,False,True,False,1
PRBEVCDM,False,True,False,1
NUMFIIN2,True,False,False,1
PRBEVCDR,False,True,False,1
PRBEVM,False,True,False,1
OXDLYNM,True,False,False,1
NUMFBIN2,True,False,False,1
PROXACDM,False,True,False,1
PROXACDR,False,True,False,1
PROXAL,False,True,False,1
PROXALCD,False,True,False,1
PROXAM,False,True,False,1
PROXAR,False,True,False,1
PRBEVR,False,True,False,1
ACHEMM,True,False,False,1
IRDURWK2,True,False,False,1
BDSINT,True,False,False,1
BDSINTR,True,False,False,1
BDSINTR2,True,False,False,1
BDURWK,True,False,False,1
BDURWK2,True,False,False,1
BMETACTI,True,False,False,1
B_ECOGCT,False,False,True,1
B_LESNM,True,False,False,1
B_LESNMN,True,False,False,1
B_LESNMT,True,False,False,1
CHEMO,True,False,False,1
CHEMOCD,True,False,False,1
CHEMOI,True,False,False,1
CHEMOICD,True,False,False,1
CSDUR,False,True,False,1
CSDURC,False,True,False,1
CSRSFU,False,True,False,1
CSSEVDRC,False,True,False,1
CSSEVDUR,False,True,False,1
CTXSEV,False,False,True,1
CTXSEVCD,False,False,True,1
DEATH2,True,False,False,1
BDSINT2,True,False,False,1
BDLYPC,True,False,False,1
DEATH60,True,False,False,1
BDLYNM,True,False,False,1
ACHEMO,True,False,False,1
ACHEMOCD,True,False,False,1
AE2,True,False,False,1
AE34_2,True,False,False,1
AEBEVDIS,True,False,False,1
AEBEVDS2,True,False,False,1
AEREL2,True,False,False,1
AERELSR2,True,False,False,1
AESER2,True,False,False,1
AETRTDIS,True,False,False,1
AETRTDS2,True,False,False,1
AETXDIS2,True,False,False,1
AINFHR,True,False,False,1
AINFTM,True,False,False,1
BADOSE,True,False,False,1
BAWDOSE,True,False,False,1
BCDOSE,True,False,False,1
BCDOSE2,True,False,False,1
BCWDOSE,True,False,False,1
BCWDOSE2,True,False,False,1
BDECPCW,True,False,False,1
DEATH30,True,False,False,1
DIAGI,True,False,False,1
IRDSINT2,True,False,False,1
FCHEMOCD,True,False,False,1
FICWDOS2,True,False,False,1
FIDECNMW,False,False,True,1
FIDSINR2,True,False,False,1
FIDSINT2,True,False,False,1
FIDURWK2,True,False,False,1
FSTIRDS,True,False,False,1
FSTOXDS,True,False,False,1
ACHEMMCD,True,False,False,1
HASEV,False,False,True,1
HASEVCD,False,False,True,1
IESEV,False,False,True,1
IESEVCD,False,False,True,1
INFREAC,True,False,False,1
INFREAC2,True,False,False,1
IRCDOSE2,True,False,False,1
IRCWDOS2,True,False,False,1
IRDECNMW,False,True,False,1
IRDLYNM,True,False,False,1
IRDLYPC,True,False,False,1
IRDSINR2,True,False,False,1
IRDSINR3,False,True,False,1
FICDOSE2,True,False,False,1
FCHEMO,True,False,False,1
DIAGICD,True,False,False,1
FBDURWK2,True,False,False,1
DIASEV,False,False,True,1
DIASEVCD,False,False,True,1
DPADJUV,False,True,False,1
DTH30_2,True,False,False,1
DTH60_2,True,False,False,1
DTHREL,True,False,False,1
DTHREL2,True,False,False,1
DURSURG,True,False,False,1
EVALCTR,False,False,True,1
EVALKEA,True,False,False,1
EVALKSA,True,False,False,1
EVALKUE,True,False,False,1
EVALQOL,False,True,False,1
EVALSAF2,True,False,False,1
FBCDOSE2,True,False,False,1
FBCWDOS2,True,False,False,1
FBDECNMW,False,False,True,1
FBDLYNM,True,False,False,1
FBDLYPC,True,False,False,1
FBDSINR2,True,False,False,1
FBDSINT2,True,False,False,1
VASSEVCD,False,True,False,1

## ADaM trials — side-by-side column lists

`NCT00113763` and `NCT00364013_ADaM` only ship pre-derived ADaM domains, not raw SDTM-like
domains — no `demo`/`disposit`/`ae` files to compare against the matrices above.
These need a separate ADaM -> common-schema mapping (per `Data/README.md`).

### `adsl_pds2019.sas7bdat`

In [20]:
a = columns_only(DATA_DIR, 'NCT00113763_panitumumab_bsc_ADaM', 'adsl_pds2019.sas7bdat').rename(columns={'adsl_pds2019.sas7bdat': 'NCT00113763_panitumumab_bsc_ADaM'})
b = columns_only(DATA_DIR, 'NCT00364013_panitumumab_folfox_ADaM', 'adsl_pds2019.sas7bdat').rename(columns={'adsl_pds2019.sas7bdat': 'NCT00364013_panitumumab_folfox_ADaM'})
pd.concat([a, b], axis=1)

   NCT00113763_panitumumab_bsc_ADaM NCT00364013_panitumumab_folfox_ADaM
0                            SUBJID                              SUBJID
1                               TRT                                 TRT
2                              ATRT                                ATRT
3                             SXANY                              PRSURG
4                            DTHDYX                               DTHDY
5                              DTHX                                 DTH
6                           PFSDYCR                             PFSDYCR
7                             PFSCR                               PFSCR
8                          DIAGMONS                            LIVERMET
9                               AGE                            DIAGMONS
10                              SEX                                 AGE
11                         B_WEIGHT                                 SEX
12                             RACE                            B_WEIGHT
13                           B_ECOG                            B_HEIGHT
14                         HISSUBTY                                RACE
15                         DIAGTYPE                              B_ECOG
16                              NaN                            HISSUBTY
17                              NaN                            B_METANM
18                              NaN                            DIAGTYPE

### `adae_pds2019.sas7bdat`

In [21]:
a = columns_only(DATA_DIR, 'NCT00113763_panitumumab_bsc_ADaM', 'adae_pds2019.sas7bdat').rename(columns={'adae_pds2019.sas7bdat': 'NCT00113763_panitumumab_bsc_ADaM'})
b = columns_only(DATA_DIR, 'NCT00364013_panitumumab_folfox_ADaM', 'adae_pds2019.sas7bdat').rename(columns={'adae_pds2019.sas7bdat': 'NCT00364013_panitumumab_folfox_ADaM'})
pd.concat([a, b], axis=1)

  NCT00113763_panitumumab_bsc_ADaM NCT00364013_panitumumab_folfox_ADaM
0                           SUBJID                              SUBJID
1                             AEPT                                AEPT
2                            AESOC                               AESOC
3                          AESTDYI                             AESTDYI
4                          AEENDYI                             AEENDYI
5                          AESEVCD                             AESEVCD
6                           AECONT                              AECONT

### `adlb_pds2019.sas7bdat`

In [22]:
a = columns_only(DATA_DIR, 'NCT00113763_panitumumab_bsc_ADaM', 'adlb_pds2019.sas7bdat').rename(columns={'adlb_pds2019.sas7bdat': 'NCT00113763_panitumumab_bsc_ADaM'})
b = columns_only(DATA_DIR, 'NCT00364013_panitumumab_folfox_ADaM', 'adlb_pds2019.sas7bdat').rename(columns={'adlb_pds2019.sas7bdat': 'NCT00364013_panitumumab_folfox_ADaM'})
pd.concat([a, b], axis=1)

  NCT00113763_panitumumab_bsc_ADaM NCT00364013_panitumumab_folfox_ADaM
0                           SUBJID                              SUBJID
1                           LBTEST                              LBTEST
2                           LBBASE                              LBBASE
3                         LBSTRESN                            LBSTRESN
4                         LBSTUNIT                            LBSTUNIT
5                          VISITDY                             VISITDY
6                            VISIT                               VISIT

### `adls_pds2019.sas7bdat`

In [23]:
a = columns_only(DATA_DIR, 'NCT00113763_panitumumab_bsc_ADaM', 'adls_pds2019.sas7bdat').rename(columns={'adls_pds2019.sas7bdat': 'NCT00113763_panitumumab_bsc_ADaM'})
b = columns_only(DATA_DIR, 'NCT00364013_panitumumab_folfox_ADaM', 'adls_pds2019.sas7bdat').rename(columns={'adls_pds2019.sas7bdat': 'NCT00364013_panitumumab_folfox_ADaM'})
pd.concat([a, b], axis=1)

   NCT00113763_panitumumab_bsc_ADaM NCT00364013_panitumumab_folfox_ADaM
0                            SUBJID                              SUBJID
1                           VISITDY                             VISITDY
2                             VISIT                               VISIT
3                             LSCAT                               LSCAT
4                             LSNEW                               LSNEW
5                             LSSLD                               LSSLD
6                              LSLD                                LSLD
7                            LSSITE                              LSSITE
8                          LSNEWANY                            LSNEWANY
9                          LSREADER                            LSREADER
10                           LSTYPE                              LSTYPE

### `adpm_pds2019.sas7bdat`

In [24]:
a = columns_only(DATA_DIR, 'NCT00113763_panitumumab_bsc_ADaM', 'adpm_pds2019.sas7bdat').rename(columns={'adpm_pds2019.sas7bdat': 'NCT00113763_panitumumab_bsc_ADaM'})
b = columns_only(DATA_DIR, 'NCT00364013_panitumumab_folfox_ADaM', 'adpm_pds2019.sas7bdat').rename(columns={'adpm_pds2019.sas7bdat': 'NCT00364013_panitumumab_folfox_ADaM'})
pd.concat([a, b], axis=1)

  NCT00113763_panitumumab_bsc_ADaM NCT00364013_panitumumab_folfox_ADaM
0                           SUBJID                              SUBJID
1                            VISIT                               VISIT
2                          VISITDY                             VISITDY
3                           WEIGHT                              WEIGHT

### `adrsp_pds2019.sas7bdat`

In [25]:
a = columns_only(DATA_DIR, 'NCT00113763_panitumumab_bsc_ADaM', 'adrsp_pds2019.sas7bdat').rename(columns={'adrsp_pds2019.sas7bdat': 'NCT00113763_panitumumab_bsc_ADaM'})
b = columns_only(DATA_DIR, 'NCT00364013_panitumumab_folfox_ADaM', 'adrsp_pds2019.sas7bdat').rename(columns={'adrsp_pds2019.sas7bdat': 'NCT00364013_panitumumab_folfox_ADaM'})
pd.concat([a, b], axis=1)

  NCT00113763_panitumumab_bsc_ADaM NCT00364013_panitumumab_folfox_ADaM
0                           SUBJID                              SUBJID
1                           RSRESP                              RSRESP
2                          VISITDY                             VISITDY
3                            VISIT                               VISIT
4                         RSCONFYN                            RSCONFYN
5                          RSTRESP                             RSTRESP
6                         RSNTRESP                            RSNTRESP
7                         RSREADER                               RSNEW
8                              NaN                            RSREADER

### `biomark_pds2019.sas7bdat`

In [26]:
a = columns_only(DATA_DIR, 'NCT00113763_panitumumab_bsc_ADaM', 'biomark_pds2019.sas7bdat').rename(columns={'biomark_pds2019.sas7bdat': 'NCT00113763_panitumumab_bsc_ADaM'})
b = columns_only(DATA_DIR, 'NCT00364013_panitumumab_folfox_ADaM', 'biomark_pds2019.sas7bdat').rename(columns={'biomark_pds2019.sas7bdat': 'NCT00364013_panitumumab_folfox_ADaM'})
pd.concat([a, b], axis=1)

   NCT00113763_panitumumab_bsc_ADaM NCT00364013_panitumumab_folfox_ADaM
0                            SUBJID                              SUBJID
1                           BMMTNM1                             BMMTNM1
2                            BMMTR1                              BMMTR1
3                           BMMTNM2                             BMMTNM2
4                            BMMTR2                              BMMTR2
5                           BMMTNM3                             BMMTNM3
6                            BMMTR3                              BMMTR3
7                           BMMTNM4                             BMMTNM4
8                            BMMTR4                              BMMTR4
9                           BMMTNM5                             BMMTNM5
10                           BMMTR5                              BMMTR5
11                          BMMTNM6                             BMMTNM6
12                           BMMTR6                              BMMTR6
13                          BMMTNM7                             BMMTNM7
14                           BMMTR7                              BMMTR7
15                              NaN                            BMMTNM15
16                              NaN                             BMMTR15
17                              NaN                            BMMTNM16
18                              NaN                             BMMTR16